- acceptance-tests/dsl/build.gradle
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/DiscoveryPeer.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/Bucket.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerTable.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgentTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryTestHelper.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/MockPeerDiscoveryAgent.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerTableTest.java
Update discovery logic to consider a peer with an unknown discovery endpoint to be unknown regardless of whether we've encountered a peer with the same node id before.  This makes the discovery logic more forgiving in the face of node restarts.  
If `nodeA` bonds with `nodeB`, then `nodeB` leaves the network and later comes back with a different ip address or listening port, `nodeA` would previously continue trying to communicate with `nodeB` at its original address.  With these changes, `nodeA` will now treat the restarted `nodeB` as a new peer and communicate with it on its updated endpoint.  Additionally, `nodeB`'s information will be updated in the peer table so that neighbors requests return updated information on this node.
> [PAN-3155] Handle discovery peers with updated endpoints

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/StateTrieAccountValue.java
Signed-off-by: Peter Robinson <drinkcoffee@eml.cc>
The version field is an integer. It is read in as an integer. Mistakenly, it is written as a long.
> StateTrieAccountValue:Version should be written as an int, not a long

- acceptance-tests/dsl/build.gradle
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/KeyValueStorageFactory.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactory.java
- plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactoryTest.java
Primary:
This fixes an issue where rolling back the default database version could cause an error. It's important that the loading logic depends only on the database version so we can have full control. It's still fine to set auxiliary properties like isSegmentIsolationSupported as we go through the creation process.
Other:
Extend the plugin interface with Closeable
> Support Version Rollbacks for RocksDB (#6)

- besu/src/main/java/org/hyperledger/besu/cli/util/EnvironmentVariableDefaultProvider.java
- besu/src/test/java/org/hyperledger/besu/cli/EnvironmentVariableDefaultProviderTest.java
For backwards compatibility, support both `BESU_` and `PANTHEON_` prefixes for environment variables.  The `BESU_` prefix is used if both are set.
> Support both BESU_ and PANTHEON_ env var prefixes

- config/src/main/resources/rinkeby.json
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolScheduleTest.java
The Rinkeby Fork Block for Istanbul is 5435345, targeting 13 Nov 2019.
As announced by the Rinkeby maintainers here: https://twitter.com/peter_szilagyi/status/1174580897980592129
> [PAN-3160] Rinkeby Istanbul fork block

- gradle.properties
> Update version to 1.2.5-SNAPSHOT

- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactory.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBPlugin.java
Some of the logging levels produce surprising results, for example the
call to `--help` spits out info about rocksdb starting, which we don't
need.  Turn down plugin start/stop to debug and using an existing DB to
debug.  Config options are only developer relevant, so down to trace.
> Downgrade some RocksDBPlugin Logging Levels

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/services/BesuConfigurationImpl.java
- build.gradle
- gradle.properties
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/services/BesuConfiguration.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactory.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/configuration/DatabaseMetadata.java
- plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/helper/Conditions.java
- plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactoryTest.java
- plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/configuration/DatabaseMetadataTest.java
The database metadata file should be stored in the root data directory rather than the database subdirectory. The database subdirectory is owned by the database itself and should not be directly manipulated by the node.
- first look in the data directory for the metadata file
- if the metadata file is found there, process it as normal
- if no metadata file is found in the root directory, look in the database subdirectory 
- if the file is found here, copy it to the root directory, and run based on the root directory version
> Store db metadata file in the root data directory.

- build.gradle
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetEvmRegistries.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/EVM.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/Operation.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/operations/VirtualOperation.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/EVMTest.java
- gradle.properties
Introduce `VirtualOperation`.
- add `isVirtualOperation` method to `Operation` interface: determines whether or not the operation has been virtually added to the contract code.
- default implementation of `isVirtualOperation` returns `false`
- create `VirtualOperation` that wraps a real `Operation` and returns `true` for `isVirtualOperation` method.
- change `constructor` of `EVM` to pass a `GasCalculator` used to create the `endOfScriptStop` and `invalidOperation` fields. 
- change visibility of `EVM.operationAtOffset` to `package` for testing purpose. (add `VisibleForTesting` annotation)
- create `EVMTest` to test `operationAtOffset` method .
> Introduce virtual operation.

- config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
- gradle.properties
Disallow comments in Genesis JSON file.
fixes [PAN-3013](https://pegasys1.atlassian.net/browse/PAN-3013)
> Disallow comments in Genesis JSON file.

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/RetestethSubCommand.java
Default logging should be 'null' - which means that Besu will do nothing
to the Log4J2 logging levels and rely on the built in or user supplied
log4j2.xml configuration files to set up logging.
> Fix default logging

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyNode.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/services/BesuConfigurationImpl.java
- besu/src/test/java/org/hyperledger/besu/PrivacyTest.java
- besu/src/test/java/org/hyperledger/besu/RunnerTest.java
- ethereum/eth/src/jmh/java/org/hyperledger/besu/ethereum/eth/sync/worldstate/WorldStateDownloaderBenchmark.java
Clean up `BesuConfiguration` construction.  Remove constructor that should never be used in production. Reorder parameters.
> Clean up BesuConfiguration construction

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivDistributeRawTransaction.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivDistributeRawTransactionTest.java
`priv_distributeTransaction` should return the enclave key instead of the private transaction hash. This is for developer experience so they can put the enclave key in a PMT they build on the client-side. The private transaction hash currently has no purpose. It will be retrievable from the private transaction receipt once the private transaction is processed to do client-side verification.
> return enclave key instead of private transaction hash

- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/validation/RoundChangeMessageValidator.java
Signed-off-by: Christopher Hare <chris.hare@consensys.net>
LGTM recommended correcting the log line to have separate words i.e. add a space.
> Adding whitespace to separate words in log message

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/syncing/NotSynchronisingResult.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/syncing/SyncingSubscriptionService.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/syncing/SyncingSubscriptionServiceTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/SyncStatus.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/state/SyncState.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/state/SyncStateTest.java
We should not send a sync status for every forking block state update.
Yes, we send status updates for detected forks as well as new canonical
heads.
Instead we should send a synching message for status changes as well as
when we reorg the chain.
PAN-3183
> [PAN-3183] Less verbose synching subscriptions

- CODEOWNERS
The functional reason to change this is now all PRs wind up adding every maintainer to the reviewers list.  This reduces the value on requesting a specific review from a specific maintainer.  If all the reviewers were not auto-added I would be neutral on this change.
> Undo "Add CODEOWNERS to match MAINTAINERS"

- build.gradle
Add a build task that will enumerate all the maven publications and fail
the build if it detects that a duplicate maven coordinate would be used.
> Check for duplicate Maven coordinates

- besu/src/main/java/org/hyperledger/besu/util/PlatformDetector.java
Add an openjdk case to platform detector, changes client info from
`besu/v1.2.4/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11`
to
`besu/v1.2.4/linux-x86_64/openjdk-java-11`
while preserving adoptopenjdk and oracle_openjdk cases.
> [minor] add openjdk to platform detector

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyAcceptanceTestBase.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/transaction/PrivDistributeTransactionTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/transaction/PrivacyTransactions.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/privacy/PrivacyRequestFactory.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/PrivacyClusterAcceptanceTest.java
Adds Acceptance test which:
1. calls `priv_distribute` from A
2. Asserts that A and B enclaves have received the payload
3. Sends marker from A
4. Asserts that A and B can access the correct private transaction receipt
> Add privDistributeTransaction AT

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- besu/src/test/resources/everything_config.toml
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/peervalidation/AbstractPeerBlockValidator.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/peervalidation/DaoForkPeerValidator.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/peervalidation/RequiredBlocksPeerValidator.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/peervalidation/AbstractPeerBlockValidatorTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/peervalidation/DaoForkPeerValidatorTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/peervalidation/RequiredBlocksPeerValidatorTest.java
Add a new CLI flag `--required-block` that takes a block number and a
block hash.  Before using a peer for syncing we validate that the block
exists with the spcified hash at the peer.
For example `--required-block=6485846=0x43f0cd1e5b1f9c4d5cda26c240b59ee4f1b510d0a185aa8fd476d091b0097a80`
deals with the current Istanbul Ropsten chainsplit.
> [PAN-3203] add --required-block flag to deal with chainsplits

- ethereum/core/src/integration-test/java/org/hyperledger/besu/ethereum/worldstate/PrunerIntegrationTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/MarkSweepPruner.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/Pruner.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/DefaultSynchronizer.java
Fixes race condition between attaching the `NodeAddedListener` and some state from post marked block being persisted. We now prepare and cleanup the listener only once each, on start and stop respectively.
Other changes:
* Start the `Pruner` before `FullSyncDownloader`. Luckily the downloader took enough time to start downloading that this wasn't an issue but it's safer this way.
> Fixes race condition between `NodeAddedListener` and `FullBlockImportStep`

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
Marking can take longer than the time it takes to accumulate the blocks to satisfy these options. We make no guarantees that exactly the number of blocks in the options will be awaited/kept.
> specify that pruning options are minimums

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
Narrowed the API on the TransactionSimulator in preparation for some potential generification and use with private transactions.  Given the hash and long overloads of doesAddressExist are unused, remove them.
Signed-off-by: Rob Dawson <robert@rojotek.com>
> Removed Unused methods in the transaction simulator.

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/account/Account.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/blockchain/Amount.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/account/ExpectAccountBalance.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/account/ExpectAccountBalanceNotChanging.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/account/TransferTransaction.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AccountLocalConfigPermissioningAcceptanceTest.java
Rework acceptance test balance checks to use stronger, clearer types.
Previously you could set an expectation for a balance with a decimal string value, but not a hex string value.  This was an error-prone approach.
> [Minor] Rework balance checks to use stronger types

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactionsTest.java
Fix bug in transaction tracking that resulted in duplicate transactions (same nonce, same sender) not being dropped.
> [PIE-1998] Fix transaction tracking by sender

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLDataFetchers.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLProvider.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/BlockchainQuery.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/LogAdapter.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/EthGraphQLHttpBySpecTest.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/eth_getLogs_range.json
Add support for the top level logs query.
fixes PAN-3223
> [PAN-3223] Add GraphQL query/logs support

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/state/SyncState.java
Make `SyncState` variables visible across threads.
> [PIE-2003] Make SyncState variables thread-safe

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/PersistBlockTask.java
Make the logic for iterating through blocks and importing in `PersistBlockTask` simpler and clearer. The different behaviour for the first block is now handled before the loop instead of as an if condition within the loop.  This makes it clearer to both humans and LGTM that `future` is never null (https://lgtm.com/projects/g/hyperledger/besu/snapshot/72b95dc86ce4d94aba338c45522656af3116c67e/files/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/PersistBlockTask.java?sort=name&dir=ASC&mode=heatmap#x57078a84215a57eb:1).
> Make logic in PersistBlockTask more explicit to fix a LGTM warning

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/PrivacyClusterAcceptanceTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DefaultMutablePrivateWorldStateUpdater.java
Fixes an edge case which causes the evm to break. If a private account does not exist (i.e. it is empty) we should return the public account. If the public account does not account (i.e. it is empty) there is no useful information that can be read from the private transaction processor - so it is ok to return the empty private account instead of null.
The AT update covers this edge.
[PAN-3222]
> [PAN-3222] Fix private transactions breaking evm

- besu/src/main/java/org/hyperledger/besu/cli/converter/MetricCategoryConverter.java
- besu/src/test/java/org/hyperledger/besu/cli/converter/MetricCategoryConverterTest.java
- build.gradle
Updated the MetricCategoryRegistry to simplify dynamic `MetricCategory` instantiation and make them consistent with the existing static entries.
#PIE-2023
> [PIE-2023] Fixed casing of dynamic MetricCategorys

- besu/src/test/java/org/hyperledger/besu/services/BesuEventsImplTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/syncing/SyncingSubscriptionService.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/AbstractEthGraphQLHttpServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/health/ReadinessCheckTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSyncingTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/syncing/SyncingSubscriptionServiceTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/DefaultSyncStatus.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/DefaultSynchronizer.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/state/SyncState.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/state/SyncStateTest.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/SyncStatus.java
- plugin-api/src/main/java/org/hyperledger/besu/plugin/services/BesuEvents.java
Simplify sync status events.
Summary:
* Update when `syncStatus` events fire.  They now fire when:
* The `Synchronizer` sets a target (starts syncing)
* The `Synchronizer` clears a target (stops syncing)
* Update `SyncStatus` fields:
*  The `inSync` field has been removed since this is a separate concern from the `Synchronizer`'s status
* The `startingBlock` value is being set to the common ancestor with the sync target, to provide more meaningful information on the status of the `Synchronizer`
* Update `BesuEvents.SyncStatusListener` to accept an `Optional<SyncStatus>`, where an empty value means that the `Synchronizer` is not currently syncing
* Rename class `SyncStatus` to `DefaultSyncStatus` to disambiguate between the implementation and the interface
This PR builds off of …
> [PIE-2031] Rework sync status events

- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactionsTest.java
This adds an additional unit test around pending transactions when transactions are replaced and then selected for mining.
> Additional unit test for selecting replaced pending transactions

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/ConnectionInitializer.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/NettyConnectionInitializer.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/MockConnectionInitializer.java
This PR fixes an issue where the `RlpxAgent` could fail to start up, but never return a failed `CompletableFuture`, causing the node to hang.
> [Pan 3238] Fix rlpx startup

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ChainState.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncTargetManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncTargetManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ChainStateTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncTargetManagerTest.java
This updates the `Synchronizer` logic to only set a `SyncTarget` using peers who have a height estimate.  This ensures that the initial `SyncStatus` event emitted from `SyncState` has a non-zero "highestBlock" value.
> [PAN-3239] Only set sync targets that have an estimated height value

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/BadCLIOptionsPluginTest.java
- besu/src/main/java/org/hyperledger/besu/services/PicoCLIOptionsImpl.java
- besu/src/test/java/org/hyperledger/besu/plugins/BadCLIOptionsPlugin.java
- besu/src/test/java/org/hyperledger/besu/plugins/TestPicoCLIPlugin.java
- besu/src/test/java/org/hyperledger/besu/services/PicoCLIOptionsImplTest.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/configuration/RocksDBCLIOptions.java
- plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBCLIOptionsTest.java
Enforce that plugin variable names are either `--plugin-<namespace>-`
or `--Xplugin-<namespace>-` when registered with the
PicoCLIOptionsService.  If the names don't match a RuntimeException is
thrown, and unless that exception is caught the plugin will not have
start or stop lifecycle messages called.
PAN-3242
> [PAN-3242] Programatically enforce plugin CLI variable names

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/PrivateContractPublicStateAcceptanceTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractMessageProcessor.java
Not catching illegal modification inside evm operation caused Besu to abruptly exit private transaction processing. This meant that on some nodes extra gas was not refunded when processing the PMT while on non-participating nodes no private transaction was processed so the PMT was successfully processed and extra gas was refunded. This causes a mismatch in the receipt root as the gas used is recorded in the receipt.
[PAN-3240]
> [PAN-3240] fix private transaction root mismatch

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthServer.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractPeerRequestTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/BlockPropagationManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/ChainHeadTracker.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncTargetManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionsMessageProcessor.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/AbstractPeerConnection.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/ApiHandler.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramer.java
Improve logging around peer disconnects.
> [Minor] Add more logging around peer disconnects

- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/IbftExtraDataTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/TopicsDeserializer.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/LogsQuery.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TopicsParameter.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/filter/LogsQueryTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/FilterParameterTest.java
An error was detected (PAN-3248) whereby if "Null" appeared in a Log
Topic filter, it and all subsequent filters were lost (and thus
were not used to filter responses) - thus Besu would return too many
results (as the filters were less restrictive than reqeusted).
This was determined to be an issue in the TopicParameterDeserialiser
which is resolved in this commit.
> Repair EthGetLogs returning incorrect results

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/LogsQuery.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/filter/FilterManagerLogFilterTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/filter/LogsQueryTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthNewFilterTest.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getLogs_nullParam.json
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/LogsBloomFilter.java
Use the bloombits for logs queries, so we only have to walk headers
and not every receipt on a large query.
> [PAN-3249] Use Bloombits for Logs queries

- .circleci/config.yml
Commenting out circles publish on the release branch so we're ready for the release tomorrow and don't have jenkins & circle both attempting to publish
Commenting out circles publish on the release branch so we're ready for the release tomorrow and don't have jenkins & circle both attempting to publish
> disable circle publishing on releases for tomorrow's release

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/resources/everything_config.toml
This reverts commit 7e2497bf95a5673faeba439bf5da2be4b6361d5b.
> Revert "[PAN-2798] Enable pruning by default for fast sync (#135)"

- build.gradle
- gradle/versions.gradle
Changes Apache Tuweni's dependency location and version so Besu depends on an official release by Apache, rather than a community build.
> Move Apache Tuweni dependency to official release

- besu/src/main/java/org/hyperledger/besu/controller/IbftBesuControllerBuilder.java
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/TransitionsConfigOptions.java
- config/src/test-support/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
- config/src/test/java/org/hyperledger/besu/config/JsonGenesisConfigOptionsTest.java
- config/src/test/resources/valid_config_with_custom_forks.json
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockHeaderValidator.java
Change the configuration name of "CustomForks" to "Transitions."  This
will better reflect that this is a list of blocks where transition
events might happen.  These may be more than forks, and mainnet is also
moving away from the name forks to "network upgrades."  Transitions is
more general purpose.
> Change CustomForks -> Transitions

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
`BesuCommandTest` and probably anything else that extends `CommandTestAbstract` leaked about 50 file descriptors per test that successfully parsed the CLI args. `BesuCommand` creates a `Vertx` instance which is never shutdown.
This is the root cause of newer Macs failing tests with "Failed to create a child event loop". They have more cores so run more processes in parallel which increases the number of file descriptors validly being used (each process needs around 200 file descriptors) and increases the chance that two of these tests will run at the same time and hit the resource limits.
This is a fairly brute-force approach to getting hold of that vertx instance and shutting it down but it solves the immediate issue.
Signed-off-by: Adrian Sutton <adrian.sutton@consensys.net>
> Shutdown vertx instance created within BesuCommand

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/pubsub/WebSocketConnection.java
- besu/src/test/java/org/hyperledger/besu/RunnerTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketRequestHandler.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketService.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketRequestHandlerTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketServiceLoginTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/methods/EthSubscribeIntegrationTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/methods/EthUnsubscribeIntegrationTest.java
* Updated WebSocketService (handle -> textMessageHandle)
* Updated WebSocketRequestHandler to accept String instead of Buffer
> BESU-128: Fix WebSocket frames handling

- gradle/versions.gradle
This solves the LPGP license issue around ktlint being imported
by mistake
Fixes https://github.com/web3j/web3j/issues/1105
> Update web3j dependency to 4.5.8

- enclave/src/main/java/org/hyperledger/besu/enclave/VertxRequestTransmitter.java
Increase the request timeout from 1s to 5s.
Some integration test started failing intermittently because of the 1s timeout.
> Increase timeout to 5s

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivGetPrivateTransactionIntegrationTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/AbstractSendTransaction.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/PrivacySendTransaction.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/eea/EeaSendRawTransaction.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivCreatePrivacyGroup.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivDeletePrivacyGroup.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivDistributeRawTransaction.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivFindPrivacyGroup.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetEeaTransactionCount.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetPrivacyPrecompileAddress.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetPrivateTransaction.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionCount.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionReceipt.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivacyApiMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EeaJsonRpcMethods.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivJsonRpcMethods.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/privacy/eea/PrivGetEeaTransactionCountTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/eea/EeaSendRawTransactionTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivCreatePrivacyGroupTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivDeletePrivacyGroupTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivDistributeRawTransactionTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivFindPrivacyGroupTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetPrivateTransactionTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionCountTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionReceiptTest.java
This is to be done similar to what is done for the permissioning API methods.
When privay is disabled, but the user specifies PRIV or EEA api groups in the cmd line, Besu should give a warning about not being able to use the methods.
If the user tries to execute the methods, Besu should give back a nice response saying that they aren't available because privacy is disabled.
* Updated `BesuCommand` to give warning if privacy is disabled and user tries to enable PRIV or EEA methods
* Created `PrivacyApiMethod` abstract class that has the logic of checking if privacy is enabled and returning a nice error when it is not
* Updated all Priv/Eea method objects to extend `PrivacyApiMethod`
* Updated unit tests
> BESU-134: Prevent execution of PRIV/EEA methods when privacy is disabled

- CHANGELOG.md
This PR fixes the broken links on the CHANGELOG.
This is the second PR in this sense since the first one had some rebase problems i couldn't solve.
Fixes BESU-110
> BESU-110: Fixing broken links on the CHANGELOG 

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketRequestHandler.java
Vertx by default orders all calls to executeBlocking in an ordered
fashion.  As a side effect all requests are single threaded, even across
multiple clients. Because JSON-RPC has request identifiers it is not
needed to thread responses as they can be answered out of order.  This
also allows multiple threads to handle requests, increasing throughput.
Performance Improvements in Websockets.
> Multithread Websockets to increase throughput

- besu/src/main/java/org/hyperledger/besu/chainimport/internal/TransactionData.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/converter/FractionConverter.java
- besu/src/main/java/org/hyperledger/besu/cli/util/CommandLineUtils.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/PrivacyParameters.java
Check the --privacy-public-key-file parameter on the besu command line and return meaningful error messages.
> check enclave public key and improve error messages

- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/GenerateBlockchainConfig.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/GenerateLogBloomCache.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/OperatorSubCommand.java
- besu/src/main/java/org/hyperledger/besu/controller/BesuController.java
- besu/src/test/java/org/hyperledger/besu/cli/operator/OperatorSubCommandTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLDataFetcherContext.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/JsonRpcMethodsFactory.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/AbstractEthGraphQLHttpServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueriesLogCacheTest.java
This comes in two parts: first a CLI program to generate the log bloom
indexes,then updating BlockchainQueries to use the indexes if present.
First, to create the bloom index on a synced node (for example Goerli):
`bin/besu --network=goerli --data-path /tmp/goerli operator generate-log-bloom-cache`
There are options where to start and to stop.  I estimate 15-30 minutes
for mainnet.
The RPCs should magically use the indexes now.  Note that the last
fragment of 100K blocks is not indexed and uses the old paths.
Add the ability to cache log bloom bits in a flat file to speed up logs queries 
via JSON-RPC and GraphQL.
* First, you must create the index via a new command:
> `bin/besu --network=goerli --data-path /tmp/goerli operator …
> [BESU-122] Index tx log bloom bits and use the index for queries.

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramer.java
There are a whole class of errors in the deframer that come from
IllegalArgumentExceptions. Those are thrown when Besu validates incoming
data. Because Besu is not the source of these errors we should not log
them any higher than DEBUG.
The most common one is `Caused by: java.lang.IllegalArgumentException:
Invalid node id. Expected id of length: 64 bytes.` and this is coming
from a non-conforming client connecting to Besu.
> Reduce Noisy Deframer Errors

- CONTRIBUTING.md
- Replaces old Pantheon Jira links with current Besu Jira.
- Adds link on DCO file to HL Besu wiki DCO page.
- small typo on readme markdown
> Fixed old Jira links (fixes #149)

- config/src/main/resources/classic.json
activates ecip-1056 on ethereum classic mainnet block 9573000. cc @edwardmack  
Ref https://github.com/ethereumclassic/ECIPs/pull/245
> config/resources: activate agharta on classic 9573000

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionReceipt.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionReceiptTest.java
When Besu has been configured to use privacy and the option `privacy-public-key-file` doesn't match the key used in Orion, the priv_getPrivateTransactionReceipt method would fail without providing any info to the system admin on what could be wrong.
This PR adds a warning log message that will help system admins to track down this issue.
> Improving error msg when privacy key doesn't match Orion key

- .circleci/config.yml
In our gradle setup the dependencies are set in `gradle/versions.gradle` not `build.gradle`
This PR ensure that we match the cache of dependencies with the file that specifies the dependencies
> Key cache by file that specifies dependencies

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/resources/everything_config.toml
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/PrivacyParameters.java
Add a privacy multi-tenancy CLI option which is hidden for now. This flag will be used to enable the multi-tenancy privacy mode.
> Privacy multitenancy cli option

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/ethsigner/testutil/EthSignerConfig.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/ethsigner/testutil/EthSignerTestHarness.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/ethsigner/testutil/EthSignerTestHarnessFactory.java
- gradle/versions.gradle
This upgrade removes the intermittent failure in
NewPendingTransactionAcceptanceTest (due to prior Ethsigner
affecting the leniency of the global json parser (making it
more strict than Besu demands)).
> Upgrade to ethsign 0.4.0

- besu/build.gradle
- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/GenerateLogBloomCache.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminGenerateLogBloomCache.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminIndexTransactionLogs.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/AdminJsonRpcMethods.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionLogsIndexer.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/AbstractEthGraphQLHttpServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/TraceJsonRpcHttpBySpecTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminGenerateLogBloomCacheTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueriesLogCacheTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueriesTest.java
- ethereum/core/build.gradle
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/BlockchainSetupUtil.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java
Add a RPC API to create the logs index.
Example usage:
```
curl -H "Content-Type: application/json" \
-X POST \
--data '{"jsonrpc":"2.0","method":"admin_generateLogBloomCache", "params":["0x0", "0x10000"], "id":1}' \
<node RPC port>
```
> Logs Index RPC API

- enclave/src/integration-test/java/org/hyperledger/besu/enclave/EnclaveTest.java
- enclave/src/main/java/org/hyperledger/besu/enclave/Enclave.java
- enclave/src/main/java/org/hyperledger/besu/enclave/types/RetrievePrivacyGroupRequest.java
Add the Orion retrieve privacy group endpoint to the Enclave so that it can be used in Besu for the multi-tenancy privacy validation.
> Enclave retrieve privacy group enclave method

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyNode.java
- enclave/src/main/java/org/hyperledger/besu/enclave/Enclave.java
- enclave/src/main/java/org/hyperledger/besu/enclave/EnclaveClientException.java
- enclave/src/main/java/org/hyperledger/besu/enclave/EnclaveFactory.java
- enclave/src/main/java/org/hyperledger/besu/enclave/EnclaveIOException.java
- enclave/src/main/java/org/hyperledger/besu/enclave/EnclaveServerException.java
- enclave/src/main/java/org/hyperledger/besu/enclave/VertxRequestTransmitter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionReceipt.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/eea/EeaSendRawTransactionTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivCreatePrivacyGroupTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionReceiptTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContract.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContractTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/PrivacyControllerTest.java
When a besu node sees a private marker transaction and the enclave is down/unavailable/unreachable block processing should stop until the enclave is available again.
This will stop ALL new blocks from node processed. The node will keep retrying forever until the enclave is available again. 
If the enclave becomes available but does not contain the expected data (i.e the enclave has lost data) then the privacy group may have an inconsistent state. 
Signed-off-by: Antony Denyer <email@antonydenyer.co.uk>
> [BESU-157] Stop processing private tx when enclave is down

- .circleci/config.yml
Uses CircleCI's test splitting capability to spread acceptance tests over 2 boxes and speed up the build.
Signed-off-by: Adrian Sutton <adrian.sutton@consensys.net>
> Split acceptance tests across multiple boxes

- plugin-api/build.gradle
Windows sorts files case insensitively, resulting in a different hash
for the API check because the files are in a different order.
> Windows Build Compatibility

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpService.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpServiceCorsTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpServiceTest.java
Signed-off-by: Anthony <anthonybuckle@gmail.com>
When users hit GraphQL url http://url:port/ they will be redirected to http://url:port/graphql.
[BESU-58](https://jira.hyperledger.org/browse/BESU-58)
> endpoint root path will redirect to /graphql

- ethereum/api/build.gradle
- gradle/versions.gradle
-- This jar is required by Tuweni API handling of known clients fingerprints at runtime
> Add missing bouncy castle library required by JSON-RPC HTTP TLS 

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlock.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockByHash.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockByNumber.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceReplayBlockTransactions.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/DebugJsonRpcMethods.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/TraceJsonRpcMethods.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/AbstractJsonRpcHttpBySpecTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/AbstractJsonRpcHttpServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/TraceJsonRpcHttpBySpecTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockByHashTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockByNumberTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockTest.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs/statediff/trace_replayBlockTransactions_diffOnly_0x2_twice.json
Now that BlockTracer has mutable state we cannot re-use it across
requests, instead we need to create a new one for each call.
To support this spec tests were upgraded to allow batched requests and
responses, which are processed sequentially.
> Trace APIs - fix reused blocktracer

- besu/src/main/java/org/hyperledger/besu/controller/IbftBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/IbftLegacyBesuControllerBuilder.java
- consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/jsonrpc/CliqueJsonRpcMethods.java
- consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/jsonrpc/methods/CliqueGetSignerMetrics.java
- consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/jsonrpc/methods/CliqueGetSignerMetricsTest.java
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/jsonrpc/AbstractGetSignerMetricsMethod.java
- consensus/ibft/src/integration-test/java/org/hyperledger/besu/consensus/ibft/support/TestContextBuilder.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/IbftContext.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/jsonrpc/IbftJsonRpcMethods.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/jsonrpc/methods/IbftGetSignerMetrics.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/jsonrpc/methods/IbftGetSignerMetricsTest.java
getSignerMetrics doesn't return missing signers (validators who never proposed a block are not displayed).  This means to find missing signers you have to use getSigners followed by getSignerMetrics and manually figure out which ones are missing. 
getSignerMetrics returns now missing signers
Example with `0x12eb759f2222d7711c63729a45c3585731521d02`
```
{
"jsonrpc": "2.0",
"id": 1,
"result": [
{
"address": "0x6639adb0e64884dc4cd9d686c15ba1ca1885c24e",
"proposedBlockCount": "0x22",
"lastProposedBlockNumber": "0xb8"
},
{
"address": "0x12eb759f2222d7711c63729a45c3585731521d02",
"proposedBlockCount": "0x0",
"lastProposedBlockNumber": "0x0"
},
{
"address": "0x187ec8a86cdd7e71e2c0e72affe48b727f894877",
"proposedBlockCount": "0x21", …
```
> [BESU-179] getSignerMetrics doesn't return missing signers

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/TracingUtils.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/diff/StateDiffGenerator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/Action.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/FlatTrace.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/FlatTraceGenerator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/Result.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/AbstractJsonRpcHttpBySpecTest.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/chain-data/blocks.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs/flat/trace_replayBlockTransactions_traceOnly_0x13.json
The iterative look back mechanism flat trace was using was missing
many of the nesting subtlties, so a stack based calculation is used.
A new test case with two levels of calls is also introduced.
> Tracing multiple levels of calls now works properly

- CHANGELOG.md
Adding back the experimental support section for `trace_replayBlockTransactions`
> Adding Danno's changelog changes back

- build.gradle
> [MINOR] typo

- .circleci/config.yml
add the binary on ci at build time, dont need it to be in the code base
> add the binary on ci at build time, dont need it to be in the code base

- besu/src/main/java/org/hyperledger/besu/services/BesuPluginContextImpl.java
Because of how the Log4J2 api works exception stack traces were not
being printed.  Update to use the explicit "throwable" overloaded
methods.
> Plugin error stack traces

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractEthTask.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractEthTaskTest.java
A prior refactoring had accidentally removed the specific task names
from the metrics labels.
> More specific task metrics names

- CHANGELOG.md
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PingPacketData.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryPacketPcapSedesTest.java
Broadcast that we support snappy compression
> [BESU-25] Ping at v5

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/AutoTransactionLogBloomCachingService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionLogBloomCacher.java
Since we use mutable files for the cache we can directly cache log blooms in the proper cache file.
The location of the cache file is deterministic based on the cache directory and the block number.
The block number is used to get the index in the binary file to write to.
[PIE-2303](https://pegasys1.atlassian.net/browse/PIE-2303)
> [PIE-2303] Automatic log bloom caching - Remove usage of pending file.

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/PluginsReloadConfiguration.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
When calling `plugins_reloadPluginConfig` on a missing plugin, the error shown is an internal error rather than a more generic "Plugin Not Found" error. We should return the latter. 
https://pegasys1.atlassian.net/browse/PIE-2305
> [PIE-2305] Plugins - Create Plugin Not Found error.

- CHANGELOG.md
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
- besu/src/main/java/org/hyperledger/besu/Runner.java
- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/GenerateLogBloomCache.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- besu/src/test/resources/everything_config.toml
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminGenerateLogBloomCache.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/AutoTransactionLogBloomCachingService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/AutoTransactionLogsIndexingService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionLogBloomCacher.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionLogsIndexer.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminGenerateLogBloomCacheTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueriesLogCacheTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/Blockchain.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/ChainReorgObserver.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchain.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/TestBlockchain.java
Add a new option `--auto-logs-bloom-indexing-enabled` which defaults to true. This performs the equivalent of the `operator generate-log-bloom-cache` CLI task or `admin_generateLogBloomCache` RPC call for each block as it arrives, in addition to caching older logs on first startup.
> Automatically cache Transaction Log Bloom Filters

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionLogBloomCacher.java
Do a cursory cache check at start up (file is present and correct size)
instead of re-generating the cache at startup.
> Reduce recaching in Transaction Log Bloom Filter Cache

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionLogBloomCacher.java
Do a cursory cache check at start up (file is present and correct size)
instead of re-generating the cache at startup.
(cherry picked from commit e28396a5dcb8cff094fc1d5b358cb46d8e8693fe)
> Reduce recaching in Transaction Log Bloom Filter Cache (#415)

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocol.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/messages/StatusMessage.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTestUtil.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManagerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/messages/StatusMessageTest.java
Wire in the fork identifier into the status messages as Eth64.
> Implement Eth/64

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGas.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java
Bug - when calculating eth_estimateGas, we always return a success response even if an error has occurred. 
Solution - We should first check to see if the result is valid and return an error response otherwise.
> BESU-146 - check if success and return errorResponse otherwise

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Address.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/AddressTest.java
> [MINOR] fixed typos

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyAcceptanceTestBase.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/transaction/PrivacyTransactions.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/privacy/PrivGetCodeTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/privacy/PrivacyRequestFactory.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/PrivGetCodeAcceptanceTest.java
- ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivGetPrivateTransactionIntegrationTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetCode.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivJsonRpcMethods.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivacyApiGroupJsonRpcMethods.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetCodeTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/DefaultPrivacyController.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/MultiTenancyPrivacyController.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivacyController.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateWorldStateReader.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/DefaultPrivacyControllerTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/MultiTenancyPrivacyControllerTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/PrivateWorldStateReaderTest.java
• Moved the logic to read the code from the private world state into PrivateWorldStateReader
• Channelling the access from PrivGetCode to PrivateWorldStateReader through the PrivacyController to enforce multi-tenancy rules
• Created an acceptance test for PrivGetCode
> Fix priv_getCode on multi-tenancy

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/LogsQuery.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/LogsQueryTest.java
LogsQuery may get passed in address lists and topics in arrays that do
not tolerat being checked for null members.  This is an unexpected and
subtle situation hence the long comment.
This new test would also trigger as it passes in null-intolerant lists.
> Copy logs query to null-tolerant collections

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
Fixed log level setting that was overriding the setting in log4j.xml file during startup.
> Fix log level setup during startup

- CODE_OF_CONDUCT.md
- SECURITY.md
This Bring our code of conduct and security file in line with automated
checks.
The changes to `SECURITY.md` are strictly formatting, adding newlines so
it line wraps at 80 lines.
The `CODE_OF_CONDUCT.md` is a more substantial change.  Rather than the
being subject to both the contributor covenant and the Hyperledger CoC
this change makes the project only subject to the Hyperledger CoC.
> Update Code of Conduct and Security

- CHANGELOG.md
Changelog entry for https://github.com/hyperledger/besu/pull/454 for bug where rpc authentication would be enabled even if it was disabled if a credentials file was specified
> changelog for bug where rpc authentication would be enabled even if a credentials file was specified

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/privacy/PrivacyNodeConfiguration.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/privacy/PrivacyNodeFactory.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyNode.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/transaction/RemoveFromOnChainPrivacyGroupTransaction.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/OnChainPrivacyAcceptanceTest.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/resources/everything_config.toml
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/eea/EeaSendRawTransaction.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EeaJsonRpcMethods.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivJsonRpcMethods.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivxJsonRpcMethods.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/eea/EeaSendRawTransactionTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivJsonRpcMethodsTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivxJsonRpcMethodsTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/PrivacyParameters.java
This PR adds a flag for using onchain privacy groups (`--privacy-onchain-groups-enabled`). This is used to ensure that offchain privacy groups can't be used at the same time as offchain privacy groups.
> Adding onchain privacy groups flag

- enclave/build.gradle
- enclave/src/main/java/org/hyperledger/besu/enclave/EnclaveFactory.java
- enclave/src/test/java/org/hyperledger/besu/enclave/EnclaveFactoryTest.java
-- Fix privacy enclave keystore password file reading eol issue
-- Read password from first line instead of reading whole file as bytes
-- Raise appropriate exceptions if file is empty or only contains eol as first line.
fixes #525 
> Fix privacy enclave keystore password file reading eol issue

- acceptance-tests/tests/build.gradle
- build.gradle
- gradle/check-licenses.gradle
- gradle/versions.gradle
License reporting depends on the deprecated "compile" dependency in the
root project.  Restore that so that license checking can work.
Also clean out old unused license types and one unneeded dependency.
> Fix License Check

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/SyncStateAdapter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/SyncingResult.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/AbstractEthGraphQLHttpServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/health/ReadinessCheckTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSyncingTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/syncing/SyncingSubscriptionServiceTest.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/eth_syncing.json
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/DefaultSyncStatus.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastDownloaderFactory.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/state/SyncState.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/worldstate/CompleteTaskStep.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/worldstate/WorldStateDownloadStatus.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/worldstate/WorldStateDownloader.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/SyncStatus.java
The EthQL API spec specifies pulledStates and knownStates in the
`syncing` query. Previously we always returned null. This plumbs through
the needed data so that the synchronization states can report the
fast sync progress via EthQL, as well as the `eth_syncing` JSON-RPC.
> Add fast sync status to eth_syncing and EthQL query

- gradle/versions.gradle
Signed-off-by: Horacio Mijail Anton Quiles <hmijail@gmail.com>
Upgrade junit to 4.13, which allows junit's MultipleExceptions to display the individual exceptions they contain and where they appeared.
> Upgrade junit to 4.13

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionLogBloomCacher.java
If we detect an EOF for the cache file switch over to an uncached query.
This is typically seen when filling a log filter and the new block has
not yet written out the log bloom cache to disk.  Fixed #473
> LogBloomCache - Do uncached query if EOF is detected

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionReceipt.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContract.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateGroupRehydrationBlockProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/storage/PrivateStateKeyValueStorage.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContractTest.java
• Storing private tx receipts indexed by PMT hashes
• Updated priv_getTransactionReceipt to have a fallback method to use the private tx hash for backwards compatibility
> Storing private tx receipts indexed by PMT hashes

- besu/src/main/java/org/hyperledger/besu/cli/util/EnvironmentVariableDefaultProvider.java
- besu/src/test/java/org/hyperledger/besu/cli/EnvironmentVariableDefaultProviderTest.java
Bypass default value from environment variable provider for positional parameter. In case of subcommands such as help this could have thrown class cast exception
> Fix potential bug in Env default value provider

- besu/src/main/java/org/hyperledger/besu/controller/CliqueBesuControllerBuilder.java
- consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/CliqueProtocolSchedule.java
- consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueBlockCreator.java
- consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueMinerExecutor.java
- consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/CliqueProtocolScheduleTest.java
- consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueBlockCreatorTest.java
- consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueMinerExecutorTest.java
Updates the Clique mining classes to use the NodeKeys framework (Created in PR #618) (rather than KeyPair directly) - allowing Clique to use pluggable crypto.
N/A
> Update Clique classes with NodeKey structure

- crypto/src/main/java/org/hyperledger/besu/crypto/BouncyCastleNodeKey.java
- crypto/src/main/java/org/hyperledger/besu/crypto/NodeKey.java
- crypto/src/main/java/org/hyperledger/besu/crypto/SECP256K1.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/handshake/ecies/ECIESEncryptionEngine.java
It was identified that during the creation of injectable crypto, that the NodeKey effectively offered duplicated functionality between ECDH and ECIES key agreements. The ECIES was superfluous and has been removed.
N/A
> Remove unused ECIES Agreement from NodeKey

- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/GeneralStateReferenceTestTools.java
Speed up build time by removing some of the most time consuming reference 
tests.
* CALLBlake2f_MaxRounds - runs Blake2f 4 billion rounds, something no
one ever does and there is never enough gas to do. We have a unit test
for this already.
* The "do this 50k times" tests.  Each has a smaller "5k times" or less
variant. This drifts into performance testing instead of conformance
testing
> Speed up build time

- besu/src/main/java/org/hyperledger/besu/Runner.java
It is possible for the service furture to fail exceptionally before we
first poll for waiting, so we should switch to a do/while loop so we
will get the exception re-thrown instead of ignoring it.
This may fix #662
> Deal with quick service start failures

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MutableProtocolSchedule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSpec.java
Pull two methods out of ProtocolSpec into the only class that uses them.
This is in preparation for future refactoring of the ProtocolSpec.
> Refactor methods out of ProtocolSpec

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PeerPendingTransactionTracker.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactionSender.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactionsMessageProcessor.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactionsMessageProcessorTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactionsSenderTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolTest.java
Make sure to not enroll peers that do not support eth/65 for sending pending transactions, as the client will otherwise throw an error when negotiating sending the message to the peer.
Fixes #723
> Fix support of peers that do not support eth/65

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/OnChainPrivacyAcceptanceTest.java
Adding a test to ensure that a former member of a privacy group cannot transact in the group.
> add AT for onchain privacy

- besu/src/main/java/org/hyperledger/besu/Runner.java
- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/RunnerTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- besu/src/test/resources/everything_config.toml
- docker/Dockerfile
This PR adds a healthcheck to the Docker image shipped by default with Besu.
The healthcheck itself consists in checking that Besu has written a file to a specific path.
The file contains the PID of the process.
The file is deleted if the process exits normally. The program does not attempt to try to clean up the file if the process exits abnormally.
> Healthcheck

- CHANGELOG.md
- KNOWN_ISSUES.md
Moved previously identified known issues into separate file
> Moved previously identified known issues into separate file

- CHANGELOG.md
> Changelog update for #713

- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandLineUtilsTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
- errorprone-checks/build.gradle
- errorprone-checks/src/main/java/org/hyperledger/errorpronechecks/PrivateStaticFinalLoggers.java
- errorprone-checks/src/test/java/org/hyperledger/errorpronechecks/PrivateStaticFinalLoggersTest.java
- errorprone-checks/src/test/resources/org/hyperledger/errorpronechecks/PrivateStaticFinalLoggersNegativeCases.java
- errorprone-checks/src/test/resources/org/hyperledger/errorpronechecks/PrivateStaticFinalLoggersPositiveCases.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/AutoTransactionLogBloomCachingService.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/AncestryValidationRule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/CalculatedDifficultyValidationRule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/EIP1559BlockHeaderGasLimitValidationRule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/EIP1559BlockHeaderGasPriceValidationRule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/ExtraDataMaxLengthValidationRule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/GasUsageValidationRule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/TimestampBoundedByFutureParameter.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/TimestampMoreRecentThanParent.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/BLAKE2BFPrecompileContract.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/MockPeerDiscoveryAgent.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/TomlConfigFileParser.java
- nat/src/main/java/org/hyperledger/besu/nat/NatService.java
- nat/src/main/java/org/hyperledger/besu/nat/core/AbstractNatManager.java
- nat/src/main/java/org/hyperledger/besu/nat/docker/DockerNatManager.java
- nat/src/main/java/org/hyperledger/besu/nat/kubernetes/KubernetesNatManager.java
- nat/src/main/java/org/hyperledger/besu/nat/manual/ManualNatManager.java
- nat/src/main/java/org/hyperledger/besu/nat/upnp/BesuUpnpServiceConfiguration.java
- nat/src/main/java/org/hyperledger/besu/nat/upnp/UpnpNatManager.java
Some of our loggers were not private, static, and final.  In a few
cases these were non-static fields in classes that were repeatedly
instantiated in core transaction logic.
This is enforced via a new ErrorProne check, so the PR includes fixes
for all of the places this was a problem, not just the performance
impacting code.
> Loggers should be private, static and final.  Enforced with errorprone

- acceptance-tests/tests/build.gradle
- build.gradle
- ethereum/evmtool/build.gradle
- gradle/versions.gradle
- gradle/wrapper/gradle-wrapper.properties
* Change Gradle version to 6.3
* Enables Java 14
* Clean up Gradle compatibility warnings
* Fix stray dependency version
> Gradle 6.3 upgrade

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/AbstractWorldUpdater.java
When updating an account we often calculate the address hash multiple
times.  We also will always calculate it at least once when tracking an
account update.  Hence, just calculate it in the constructor and re-use
it.
> Performance: Cache address hash

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetLogs.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthNewFilter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/BlockParameter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/FilterParameter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetLogs.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivNewFilter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/SubscriptionBuilder.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/logs/LogsSubscription.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/logs/LogsSubscriptionService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/request/SubscribeRequest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/request/SubscriptionRequestMapper.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthNewFilterTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/FilterParameterTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetLogsTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivNewFilterTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/SubscriptionBuilderTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/logs/LogsSubscriptionServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/request/SubscriptionRequestMapperTest.java
Geth sneakily accepts from and to blocks in its websocket log subscriptions parameters. This extends the websocket subscription to be able to take block parameters. That makes us compatible with their implementation and also our http and ws filter parameters align.
fixes #654
> recognize from and to block parameters in eth subscribe

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/FeeMarket.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/FeeMarketConfig.java
Set the gas block limit as a factor of the target gas usage instead of hard coded value.
#817 
> [EIP-1559] Set the gas block limit as a factor of the target gas usage instead of hard coded value.

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/BlockResult.java
Update eth_getBlock* to add base fee in the response.
#840 
> Update eth_getBlock* to add base fee in the response.

- consensus/ibft/src/integration-test/java/org/hyperledger/besu/consensus/ibft/tests/round/IbftRoundIntegrationTest.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/network/IbftMessageTransmitter.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/payload/MessageFactory.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/statemachine/IbftBlockHeightManager.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/statemachine/IbftController.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/statemachine/IbftRound.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/statemachine/IbftRoundTest.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/handshake/ecies/ECIESHandshaker.java
IbftRound has been updated to handle Signing errors (eg no signature supplier available) and
continue operating if possible.
> Ibft now handles failing sign operations

- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionReceiptTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/RewardTraceGeneratorTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/TransactionGasBudgetCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicBlockProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSpec.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSpecBuilder.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/fees/TransactionGasBudgetCalculatorTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockProcessorTest.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/NoRewardProtocolScheduleWrapper.java
- `MAX_GAS_EIP1559` acts as the hard in-protocol gas limit, instead of the gas limit calculated using the previously existing formulas
- The `GASLIMIT` field in the block header is the gas limit for the `EIP1559 gas pool`, and over the transition period this value increases until it reaches `MAX_GAS_EIP1559` at `FINAL_FORK_BLKNUM`
- The gas limit for the legacy gas pool is `MAX_GAS_EIP1559 - GASLIMIT`, as `GASLIMIT` increases towards `MAX_GAS_EIP1559` gas is moved from the legacy pool into the EIP1559 pool until all of the gas is in the EIP1559 pool
- At `block.number == INITIAL_FORK_BLKNUM, let GASLIMIT = (MAX_GAS_EIP1559 / 2)` so that the gas maximum is split evenly between the legacy and EIP1559 gas pools
- As `block.number` increases towards `FINAL_FORK_BLKNUM`, at every block we …
> [EIP-1559] Compute transaction gas budget allocation according to EIP-1559 rules.

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetWork.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetWorkTest.java
- Updated `eth_getWork` response to add hex encoded current block number.
- Updated unit tests accordingly.
```bash
curl --data '{"method":"eth_getWork","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```
```json
{
"jsonrpc": "2.0",
"id": 1,
"result": [
"0xce5e32ca59cb86799a1879e90150b2c3b882852173e59865e9e79abb67a9d636",
"0x0000000000000000000000000000000000000000000000000000000000000000",
"0x00a3d70a3d70a3d70a3d70a3d70a3d70a3d70a3d70a3d70a3d70a3d70a3d70a3",
"0x42"
]
}
```
#849 
> Add current block number to eth_getWork response

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockByHash.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/DebugStorageRangeAtResult.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethService.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestMineBlocks.java
When in retesteth return the coinbase in the eth_getBlockByHash, as
required by the retesteth tool.
> Retesteth eth_getBlockByHash requires "author" field.

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactionsMessageProcessor.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactory.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactionsMessageProcessorTest.java
prior to Eth/65 we did not participate in transaction gossiping until we
were close to in sync.  With this change we won't request pooled
transaction hashes until we are similarly close to sync.
> Eth/65 - don't request transactions when out of sync

- metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/MetricsHttpService.java
When a request is made to the metrics service with no host header, it should be allowed if `*` is whitelisted and rejected otherwise.  Currently it fails with a `NullPointerException`.
> Handle metrics requests with no host header

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/EnclavePublicKeyProvider.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EeaJsonRpcMethods.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivacyApiGroupJsonRpcMethods.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketRequestHandler.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/methods/AbstractPrivateSubscriptionMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/methods/PrivSubscribe.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/methods/PrivUnsubscribe.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/methods/PrivateWebSocketMethodsFactory.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/methods/WebSocketMethodsFactory.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/SubscriptionBuilder.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/SubscriptionManager.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/logs/LogsSubscriptionService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/logs/PrivateLogsSubscription.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/request/InvalidSubscriptionRequestException.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/request/PrivateSubscribeRequest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/request/PrivateUnsubscribeRequest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/request/SubscriptionRequestMapper.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/response/SubscriptionResponse.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/response/SubscriptionResponseResult.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketRequestHandlerTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/methods/PrivSubscribeTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/methods/PrivUnsubscribeTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/SubscriptionBuilderTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/SubscriptionManagerSendMessageTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/logs/LogsSubscriptionServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/request/SubscriptionRequestMapperTest.java
• Created the two private subscription-related methods (priv_subscribe/priv_unsubscribe)
• Created a new type of subscription `PrivateLogsSubscription`
• Updated `LogsSubscriptionService` to observe new blocks and check for private logs (similar to what is done in the `FilterManager`).
• Updated `WebSocketRequestHandler` to deal with `InvalidJsonRpcParameters` exception
• Some plumbing work to get everything working together!
fixes #762
> Add support for private log subscriptions (Pub-Sub API)

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/DebugStorageRangeAtResult.java
Retesteth requires even length quantities (in contravariance to the Eth
JSON-RPC standards).  For storage range at provide even length
quantities.
> Cope with retesteth's aversion to odd quantities

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcErrorConverter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcErrorConverterTest.java
I noticed that when we send a tx with the wrong chainId, Besu returns a generic "Invalid Params" (not super helpful). This PR is mapping `WRONG_CHAIN_ID` and `REPLAY_PROTECTED_SIGNATURES_NOT_SUPPORTED` tx validation errors to JsonRpcErrors so the user knows what is wrong with the tx.
Thanks to @pinges for finding out this was happening! I could've saved him a few hours... :)
> Exposing chainId related errors on JSON-RCP responses

- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- nat/src/main/java/org/hyperledger/besu/nat/NatMethod.java
- nat/src/main/java/org/hyperledger/besu/nat/manual/ManualNatManager.java
- nat/src/test/java/org/hyperledger/besu/nat/manual/ManualNatManagerTest.java
This reverts commit 013280b843c86ba04715e4315713fdcc10443625.
We must wait for a quarterly version before changing the CLI options
> Revert "Remove manual nat manager (#921)"

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolConfiguration.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolReplacementHandler.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionReplacementByPriceRule.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactionsTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionReplacementByPriceRuleTest.java
We should implement a new transaction replacement mechanism, similar to other client implementations.
Currently a new transaction (same user and same nonce) replaces an old one if the new gas price is higher than the old one. Other client implementations require the delta to be higher than a minimum percentage.
For instance this option is called `pricebump` in Geth implementation, configurable using `--txpool.pricebump` . This command line option is described as Price bump percentage to replace an already existing transaction and is defaulted to `10%`.
The current PR introduces the price bump without making this option configurable. A follow up PR will then come after to expose this parameter to the `CLI` interface.
- #559 
- #906 
Signed-off-by: Abdelhamid Bakhta …
> Implement price bump mechanism for transaction pool replacement.

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/FlatTraceGenerator.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/chain-data/blocks.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs/trace-block/trace_block_0x1C.json
Calling `trace_block` or `trace_transaction` rpc method fails with a `NullPointerException` when a transaction consists of a contract creation in which the contract self destructs within its own constructor.  
This PR fixes this bug.
fixes #911 
> Fix NullPointerException in FlatTraceGenerator.

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/DebugOperationTracer.java
Calling trace_block for block [#4063089](https://ropsten.etherscan.io/block/4063089) in Ropsten causes the DebugOperationTracer to throw an IndexOutOfBoundsException.
fixes #915 
> Fix IndexOutOfBoundsException in DebugOperationTracer

- .circleci/config.yml
In the event that someone who has forked this repository sets up CircleCI integrations for it, we would like that builds on their master branch would not be able to send alerts to the Hyperledger Rocket Chat #besu-contributors channel.  Here we move to having the notification web-hook be sent to an address set by the `HUBOT_URL` variable instead.  This environment variable is set in the CircleCI web-app in the same place we set the variables for our secrets for other 3rd party app access.
It has been tested that an environment without the variable being set would cause no issues for the CircleCI build system either for other forked projects.
> Set the notifications webhook by URL to prevent false alerts

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManagerTest.java
While implementing EIP-1559, we realized our EIP-2124 implementation differs from geth in how we handle forks on block #0.
In short, if we set fork block numbers to 0 to activate fork rules directly for a private network Besu nodes don't include those forks to compute the fork ID, Geth includes them. That results in an error and Besu nodes cannot connect to Geth nodes.
If we change to comply with geth, all previous Besu versions using the non-geth way will not interoperate with future Besu versions.
This PR introduces a more permissive check for private networks and aims to be backward compatible with previous versions.
> [EIP-2124] Backward compatible fork id management implementation

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManagerTest.java
Fork Id computation has been updated to work with Geth nodes in consortium networks.
Besu should allow fork id generated with old versions of Besu.
fixes #980 
> Handle backward compatibility for EIP-2124 fork id management

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/FindNeighborsPacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PingPacketData.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/MockPacketDataFactory.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryControllerTest.java
Don't respond to neighbors and ping packets that have an expiration
prior to the system's current time.
Addresses two tests in #975
> Enforce devp2p packet expiration

- build.gradle
SPDX checks shouldn't be done against jmh generated files.  Make it
generic so that the gradle/intellij favoured location of generated files
will never be a problem. These are also covered by `.gitignore` already.
> update spdx exclusions

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
Prevent user from starting up Besu using multi-tenancy AND onchain privacy groups. The support for using both features at the same time is under development and targeting 1.5 release.
> Add gate for multi-tenancy + onchain privacy groups

- CHANGELOG.md
- KNOWN_ISSUES.md
Updated known issues for 1.4.6
> Updated known issues for 1.4.6 

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManagerTest.java
Rollback a Eth64 change intended to improve compatibility in consortium network.  It resulted in many nodes not connecting on named networks such as goerli and mordor.
> Improve Eth/64 compatibility

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/FindNeighborsPacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/NeighborsPacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PingPacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PongPacketData.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryPacketSedesTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/FindNeighborsPacketDataTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/MockPacketDataFactory.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/NeighborsPacketDataTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryControllerTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PingPacketDataTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PongPacketDataTest.java
DevP2P packets expiration fields should be in seconds past the epoch,
not milliseconds past the epoch.
> DevP2P expiration conformance

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/eth/SanityCheckEthGetWorkValues.java
The EthGetWork.shouldReturnSuccessResponseWhenMining was exhibiting intermittent failures, as a mining node would occasionally report "No mining work available yet" - rather than the inputs required to be solved for the current block.
From investigation, it was found that Besu's EthHash miner has a small time window after completing a block, in which the target for the next block has not yet been computed (eg while collating transactions) - during this interval, Besu will validly report "No mining work available yet".
To overcome this, the acceptance test has been updated to poll Besu for upto 5 seconds, waiting for a valid work target to be provided - rather than executing a single-attempt (which may fall within the window specified above).
> Repair intermittent EthGetWork test

- CHANGELOG.md
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/eth/SanityCheckEthGetWorkValues.java
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
- config/src/main/resources/classic.json
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
- config/src/test/resources/valid_config_with_etc_forks.json
This PR implements functionality to ignore ClassicForkBlock chain config parameter in getForks method. Since getForks method is intended to list blocks when chains have forked, and the ClassicForkBlock parameter is to define when a fork on classic network did NOT happen, it should not be included in this list.
update ETC gotham fork number to conform with spec.
> update getForks to ignore ClassicForkBlock param, update gotham number

- besu/src/main/java/org/hyperledger/besu/cli/util/TomlConfigFileDefaultProvider.java
- besu/src/test/java/org/hyperledger/besu/cli/TomlConfigFileDefaultProviderTest.java
This PR resolves an issue in decoding nested TOML arrays, where the default value decoder would always assume a multi-value/array was only one level deep. In so doing, toString would be called, even when the array element was an array itself, resulting in a parsing error.
This PR tests each array element during decoding to see if it is an array itself, and if it is, the decoding function is called recursively until a base primitive is found. In addition, this PR allows the `TomlConfigFileDefaultProvider` to determine if a `picocli` option should be treated as a multi-value, even if the base type failed to implement Collection.
Fixes issue in PegaSys Plus/plugins.
Signed-off-by: Steven J Schroeder <steven.schroeder@consensys.net>
> Accept Nested TOML Array for Default Value Decoding

- besu/src/main/java/org/hyperledger/besu/Besu.java
- besu/src/main/java/org/hyperledger/besu/chainimport/RlpBlockImporter.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- besu/src/test/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommandTest.java
Extend the `blocks import` subcommand to accept multiple files in the
command line and import them in the same batch.
> Bulk block file import

- besu/src/main/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommandTest.java
Add an option to run besu after blocks import.  This is aimed to cut the
startup penalty in half for hive testing, combining the block import
with the node execution.
> Option to run besu after blocks import

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/AbstractCallOperation.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/Memory.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/MessageFrame.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/GeneralStateReferenceTestTools.java
Performance measurements have indicated that the list of Bytes32 for
memory is not performant enough. Moving to a byte array reduces wrapper
object thrashing as well as simplifying cross-word boundary logic (there
are no boundaries).
> Move EVM memory to a flat bytes array

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/CheckpointHeaderValidationStep.java
When the first header in the last checkpoint range of a sync fails validation, Besu attempts to create an `InvalidBlockException` which includes the range being downloaded.  Since this is the last checkpoint range there is no end so a `NoSuchElement` exception is thrown while trying to build that error.
#582 and #992 are encountering this error.  Both may have separate underlying issues that need further investigation to determine why the block is invalid.
> Don't throw NoSuchElementException when the last checkpoint range fails validation

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/cluster/Cluster.java
In AT, when starting a cluster of nodes, they are to be started in parallel rather than sequentially.
This appears to not affect test stability, while offering a time saving.
> Allow nodes to start in parallel during AT

- enclave/src/main/java/org/hyperledger/besu/enclave/Enclave.java
- ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivGetPrivateTransactionIntegrationTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetPrivateTransaction.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionReceipt.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivJsonRpcMethods.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetPrivateTransactionTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionReceiptTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PrivacyBlockProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/DefaultPrivacyController.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/ExecutedPrivateTransaction.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/MultiTenancyPrivacyController.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivacyController.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateTransaction.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateTransactionLocator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateTransactionWithMetadata.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/PrivateTransactionDataFixture.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/PrivateTransactionLocatorTest.java
- Created method `findPrivateTransactionByPmtHash(..)` on `PrivacyController`. This method is used to return a private transaction that has been executed (contains an associated PMT and the hash of the block that the PMT was included in the chain.
- Updated `PrivGetPrivateTransaction` and `PrivGetPrivateTransactionReceipt` to use the new controller method, avoiding code duplication.
- Updated the code when retrieving the payload from the transactions blob in the Enclave to always use the associated participant public key. This makes the retrieval of this data compatible with multi-tenancy.
**IMPORTANT**: this work is ongoing and complete support for multi-tenancy and flexible privacy groups isn't complete.
(see #879 and #880)
> Initial support for multi-tenancy with flexible privacy groups

- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- besu/src/test/resources/everything_config.toml
- nat/src/main/java/org/hyperledger/besu/nat/kubernetes/KubernetesNatManager.java
- nat/src/test/java/org/hyperledger/besu/nat/kubernetes/KubernetesNatManagerTest.java
Add cli option to specify the name of the loadbalancer used by the Kubernetes nat manager 
`--Xnat-manager-pod-name`
We can specify the name of the load balancer
```yaml
---
apiVersion: v1
kind: Service
metadata:
labels:
app.kubernetes.io/name: besu
app.kubernetes.io/release: "1.0.0"
name: besu-custom-name
spec:
ports:
- name: "json-rpc"
port: 8545
targetPort: 8545
- name: "rlpx"
port: 30303
targetPort: 30303
selector:
app.kubernetes.io/name: besu
app.kubernetes.io/release: "1.0.0"
type: LoadBalancer
```
And add the `BESU_XNAT_MANAGER_POD_NAME`on the deployment script of Besu to specify the name.
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
name: besu-config
labels:
app.kubernetes.io/name: besu
app.kubernetes.io/release: 1.0.0
data:
BESU_LOGGING: "DEBUG"
.... …
```
> Add cli option to specify the name of the loadbalancer used by the Kubernetes nat manager 

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/BlockResult.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getBlockByNumber_complete.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getBlockByNumber_hashes.json
Add missing `mixHash` field for `eth_getBlockBy*` JSON RPC endpoints.
Affected JSON RPC endpoints:
- **eth_getBlockByHash**
- **eth_getBlockByNumber**
|  Item 	|  Manual tests 	| Unit tests | 
|---	|---	|--- |
|   eth_getBlockByHash	| * | * |
|   eth_getBlockByNumber	| * | * |
Updated test specification files:
- `eth_getBlockByNumber_complete.json`: added expected `mixHash` json field in response.
- `eth_getBlockByNumber_hashes.json`: added expected `mixHash` json field in response.
```json
{
"jsonrpc": "2.0",
"id": 1,
"result": {
"number": "0x2",
"hash": "0x6d5fef8800e21e32e57132672dfa0afd2d893ac0fee2f21f59e5fc287dae1bba",
"mixHash": "0xa8dc926337449743bc58dd06c7eef1a67f7e55c00e89f17e3df374bf9c0b3ec0",
"parentHash": "0x5311ed4d6103d6768a67df8710ef9b4f440f4af2dcd244e76fbbdf88d9d98ca2", …
```
> Add missing mixHash field for eth_getBlockBy* JSON RPC endpoints

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermAddAccountsToWhitelist.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermAddNodesToWhitelist.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermGetAccountsWhitelist.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermGetNodesWhitelist.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermRemoveAccountsFromWhitelist.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermRemoveNodesFromWhitelist.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PermJsonRpcMethodsTest.java
Refactoring to remove duplicated code. Whitelist methods now extend the Allowlist methods and just override getName()
See #1108
> Permissioning Whitelist JSON-RPC methods now extend Allowlist methods

- metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/MetricsConfiguration.java
Deprecated in favour of get/setAllowlist rather than removing which may break things elsewhere
> [MINOR] Metrics: reinstated get/setWhitelist with Deprecated warning

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/account/Account.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/ibft2/Ibft2BlockRewardPaymentAcceptanceTest.java
- acceptance-tests/tests/src/test/resources/ibft/ibft.json
- besu/src/main/java/org/hyperledger/besu/controller/IbftBesuControllerBuilder.java
- config/build.gradle
- config/src/main/java/org/hyperledger/besu/config/IbftConfigOptions.java
- config/src/test/java/org/hyperledger/besu/config/JsonGenesisConfigOptionsTest.java
- config/src/test/resources/valid_config_with_custom_forks.json
- consensus/ibft/src/integration-test/java/org/hyperledger/besu/consensus/ibft/support/TestContextBuilder.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/IbftProtocolSchedule.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/blockcreation/IbftBlockCreator.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/blockcreation/IbftBlockCreatorFactory.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/IbftProtocolScheduleTest.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/blockcreation/IbftBlockCreatorTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicBlockProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockProcessor.java
Allow IBFT2 to deliver block rewards (of a configurable value), and transaction fees to a configured address.
> Added configurable block reward and recipient for IBFT2

- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/EIP1559.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/FeeMarket.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/FeeMarketConfig.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockBodyValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockHeaderValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidatorTest.java
Removes riders as specified in: https://github.com/ethereum/EIPs/pull/2635
> Remove block size and transaction size riders from EIP 1559.

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/authentication/AuthenticationUtils.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/JsonRpcMethod.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceLoginTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/NetListeningTest.java
- ethereum/api/src/test/resources/JsonRpcHttpService/auth.toml
Exit early when checking user permissions, ie if matching permission is found, don't keep checking.
Also reordered permissions produced by JsonRpcMethod to be in descending order of granularity
Added unit test for *:* permission
See #1118
> Improvements to authenticated JSON-RPC permissions checking

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/StructLog.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceTransactionTest.java
Signed-off-by: David Mechler <david.mechler@consensys.net>
Changed the `StructLog` code to use an unprefixed hex string for memory and stack values.
- Ran test suite locally
- Started Goerli sync
- Started Ropsten sync
- Started mainnet sync
#1066
> #1066 Switched to use unprefixed hex strings for memory and stack values

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractRetryingPeerTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTask.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ethtaskutils/AbstractMessageTaskTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java
This PR fixes an error when downloading chain (Async operation failed)
When there are several blocks which are very large (> 12M) and which are requested in the same segment (by default 200) we can have timeouts and never manage to synchronize. This modification will make it possible to gradually reduce the size of the segment with each attempt. Then the segment resumes its default size for the next blocks
If the reduction is not enough at the last attempt we try with a single block
| Test |   |  
|-------|---|
|      Mordor - Fullsync after already Fastsync completed     |  OK  |   
|      Mordor - Complete Fastsync        | OK  |   
|      CLIQUE - Local      |  OK |   
|      IBFT - Local     | OK  |  
|      IBFT - Lacchain     | OK  | …
> Fix sync timeout issue 

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/NettyConnectionInitializer.java
When starting with p2p-port already in use, the error (including stack trace) comes out twice
See #1064
> remove duplicate logging of P2P port conflicts on startup

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTlsTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/TlsOkHttpClientBuilder.java
Enable http/2 support for Json RPC Http API over TLS
Fixes issue #519 
> [#519] - Enable http/2 support for Json RPC Http API over TLS

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/Quantity.java
With privacy enabled, it is only valid to omit --privacy-marker-transaction-signing-key-file
if --min-gas-price=0
So - if --privacy-enabled and --min-gas-price > 0 and --privacy-marker-transaction-signing-key-file not specified, throw exception and prevent startup.
See #505
> exception if --privacy-marker-transaction-signing-key-file not specified in non-zero-gas network

- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/GeneralStateReferenceTestTools.java
Update to the reference tests used on hivetests.etherdevops.io and
retesteth.etherdevops.io.  Both are using a more current release of the
reference tessts that includes performance and subroutines items.
> Update Reference Tests

- CHANGELOG.md
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/multitenancy/MultiTenancyAcceptanceTest.java
- enclave/src/main/java/org/hyperledger/besu/enclave/EnclaveConfigurationException.java
- ethereum/core/src/integration-test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContractIntegrationTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractPrecompiledContract.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/OnChainPrivacyPrecompiledContract.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContract.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/PrivateTransactionDataFixture.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContractTest.java
- gradle/versions.gradle
- testutil/src/main/java/org/hyperledger/orion/testutil/OrionConfiguration.java
- testutil/src/main/java/org/hyperledger/orion/testutil/OrionTestHarness.java
- testutil/src/main/java/org/hyperledger/orion/testutil/OrionTestHarnessFactory.java
Adds strict privateFrom checking for private transactions.
This change requires Orion 1.6+ to work.
(WARNING: this PR CI build won't work until we release Orion 1.6)
> Add strict check for privateFrom in private txs

- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestImportRawBlock.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestSetChainParams.java
Besu's Retesteth implementation failed transition tests.  Two reasons:
* It wasn't adding the DaoForkBlock to genesis files correctly
* It wasn't using the  protocol schedules og the block being imported,
but instead to the current chain head.
> Fix retesteth testing of blockchain transition tests

- ethereum/referencetests/build.gradle
- gradle/versions.gradle
Add a check test to fail the build if the reference test submodule is
accidentally updated.
> Add Reference Test checker

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyNode.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/PrivacyTest.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetPrivacyPrecompileAddressTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/PrivacyParameters.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetPrecompiledContractRegistries.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSpecBuilder.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetPrecompiledContractRegistriesTest.java
Deprecate the CLI option and log a warning if used. Derive the address instead based on whether onchain privacy groups option is enabled.
See #469
> deprecate CLI option for privacy precompile address

- CHANGELOG.md
- KNOWN_ISSUES.md
> Release 1.5.1 Changelog updates

- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/NodePermissioningControllerFactory.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/node/InsufficientPeersPermissioningProvider.java
- ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/node/NodePermissioningControllerFactoryTest.java
Do not create sync status permissioning check if onchain permissioning is not enabled.
There was a flaw in the logic in that if onchain permissioning was configured (but not enabled) AND fixed nodes configured ie bootnodes, then the sync status permissioning check was rejecting connections.
> Sync status permissioning check conditional on onchain permissioning enabled

- util/src/main/java/org/hyperledger/besu/util/platform/PlatformDetector.java
How the GraalVM reports itself in the vendor and vm flags has evolved in
newer version.  Report GraalVM if it is seen in either string.
> Update GraalVM detection in Platform Detector

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/DiscoveryPeer.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/VertxPeerDiscoveryAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgentTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryTestHelper.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/MockPeerDiscoveryAgent.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetworkTest.java
Rework discovery-level handling of static peers to fix a few issues:
* Make sure that permissions are respected when pushing static peers into the discovery layer
* Initiate ping-pong bonding cycle rather than directly adding peers to our peer table to ensure that peer is live and running discovery
* Check that enode url indicates discovery protocol is running before attempting to bond with peer
* Remove duplicate `dropPeer` logic
Fixes #1278
> [Issue 1278] Rework static peer discovery handling

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/BlockAdapterBase.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/EmptyAccountAdapter.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/AbstractDataFetcherTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/BlockDataFetcherTest.java
When IBFT produces blocks the coinbase may correspond to an empty
account (as mining rewards are not paid out).  In this case allow
GraphQL to return an all zero account for the empty account only in
context of a miner.  Other tests exist that verify a plain accounts
query of a non-existent account throws an exception.
> Fix GraphQL IBFT Coinbase Query

- besu/src/main/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/PasswordSubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommandTest.java
- gradle/versions.gradle
Upgrade PicoCLI to 4.5.0. The main motivation was to enable inherited
options: options that can show up on either side of a subcommand and be
managed by one field.
> Upgrade picocli

- .circleci/config.yml
Added a step to CI config to capture AT core dump output
> capture core dumps from AT

- CHANGELOG.md
- KNOWN_ISSUES.md
Added more information on onchain privacy group breaking change and updated known issue
> Added more information on onchain privacy group breaking change and updated known issue

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicBlockProcessor.java
Fixed typo with spelling of variable name that was introduced in PR #1329 
Signed-off-by: Edward Mack <ed@edwardmack.com>
> fix typo in variable name

- CHANGELOG.md
- metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/MetricsHttpService.java
- metrics/core/src/test/java/org/hyperledger/besu/metrics/prometheus/MetricsHttpServiceTest.java
The metrics HTTP service only has one supported representation for content but is applying overly strict content type negotiation and refusing to return any content if the Accept header is present and set to anything other than `text/plain; version=0.0.4; charset=utf-8`.  This makes it incompatible with tools like DataDog which specify `Accept: text/plain`.
https://github.com/PegaSysEng/teku/issues/2678
> Ignore accept header in requests to metrics service

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/PendingPeerRequest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/RequestManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthPeersTest.java
This PR solves the same problem as 3a39fbb70740f921436bb2f26548d977c48a0d23 but better. The attempt there has an issue where it still emulates sending the request and therefore only 5 requests max can be aborted. Thus the problem of the peer becoming stuck in a busy state remains. Here we do what we should've done all along, which is proactively abort these requests when a disconnect event occurs.
> Better Handling of Pending Peer Requests Assigned to Disconnected Peers

- enclave/build.gradle
- enclave/src/integration-test/java/org/hyperledger/besu/enclave/EnclaveTest.java
Make async calls in integrationTest to findPrivacyGroup
See #1099
> async findPrivacyGroup calls

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/NetVersion.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/JsonRpcMethodsFactory.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/NetJsonRpcMethods.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/NetVersionTest.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_chainId.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/net_version.json
This PR implements fix to JSON-RPC method `net_version` to return network ID as specified in [https://eth.wiki/json-rpc/API#net_version](https://eth.wiki/json-rpc/API#net_version). 
Signed-off-by: Edward Mack <ed@edwardmack.com>
fixes #1300
> [issue-1300] Update net_version JSON-RPC call to return network ID instead of chain ID

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/DnsOptions.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/EthProtocolOptions.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/EthstatsOptions.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/MetricsCLIOptions.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/MiningOptions.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/NatOptions.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/NativeLibraryOptions.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/NetworkingOptions.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/RPCOptions.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/SynchronizerOptions.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/TransactionPoolOptions.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- besu/src/test/java/org/hyperledger/besu/cli/options/EthProtocolOptionsTest.java
- besu/src/test/java/org/hyperledger/besu/cli/options/MetricsCLIOptionsTest.java
- besu/src/test/java/org/hyperledger/besu/cli/options/NetworkingOptionsTest.java
- besu/src/test/java/org/hyperledger/besu/cli/options/SynchronizerOptionsTest.java
- besu/src/test/java/org/hyperledger/besu/cli/options/TransactionPoolOptionsTest.java
- errorprone-checks/src/main/java/org/hyperledger/errorpronechecks/ExperimentalCliOptionMustBeCorrectlyDisplayed.java
- errorprone-checks/src/test/java/org/hyperledger/errorpronechecks/ExperimentalCliOptionMustBeCorrectlyDisplayedTest.java
- errorprone-checks/src/test/resources/org/hyperledger/errorpronechecks/ExperimentalCliOptionMustBeCorrectlyDisplayedNegativeCases.java
- errorprone-checks/src/test/resources/org/hyperledger/errorpronechecks/ExperimentalCliOptionMustBeCorrectlyDisplayedPositiveCases.java
All --X options listed in the BesuCommand class are not displayed.
- Add new errorprone check to avoid future --X options in  theBesuCommand class
- Small refactor of the Experimental Options classes
List of missing options : 
```
--Xsecp256k1-native-enabled
--Xaltbn128-native-enabled
--Xhttp-timeout-seconds
--Xws-timeout-seconds
--Xdns-enabled
--Xdns-update-enabled
--Xminer-stratum-extranonce
...
```
````
Unstable options for Native Library
--Xaltbn128-native-enabled=<nativeAltbn128>
Path to PID file (optional)
--Xsecp256k1-native-enabled=<nativeSecp256k1>
Path to PID file (optional)
Unstable options for RPC
--Xhttp-timeout-seconds=<httpTimeoutSec>
HTTP timeout in seconds (default: 300)
--Xws-timeout-seconds=<wsTimeoutSec>
Web socket …
```
> Fix experimental options not correctly displayed

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
We were attempting to use hashes from a queue we frequently evict from and not handling that case in an iterator that walks over that collection.
fixes #1370
> Don't Fail When Encountering Evicted Pooled Transaction Hash

- ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/util/NetstatsUrl.java
- ethereum/ethstats/src/test/java/org/hyperledger/besu/ethstats/util/NetstatsUrlTest.java
Our ethstats is hosted on the following domain (example): consortium-netstats.settlemint.com
The NETSTATS_URL_REGEX allows domain names (hence \w and not \d) but only allows dots, letters and numbers.
So netstats.settlemint.com would work, and consortium.netstats.settlemint.com and 10.10.10.15, but not consortium-netstats.settlemint.com
Modified the NETSTATS_URL_REGEX to allow dashes
> fix: allow domain names with - in ethstats

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/TransactionRLPEncoder.java
Remove ternary operator for better readability during encoding of transactions .
> Remove ternary operator for better readability

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/cache/AutoTransactionLogBloomCachingService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/cache/LogBloomCacheMetadata.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/cache/TransactionLogBloomCacher.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/cache/TransactionLogBloomCacherTest.java
LogBloom could be invalid in the cache after a reorg. With this PR, there is an update of the cache every time a reorg takes place
- Sync on goerli (reorg etc.)
> Fix get logs patch 2

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/MultiTenancyPrivacyController.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/MultiTenancyPrivacyControllerOnchainTest.java
Onchain groups do not get created before they are queried. This means we cannot assume the privacyGroup will exist. Also added unit tests for this case.
Manual testing:
Postman query priv_getTransactionCount() for a group that does not exist returns zero (previously "Unable to determine nonce for account in group.")
WIP web3js-eea onChainPrivacy/multiTenancyExample can now create privacy group  (previously "Unable to determine nonce for account in group.")
See #1389 for further testing that was carried out
> handle case where onchain groups do not exist

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/chainimport/RlpBlockImporter.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommandTest.java
Add starting and ending blocks options to import.  The command will only
import blocks within the [start, end) range specified in the CLI when
iterating through the blocks files.
> Add `--start-block` and `--end-block` to `blocks import` subcommand

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
Added a check to throw an exception if duplicate port numbers are specified in the configuration.
Fixes #1340
> [1340] Added check for duplicate configuration ports.

- CHANGELOG.md
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockProcessor.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/StateTestSubCommand.java
Add better invalid reason logging.
The EVMTool state-test will add a field in the json result object.
Block transaction processing will log at INFO why the block is invalid
and include the block hash and (if relevant) transaction hash.
> Better invalid reasons logging

- CHANGELOG.md
- KNOWN_ISSUES.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocolConfiguration.java
Enable eth65 by default for the RC period. This commit should be reverted if issues are found before the release date.
> Change eth65 default

- CHANGELOG.md
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/eth/ExpectEthAccountsException.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/eth/ExpectEthGetWorkException.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/eth/ExpectEthSendRawTransactionException.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/priv/ExpectJsonRpcError.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/condition/ExpectInternalErrorPrivateTransactionReceipt.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/transaction/CreatePrivacyGroupTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/transaction/FindOnChainPrivacyGroupTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/eth/EthAccountsTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/eth/EthGetWorkTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/eth/EthSendRawTransactionTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/net/NetPeerCountTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/perm/PermAddNodeTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/privacy/EeaSendRawTransactionTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/privacy/PrivDeletePrivacyGroupTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/privacy/PrivDistributeRawTransactionTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/privacy/PrivFindPrivacyGroupTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/privacy/PrivGetEeaTransactionCountTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/privacy/PrivGetTransactionCountTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/privacy/PrivacyRequestFactory.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/P2pDisabledAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/RpcApisTogglesAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthGetWorkAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AllowlistPersistorAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/multitenancy/MultiTenancyValidationFailAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/multitenancy/OnChainMultiTenancyAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/EnclaveErrorAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/PrivacyClusterAcceptanceTest.java
Turns out it's not really a web3j problem, but an issue with how we read
errors now that we don't throw HTTP status codes for expected failures.
Most of the fixes revolve around having the AT framework checking for an
error and throwing a RuntimeException with the message.  Others involve
a new target exception type, with one strange serialization case.
Fixes #1425
> Fix JSON-RPC Errors in ATs

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- besu/src/test/resources/everything_config.toml
- crypto/src/main/java/org/hyperledger/besu/crypto/SECP256K1.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgentTest.java
Thanks to @shemnon for the suggestion of using a randomly generated mask so we get a "deterministic" randomness without allowing nodes to nodeId farm. Review suggestion: hide widespace.
fixes #983
Manually tested that 2 peers connected with `max-peers` of 1 and unlimited inbound peers reject a 3rd peer unless the flag is enabled.
> Allow Random Peer Prioritization

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/multitenancy/MultiTenancyAcceptanceTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/eea/EeaSendRawTransaction.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/eea/EeaSendRawTransactionTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/DefaultPrivacyController.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/MultiTenancyPrivacyController.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivacyController.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/markertransaction/FixedKeySigningPrivateMarkerTransactionFactory.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/markertransaction/PrivateMarkerTransactionFactory.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/markertransaction/RandomSigningPrivateMarkerTransactionFactory.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/OnChainPrivacyPrecompiledContractTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContractTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/DefaultPrivacyControllerTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/PrivateTransactionLocatorTest.java
Rename enclaveKey to avoid confusion - ensure `enclaveKey` is only used as the participant (node or tenant) enclaveKey. The "lookup" key is now renamed `privateTransactionLookupId`
See #517
> Enclave key rename

- CHANGELOG.md
- KNOWN_ISSUES.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocolConfiguration.java
> Revert "Enable Eth/65 by Default (#1420)"

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
The current implementation rejects transaction if the gas price is below the chain head base fee. We should remove this restriction on the RPC endpoint. If we implement a restriction it should be on the P2P layer rather than the RPC interface.
#1472 
> Remove restriction about base fee on eth_sendRawTransaction

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/controller/MainnetBesuControllerBuilder.java
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
- config/src/main/resources/classic.json
- config/src/main/resources/mordor.json
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/EthHashMinerExecutor.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/EthHashBlockCreatorTest.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/EthHashMinerExecutorTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/EthHash.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/EthHashCacheFactory.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/EthHashSolver.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/EthHasher.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockHeaderValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/ProofOfWorkValidationRule.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/EtcHashTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/EthHashSolverTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/ProofOfWorkValidationRuleTest.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java
> Cherry pick thanos

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
I previously had it ignore the evicted hashes when it there was a concurrent modification exception but this is more elegant. It shouldn't matter if the hash that we send has been evicted by the time the peer recieves it. The protocol is not designed such that nodes have to have the hashes they advertise.
> Thread Safe Evicting Queue Access

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullImportBlockStep.java
To provide more context to admins and to add more meaning the full sync
log lines report the amount of gas processed in MegaGas/Second.  Some
blocks are fuller than others and this provides a gauge as to wether the
import is slowing down or if the blocks are filling up.
> Add gas measurement to full import log line

- config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
GoQuorum has added `qip74Block` to genesis - exclude this from forkId generation
> Exclude quorum permissioning custom fork in genesis

- CHANGELOG.md
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/AcceptanceTestBase.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeFactory.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AccountLocalConfigPermissioningImportAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningAcceptanceTestBase.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningV2AcceptanceTestBase.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/TransactionFilter.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidatorTest.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningController.java
- ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningControllerTest.java
Updates transaction validation to address the case where a node, with local permissioning enabled, tries to import a block containing a transaction from an account that's not in its allowlist and throws an InvalidBlockException.
Fixes #1476
> [1476] Fixed transaction validation bug when local permissioning is enabled

- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
- config/src/test/java/org/hyperledger/besu/config/JsonGenesisConfigOptionsTest.java
- config/src/test/resources/valid_config_with_quorum_config.json
- Added support for Quorum config options in genesis in preparation for Quorum-compatibility mode.
(I'll update the changelog once we finish the Quorum-compatibility mode)
> Adding support for isQuorum and qip714block options in genesis

- besu/src/main/java/org/hyperledger/besu/controller/TargetingGasLimitCalculator.java
- besu/src/test/java/org/hyperledger/besu/controller/TargetingGasLimitCalculatorTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractGasLimitSpecification.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/GasLimitRangeAndDeltaValidationRule.java
This PR is aimed to fix the disobedience for `GasLimitRangeAndDeltaValidationRule` in `TargetingGasLimitCalculator`.
There is a bound of  block gas limit delta in Ethereum specification which is enforced by `GasLimitRangeAndDeltaValidationRule` in Besu to limit the delta to 1024th of parent block gas limit.
The scenario can be reproduced in the added test case (which gas limit is less or equal than `1024 * 1024`).
> Fix `TargetingGasLimitCalculator`

- ethereum/trie/src/main/java/org/hyperledger/besu/ethereum/trie/StoredNodeFactory.java
The current formulation of the decode can hide exceptions if the finally
block does not complete.  Since exceptions are thrown mid-rlp processing
this typically results in the list not being fully consumed and the real
exception is hidden by a "not at end of list" exception.
This more verbose form prevents such exceptions from being overruled by
rlp processing errors.
> Reduce Exception Hiding in Trie RLP Processing

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeFactory.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/permissioning/PermissionedNodeBuilder.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningIbftStallAcceptanceTest.java
- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigOptionsTest.java
- config/src/test/java/org/hyperledger/besu/config/JsonGenesisConfigOptionsTest.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/NodePermissioningControllerFactory.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/PermissioningConfiguration.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/QuorumPermissioningConfiguration.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/QuorumQip714Gate.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningController.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningControllerFactory.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/node/NodePermissioningController.java
- ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/QuorumQip714GateTest.java
- ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningControllerFactoryTest.java
- ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningControllerTest.java
- ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/node/NodePermissioningControllerFactoryTest.java
- ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/node/NodePermissioningControllerTest.java
- If `qip714block` option isn’t set, yield to controller's providers.
- If the option is set, monitor the chain for that height:
- Before reaching the block height, allow everything
- Upon reaching that block height, yield to controller's providers.
- `qip714block` is inclusive, so if I set `qip714block=123`, permissioning will be enforced from block 123 onwards (including block 123).
> Add Quorum Permissioning gate to Account and Node permissioning

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/CliqueProtocolSchedule.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/IbftProtocolSchedule.java
- consensus/ibftlegacy/src/main/java/org/hyperledger/besu/consensus/ibftlegacy/IbftProtocolSchedule.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcErrorConverter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcErrorConverterTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSendRawTransactionTest.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/EthHashBlockCreatorTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/difficulty/fixed/FixedDifficultyProtocolSchedule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSchedule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionInvalidReason.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/ExecutionContextTestFixture.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidatorTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/VMReferenceTest.java
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestProtocolSchedules.java
- util/src/test/java/org/hyperledger/besu/util/SubscribersTest.java
Updates transaction validation to enforce zero gasPrice when `isQuorum` genesis config is set.
Fixes #1551
> Added zero gasPrice validation for Quorum compatibility mode.

- CHANGELOG.md
- build.gradle
The addition of the EvmTool resulted in duplication of some files in the
zip and tar.gz distributions.  Remove the build configurations that
caused that duplication.
> Remove duplicate files in zip distribution (#1565)

- besu/src/main/java/org/hyperledger/besu/controller/IbftBesuControllerBuilder.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/statemachine/IbftRound.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockMiner.java
For every block produced and imported directly log the same information
we would get from other import paths.
* If this node produced the block, note that with "Produced" instead of
"Imported"
* Log the size of the pending transaction pool
* Only log IBFT rounds at INFO if they go past round 0, DEBUG otherwise.
> IBFT Block Production Logging Improvements

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- besu/src/test/resources/everything_config.toml
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/ApiConfiguration.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLDataFetchers.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGasPrice.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthJsonRpcMethods.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/AbstractEthGraphQLHttpServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGasPriceTest.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/eth_gasPrice.json
Update eth_gasPrice to return the median gas price of transactions in
the last 100 blocks (or whole chain if the chain is short).  If there
are no TXes return the old value.
> eth_gasPrice based on median block cost (#1546)

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/test/java/org/hyperledger/besu/RunnerBuilderTest.java
Fix invalid enode url when discovery is disabled.
- With discovery-enabled=true:
> main | INFO  | DefaultP2PNetwork | Enode URL enode://7315cd61201b679015287ef51f358cb5cbb69b0877392d247d07ced11ef9214168ad026ca862c600bda01e8f97c3b7ecdaf75a7928066a786df2e4e95e7478e7@172.0.0.1:30304
- With discovery-enabled=false:
> main | INFO  | DefaultP2PNetwork | Enode URL enode://7315cd61201b679015287ef51f358cb5cbb69b0877392d247d07ced11ef9214168ad026ca862c600bda01e8f97c3b7ecdaf75a7928066a786df2e4e95e7478e7@172.0.0.1:30304?discport=0
> Fix invalid enode url when discovery is disabled

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketRequestHandler.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketRequestHandlerTest.java
Handle batched requests in WebSockets as for Http
See #1564
> handle batch requests in WebSockets

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- Add CLI option `--goquorum-compatibility-enabled` to enable GoQuorum compatibility mode.
> Adding goquorum-compatibility-enabled config option

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/FrontierGasCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/IstanbulGasCalculator.java
Make it clear they're different and remove a redundant `Gas.ZERO`.
> Differentiate Gas Calculator Methods

- .circleci/config.yml
switch to bash comments for commented out commands.
(It's inside a scalar, so it should still go to bash)
> [ci] bash comments

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/config/EthNetworkConfig.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/config/EthNetworkConfigTest.java
Fix for DNS discovery URLs being added outside of the few named networks.
fixes #1634
> Make sure DNS discovery URLs are never present if using a genesis file

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateTransactionProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/MessageFrame.java
I'm looking to add the common field of initial warmed up accounts/storage for EIP-2930 and thought that this would make it cleaner for myself and future additions to the `MessageFrame`
> [REFACTOR] Clearly Separate Common MessageFrame Fields

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/TransactionGoQuorumTest.java
Adding Transaction.isGoQuorumPrivateTransaction() method
> Adding Transaction.isGoQuorumPrivateTransaction() method

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
RPC HTTP should be able to use WS default port if not in use.
This PR enables to use default port values if corresponding services are not enabled.
Addresses #1665 
> Accept to use default port values if not in use.

- testutil/src/main/java/org/hyperledger/orion/testutil/OrionConfiguration.java
- testutil/src/main/java/org/hyperledger/orion/testutil/OrionTestHarness.java
- testutil/src/main/java/org/hyperledger/orion/testutil/OrionTestHarnessFactory.java
Changed the default OrionTestHarness datastore from `leveldb` to `memory` to improve test stability.
Fixes #1660.
> Refactored OrionTestHarness to use in memory storage.

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/BesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/cluster/Cluster.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/RunHelpTest.java
- acceptance-tests/tests/src/test/resources/log4j2.xml
- besu/src/main/resources/log4j2.xml
- besu/src/test/resources/log4j2.xml
- crypto/src/test/resources/log4j2.xml
- ethereum/core/src/test/resources/log4j2.xml
- ethereum/eth/src/test/resources/log4j2.xml
- ethereum/evmtool/src/main/resources/log4j2.xml
- ethereum/p2p/src/test/resources/log4j2.xml
- services/kvstore/src/main/resources/log4j2.xml
- services/pipeline/src/test/resources/log4j2.xml
- services/tasks/src/main/resources/log4j2.xml
- testutil/src/main/resources/log4j2.xml
Adding the Log4j "jul" (java.util.logging) adapter resulted in many
messages like this at startup:
`main INFO Registered Log4j as the java.util.logging.LogManager.`
These come from the Log4j status logger.  We can get rid of those by
setting the status attribute on all confiurations to a higher logging
level.  WARN is the next higher level.
> Reduce Spurious Log Messages

- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/messagewrappers/Commit.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/messagewrappers/Prepare.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/messagewrappers/Proposal.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/messagewrappers/RoundChange.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/payload/PayloadDeserialisers.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/payload/PayloadDeserializers.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/payload/PreparedCertificate.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/payload/RoundChangeCertificate.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/payload/SignedData.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/payload/PreparedCertificateTest.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/payload/RoundChangeCertificateTest.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/payload/RoundChangePayloadTest.java
SignedData is to be used as part of QBFT, and as such the IBFT specific aspects of this class are to be moved into a separate class (allowed SignedData to be moved into the common package)
> Split signedData into separate types

- consensus/common/build.gradle
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/messagedata/AbstractBftMessageData.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/messagedata/CommitMessageData.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/messagedata/PrepareMessageData.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/messagedata/ProposalMessageData.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/messagedata/RoundChangeMessageData.java
A minor step in the move to genericising the IBFT2 code for use in the QBFT implementation.
> Rename AbstractIbftMessageData to AbstractBftMessageData and move to common package

- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/messagewrappers/BftMessage.java
- consensus/ibft/src/integration-test/java/org/hyperledger/besu/consensus/ibft/support/RoundSpecificPeers.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/messagewrappers/Commit.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/messagewrappers/Prepare.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/messagewrappers/Proposal.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/messagewrappers/RoundChange.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/statemachine/IbftBlockHeightManager.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/statemachine/IbftController.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/IbftGossipTest.java
Moving the IbftMessage (and rename to BftMessage) to the common package such that it can be reused as part of the QBFT implementation.
> Move IbftMessage to common

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
Remove support for capturing the console in threaded acceptance tests.
> Remove Console Capture support from Threaded ATs

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
Added a missing parenthesis in help text
> [MINOR] Typo - missing parenthesis in help

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGas.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/EthByzantiumJsonRpcHttpBySpecTest.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_estimateGas_invalid.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth_latest/eth_estimateGas_revert.json
Here I added revert reason to the `data` field of eth_estimateGas rpc error.
The error looks as shown here:
```
{
"code": -32000,
"message": "Execution reverted",
"data": "0x08c379a0..."
}
```
fixes #1207
> Add revert reason to eth_estimateGas RPC call error

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionsForSenderInfo.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactionsTest.java
Rework the pending transaction gap calculation to store only one gap.
> Rework Pending Transaction Gap Calculation

- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/headervalidationrules/BftValidatorsValidationRule.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/messagedata/ProposalMessageData.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/messagedata/RoundChangeMessageData.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/messagewrappers/Proposal.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/messagewrappers/RoundChange.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/payload/MessageFactory.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/payload/PayloadDeserializers.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/payload/PreparedCertificate.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/payload/PreparedRoundMetadata.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/payload/ProposalPayload.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/payload/RoundChangeCertificate.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/payload/RoundChangeMetadata.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/payload/RoundChangePayload.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/messagewrappers/ProposalTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/messagewrappers/RoundChangeTest.java
This adds the proposal and roundchange messages required for QBFT.
This does _not_ wire in the ability to transmit/receive these messages, it just defines the message structure.
- [ X] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
> Add QBFT Propose and RoundChange messages

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/RunHelpTest.java
The Acceptance Test harness occasionally misses the last line of the
help text (not sure if it's a linux, java, or harness issue, or all
three).
Accept two possible variants for trailer text.
> Reduce RunHelpTest Acceptance Test

- besu/src/main/java/org/hyperledger/besu/chainimport/RlpBlockImporter.java
Exceptions encountered during the import of blocks is suppressed and the
importer can hang. Normally not a problem with perfect blocks but when
testing broken chains its a hinderance.
> RLP Import Error Reporting

- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/validation/ValidationHelpers.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validation/RoundChangePayloadValidator.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validation/ValidationHelpers.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validation/PrepareValidatorTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validation/RoundChangePayloadValidatorTest.java
Adds the SignedData<RoundChangePayload> validation code, along with unit tests.
Does not wire this validation code into the QBFT business logic at this stage.
N/A
> Add RoundChangePayload validation for QBFT

- consensus/ibft/src/integration-test/java/org/hyperledger/besu/consensus/ibft/tests/RoundChangeTest.java
- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/test/FutureHeightTest.java
- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/test/FutureRoundTest.java
- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/test/LocalNodeIsProposerTest.java
- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/test/LocalNodeNotProposerTest.java
- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/test/ReceivedFutureProposalTest.java
- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/test/RoundChangeTest.java
- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/test/round/QbftRoundIntegrationTest.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftRound.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/statemachine/RoundState.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftBlockHeightManagerTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftRoundTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/statemachine/RoundStateTest.java
Change QBFT to also send a prepare when receive a proposal. This also requires changing the quorum needed to be same as the standard quorum used for other QBFT messages.
> QBFT to send prepare when we receive a proposal

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/EIP1559.java
Intermediate values of the base fee can be higher than maximum value encoded by a long. Now using BigInteger to compute intermediate fee delta.
> EIP-1559 Fix consensus issue. (Testnet issue only)

- besu/src/main/java/org/hyperledger/besu/controller/IbftBesuControllerBuilder.java
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/network/ValidatorPeers.java
- consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/network/ValidatorPeersTest.java
Make the BFT validators peers tracking sub-protocol configurable so that it can be re-used by QBFT.
> Make BFT validator peers sub-protocol configurable

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommandTest.java
The JSON block format doesn't include a nonce so we can't skip PoW.
fixes #1048
> Error on PoW Skipping for JSON Block Import

- docker/graalvm/Dockerfile
Oracle moved their graalvm container hating from docker to github.
Update the docker file to keep up with this change.
> Update GraalVM Docker Container

- build.gradle
According to spring's notification @ https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020, starting january 21, 2021 repo.spring.io doesnot allow anonymous download of 3rd-party Maven Central artifacts. They suggest all their releases are available at maven central.
Signed-off-by: Saravana Perumal Shanmugam <perusworld@linux.com>
fixes #1827
> Remove repo.spring.io maven repo dependency (#1827)

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java
Adds `besu_transaction_pool_transactions` metric reporting the size
of the transaction pool.
> Add transaction pool size metric

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
Besu privacy and GoQuorum modes cannot be used together. Hence prevent starting with both enabled.
See #1873
> prevent startup with privacy and GoQuorum modes enabled together

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/clique/CliqueMiningAcceptanceTest.java
Improve the stability of the Clique stall mining AT by waiting for the still running miner node head block to be the proposed by this miner. If the head block is proposed by another miner just before they were shutdown then it would be valid for this node to create another block.
fixed #1876
> Improve the stability of the Clique stall mining AT

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminPeers.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/PeerResult.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/AdminJsonRpcHttpServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/MockPeerConnection.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminPeersTest.java
Besu and GoQuorum provide different information in the response from the admin_peers Json RPC.
This change adds just the "enode" field to the Besu response, to make the results more similar (but still different).
admin_peers now includes the remote node's enode URL as a string
> Add remote enode to admin_peers

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/GoQuorumStoreRawPrivateTransaction.java
Base64 encode the payload sent to Tessera /storeraw
> GoQuorum store raw private transaction base64 encoding of payload

- CHANGELOG.md
- config/src/main/resources/goerli.json
- config/src/main/resources/mainnet.json
- config/src/main/resources/rinkeby.json
- config/src/main/resources/ropsten.json
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolScheduleTest.java
Update ropsten, goerli, rinkeby, and mainnet block numbers to activate
Berlin.
> Update Berlin Block numbers

- consensus/qbft/build.gradle
- ethereum/referencetests/build.gradle
Fix submodule path in gradle for hash check
> Fix submodule path in gradle for commit hash check

- build.gradle
- gradle/versions.gradle
Upgrade discovery dependency to 0.4.3 which is published to the new repo (bintray repo is being shut down).
> Upgrade discovery to a version available from the new repository

- docker/graalvm/Dockerfile
- docker/openjdk-11/Dockerfile
- docker/openjdk-latest/Dockerfile
Hadolint introduced a new linting rule prohibiting using the same env
var in it's definition. Move to a two step definition.
> Update Docker files due to hadolint

- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/messagedata/QbftV1.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/protocol/QbftSubProtocolTest.java
This was required to ensure interop with GoQuorum.
> Change qbft msg codes

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateUpdater.java
Setting contract code on a bonsai account results in a re-hashing. To
reduce this only set the code if the code was changed.  In some cases
this was responsible for 40% of load.
> Reduce hash calculations in Bonsai Tries

- CHANGELOG.md
Remove download links for Besu versions with Berlin consensus bug, and have both 21.1.0 and 21.1.1 point to 21.1.2.
> Remove download links and specify 21.1.2 where 21.1.1 was

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgentTest.java
Review suggestion: hide whitespace
We wrote the saved the new node record to disk but we didn't set it on the `DiscoveryPeer` class so we were still responding with the old one.
#1931
> Update `NodeRecord` on `DiscoveryPeer`

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
- config/src/test/java/org/hyperledger/besu/config/JsonGenesisConfigOptionsTest.java
- crypto/src/main/java/org/hyperledger/besu/crypto/SignatureAlgorithmFactory.java
- crypto/src/main/java/org/hyperledger/besu/crypto/SignatureAlgorithmType.java
- crypto/src/test/java/org/hyperledger/besu/crypto/SignatureAlgorithmFactoryTest.java
- crypto/src/test/java/org/hyperledger/besu/crypto/SignatureAlgorithmTypeTest.java
This PR reintroduces the changes from #2036 and always sets the instance of `SignatureAlgorithmFactory` already in `BesuCommand`. This should avoid the blocking of the vertX thread, that was introduced with #2036
> Fixed elliptic curve configuration in genesis file

- CHANGELOG.md
- gradle/versions.gradle
Upgrade the discv5 library to pull in https://github.com/ConsenSys/discovery/pull/98
> Upgrade discovery to include fix for nonce generation

- besu/src/main/java/org/hyperledger/besu/controller/QbftBesuControllerBuilder.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/protocol/Istanbul100SubProtocol.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/protocol/Istanbul100SubProtocolTest.java
Use istanbul/100 subprotocol in qbft to match the sub-protocol used in Quorum for qbft.
> Use istanbul 100 subprotocol in QBFT

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
> [MINOR] removed spurious path help

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivDebugGetStateRootOnchainGroupAcceptanceTest.java
Simplify this test setup by making only one node a miner. This also improves performance of the test.
Before: was failing 20% of the time when running locally (100 runs)
After: passing 100% of the time (100 runs)
> Fix flaky test

- MAINTAINERS.md
I propose moving the following maintainers to Emeritus status, pursuant to the inactivity clause.  Since this is the first such proposal I am extending the window so that _two_ reporting quarters of inactivity be required for movement to Emeritus. (28 Sep 2020 was the start of the Q4 report)
* @iikirilov's last commit was on 24 Mar 2020
* @CjHare's last commit was on 5 Mar 2020
* @rojotek's last commit was on 7 Oct 2019
We very much appreciate their contributions but moving their status to emeritus (and thus revoking PR approval privileges) is in the interest of an orderly project. If any of these maintainers express in this PR that the intend to make contributions in the next quarter then they will not be moved to emeritus status.
I propose this vote is open until either an absolute …
> Move 3 maintainers to Emeritus status.

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullImportBlockStep.java
Remove ellipsis from block hash logs. Thus, full block hashes will be shown in logs.
Fixes #1594
> Remove ellipsis from block hash logs

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetEvmRegistries.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/operations/BaseFeeOperation.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/operations/BaseFeeOperationTest.java
Implement [EIP-3198](https://eips.ethereum.org/EIPS/eip-3198).
Adds an opcode that gives the EVM access to the block’s base fee.
Addresses #1792 
> Implement EIP-3198 BASEFEE opcode

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonCallParameter.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java
Ignore nonce when supplied to eth_estimateGas or eth_call. This is to better support web3j calls as per #2125
> Estimate gas: ignore nonce

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSendRawTransaction.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/util/DomainObjectDecodeUtils.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/util/DomainObjectDecodeUtilsTest.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionType.java
resubmitting this PR.  The recent 1559 merge changed the behavior of EthSendRawTransaction with the intent to work for both rlp encoded raw transactions *and* byte prefixed typed transactions.  However the result was that properly encoded 2718 transactions fail.
Dimitry updated retesteth to use the 2718 style encoding, so we need to fix this.
> handle json-rpc raw transactions encoded in either

- consensus/qbft/build.gradle
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/payload/PreparedRoundMetadata.java
Update encoding of round change encoding to match that of quorum.
Order of fields in the metadata are different to what Besu was using.
fixes #2145
> qbft roundchange metadata message encoding to match quorum

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonCallParameter.java
Related to #2125, private tx estimation passes the `privateFor` field eg 
```
{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x6402a0d7d3ed9db2163a234925e2bf82d45c7f99","gas":"0x47b760","value":"0x0","data":"0x608060405234801561001057600080fd5b5060405160208061011b8339810180604052602081101561003057600080fd5b505160005560d8806100436000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c806360fe47b11460375780636d4ce63c146053575b600080fd5b605160048036036020811015604b57600080fd5b5035606b565b005b605960a6565b60408051918252519081900360200190f35b60008190556040805182815290517f281b9a35503a0b511f50336e3e6b0d05a64fdadae7255e70f430feb2313c3c689181900360200190a150565b6000549056fea165627a7a7230582044f05a413bc …
```
> ignore privateFor for tx estimation

- .circleci/config.yml
Run buildDocker in parallel with tests. publishDocker still happens after buildDocker AND all tests (but doesn't run on PRs)
> buildDocker depends on assemble only

- container-tests/tests/src/test/java/org/hyperledger/besu/tests/container/ContainerTestBase.java
`dev` isn't present in the version string during a release. `besu` is, however.
> check that doesn't break during release

- .circleci/config.yml
Change to docker creds handling so that CI can run on external contributors' PRs
n/a
> Remove docker-ro creds from circle ci pipeline

- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/experimental/ExperimentalEIPs.java
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigOptionsTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/GenesisState.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestSetChainParams.java
- ethereum/retesteth/src/test/java/org/hyperledger/besu/ethereum/retesteth/methods/TestSetChainParamsTest.java
- ethereum/retesteth/src/test/resources/org/hyperledger/besu/ethereum/retesteth/methods/1559ChainParams.json
* add support for 1559 in test_setChainParams 
* add a "1559 at genesis" provision
This pr kicks the can down the road for 2 things: 
* hardfork naming
* 1559 baseFee as a part of genesis json configuration
the first is NBD, but we might want to incorporate baseFee in genesis config at some point.  Probably once we move 1559 out of 'experimental' status.
fixes #2180
> add support for 1559 in retesteth besu command

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiAccount.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiValue.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateUpdater.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/UpdateTrackingAccount.java
Fix an invalid originalValue for a specific storage slot :
in the same block we are doing
1 ) create a contract
2) change the value of a slot
3) change a second time the value of the same slot. the original is empty while it should be the previous value of the step 2
Why because when we create a contract we clear the storage so the method return 0x 
https://github.com/hyperledger/besu/blob/e13dd77c8d3a4ad6b003d2c71526a39818195ea8/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateUpdater.java#L314
> Bonsai trie : fix consensus issue on ropsten

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncDownloader.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/worldstate/CompleteTaskStep.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/worldstate/CompleteTaskStepTest.java
Users have been confused by this logging all the time. Probably best we remove those aspects that confuse them.
fixes #2156
> Remove Misleading Fast-Sync Logging

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/GenerateBlockchainConfig.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/operator/OperatorSubCommandTest.java
- besu/src/test/resources/operator/config_generate_keys_ec_invalid.json
- besu/src/test/resources/operator/config_generate_keys_secp256r1.json
- besu/src/test/resources/operator/config_import_keys_secp256r1.json
- besu/src/test/resources/operator/config_import_keys_secp256r1_invalid_keys.json
- crypto/src/main/java/org/hyperledger/besu/crypto/AbstractSECP256.java
- crypto/src/main/java/org/hyperledger/besu/crypto/SignatureAlgorithm.java
- crypto/src/main/java/org/hyperledger/besu/crypto/SignatureAlgorithmType.java
- crypto/src/test/java/org/hyperledger/besu/crypto/SignatureAlgorithmTypeTest.java
Support for secp256r1 is added to the CLI sub command `generate-blockchain-config`. The command checks if the genesis property of the configuration file has a field `ecCurve`. This field is used to select the alternative signature algorithm secp256r1. If secp256r1 is indeed set, the public keys in extraData are generated using this signature algorithm. In any other case the default signature algorithm is used.
If the public keys are already provided in the blockchain property of the configuration file, it is verified if those keys are valid for the selected signature algorithm. This avoids that a user error could generate a genesis file with invalid keys.
Fixes #2182
> Add SECP256R1 support to CLI sub command generate-blockchain-config

- CHANGELOG.md
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/Packet.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PacketTest.java
Catches packets where deciding public key failed, reducing the log level from ERROR to DEBUG.
fixes #2142
> Make public key decode errors debug level

- enclave/src/integration-test/java/org/hyperledger/besu/enclave/GoQuorumEnclaveTest.java
- enclave/src/main/java/org/hyperledger/besu/enclave/Enclave.java
- enclave/src/main/java/org/hyperledger/besu/enclave/GoQuorumEnclave.java
- enclave/src/main/java/org/hyperledger/besu/enclave/RequestTransmitter.java
- enclave/src/main/java/org/hyperledger/besu/enclave/VertxRequestTransmitter.java
There are two RPC in Tessera for GET "/transaction/{hash}". This makes sure we are using the right one.
> fix selection of receive RPC

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/WorldUpdater.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetContractCreationProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetMessageCallProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/GoQuorumMutablePrivateWorldStateUpdater.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/StateTestSubCommand.java
fixes #2198
The bug was that when we have a private transaction in goquorum mode and a contract calls another contract or a contract deploys another contract the sender account from the public world state was used, which caused the nonce to be incremented in the public state. 
> fix goquorum privacy

- .circleci/config.yml
Reduce parallelism to improve thread blockage situation.
Changing from 8 to 4 increased test time from 13 to 23 min
Changing to 6 made it ~15 min which is acceptable.
> entropy - reduce parallelism

- .circleci/config.yml
- acceptance-tests/tests/src/test/resources/acceptanceTesting.security
Install haveged on AT executor to increase entropy available for non-java processes.
Also setting secure source to /dev/urandom/ explicitly (but not sure that is relevant)
> haveged + urandom

- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/Vote.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/IbftExtraDataCodec.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/IbftExtraDataEncoderTest.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/QbftExtraDataCodec.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/QbftExtraDataCodecTest.java
Qbft vote encoding to use empty for drop for extradata to match quorum
fixes #2233
> Qbft vote encoding to use empty for drop for extradata to match quorum

- CHANGELOG.md
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/TransactionPriceCalculator.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/fees/TransactionPriceCalculatorTest.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionType.java
* Makes 1559 transaction price calculator use frontier for ACCESSLIST txns (as well as frontier txns)
fixes #2220
> Make 2930 accesslist transactions use frontier txn price calculator

- gradle/check-licenses.gradle
when clean task is mentioned the lazyDownloadLicenses gets called before the clean runs, but during clean the license-dependency.xml also gets removed hence the checkLicenses.doLast fails. added the check to force downloadLicenses when clean task is going to run
Signed-off-by: Saravana Perumal Shanmugam <perusworld@linux.com>
fixes #2104
> force downloadLicenses when clean (#2104)

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ConsensusNewBlock.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/ConsensusNewBlockParameter.java
Previous `consensus_newBlock` (for the Merge prototype) was expecting full transactions, but the beacon node sends opaque transactions, and so blocks with a transaction would fail and cause the besu node to fail to sync the chain.
This mirrors the encoding code (stream tx list, map from hex and decoding instead of encoding and to hex, collect in list), and wraps it with some logging and error handling just in case. Tested this on a local merge testnet with all consensus and execution clients mining on top of the blocks, no errors.
- Small fix in experimental fork of besu, no new features, not updating changelog.
> rayonism: fix newblock transaction decoding RPC

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgentTest.java
Make sure Besu sends NEIGHBORS packets under MTU size.
#2250
> Fix discovery packet size

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/crypto/SECP256R1AcceptanceTest.java
ignore these tests for now as the static reference to the signatureAlgorithm breaks other tests.
See #2267 
> Ignore SECP256R1 tests for now

- build.gradle
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulatorTest.java
Revert #2282 
Enabling one more passing GoQuorum AT 
See https://github.com/hyperledger/besu/pull/2282
> GoQuorum ATs: run the estimate gas test

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/TransactionGasBudgetCalculator.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java
A couple quick fixes for bugs I found In scale testing 21.1.6 pending transactions:
* baseFee = null was not handled correctly in PendingTransactions.updateBaseFee for a fork block
* the transaction gas budget calculator was 2x'ing the already 2x'd gasLimit at and past fork block
we should probably write some tests that cover these cases, but it is late and the release is already out there...
> errata discovered in 21.1.6

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/FrontierGasCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/IstanbulGasCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/GasCalculator.java
If GoQuorum mode and value = 0, modify tx simulator result to return estimate which will cover a PMT transaction
> GoQuorum: Gas estimate to cover PMT

- MAINTAINERS.md
These changes are expected to clarify the rules to reach maintainer status. Some edits were made on the voting process, template PR description added, simplified language,...
The PR also adds a new maintainer type in addition to code maintainer to enable people who significantly contribute to the Besu project to be able to access some project management features such as issues triage and assignation.
Some features, expecially when using Zenhub, indeed require a write access on the repository even though the contributor will not make any code changes. But things like assigning a user to an issue requires maintainer role.
See https://github.com/NicolasMassart/besu/blob/maintainer-rules/MAINTAINERS.md for the easier to read rendered doc.
As for the maintainer addition, this PR being a …
> update maintainer rules

- MAINTAINERS.md
Sajida has started helping manage Github issues and collaborating with the existing maintainers to help coordinate the development of Besu.
Voting ends 2 weeks from the publication of this PR.
For more information on this process see the Becoming a Maintainer section in the MAINTAINERS.md file.
> Add Sajida Zouarhi to maintainers

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/TransactionGasBudgetCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/fees/TransactionGasBudgetCalculatorTest.java
The specification of the EIP1559 has changed and no longer requires a specific gasBudgetCalculator implementation. This PR clean the code by removing this unnecessary part of code
> Remove EIP1559 Gas budget calculator implementation

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
Add error message and remove reference to GoQuorum options.
```
$ besu --genesis-file=xyz.json
Unable to read genesis file. java.io.FileNotFoundException: /Users/sallymacfarlane/workspace/besu/xyz.json (No such file or directory)
To display full help:
besu [COMMAND] --help
$ besu --genesis-file=bob.json
Unable to read genesis file. com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'bob': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
at [Source: (String)"bob
"; line: 1, column: 4]
To display full help:
besu [COMMAND] --help
$ cat bob.json
bob
```
> non-existent genesis file: clarify error

- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockTransactionSelector.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/BlockTransactionSelectorTest.java
The segregated tracking was used in an older version of the spec but not anymore.
> Remove Separation of EIP-1559 and pre-EIP-1559 Gas Tracking

- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestSetChainParams.java
quick pr to unblock retesteth testing, remove aleut and calaveras from retesteth chain genesis.  
Aleut config was an artifact from when we did not have London configs.
> Fixes for 1559 retesteth behaviors

- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/QbftBlockHeaderValidationRulesetFactory.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/QbftBlockHeaderValidationRulesetFactoryTest.java
Use the fixed IBFT mixedHash value in QBFT as this is what is being done in Quorum.
> QBFT to use fixed IBFT mixhash value for headers

- .circleci/config.yml
- build.gradle
Signed-off-by: Ricardo Silva <ricardo.silva@consensys.net>
As the work is done for the privacy interop, we remove now the ignore of the results so if it fails, it breaks the build.
* Removed `|| true` to make the job fail if the tests fail.
* Make the publish of docker images depend on the Quorum AT.
* Add the `nosupport` tag as privacy polishing to be done later.
> ci/cd: Require Quorum Acceptance Tests to pass

- .circleci/config.yml
Use medium executor where xl not needed.
> CI: use med executor for more steps

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/AbstractHandshakeHandler.java
This takes care of the current requirements as well as provide the possibility of adding other channel handlers before that like for example a TLS handler
> Add ValidateFirstOutboundMessage just before DeFramer

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/BlockResult.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetUncleByBlockNumberAndIndexTest.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/BlockHeaderTestFixture.java
make blockresult conform to json-rpc spec ; use `baseFeePerGas` instead of `baseFee`
#2369
> change BlockResult to use baseFeePerGas per eth1 json-rpc spec

- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestImportRawBlock.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestRewindToBlock.java
- ethereum/retesteth/src/test/java/org/hyperledger/besu/ethereum/retesteth/methods/TestImportRawBlockTest.java
Ensures `test_importRawBlock` appends the block to the chain even if the block already exists in storage.  This behavior is limited to the test endpoint, rather than pushing it down into the block importer.
#2409
> ensure test_importRawBlock appends to chain head

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramer.java
Signed-off-by: Justin Florentine <justin.florentine@consensys.net>
[Previous assumption](https://github.com/hyperledger/besu/pull/2406#discussion_r649821858) was a mistake, I didn't realize those canaries I checked were not running at DEBUG. Invalid HELOs happen often enough, without any impact, that the log level should remain at debug.
fixes #2004
> dialing down logging of invalid HELO to debug

- docker/openjdk-11/Dockerfile
This PR aims to fix the Issue [2451](https://github.com/hyperledger/besu/issues/2451) reported about base image vulnerabilities.
Now scan report does not show any high vulnerabilities:
```
docker scan -f docker/openjdk-11/Dockerfile docker.io/hyperledger/besu:21.7.0-RC1-SNAPSHOT-openjdk-11 --severity high
Testing docker.io/hyperledger/besu:21.7.0-RC1-SNAPSHOT-openjdk-11...
Organization:      juan.dominguez
Package manager:   deb
Target file:       docker/openjdk-11/Dockerfile
Project name:      docker-image|docker.io/hyperledger/besu
Docker image:      docker.io/hyperledger/besu:21.7.0-RC1-SNAPSHOT-openjdk-11
Base image:        adoptopenjdk/openjdk11:jre-11.0.11_9
Licenses:          enabled
✓ Tested 132 dependencies for known issues, no vulnerable paths found.
```
> Fix vulnerabilities from openjdk-11 base image

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetMinerDataByBlockHash.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionReceipt.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/TransactionReceiptResult.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionReceiptTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
- ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/EthStatsService.java
> Fix NoSuchElementException in Transaction Receipt Logic

- ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcTestMethodsFactory.java
- ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthGetBlockByNumberLatestDesyncIntegrationTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockByNumber.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthJsonRpcMethods.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTest.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/DummySynchronizer.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethService.java
Introduces a dependency from eth_getBlockByNumber onto the Synchronizer, in order to determine download state, and current most recent block that we have state for. JsonRPC test classes also were refactored to provide a Synchronizer.
fixes #2209 
When asking for the latest block while downloading state, will return most recent block we have state for. While still downloading block headers, will return genesis block.
> Implement eth_getBlockByNumber while downloading state.

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/EIP1559.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/EIP1559BlockHeaderGasPriceValidationRule.java
Fix a consensus issue detected on ropsten. There was a check of elasticity that seems to be related to old version of the specification. This made a double check of the elasticity in the code. I only kept the version that corresponds to the latest version of the spec.
>
if INITIAL_FORK_BLOCK_NUMBER == block.number:
expected_base_fee_per_gas = INITIAL_BASE_FEE
elif parent_gas_used == parent_gas_target:
expected_base_fee_per_gas = parent_base_fee_per_gas
elif parent_gas_used > parent_gas_target:
gas_used_delta = parent_gas_used - parent_gas_target
base_fee_per_gas_delta = max(parent_base_fee_per_gas * gas_used_delta // parent_gas_target // BASE_FEE_MAX_CHANGE_DENOMINATOR, 1)
expected_base_fee_per_gas = parent_base_fee_per_gas + …
> fix ropsten consensus issue

- besu/src/test/java/org/hyperledger/besu/ForkIdsTest.java
- config/src/main/resources/mainnet.json
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolScheduleTest.java
Signed-off-by: Justin Florentine <justin.florentine@consensys.net>
Adds protocol hardfork to London.
> added london block

- crypto/src/main/java/org/hyperledger/besu/crypto/AbstractSECP256.java
- crypto/src/main/java/org/hyperledger/besu/crypto/SECP256K1.java
- crypto/src/main/java/org/hyperledger/besu/crypto/SECP256R1.java
- crypto/src/main/java/org/hyperledger/besu/crypto/SignatureAlgorithm.java
- crypto/src/test/java/org/hyperledger/besu/crypto/SECP256R1Test.java
- Updated our `SignatureAlgorithm` interface with a method to return the K calculator implementation (BC)
- Each concrete implementation returns the expected calculator:
- SECP256K1: deterministic calculator
- SECP256R1: non-deterministic calculator
Fixes #2500
N/A
> SECP256R1 BC now using non-deterministic variant

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/MiningOptions.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommand.java
- besu/src/main/java/org/hyperledger/besu/controller/MainnetBesuControllerBuilder.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/PoWMinerExecutor.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/PoWBlockCreatorTest.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/PoWMinerExecutorTest.java
- ethereum/core/build.gradle
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/MiningParameters.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PoWSolver.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/PoWSolverTest.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java
- gradle/versions.gradle
This allows miners to send solutions for blocks up to 8 blocks behind head, to be included as ommers.
Fixes #2572
> Add support for mining ommers, up to 8 blocks behind the head job

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
See #2579 
For goQuorum mode, min-gas-price must be zero and this is checked separately so I think this warning is adequate.
> simplify --min-gas-price dependency check

- ethereum/stratum/src/main/java/org/hyperledger/besu/ethereum/stratum/GetWorkProtocol.java
- ethereum/stratum/src/main/java/org/hyperledger/besu/ethereum/stratum/Stratum1EthProxyProtocol.java
- ethereum/stratum/src/main/java/org/hyperledger/besu/ethereum/stratum/Stratum1Protocol.java
- ethereum/stratum/src/main/java/org/hyperledger/besu/ethereum/stratum/StratumConnection.java
- ethereum/stratum/src/main/java/org/hyperledger/besu/ethereum/stratum/StratumProtocol.java
- ethereum/stratum/src/main/java/org/hyperledger/besu/ethereum/stratum/StratumServer.java
- ethereum/stratum/src/test/java/org/hyperledger/besu/ethereum/stratum/GetWorkProtocolTest.java
- ethereum/stratum/src/test/java/org/hyperledger/besu/ethereum/stratum/Stratum1EthProxyProtocolTest.java
- ethereum/stratum/src/test/java/org/hyperledger/besu/ethereum/stratum/StratumConnectionTest.java
Adds the JSON-RPC methods getWork/submitWork to the stratum port, so miners can communicate with Besu over the stratum port. This allows to keep the JSON-RPC port closed to miner traffic.
Fixes #2065
> Add ability to expose getWork/submitWork JSON-RPC methods over the stratum port

- CHANGELOG.md
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AccountLocalAndOnChainPermissioningAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AccountSmartContractPermissioningAcceptanceTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/TransactionValidationParams.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/TransactionValidationParamsTest.java
Updates the configuration of the transaction validator to check whether the sender is permitted when submitting the transaction while onchain permissions are enabled. This addresses an issue where clients were not receiving a response when the sending account was not permitted.
Fixes #1466.
> Updated transaction validation to check onchain permissions at the transaction pool level

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolTest.java
Clarify isGoQuorumPrivateTransaction method. v value is set directly for GoQuorum private transactions, and they don't have a chainId. All other tx derive their v value from the chainId.
fixes #2606
> Fix bug with value transfer

- besu/build.gradle
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/PkiBlockCreationOptions.java
- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/QbftBesuControllerBuilder.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/pki/PkiBlockCreationConfiguration.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/pki/PkiBlockCreationConfigurationProvider.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/pki/PkiQbftContext.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/pki/PkiBlockCreationConfigurationProviderTest.java
- pki/src/main/java/org/hyperledger/besu/pki/config/PkiKeyStoreConfiguration.java
- added all CLI options for PKI Block Creation as a Mixin
- created `PkiBlockCreationConfigurationProvider` that will be used to inject the PkiOptions into QBFT-related objects
> PKI Block Creation cli configuration

- pki/src/main/java/org/hyperledger/besu/pki/cms/CmsValidator.java
- pki/src/test/java/org/hyperledger/besu/pki/cms/CmsCreationAndValidationTest.java
Loading CRL list inside CmsValidator (instead of externally)
> Refactoring CmsValidator (internal CRL resolution)

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionCount.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionCountTest.java
Fixed bug where EthGetTransactionCount would return a lower value for pending than latest when there are old transactions in the transaction pool.
Wrote a failing test to show the expected behaviour and ensured that the max of latest and pending is used.
> Fixed nonce bug in EthGetTransactionCount

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/TransactionDecoder.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/GoQuorumPrivateTransactionDetector.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/TransactionGoQuorumTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolTest.java
Refactor the GoQorum private transaction detection logic to be more DRY.
This also unifies `Transaction.isGoQuorumPrivateTransaction()` to also consider the `GoQuorumOptions.goQuorumCompatibilityMode` flag. Previously this flag was only considered in `TransactionDecoder`. This difference in behaviour could result in transaction encoding not being the inverse of transaction decoding.
fixes #2610
> refactor GoQuorum private transaction detection

- besu/src/main/java/org/hyperledger/besu/controller/QbftBesuControllerBuilder.java
- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/support/RoundSpecificPeers.java
- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/support/TestContext.java
- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/support/TestContextBuilder.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/QbftGossip.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/messagedata/ProposalMessageData.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/messagedata/RoundChangeMessageData.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/messagewrappers/Proposal.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/messagewrappers/RoundChange.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/payload/ProposalPayload.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftController.java
- consensus/qbft/src/reference-test/java/org/hyperledger/besu/consensus/qbt/support/ProposalMessage.java
- consensus/qbft/src/reference-test/java/org/hyperledger/besu/consensus/qbt/support/RoundChangeMessage.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/messagewrappers/ProposalTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/messagewrappers/RoundChangeTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftBlockHeightManagerTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftControllerTest.java
- Updated `RoundChange` and `ProposalPayload` `decode()` methods to accept a `BftExtraDataCodec` implementation (instead of creating a new instance of `QbftExtraDataCodec`.
- A bit of plumbing work all the way to `QbftBesuControllerBuilder`, where we choose the concrete codec instance to use.
- For the tests, we are using the `QbftExtraDataCodec` (to keep the previous behaviour)
> Refactor QbftExtraDataCodec from new instance to injection

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/feemarket/FeeMarketException.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/BaseFeeBlockBodyValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockBodyValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/BaseFeeBlockBodyValidatorTest.java
* add BaseFeeBlockBodyValidator extends MainnetBlockBodyValidator
* use in London protocolschedule
fixes #2565
> Encapsulate London Block transaction gas price validation

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetEvmRegistries.java
While familiarizing myself with the EVM code, I noticed that there is a duplicate `AddOperation` being added to the `MainnetEvmRegistries`. The `MainnetEvmRegistries#put()` function just assigns the operation to a map using the operation's opcode so removing this duplicate line has no effect on the EVM itself as it was just overwriting the previous line.
> Remove duplicate AddOperation on MainnetEvmRegistries

- gradle/versions.gradle
- Updated besu-native to 0.4.2 for ec libraries
- Not updating bls12-381 because of https://github.com/hyperledger/besu/issues/2668
fixes #2665
> Updated besu-native to 0.4.2 for ec libraries

- acceptance-tests/dsl/build.gradle
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/BesuNode.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeConfiguration.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeConfigurationBuilder.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeFactory.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/pki/PkiKeystoreConfigurationFactory.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyNode.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/PkiBlockCreationOptions.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/pki/PkiBlockCreationConfigurationProviderTest.java
- pki/build.gradle
- pki/src/main/java/org/hyperledger/besu/pki/config/PkiKeyStoreConfiguration.java
- pki/src/main/java/org/hyperledger/besu/pki/keystore/SoftwareKeyStoreWrapper.java
- Exposing utility classes from `:pki` module
- Simplified `PkiKeyStoreConfiguration` replacing password **supplier** with actual password file path
- Added `createPkiQbftNode` method on BesuNodeFactory
- Updated Thread and Process runner to consume PKI configuration when starting nodes
- Created `PkiKeystoreConfigurationFactory` responsible for creating PKI config (including certificate temp files and issuing certs from the same CA).
> Updated ATs DSL to create PKI QBFT node configuration

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocol.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/EthProtocolTest.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/wire/Capability.java
Besu using the instanbul/99 or instanbul/100 incorrectly encodes messages with a requestId from eth66.
Fixes #2682
> Eth66 protocol request id changes should only apply to the Eth protocol

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonCallParameter.java
Changed to ignore all unknown fields in JsonCallParameter. This matches geth's behaviour. Different third-party libraries send through extra fields from time to time, for example
ethers.js 5.4.2 sends eth_estimateGas with a `type` parameter which Besu was rejecting.
```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "type" (class org.hyperledger.besu.ethereum.api.jsonrpc.internal.parameters.JsonCallParameter), not marked as ignorable (11 known properties: "gasPrice", "value", "gasLimit", "gas", "from", "to", "maxFeePerGas", "strict", "maxPriorityFeePerGas", "payload", "data"])
at [Source: (StringReader); line: 1, column: 42492] (through reference chain: …
```
> ignore all unknown fields for eth_call and eth_estimateGas

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
When registering a PrivacyPluginService you need to call setPayloadProvider before blocks get mined. You have two opportunities to do this, once when besu calls register in your plugin and once when besu calls start in your plugin.
Ideally, you would setPayloadProvider when register is called. That way Besu can confirm that you've set the various command line options correctly in BesuCommand. But the problem is when Besu calls register it hasn't yet parsed the command line args into. So if you've got some cli arguments set in your plugin they will not be populated yet.
> A plugin implementer may register the payload provider in start or register

- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/blockcreation/BftBlockCreator.java
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/blockcreation/BftBlockCreatorFactory.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/statemachine/IbftRound.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/statemachine/IbftRoundFactory.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/blockcreation/PkiQbftBlockCreator.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/blockcreation/QbftBlockCreatorFactory.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/pki/PkiQbftExtraData.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftRound.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftRoundFactory.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/blockcreation/PkiQbftBlockCreatorTest.java
Move the CMS creation out of the QbftRound and into a QBFT block creator.
This allows the CMS to be only created the once per block regardless of how many rounds and removes the need for a proposal block behaviour in the qbft round.
> Move QBFT CMS creation to block creator

- CHANGELOG.md
- metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/MetricsHttpService.java
When metrics are in use in teku (which uses besu metrics), and the prometheus service restarts, connections can be left open and never closed.
These connections should close after an idle timeout to avoid causing issues with running out of ports.
Reported in teku issue https://github.com/ConsenSys/teku/issues/4327 .
Signed-off-by: Paul Harris <paul.harris@consensys.net>
> Cleanup metrics connections after idle timeout

- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/MetricsCLIOptions.java
- besu/src/test/java/org/hyperledger/besu/cli/options/MetricsCLIOptionsTest.java
- metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/MetricsConfiguration.java
- metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/MetricsHttpService.java
#2748 introduced a timeout for metrics TCP connections. With this PR user can set a value in seconds for that timeout.
> Metrics idle timeout is now configurable

- CHANGELOG.md
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/transaction/PrivacyTransactions.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/transaction/UnlockOnChainPrivacyGroupTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/privacy/PrivacyRequestFactory.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/OnChainPrivacyAcceptanceTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/OnChainPrivacyPrecompiledContract.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateTransaction.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/group/OnChainGroupManagement.java
Prior to this commit, the only allowed transactions in locked onchain privacy groups were those making the `addParticipants` call to *any* contract--not just the proxy. This commit ensures that:
- while locked, only the group management proxy can be called
- while locked, all functions of the management proxy can be called
Corollary, this commit allows unlocking a group using `unlock` instead of implicitly unlocking it via `addParticipants`. This fixes #2693.
fixes #2693
> allow unlocking onchain privacy groups

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
On #2659 the gas calculator was split but the ETC specification wasn't properly updated, letting 21.7.3 nodes out of consensus.
Fixes #2715
> Set TransactionGasCalculator in ETC specs

- CHANGELOG.md
Move entires that were mistakenly added to 21.7.3 lists to 21.7.4.
Add entry for ETC gas calculator bug.
> Changelog for 21.7.4

- CHANGELOG.md
- evm/src/main/java/org/hyperledger/besu/evm/frame/ExceptionalHaltReason.java
- evm/src/main/java/org/hyperledger/besu/evm/processor/ContractCreationProcessor.java
- evm/src/main/java/org/hyperledger/besu/evm/processor/MessageCallProcessor.java
Migrate ExceptionalHaltReason to an interface from an enum. The enum
made it difficult for downstream implementations to add custom reasons
as to why the EVM has halted. Switching to an interface is needed
because enums are final and not extensible.
> Make ExceptionalHaltReason an interface

- evm/src/main/java/org/hyperledger/besu/evm/operation/BalanceOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/ExtCodeCopyOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/ExtCodeHashOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/ExtCodeSizeOperation.java
* Extract gas cost calculation for Balance, ExtCodeCopy, ExtCodeHash, ExtCodeSize operations into `cost` function.
* Allow `cost` function to be called outside library
> Refactor(Balance/Ext-*Operations): Extract gas calculation into separate function

- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/NodeSmartContractV2PermissioningController.java
Added some logging so users can see more details on what is being resolved and what is being rejected/permitted with regard to IP and DNS versions of enode. This will help when troubleshooting DNS + permissioning.
```
2021-09-29 11:08:50.183+10:00 | vert.x-eventloop-thread-2 | TRACE | NodePermissioningController | Node permissioning: Checking enode://3548c87b9920ff16aa4bdcf01c85f25117a29ae1574d759bad48cc9463d8e9f7c3c1d1e9fb0d28e73898951f90e02714abb770fd6d22e90371882a45658800e9@127.0.0.1:40404 -> enode://fcbe9f83218487b3c0b50878193880e6c25cfd86708c0a0bf0ca91f0ce633746a892fe240afa5b9a880b8bca48e8a22704ef937fdda2d7cc63e4d41ed1b417ae@127.0.0.1:30303
2021-09-29 11:08:50.186+10:00 | vert.x-eventloop-thread-2 | INFO  | …
```
> added trace logging for ip -> dns when checking smart contract permissioning

- CHANGELOG.md
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivateContractPublicStateAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/RemoteSimpleStorage.sol
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/generated/RemoteSimpleStorage.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DefaultMutablePrivateWorldStateUpdater.java
- evm/src/main/java/org/hyperledger/besu/evm/processor/MessageCallProcessor.java
Private contracts not able to call public contracts that call other public contracts. 
The root cause is that during `transferValue` the `MessageCallProcessor` attempts to get a mutable account. At this point the evm throws an exception as it is rightly not mutable!
This can be avoided in situations when there is no value to transfer.
fix #2803 Private Transaction Failed when invoking a Public Contract that calls another Public Contract
> fix: private contracts not able to call public contracts that call other public contracts

- .circleci/config.yml
Add manual approval to benchmark until fixed
Alternatively we could revert https://github.com/hyperledger/besu/commit/ce28aae8b1c789298097deba0b4acc188e5088cb
> Add manual approval to benchmark until fixed

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/options/stable/NodePrivateKeyFileOption.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/PublicKeySubCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- besu/src/test/java/org/hyperledger/besu/cli/PublicKeySubCommandTest.java
This PR adds `--node-private-key-file` option to `public-key export-address` and `public-key export` commands.
Fixes #536
> [#536] Add support for custom private key file for public-key export and public-key export-address commands

- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryTimestampsTest.java
Signed-off-by: Caitlin Harding <chardingcs@gmail.com>
The unit test `PeerDiscoveryTimestampsTest.lastContactedTimestampUpdatedOnOutboundMessage()` fails intermittently due to a timestamp precision issue. In the unit tests, we are comparing the before and after state of a timestamp to ensure it was updated. When the test runs too quickly, the before and after states appear equal due to a loss of precision.
I tried the following solutions:
1. Fixing the precision issue by using the `org.hyperledger.besu.testutil.TestClock` test fixture.
- This did not solve the problem because the underlying class used in the SUT (`DiscoveryPeer`) stores the timestamps as longs, so we are constrained by the precision of longs.
2. Using Mockito to spy on the peer and assert that the `setLastSeen` and …
> 2742: Fix flaky timestamp unit test

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocol.java
To support following the chain prior to TTD being reached, the NEW_BLOCK_HASHES and NEW_BLOCK messages must remain enabled.  
Potentially validation could/should be added to reject an new blocks if their parent already meets the total difficulty requirement for transition but that likely should live in the block import code rather than the networking code. That hasn't been done in this PR.
> Leave block p2p messages enabled

- CHANGELOG.md
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/operations/CreateOperationTest.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCreateOperation.java
Always copy the create code. Since it is memory bytes it is subject to
re-writing by the caller and all data would otherwise have to be treated
as mutable.
#2899
> Always copy create code

- CHANGELOG.md
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/EthGraphQLHttpBySpecTest.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/eth_call_from_contract.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/eth_estimateGas_from_contract.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_call_from_contract.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_estimateGas_from_contract.json
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/TransactionValidationParams.java
> Fix #2890: Allow eth_call and eth_estimateGas to accept contract address as sender

- .circleci/config.yml
- CHANGELOG.md
Upgrade OpenJDK used by CircleCI to version 11.0.12
fixes #2927
> Upgrade OpenJDK used by CircleCI to version 11.0.12 [#2927]

- CHANGELOG.md
- docker/graalvm/Dockerfile
- docker/openjdk-11/Dockerfile
AdoptOpenJDK project is now deprecated.
Replace AdoptOpenJDK base image for Java 11, with the updated base image provided by Eclipse Temurin.
fixes #2925
> [#2925] Update JDK 11 to latest version in Besu Docker images 

- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validator/ValidatorContractController.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validator/ValidatorContractControllerTest.java
Add an extra check to ensure that a successful contract call with an empty result configures an error, as we never expect the validator contract to return an empty list of validators.
This is important because of the way that contract call works. It is possible to call an address that does not have a  contract deployed, and still get a successful call with an empty result.
fixes #2900
> Improve ValidatorContractController result validation

- CHANGELOG.md
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestSetChainParams.java
Add 21.10.0 release changes from the release branch back to main
* update changelog to reflect the 21.10.0 release
* fix a bit of copypasta in retesteth chain params for the arrowGlacier definition
> Add 21.10.0 release changes to main

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyNode.java
- acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/plugins/BadCLIOptionsPlugin.java
- acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/plugins/TestPrivacyServicePlugin.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/BadCLIOptionsPluginTest.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
This is required because plugin implementation may need to wait until cli options have been bound to decide if they wish to initialise. 
> Move plugin validation to happen after startPlugins

- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/protocol/BftProtocolManager.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/QbftGossip.java
- Add a trace log message when `BftProtocolManager` receives a subprotocol message. This is the entry-point for BFT related logic in response to the message.
N/A
> More BFT tracing log messages

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractBlockParameterMethod.java
description in https://github.com/hyperledger/besu/issues/3020
fixes #3020
> Fix a double execution of the same method

- config/src/main/java/org/hyperledger/besu/config/JsonUtil.java
- config/src/test/java/org/hyperledger/besu/config/JsonUtilTest.java
- Updated JsonUtils to handle ArrayNode. This is important now that we have bft transitions that are specified in an array in the genesis file.
fixes #2856
> JsonUtil.normalizeKeys should handle ArrayNodes

- gradle/versions.gradle
The discovery dependency is responsible for handling the v5 version of the discovery process of peers. This PR is updating the version to the latest. The project changed versioning after 0.5.0. The following version was 21.10.0 as can be seen on
the [release page](https://github.com/ConsenSys/discovery/releases).
fixes #3027
> [3026] Updating version of disovery dependency 

- crypto/src/test/java/org/hyperledger/besu/crypto/NodeKeyTest.java
The NodeKeyTest might fail in case the SignatureAlgorithmFactory has an
instance already set from some previous test.
fixes #3011
> [3011] Calling SignatureAlgorithmFactory::resetInstance before test

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/config/DiscoveryConfiguration.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetworkTest.java
We are creating but not starting the dns discovery daemon. After this modification the node find peers instantly.
> Fix dns discovery issue 

- build.gradle
Jacoco failed to instrument some tests using the old version of the tool
when build under jdk17
Fixes #3040
> Updating the jacoco toolVersion

- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/test/ValidatorContractTest.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/QbftForksSchedulesFactory.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validator/QbftForksSchedulesFactoryTest.java
A runtime is thrown at startup if this requirement is not met.
A second PR will remove some now redundant complexity in ForkingValidatorProvider
https://github.com/hyperledger/besu/issues/3038
> Require blockheader mode validators

- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/DataStorageOptions.java
- besu/src/main/java/org/hyperledger/besu/cli/util/TomlConfigFileDefaultProvider.java
- besu/src/test/java/org/hyperledger/besu/cli/TomlConfigFileDefaultProviderTest.java
Fix toml config file parsing for options that map to type Long or long.  Previously setting a value in toml config for a long option type would result in, e.g. :
```org.apache.tuweni.toml.TomlInvalidTypeException: Value of 'Xbonsai-maximum-back-layers-to-load' is a integer```
> fix toml parsing of Long option types

- config/src/main/java/org/hyperledger/besu/config/JsonQbftConfigOptions.java
- config/src/test/java/org/hyperledger/besu/config/JsonQbftConfigOptionsTest.java
- ethereum/api/build.gradle
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketService.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/util/TestJsonRpcMethodsUtil.java
We were not handling JDK8 (de)serialization properly in our RPC services. This PR is using jackson-jdk8 module to handle Optional (de)serialization for responses.
This will ensure that serialization maps the value of Optional to null, if no value is present, or the wrapped value if present.
It does not make sense for the QBFT config to return null for the validator address and start block, so we are not including it into the json when these values are not present.
N/A
> Fix admin_nodeInfo when response has jdk8 optional values

- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/ForkSpec.java
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BaseBftProtocolSchedule.java
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BftForksSchedule.java
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BlockTimer.java
- consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/BaseBftProtocolScheduleTest.java
- consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/BftForksScheduleTest.java
- consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/BlockTimerTest.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/IbftForksSchedulesFactory.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/IbftForksSchedulesFactoryTest.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/IbftProtocolScheduleTest.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/blockcreation/BftBlockCreatorTest.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/QbftForksSchedulesFactory.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/blockcreation/QbftBlockCreatorFactory.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validator/ForkingValidatorProvider.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validator/TransactionValidatorProvider.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validator/ValidatorModeTransitionLogger.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/QbftProtocolScheduleTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/blockcreation/QbftBlockCreatorFactoryTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validator/QbftForksSchedulesFactoryTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validator/ValidatorModeTransitionLoggerTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validator/ValidatorTestUtils.java
This was split out of #3069. Changes the BftForkSpec to more generic concept so it can be reused in the QBFT migration.
* Rename BftForkSpec to ForkSpec
* Move from consenus.common.bft package in the consensus.common package
* Allow it to hold any value not just a BftConfigOption
* Rename getConfigOption to getValue
> Rename BftForkSpec to ForkSpec and make it generic

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/ParameterizedEnclaveTestBase.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyNode.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/BftPrivacyClusterAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/EnclaveErrorAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/OnchainPrivacyAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivDebugGetStateRootOnchainGroupAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivacyClusterAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivacyGroupAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/multitenancy/OnchainMultiTenancyAcceptanceTest.java
- testutil/src/main/java/org/hyperledger/enclave/testutil/EnclaveType.java
ORION is getting deprecated. There is no need to run these acceptance
tests any more.
Fixes [3030](https://github.com/hyperledger/besu/issues/3030)
> Removing the orion acceptance tests

- besu/src/main/java/org/hyperledger/besu/controller/ConsensusScheduleBesuControllerBuilder.java
Initialise the ConsensusScheduleBesuControllerBuilder delegate BesuControllerBuilders
> Initialise the ConsensusScheduleBesuControllerBuilder delegate BesuControllerBuilders

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/logging/XmlExtensionConfiguration.java
Adding support of the NO_COLOR environment variable as described in
the [NO_COLOR](https://no-color.org/) standard.
The new behaviour looks like this:
1) Both NO_COLOR is not set and color-enabled options is not set => colors
will be enabled (by default we have colors on)
2) NO_COLOR is not set but color-enabled option is set to false =>
colors will be disabled (we can disable colors using an option)
3) NO_COLOR is set to any value and color-enabled option is not used =>
colors will be disabled (we can disable colors using an environment
variable this is new!)
4) NO_COLOR is set to any value but color-enabled option is set to true
=> colors will be enabled (an option has precedence over the environment
variable)
Fixes issue …
> Adding support for NO_COLOR environment variable

- build.gradle
- settings.gradle
Temporary use a build of this plugin that contains the proposed PR[1],
that improve the downloadLicenses task, reducing its execution time from
about 10 minutes to under 1 minute.
The build is temporary hosted in a custom repository, until a new upstream
version with the patch is released.
[1]https://github.com/hierynomus/license-gradle-plugin/pull/203
fixes #3094
> Use an improved version of the Gradle plugin used to check licenses

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgentTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/MockConnectionInitializer.java
Previously we would always process the list of DNS resolved peers from the beginning. We would
at most only try `maxConnections` valid elements from the list and never try more. So the each
time we might be trying the same 25 peers, we connect with them and then drop them. This PR
firstly shuffles the peers list each time before applying it and then also takes from the list for
as long as there are free peers slots available as opposed to guess the limit upfront and hope
that all the peers connect.
> Making sure that the resolved DNS lists get used in full

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/MergeContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeMiningCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/PayloadIdentifier.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/TransitionCoordinator.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/PayloadIdentifierTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExecutePayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdated.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/ExecutionUpdateForkChoiceResult.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/ExecutionEngineJsonRpcMethods.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/JsonRpcMethodsFactory.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadTest.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/BlockHeaderTestFixture.java
minor refactor in support of merging getPayload rpc method into main
* ensure we always serialize as even length hex representation
* move payload id into consensus namespace
* remove unused protocolSchedule
> Prepare to merge execute_getPayload json-rpc endpoint into main

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockHeader.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockHeaderBuilder.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/ProcessableBlockHeader.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/SealableBlockHeader.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/KeccakHasherTest.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/BlockHeader.java
In support of [EIP-4399](https://github.com/ethereum/EIPs/blob/979cf123558bab61e2278f3c962c9a68d1adc2f4/EIPS/eip-4399.md) this PR adds a field to block headers, `random` which is 32 bytes of randao randomness data.
In accordance with spec, we re-purpose mixHash as random in RLP encoding and decoding, since they should be mutually exclusive -  a block with `random`  will not have a `mixHash` and vice-versa
related to #2897
> merge of Blockheader changes to support random field

- gradle/wrapper/gradle-wrapper.properties
check the [release notes](https://docs.gradle.org/7.3/release-notes.html) to see what is new (jdk17 support among other things).
> Updating gradle to version 7.3

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
Reduce log level down to debug on EthPeer Permissioning - the logs can become very verbose when blocking p2p transactions in private networks.
> Reduce log level down to debug on EthPeer Permissioning

- .circleci/config.yml
- gradle/versions.gradle
Remove duplicate code (TODO) in FlexiblePrivacyPrecompiledContract. The getParticipantsFromParameter method was copied from FlexibleUtil, this has now been removed.
#2961
> Removing duplicate code from FlexiblePrivacyPrecompiledContract [#2961]

- besu/src/main/java/org/hyperledger/besu/controller/ConsensusScheduleBesuControllerBuilder.java
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/ForksSchedule.java
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BftForksScheduleFactory.java
- consensus/common/src/test/java/org/hyperledger/besu/consensus/common/ForksScheduleTest.java
- consensus/common/src/test/java/org/hyperledger/besu/consensus/common/MigratingMiningCoordinatorTest.java
- consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/BaseBftProtocolScheduleTest.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/IbftProtocolScheduleTest.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/blockcreation/BftBlockCreatorTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/QbftProtocolScheduleTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validator/ForkingValidatorProviderTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validator/TransactionValidatorProviderTest.java
Simplify the constructor for the ForkSchedule. This removes the need to seperate out a seperate ForkSpec for the genesis block.
fixes #3131
> Change the ForkSchedule to take a single argument

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/EnclaveErrorAcceptanceTest.java
Use generic language, remove reference to Orion formatted messages
> [MINOR] updating enclave AT code to remove orion references

- CHANGELOG.md
- build.gradle
- gradle/versions.gradle
Upgrades log4j and explicitly disables JNDI message format lookups to improve security.
> Upgrade log4j

- CHANGELOG.md
- gradle.properties
- [X ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
> uprev to 20.10.4-SNAPSHOT

- CHANGELOG.md
Correct link and hash for 21.10.3 release
> corrected download link for 21.10.3

- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/operations/RandomOperationTest.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/RandomOperation.java
comparison fix for random operation - compare to UInt256.ZERO rather than Bytes.of(0) when operating in the 'transition' mode between preMergeFork and terminal total difficulty
> fix comparison in random operation

- CHANGELOG.md
- docker/openjdk-11-debug/Dockerfile
- docker/openjdk-11/Dockerfile
- docker/openjdk-latest/Dockerfile
- ethereum/evmtool/src/main/docker/Dockerfile
Change the docker base images from debian (implied by openjdk image) to
ubuntu explicitly. Ubuntu has quicker reaction time to base image
security vulnerabilities.
Fixes #3045
> Change docker base images from debian to ubuntu

- CHANGELOG.md
- gradle/versions.gradle
Updates to log4j2 2.16.0 which identified a second vector for JNDI attacks via `ThreadContext`. Besu only uses `ThreadContext` as part of the acceptance test framework and not in production code so isn't vulnerable to this issue.
> Update to log4j 2.16.0

- .circleci/config.yml
- acceptance-tests/tests/build.gradle
- acceptance-tests/tests/contracts/CrossContractReader.sol
- acceptance-tests/tests/contracts/EventEmitter.sol
- acceptance-tests/tests/contracts/RemoteSimpleStorage.sol
- acceptance-tests/tests/contracts/RevertReason.sol
- acceptance-tests/tests/contracts/SimpleStorage.sol
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PluginPrivacySigningAcceptanceTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/AbstractBlockPropagationManagerTest.java
* install solc on CI executor
* specify version of solidity
* update pragma of all solidity files to allow 0.8 
* two minor changes to solidity so it compiles under solc 0.8
> install solc in CI; specify solidity version for web3j plugin

- CHANGELOG.md
* Fixes up some alignment issues in the 21.10.x changelog. 
* Adds 21.10.5 
* and removes download link for earlier 21.10.x releases
> CHANGELOG got a bit out of sync. this fixes it

- CHANGELOG.md
- gradle/versions.gradle
Apache Log4j2 versions 2.0-alpha1 through 2.16.0 did not protect from uncontrolled recursion from self-referential lookups. When the logging configuration uses a non-default Pattern Layout with a Context Lookup (for example, $${ctx:loginId}), attackers with control over Thread Context Map (MDC) input data can craft malicious input data that contains a recursive lookup, resulting in a StackOverflowError that will terminate the process. This is also known as a DOS (Denial of Service) attack.
> Update to Log4j 2.17.0

- CHANGELOG.md
- gradle/versions.gradle
Update log4j to 2.17.1
https://logging.apache.org/log4j/2.x/security.html
> update log4j 2.17.1

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxFrameConstants.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/P2PPlainNetworkTest.java
TLS fragments large messages into 16KB records.
Actual fix was done in an earlier commit: https://github.com/hyperledger/besu/commit/f2f7ac9af1a52e04c422f5663063ad27aad35137
This fixes https://github.com/hyperledger/besu/issues/3254
> Added integration test to ensure DevP2P-over-TLS can handle large messages

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/NettyTLSConnectionInitializer.java
Enabling Snappy compression for DevP2P-over-TLS. I'll follow up with a PR adding some testing around the Netty pipeline, however, this code is already being tested as part of our TLS acceptance tests so it is safe to merge.
see #3259
> besu-3259 Add Compression to TLS P2P

- .circleci/config.yml
- acceptance-tests/tests/build.gradle
Remove install of solc on CI executor and revert to using solc that is bundled with the gradle plugin
Fixes #3277
> revert to using bundled solc

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceCorsTest.java
Before the vert.x upgrade (#3135), the usage of `*` in the Cors-Origin [allowed any string](https://github.com/vert-x3/vertx-web/blob/3.9.8/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java#L169) to pass. Meanwhile the [current version](https://github.com/vert-x3/vertx-web/blob/4.2.1/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java#L231) performs a series of validations for the same wildcard, which allows only a fixed set of protocols (i.e. ftp, http, https). To return the original semantics of `*` according the documentation, an actual regex must be used.
This causes problems when a browser extension, like [Metamask](https://metamask.io/), tries to connect to a Besu client because …
> [regression] Reenable cors-origin to support any protocol

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthFeeHistory.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/UnsignedLongParameter.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthFeeHistoryTest.java
Correctly parse hex parameters for ethFeeHistory blockCount
Fixes #3301
> make ethFeeHistory accept hex values for blockCount

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthFeeHistory.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/UnsignedLongParameter.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceCorsTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthFeeHistoryTest.java
- gradle.properties
Fixes CORS regression caused by Vert.x upgrade.
> 21.10.9 release

- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftBlockHeightManager.java
Removes an unnecessary warning from the QBFT logs. Due to precision of the Java timer sometimes the proposal message can be received before our block timer expiry event.
> Remove unnecessary log when block timer expiry happens after the proposal

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/PipelineChainDownloader.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/PipelineChainDownloaderTest.java
There right way of halting a ChainDownloader is only via the cancel method,
no special action should be taken on a generic CancellationException, that
could be triggered by peer tasks that run in the pipeline, since in that
case the error is transient and the download should restart.
For example this exception that is triggered by a timeout talking with a peer, causes the ChainDownloader to completely exit, while it should restart after the configured timeout.
To correctly shutdown the ChainDownloader, the method `cancel()` must be used, and it aborts the underlying pipeline, that  triggers a `CancellationException`, but the downloader exits anyway since the `cancelled.get()` now returns `true`
```
{
"timestamp": …
```
> Do not exit ChainDownloader in case of a generic CancellationException

- CHANGELOG.md
Besu CI pipeline was re-run on the same commit, generating the same artefact with a different hash
See https://app.circleci.com/pipelines/github/hyperledger/besu?branch=release-21.10.x&filter=all 
^ looking at this - pipeline for commit 8f465c0 was run twice. 7 days ago and 2 days ago.
Since the commit is the same https://github.com/hyperledger/besu/commit/8f465c0faf568b395c8e271c6caff6f79d77a7a7
I'm updating the hashes.
Also ref https://github.com/hyperledger/homebrew-besu/pull/70
> 21.10.9 update hashes to match regenerated artefacts

- CHANGELOG.md
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/permissions/PeerPermissionsDenylist.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/permissions/PeerPermissionsDenylistTest.java
Prevent connecting to self enode.
See #2689 and #3322
> Eliminate connect to self

- .circleci/config.yml
small executor does not have sudo
but we don't need libSodium install in order to scan the docker image
> change dependencies for trivy scan step

- ethereum/rlp/src/main/java/org/hyperledger/besu/ethereum/rlp/AbstractRLPInput.java
- ethereum/rlp/src/main/java/org/hyperledger/besu/ethereum/rlp/RLPInput.java
- ethereum/rlp/src/test/java/org/hyperledger/besu/ethereum/rlp/BytesValueRLPInputTest.java
Expose the RLP index when decoding RLP input.
> Expose RLP Index in Input Decoding

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/PublicKeySubCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/PublicKeySubCommandTest.java
- crypto/src/main/java/org/hyperledger/besu/crypto/KeyPairUtil.java
- crypto/src/main/java/org/hyperledger/besu/crypto/SignatureAlgorithmType.java
- Add ec-curve parameter public key export/export-address subcommands
- Defaults to secp256k1
- Support secp256k1 and secp256r1
- Added a log message when creating a key with the selected ec curve name 
Note: due to the static initialization of the SignatureAlgorithmFactory, we need to ensure that its setup happens before any other key-related operation. This is why I have added it as the first instruction in the `run()` method in the subcommands.
fixes #3206
> Add ec-curve parameter public key export/export-address subcommands

- CHANGELOG.md
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java
Disable RocksDB TTL compactions, since they are not needed for Besu, and consume a lot of I/O
fixes #3355
> Disable RocksDB TTL compactions

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonResponseStreamer.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/JsonResponseStreamer.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonResponseStreamerTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/JsonResponseStreamerTest.java
Queue management is removed, since it is not working at the moment,
and can cause deadlock, will be reimplemented later if needed.
fixes #3381
> Response streaming: stop on IO error and remove queue management

- .circleci/config.yml
add kintsugi as a branch we publish to docker from.  This is likely the only commit this branch will get as the network is nearing end-of-life
> add kintsugi to publishDocker

- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/MergeOptions.java
- besu/src/test/java/org/hyperledger/besu/cli/options/unstable/MergeConfigOptionsTest.java
- config/src/main/java/org/hyperledger/besu/config/experimental/MergeConfigOptions.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/PoWMinerExecutor.java
> Rename MergeOptions to MergeConfigOptions to follow the standard

- DCO.md
Hyperledger has moved to Discord.
Signed-off-by: Ry Jones <ry@linux.com>
> Change chat pointers

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/CliqueBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/MergeBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/MiningParameterOverrides.java
- besu/src/main/java/org/hyperledger/besu/controller/TransitionBesuControllerBuilder.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/controller/MergeBesuControllerBuilderTest.java
- besu/src/test/java/org/hyperledger/besu/controller/TransitionControllerBuilderTest.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/PostMergeContextTest.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchain.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/PipelineChainDownloader.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/state/SyncState.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolEvictionService.java
Correctly and consistently handle mining pre/post merge for PoW and Clique networks.  The majority of this PR is code from the merge branch which needed some 'treatment' in order to not cause regressions in behavior on main.
* for clarity, rename isStoppedAtTerminalDifficulty to hasReachedTerminalDifficulty 
* use AtomicReference for PostMergeContext rather than synchronized
* add mining parameter override for consensus mechanisms that mine regardless of miningParameters
* merge parameter validation from `merge` branch which allows mining parameters without PoW mining (if merge is enabled)
* merge fix for optional in TxPoolEvictionService
* fix for ancestorIsValidTerminalProofOfWork in MergeCoordinator when close to TTD
* address Rayonism …
> Handle TTD and mining pre and post merge 

- .github/workflows/gradle-wrapper-validation.yml
Checks that the gradle wrapper jar is from an official release since a maliciously modified jar added as part of a gradle upgrade would be a significant security risk but is hard to verify from the code diff.  This checks the jar comes from an Official Gradle release.
See https://github.com/gradle/wrapper-validation-action for more details.
> Add GitHub action to verify gradle-wrapper.jar

- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Synchronizer.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthMessages.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/BlockPropagationManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/CheckpointRangeSource.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/DefaultSynchronizer.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/PipelineChainDownloader.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncDownloadPipelineFactory.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FlexibleBlockHashTerminalCondition.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullImportBlockStep.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncChainDownloader.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncDownloadPipelineFactory.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncDownloader.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncTargetManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncTerminationCondition.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/SyncTerminationCondition.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/CheckpointRangeSourceTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/PipelineChainDownloaderTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullImportBlockStepTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncChainDownloaderForkTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncChainDownloaderTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncChainDownloaderTotalTerminalDifficultyTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncDownloaderTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncTargetManagerTest.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/DummySynchronizer.java
The Full sync future should finish executing once the terminal total difficulty is reached. Note that we will not stop syncing exactly at the TTD but we will finish syncing the current batch of blocks.
> FullSync Future should stop when total terminal difficulty is reached

- .circleci/config.yml
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/BlockParameterOrBlockHash.java
* Address this error: Resource class "med" is not a valid resource class. The default resource class will be used. eg https://app.circleci.com/pipelines/github/hyperledger/besu/13609/workflows/3b159bdb-3556-4612-bb4f-3fa89c0271b4/jobs/76148
* And also fixed another typo
> [MINOR] typo in resource class 

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugAccountAt.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugAccountAtTest.java
If contract address supplied as the account parameter to `debug_accountAt`, I get an Internal Error with this IllegalArgumentException:
```
Expected at most 32 bytes but got 44
java.lang.IllegalArgumentException: Expected at most 32 bytes but got 168
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:299)
at org.apache.tuweni.bytes.Bytes32.leftPad(Bytes32.java:176)
at org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.Quantity.create(Quantity.java:54)
at org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.Quantity.create(Quantity.java:50)
at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.DebugAccountAt.debugAccountAtResult(DebugAccountAt.java:130)
at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.DebugAccountAtTest.testResult(Deb …
```
> debug_accountAt - fixed issue with contract code

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfiguration.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/EngineExchangeTransitionConfigurationParameter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/EngineExchangeTransitionConfigurationResult.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/ExecutionEngineJsonRpcMethods.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfigurationTest.java
Implements the `engine_exchangeTransitionConfigurationV1` API endpoint according to [specification](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#engine_exchangetransitionconfigurationv1). It is part of the Kiln v2 spec.
fixes #3471
> MERGE: engine_exchangeTransitionConfigurationV1 API

- .circleci/config.yml
Use docker executor and jdk image as before (but keep medium resource class)
> [MINOR] quorum ATs use docker executor

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractTraceByBlock.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceCall.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceCallMany.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceGet.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/AbstractJsonRpcHttpBySpecTest.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs/trace-call/trace_call_12_1_trace.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs/trace-callMany/trace_callMany_12_trace.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs/trace-get/trace_get_12_1_0_trace.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs/trace-raw-transaction/trace_rawTransaction_12_1_trace.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs/trace-transaction/trace_transaction_12_1_trace.json
Add revertReason to trace_transaction, trace_call, trace_callMany, trace_rawTransaction and trace_get
Note revertReason manually added to the relevant test files generated from OE.
Also added a new test file for trace_transaction.
> Trace APIs: add revert reason

- acceptance-tests/tests/build.gradle
- build.gradle
- gradle/versions.gradle
Updated dependencies
* netty
* solidity plugin
* artifactory plugin
* jmh
* spring crypto
* testcontainers
> Updated netty

- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLContextType.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLDataFetchers.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/BlockAdapterBase.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/PendingStateAdapter.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/AbstractDataFetcherTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/AbstractEthGraphQLHttpServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/BlockDataFetcherTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpServiceCorsTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpServiceHostWhitelistTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpServiceTest.java
Signed-off-by: Sandra Wang <yx97.wang@gmail.com>
This PR is focused on resolving the deprecated dependency of graphQL context.
Deprecated: `graphql.schema.DataFetchingEnvironment#getContext`
Issue #2776
> Refactor graphqlcontext since getContext() is deprecated

- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketRequestHandlerTest.java
Send 2 x the same request as the batch. The request of "" seems to cause different behaviour.
> modified batch request test to avoid async complete issue

- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketRequestHandlerTest.java
Ignoring flaky websocket batch test
> ignore flaky test

- gradle/versions.gradle
This reverts commit 9d2d87e954f5f74007d64dffd11a5f2f742d938b.
Revert the version of vertx just in case it is responsible for the change in behaviour of the WebSocket batch request test
> Revert "upgrade vertx (#3530)"

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
Fixed some typos including in the CHANGELOG
> [MINOR] corrections to changelog and typos

- besu/src/main/java/org/hyperledger/besu/cli/subcommands/PasswordSubCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/PublicKeySubCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/RetestethSubCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/ValidateConfigSubCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/BackupState.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/GenerateBlockchainConfig.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/GenerateLogBloomCache.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/OperatorSubCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/RestoreState.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/rlp/RLPSubCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/PasswordSubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/PublicKeySubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/ValidateConfigSubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/operator/OperatorSubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/rlp/RLPSubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommandTest.java
Signed-off-by: Davide Savazzi <davide@davidesavazzi.net>
Added --version flag to subcommands. Added a test for each subcommand.
fixes #2762
> Added --version flag to subcommands [#2762]

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/options/stable/DataStorageOptions.java
- besu/src/test/resources/everything_config.toml
This is a leftover from #3578 to display the new stable options in the `--help` output
> Display data storage options in CLI help

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
BEFORE
```
2022-03-18 13:38:22.593+10:00 | vert.x-worker-thread-0 | DEBUG | JsonRpcHttpService | Invalid Params
org.hyperledger.besu.ethereum.api.jsonrpc.internal.exception.InvalidJsonRpcParameters: Invalid json rpc parameter at index 1
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.hyperledger.besu.ethereum.api.jsonrpc.internal.parameters.TraceTypeParameter`, problem: Invalid trace types supplied: foo
at [Source: (String)"["foo","stateDiff"]"; line: 1, column: 19]
```
AFTER:
```
2022-03-18 13:38:22.593+10:00 | vert.x-worker-thread-0 | DEBUG | JsonRpcHttpService | Invalid Params for method: trace_rawTransaction …
```
> [MINOR] add RPC method name to log for InvalidParams

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueSegmentIdentifier.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueStorageProvider.java
This PR should put back a missing GOQUORUM_PRIVATE_STORAGE enum that I accidentally removed.
> Return GOQUORUM_PRIVATE_STORAGE where it was

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/BufferedGetPooledTransactionsFromPeerFetcher.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetPooledTransactionsFromPeerTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/NewPooledTransactionHashesMessageProcessor.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PeerTransactionTracker.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactory.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionsMessageProcessor.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/AbstractPendingTransactionsSorter.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/task/BufferedGetPooledTransactionsFromPeerFetcherTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/NewPooledTransactionHashesMessageProcessorTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionsMessageProcessorTest.java
This is the last PR in the series to review and optimize transaction synchronization, and its goal is to avoid reprocessing transactions, that Besu have already seen recently.
The currently way Besu has to spot if a transaction has already been process, is to look if the transaction is present in the transaction pool, that by default is 4K, while the amount of pending transactions on the mainnet, is much more, the order of hundred of thousands, so basically even if a transaction has been already processed, the chances that it gets reprocessed is very high, with the result of doing a lot of useless work, that affects Besu performance.
A trivial solution could be to just raise the transaction pool size, but that is not always advisable, because it is critical for block production to keep it …
> Skip seen transactions

- CHANGELOG.md
- gradle/versions.gradle
Previsous jackson-databing version has been flagged (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518).
> Updated jackson-databind to version 2.13.2.2

- CHANGELOG.md
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/NodeSmartContractV2PermissioningController.java
- ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/NodeSmartContractV2PermissioningControllerTest.java
Instead of throwing, log IllegalStateException and the enode that was being checked. and return notPermitted
> Onchain Node Permissioning: log enode being checked with IllegalStateException

- .circleci/config.yml
Add docker setup step
Job is currently failing with this error:
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
eg https://app.circleci.com/pipelines/github/hyperledger/besu/14269/workflows/87252694-72a0-4c5e-845d-0c5be9d09848/jobs/81171
The last time this job passed https://app.circleci.com/pipelines/github/hyperledger/besu/13644/workflows/0fb32713-e855-4cec-b079-680b67f14aa8/jobs/76357
> Quorum ATs nightly CI task: setup docker

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateKeyValueStorage.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateKeyValueStorageTest.java
Fix a bug that caused the worldstate to be missing during a fastsync and prevented it from completing properly
> Fix save worldstate issue on bonsai and fastsync

- besu/src/main/java/org/hyperledger/besu/controller/MergeBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/TransitionBesuControllerBuilder.java
- besu/src/test/java/org/hyperledger/besu/controller/TransitionControllerBuilderTest.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionBackwardSyncContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionProtocolSchedule.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionUtils.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncContext.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/ForwardSyncPhase.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/ForwardSyncPhaseTest.java
Address a post-merge case where we have transitioned to the post-merge rules, but need to import pre-merge blocks due to a reorg ahead of finalization.
BackwardSync is the only mechanism that should be able to reorg below TTD post merge, this PR creates a method In TransitionProtocolSchedule to get ProtocolSpec by block rather than by number.  
TransitionBackwardSyncContext is a transition specific subclass of BackwardSyncContext that leverages the protocol spec by block (without dragging merge consensus into the core ethereum subproject where BackwardSync lives). This backward sync subclass can be removed post-merge with the rest of the transition-by-difficulty code removal.
CURRENTLY DRAFT while writing test coverage.
fixes #3688 …
> Merge: Backward sync re-org below TTD fix

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java
remove TTD search depth limit.  Ideally we will set a recent finalized block when we finish backward sync (and fast and snap sync as well), as that will be more performant than scanning through blocks looking for TTD when we do not have a finalized block.  However, removing this limit will prevent us from incorrectly failing an `engine_forkchoiceUpdate` call post-sync when there is a significant distance between HEAD and TTD.
#3727
> remove TTD depth limit for ancestorIsValidTerminalProofOfWork

- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBMetricsFactory.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/unsegmented/RocksDBKeyValueStorage.java
- plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBMetricsTest.java
Revert to TransactionDB to resolve 'busy' exception from OptimisticTransactionDB.  
As I understand it, we originally went to OptimisticTransctionDB in order to support `deleteRange()` for our implementation of `RocksDBColumnarKeyBValueStore.clear()`.  In light of the change to the `clear` implementation in #3634, we do not need to use OptimisticTransactionDB.  
Currently in Draft while testing and while discussing the merits of sticking with OptimisticTransactionDB for locking performance.
fixes #3719
> revert to TransactionDB to resolve 'busy' exception 

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/MergeProtocolSchedule.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/MergeProtocolScheduleTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessor.java
catch exception on block persist so that it can be added to badBlocks
> use paris evm config in merge protocolschedule

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/TransactionPendingResult.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TxPoolBesuPendingTransactionsTest.java
Currently, there is an issue with the way `TransactionPendingResult` gets serialized by in the JSON-RPC subsystem. Specifically, when responding to `eth_getTransactionByHash,` the `gasPrice`, `maxFeePerGas`, and `maxPriorityFeePerGas` values should be Quantities without leading zeros like so:
```
"gas" : "0x11e63",
"gasPrice" : "0x77359407",
"maxPriorityFeePerGas" : "0x77359400",
"maxFeePerGas" : "0xd09dc3000",
```
This is the official behavior defined in the spec and the behavior demonstrated by Geth and Nethermind.
However, in Besu, they are treated like 32-byte arrays and serialized with the leading zeros in place:
```
"gas" : "0x10c83",
"gasPrice" : "0x0000000000000000000000000000000000000000000000000000000ab5d04c00",
"maxFeePerGas" : …
```
> Remove Leading Zeros from TransactionPendingResult

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/transaction/GetAllPrivateMarkerTransactionHashes.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/RestoreState.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeReorgTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/StateBackupService.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/DirectAcyclicGraphSeed.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/EthHash.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/FlexiblePrivacyController.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/FlexiblePrivacyGroupContract.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/storage/migration/PrivateStorageMigration.java
Where int was being compared with long. Mostly int being used to iterate over values which could be long.
Not sure about these 2 since they are dealing with uint
- FlexiblePrivacyGroupContract
- FlexiblePrivacyGroupController
> changed for loops with int vs long comparison

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldDownloadState.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldDownloadStateTest.java
Fixes a bug that caused Besu to not restart healing properly when changing pivot blocks. Snapsync thought the sync was done instead of restarting on a new pivot block. 
> fix nullpointer on snapsync

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/SizeLimitedMap.java
* dereferenced variable is always null in log message
> [MINOR] fixed one more error from CodeQL

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AllowlistWithDnsPersistorAcceptanceTest.java
This test is consistently passing locally but failing in CI. Ticket here to figure it out - but in the meantime, ignoring it to unblock other PRs. 
> ignore failing test

- metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/MetricsHttpService.java
The metrics service start message was logging the port twice, rather than the host and port as expected.  This changes the log message to print the correct information in standard host:port format.
> Log host and port when starting metrics service.

- .circleci/config.yml
- CHANGELOG.md
- build.gradle
- docker/test.sh
* Add arm64 docker image building 
* add arch suffix to docker image publishing
* add manifest task to  create a unified docker manifest (arm64 and amd64) image publishing
> Build arm64 besu docker images 

- .circleci/config.yml
- build.gradle
In the multi-arch docker build pr #2954, the manifest step is not correctly creating the `develop` and `latest` multi-arch tags.  This pr fixes the tag creation in the manifestDocker step
> Fix for multi-arch docker develop and latest tags 

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AllowlistWithDnsPersistorAcceptanceTest.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/AllowlistPersistor.java
- ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/AllowlistPersistorTest.java
Test was failing because enode containing IP was being resolved via DNS to a hostname, but assertion was still checking for IP. 
Added tests for allowlist behaviour with DNS enabled:
* add enode with IP and then same enode with hostname throws exception
* add enode with hostname should "just work" 
* add enode with IP will resolve to DNS hostname. So check with this behaviour by creating the enodeUrl with DNS config
debug logs from CI
```
03:56:50.876 | Test worker | INFO  | AllowlistWithDnsEnodePersistorAcceptanceTest | enode 2 string enode://5f8a80d14311c39f35f516fa664deaaaa13e85b2f7493f37f6144d86991ec012937307647bd3b9a82abe2974e1407241d54947bbb39763a4cac9f77166ad92a0@192.168.0.10:1234
03:56:50.916 | Test worker | INFO  | …
```
> fix and reinstate the ignored dns/permissioning/allowlist test 

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AllowlistWithDnsPersistorAcceptanceTest.java
Added one more test for the permissioning / allowlist / DNS host resolution issue see #3804 
> [MINOR] one more test for allowlist / DNS scenario

- .circleci/config.yml
Change quorum ATs (nightly) from XL to medium executor. 
The job ran successfully on medium executor https://app.circleci.com/pipelines/github/hyperledger/besu/14864/workflows/e1c2b5d0-44b1-45aa-a5c6-f46eeca7f4bc/jobs/85796
> quorum ATs can run on medium executor

- crypto/build.gradle
- datatypes/build.gradle
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/QosTimer.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfiguration.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/QosTimerTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfigurationTest.java
- ethereum/p2p/build.gradle
- ethereum/rlp/build.gradle
- util/build.gradle
Reduce the runtime dependencies of the EVM module by moving a
class used by a single class out of util to the owned module (QosTimer)
and them removing un-used dependencies from EVM and dependant modules.
> Reduce EVM library dependencies

- CHANGELOG.md
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/ProcessableBlockHeader.java
> Fix: getMixHashOrPrevRandao to return the value present in the block header

- .circleci/config.yml
currently we are not publishing multi-arch `develop` besu docker images.  The most recent `develop` tagged image is 8 days old.  The dockerManifest task which combines specific-arch images (like *-amd64 and *-arm64)  into a single multi-arch image is missing a gradle define for the branch name.
This PR adds circle-ci branch define to dockerManifest task to fix multi-arch `develop` tagged docker publishing. 
- [X ] I thought about documentation and added the `doc-change-required` label to this PR if
> fix manifestDocker develop tag

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/QosTimer.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfiguration.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/QosTimerTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfigurationTest.java
Passing the same vert.x instance as the one used by the test seems to fix the erratic behaviour. Also it reuses the runtime wise instance.
> [Flacky test] Pass vertx instance to QosTimer

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PandaPrinter.java
It still happens that merge pandas are printed twice, by 2 different threads, for example:
```
2022-05-19 13:06:59.984+00:00 | pool-9-thread-1 | INFO  | PandaPrinter |
[...]
2022-05-19 13:07:00.599+00:00 | main | INFO  | PandaPrinter |
```
so PandaPrinter should be made thread safe
> Make pandas thread safe

- CHANGELOG.md
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
- config/src/main/resources/ropsten.json
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
Add ropsten merge terminal total difficulty config, without a paris fork block, as specified by:
https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md#upgrade-schedule
addresses the ropsten TTD config from #3838 
> ropsten TTD config

- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/QosTimerTest.java
Test has been flaky. This is a refactor aiming to fix flakiness.
Refactor extracted from #3850 courtesy @diega 
> attempt to fix QosTimerTest

- build.gradle
> fixed manifest generation for latest docker tag

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncContext.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncContextTest.java
> Stop backward sync if genesis block has been reached

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/MergeOptions.java
the intent of #3875 was to deprecate and warn (not remove) the experimental merge flag.  
This PR re-adds the option as a deprecated useless param
> Re-add deprecated MergeOptions flag

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncStep.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncStepTest.java
Remove the limit that prevents Backward sync to download headers for block with height less than current head block height, that prevents some reorgs to happen
fixes #3887
> Allow to backward sync to request headers back to last finalized block if present or genesis

- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/MergeOptions.java
consume optional boolean argument for deprecated `--Xmerge-support` param
fixes #3648  
> Consume optional boolean for merge-support param

- .circleci/config.yml
remove former rocketchat notification url config 
> Remove defunct rocketchat notification webhook

- evm/src/main/java/org/hyperledger/besu/evm/fluent/EVMExecutor.java
It seems like the message call processor and contract creation processors were inverted in the call going over message frames in the fluent EVM lib.
> use the right processor based on message type

- config/src/main/resources/ropsten.json
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
The problem the beacon chain is not yet ready on Ropsten. It is planned to go up on Monday and will make the fork to Bellatrix  3 days later. So we would run into a scenario where the EL clients make the transition tomorrow, but the CL clients wouldn't do it around 6 days later. So Ropsten would be stalled for around 6 days and we could have a gigantic reorg once the Merge happens, because it is assumed that some people would not have updated their clients and just continue with PoW.
In practice, this means:
1. Users who already upgraded their nodes need to do a TTD override (including most of the genesis beacon chain validators, but these are controlled by clients/testing teams)
2. Clients need to put out a new release with the 100000000000000000000000 (twice the current mainnet TD) TTD …
> new ropsten ttd

- CHANGELOG.md
- gradle/versions.gradle
bump besu-native deps to 0.5.0 for:
* libsecp256k1
* libsecp256r1
* bls12-381 (currently not part of protocol schedule)
relates to #3859 and [besu-native #57](https://github.com/hyperledger/besu-native/issues/57)
> bump besu-native deps to 0.5.0

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/BesuNode.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeConfigurationBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/resources/everything_config.toml
deprecates engine-jwt-enabled, adds engine-jwt-disabled with a default `false` value.  
This is to prevent unintentional "flipping" of this boolean for configs using the flag without a boolean value, e.g.:
`besu --network=ropsten --engine-jwt-enabled`
fixes #3838
> Make engine jwt auth enabled by default

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractBlockParameterMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/BlockParameter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockByNumberTest.java
> Extend block parameter methods to accept 'finalized' and 'safe' as block tags

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
To ease configuration problems stemming from the merge of the engine websocket and engine rpc ports onto a single port with a single config, add an alias, `--engine-rpc-http-port` for former parameter name for engine rpc port.
fixes #3931
> alias former engine port parameter

- container-tests/tests/src/test/java/org/hyperledger/besu/tests/container/ContainerTestBase.java
On my new M1 mac book the Tessera docker wouldn't start. Updating the Tessera docker version fixed that.
> update the docker container versions for Tessera and GoQuorum

- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java
Apply some [RocksDB documentation suggestions](https://github.com/facebook/rocksdb/wiki/Memory-usage-in-RocksDB) to reduce memory usage.
- Set format_version to 5
- set optimize_filters_for_memory to true
- Increase block size to 32K
- set cache_index_and_filter_blocks to true 
There is almost 1,5 GiB difference in memory consumption between this version and version 22.4.2 on a 16 GB RAM VM after 1 day of syncing (the green line represents the metrics of this PR). 
Sync time is equivalent between the two versions.
Disk usage, CPU consumption and the number of open file descriptors is quite similar for tho instances.
> Apply some RocksDB documentation suggestions to reduce memory usage.

- .circleci/config.yml
Seeing periodic failures on the Quorum ATs which can pass after re-running. Changing to large executor should help this.
> large executor for qats

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeMiningCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/TransitionCoordinator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/BadBlockManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncContext.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardsSyncAlgorithm.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncContextTest.java
> Backwards Sync now adding blocks to BadBlocksManager

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
Add a `process_release` metric containing release information.  This shows up as following:
```
process_release{version="besu/v22.4.1-dev-fe8ad2d5/linux-x86_64/openjdk-java-11",} 1.0
```
> Add process_release metric.

- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/EthProtocolOptions.java
- besu/src/test/java/org/hyperledger/besu/cli/options/EthProtocolOptionsTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocolConfiguration.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthServerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactoryTest.java
- util/src/main/java/org/hyperledger/besu/util/number/ByteUnits.java
PR #2485 introduced a limit on incoming `eth` subprotocol message sizes.  However, there is no logic to force outgoing messages to conform to this size limit.  As a result of this asymmetry, a new node trying to sync with other besu nodes may end up disconnecting many of its peers for exceeding this limit.  This can cause nodes to get stuck during the sync process. 
This PR makes the max message size configurable via a hidden option: `--Xeth-max-message-size`.  This provides a workaround for nodes that are stuck in this way.  
Remaining TODOs (to be handled in follow-up PRs):
* Handle message size limit consistently by enforcing limits on outbound messages
This partially addresses the issue described in #3867. 
[updates are required](https://wiki.hyperledger.org/display/BESU/Documentation) …
> [Issue 3867] Make eth subprotocol message size limit configurable

- nat/src/main/java/org/hyperledger/besu/nat/NatService.java
Improve logging in NatService to clarify what's happening. Increase log severity as it can cause peers to fail to connect when running in k8s.
> Improve logging in NatService

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/checkpointsync/CheckpointDownloadBlockStep.java
Fixes a mostly benign error during checkpoint sync which causes the pipeline to pause and restart upon failure to import blocks.  If during the CheckpointDownloadBlockStep we fail to get receipts for the block we are importing, CheckpointBlockImportStep will throw an NPE when attempting to save receipts.
```
2022-07-01 15:14:59.361+00:00 | EthScheduler-Services-29 (importBlock) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.
java.util.concurrent.CompletionException: java.lang.NullPointerException
...
Caused by: java.lang.NullPointerException
at org.hyperledger.besu.ethereum.rlp.RLPOutput.writeList(RLPOutput.java:245)
at org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStoragePrefixedKeyBlockchainStorage$Updater.lambda$rlpEncode$2(KeyValueStora …
```
> checkpoint sync retry download block when we did not get receipts

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdated.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadTest.java
Addresses failures of hive engine test suite "Invalid Timestamp" and "Invalid Transition Payload" tests.  
* on invalid timestamp, return a success response with an INVALID status and validation error message rather than error response
* for latest valid ancestor blocks which are PoW, return Hash.ZERO rather than the PoW hash 
* check tracked bad blocks for forkchoiceUpdated head blockhash, return INVALID rather than SYNCING
> Hive engine suite conformance: Invalid Timestamp, Invalid Transition Payload

- besu/src/test/java/org/hyperledger/besu/controller/TransitionControllerBuilderTest.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionProtocolSchedule.java
hive engine test "Sync Client Post Merge" highlighted a corner case with a method in TransitionProtocolSchedule which supported backward sync below/around TTD block.  
`getByBlockHeader` defers to the block header to find the appropriate pre or post merge protocol schedule, but in the case where we do not have a finalized block, and the terminal block difficulty was *exactly* the TTD value, we would erroneously return a pre-merge protocol schedule for blocks which were children of the terminal block.
PR fixes this behavior, adds some additional logging, and fixes the hive engine test.
relates to #3841
> Fix for TransitionProtocolSchedule by header when terminal block exactly at TTD

- CHANGELOG.md
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeMiningCoordinator.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdated.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedTest.java
A forkchoice update will be ignored if `newHead` is an ancestor of chain head.
fixes #4051
> fcU: Ignore newHead if it is an ancestor of chain head

- CHANGELOG.md
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiPersistedWorldState.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchiveTest.java
We have this issue because we are replacing valid trielog by invalid trielog during a reorg. 
Can explain this strange trie log layer
>  : 0xd77f7f8868f20835fdfc8c7e851f6f23ce9f651d
- StateTrieAccountValue{nonce=859, balance=0x00000000000000000000000000000000000000000000000006d141b0befb39fe, storageRoot=0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, codeHash=0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470}
+ StateTrieAccountValue{nonce=858, balance=0x00000000000000000000000000000000000000000000000006e96a274881e7b6, storageRoot=0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, codeHash=0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470}
The nonce comes from 859 to 858 …
> fix issue because parent world state is not available

- CHANGELOG.md
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/MergeValidationRulesetFactory.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/headervalidationrules/IncrementalTimestampRule.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/headervalidationrules/MergeConsensusRule.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeReorgTest.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/headervalidationrules/IncrementalTimestampValidationTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncContext.java
In PoS current block timestamp must be greather than its parent block timestamp, so adding a new header validation rule to check that.
There is also a fix in the `shouldUsePostMergeRules` that was not correctly checking for TD >= TTD.
With this the Hive test *Invalid Ancestor Chain Re-Org, Invalid Timestamp, Invalid P9', Reveal using sync* passes.
> After merge add a rule to check that the current block is more recent than its parent

- gradle.properties
Release 22.4.4
cherry picks from main:
49e4fd860 -> worldstate not avail (#4069)
6aa88129e -> stateroot mismatch (#4041)
043191a40 -> jwt auth on websockets (#4039)
90f891b78 -> do not move head on exec and propose (#4013)
b5fa62c0b -> sync check before processing remote transactions (4035)
3baa4da99 -> upgrade for websockets (#4019)
5024c0788 -> sepolia TTD (#4024)
5ee9be837 -> heal step in snap (#3920)
261b1e03f -> remove peer block height requirements (#3911)
> Release 22.4.4

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/SnapProtocolManager.java
SnapProtocolManager uses EthPeers so no need to handle connect/disconnect events here as well.
Eliminates some duplicated peer-related logging.
I have tested that Snap Sync works with this change
Before this change
```
2022-07-08 09:51:47.899+10:00 | nioEventLoopGroup-3-10 | TRACE | EthProtocolManager | Process message eth/66, 0
2022-07-08 09:51:47.899+10:00 | nioEventLoopGroup-3-10 | DEBUG | EthProtocolManager | Peer 0xd094aaee3baa666249... PeerReputation 100, validated? true, disconnected? false has mismatched network id: 128
2022-07-08 09:51:47.900+10:00 | nioEventLoopGroup-3-10 | TRACE | EthPeer | handleDisconnect - peer... 0xd094aaee3baa666249, PeerReputation 100
2022-07-08 09:51:47.900+10:00 | nioEventLoopGroup-3-10 | …
```
> no need to register peers connect/disconnect for Snap as well

- CHANGELOG.md
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeMiningCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/TransitionCoordinator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadTest.java
If a block is deemed invalid, because it did not descend from the terminal block, we add it to our bad blocks. This is a fix for the failing Hive engine test `Transition to a Chain with Invalid Terminal Block, Lower Configured Total Difficulty (Transition Payload)`.
> New payload: add invalid to bad blocks

- CHANGELOG.md
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncContext.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/InMemoryBackwardChainTest.java
During the investigation of a Hive test that triggers backward sync, found some improvements that could be applied to backward sync exceptions.
1) Remove of recoursive exceptions nesting, that produces monster exception like this one
[deeply-nested-exception.txt](https://github.com/hyperledger/besu/files/9100608/deeply-nested-exception.txt)
2) Avoid to return `null` from `syncBackwardsUntil` methods in case the block is already trusted
3) Log a warning for backward sync exception that are not recoverable, likewise it is already done for recoverable exceptions
4) Rephrase the error messages when there is a validator error found during the backward sync, with the assumption that the child block is the invalid one, and the parent is …
> Backward sync exception improvements

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncContext.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncContextTest.java
We should allow reorgs bellow finalized blocks during Backwards Sync.
> Finalised blocks should not prevent reorgs in BWS

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/InMemoryBackwardChainTest.java
Remove preventive checks during sync, since they will be performed always performed during the import phase later, where the block will be also flagged as bad block.
With this the last failing Hive test (Invalid Ancestor Chain Re-Org, Invalid Number, Invalid P9', Reveal using sync) passes.
> Delegate all the block checks and validation to the block import phase

- CHANGELOG.md
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/NetworkingServiceLifecycleTest.java
2 of our tests that check error messages from the JVM assume that the system language is always English. If that is not the case, the JVM error messages will be localized and the tests will fail. This PR checks the system language before running those 2 tests and ignores them, if it is not English. If the system language is English the tests are executed like before.
fixes #2190
> Ignore 2 tests that assume that the system language is English, if that should not be the case

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ExecutionEngineJsonRpcMethod.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/BlockPropagationManager.java
log execution errors at right level, stops transition message propagation post-merge sync
> log execution errors at right level, stops transition message propagation post-merge sync

- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/NetworkingOptions.java
- besu/src/test/java/org/hyperledger/besu/cli/options/NetworkingOptionsTest.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/config/DiscoveryConfiguration.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
Signed-off-by: Gabriel Trintinalia <gabriel.trintinalia@consensys.net>
Add experimental config option to enable v5 discovery## 
fixes #4088
> Add experimental config option to enable v5 discovery

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardsSyncAlgorithm.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/InMemoryBackwardChainTest.java
In case of an error the first hash to fetch is lost, and then the backward sync tries to go ahead and start a forward sync.
Sample log 
[first-hash-not-retry.txt](https://github.com/hyperledger/besu/files/9112753/first-hash-not-retry.txt)
This PR remove the hash from the queue only when its successfully fetched
> Remove hash to append from the queue only if the step succeeds

- config/src/main/resources/goerli.json
- config/src/main/resources/mainnet.json
- config/src/main/resources/ropsten.json
- config/src/main/resources/sepolia.json
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/blockheaders/NewBlockHeadersSubscriptionService.java
For the merge the block of the checkpoint must not be after the deployment of the deposit contract 
> checkpoint sync for merge

- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- besu/src/test/java/org/hyperledger/besu/controller/BesuControllerBuilderTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiInMemoryWorldState.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiPersistedWorldState.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchive.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/TrieLogManager.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/InMemoryKeyValueStorageProvider.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchiveTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/LogRollingTests.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/RollingImport.java
when we remember block after the merge we must persist the trielog. because if we lose the trielog in the memory   (ex  restart besu) we can end up in a case where the block is saved but not the trielog. this can prevent the rollback or the rollforward to work because besu will consider that it can do it as the block is present but it will failed because trielog is missing. 
may be one of the reasons for the problem found on a ropsten test node
A possible edgecase description : 
- the head is block 5
- we remember block 6
- as we remember block 6 , we save trielog 6 only in memory
- CL is saying to go to block 7
now we have
- block5 in database + trielog 5 in database
- block6 in database + trielog 6 in memory
- block7 in database + trielog …
> candidate fix for missing parent worldstate

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
PR #3695 uses [i.o.v.e.web.Route#blockingHandler](https://vertx.io/docs/apidocs/io/vertx/ext/web/Route.html#blockingHandler-io.vertx.core.Handler-) to attend JSON-RPC HTTP requests, but [according documentation](https://vertx.io/docs/vertx-web/java/#_using_blocking_handlers) it does it linearly. This PR adds `ordered=false` to let vert.x parallelize the processing.
fixes: #3959
> Fix for RPC performance regression

- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/configuration/RocksDBCLIOptions.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java
Update RocksDB default block cache size to mitigate a performance regression from #3985.
We can see in the dashboard below that we have some blocks behind with the RocksDB block cache default value 8 MB, and Besu with block cache size 128 MB is performing better (no blocks behind).
#4128
> Update RocksDB default block cache size

- .circleci/config.yml
- CHANGELOG.md
- besu/src/main/scripts/unixStartScript.txt
- docker/openjdk-11-debug/Dockerfile
- docker/openjdk-11/Dockerfile
- docker/openjdk-latest/Dockerfile
Use jemalloc with linux runtimes to better manage rocksdb memory usage.
* add malloc arena max envar to besu startup
* add jemalloc preload envar to besu startup
* add jemalloc lib download to docker jvm images
smoke tested and verified working on:
Linux x86_64
Docker linux aarch64 (on OSX M1)
Native OSX ([El Capitan +](https://developer.apple.com/forums/thread/13161https://developer.apple.com/forums/thread/13161)) is not loading jemalloc currently
potentially addresses:
#4057
If we end up going with jemalloc as an alternative malloc implementation for besu, we should document the need to have jemalloc installed in your environment, how to do it for each platform.
> alternative malloc implementation - jemalloc

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputation.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractPeerRequestTask.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthPeerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputationTest.java
Currently there is no way for peers improve their reputation. With this PR peers improve their reputation when they send a useful response.
> Useful response improves reputation

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocolConfiguration.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTest.java
The current limit means that we are disconnecting useful peers during syncing.
> increase the default max message size for p2p messages

- besu/src/main/resources/log4j2.xml
Filters out the log message `Refreshing DNS records with...` which is printed once per minute, to reduce the noise in the logs
> Filter out the periodic log message "Refreshing DNS records with ..."

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/authentication/EngineAuthService.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/authentication/EngineAuthServiceTest.java
The engine specification has changed the expiration time of JWT tokens. Before it as 5 seconds, now it is 60 seconds. This PR reflects this change in the spec.
https://github.com/ethereum/execution-apis/pull/256
> Change expiration for JWT authentification of engine port to 60 seconds

- besu/src/test/java/org/hyperledger/besu/ForkIdsTest.java
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
- config/src/main/resources/kiln.json
- config/src/main/resources/sepolia.json
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
- config/src/test/resources/all_forks.json
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/ForkIdTestUtil.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestProtocolSchedules.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestSetChainParams.java
Add sepolia fork next, aka mergeNetSplitBlock.  see https://github.com/ethereum/execution-specs/pull/564
Also:
* remove terminalBlockNumber from the list of forks (it is informational only)
* remove paris from list of forkblocks / aliases
fixes #4157 
> add sepolia mergeNetSplit block

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ExecutionEngineJsonRpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdated.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java
Limit the info logging of the engine API:
* restrict fcU to one forkchoice log line to a max of once per minute
* drop logging of newPayload to debug 
* change invalid newPayload response to warn rather than info, and restrict this to a max of once per minute
Rather than not emitting useful information (like head, safe, and finalized block hashes), restrict the logging of this info so that periods of heavy traffic (like CL syncing) does not cause a torrent of log info
#4143 
> limit engine-api info logging

- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestMineBlocks.java
> Fixed desired gas limit setting in the reference tests service

- .github/workflows/checks.yml
- .github/workflows/dco.yml
Separate dco from spotless, make dco only run for pull requests.
Run on workflow dispatch on demand
> Fix dco on main branch build

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/BlockPropagationManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/state/PendingBlocksManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/AbstractBlockPropagationManagerTest.java
Signed-off-by: Gabriel Trintinalia <gabriel.trintinalia@consensys.net>
Add mechanism to retrieve missing blocks when a pending block is saved
#3955
> Add mechanism to retrieve missing blocks 

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncActions.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotSelectorFromFinalizedBlock.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/TransitionPivotSelector.java
Signed-off-by: matt-nelson-csi <matt.nelson@consensys.net>
Fixes #4182 - switches info to trace on the three noisy Sync commands 
> Switching info to trace on several noisey logs during sync.

- CHANGELOG.md
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/LondonFeeMarket.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/feemarket/LondonFeeMarketTest.java
Also made baseFeeFloor final.
Even if not pratical on mainnet or main testnes, in theory in the genesis file, the `baseFeePerGas` field could be set to any Wei value, for example it could be 1 Wei, as done in the Hive test `consensus/checkGasLimit_London`.
fixes  Hive test `consensus/checkGasLimit_London`
> Allow to set any value for baseFeePerGas in the genesis file

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/range/RangeHeaders.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/range/RangeHeadersValidationStep.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/RangeHeadersValidationStepTest.java
If a response to the get header P2P request only returns the header that
is the start of the range we may need to trim it to an empty response,
this is breaking the validation response. One client has started
returning only the range header start in some circumstances (which is a
valid response per spec). Because we sometimes request an overlapping
header this results in an empty stream once we cut the duplicates.
> Accept empty header set in range headers validation

- CHANGELOG.md
- build.gradle
- gradle.properties
Upgrade spotless to 6.8.0, removing workaround for JDK 17 support.
> upgrade spotless to 6.8.0

- CHANGELOG.md
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
Upgrade Gradle to 7.5. Silence the Gradle welcome message.
> Upgrade gradle to 7.5, silence the welcome message

- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/TransitionBesuControllerBuilder.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PandaPrinter.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionBestPeerComparator.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/PandaPrinterTest.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/PostMergeContextTest.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/TransitionBestPeerComparatorTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/consensus/merge/MergeStateHandler.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/MergePeerFilter.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/state/SyncState.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTest.java
ensure Pandas only print when we merge, not just when we initially set a new merge state (like on startup)
* make panda printer static
* add prior merge state to MergeStateHandler
* move pandas into TransitionControllerBuilder's transition watcher
*  before we print, ensure we are PoS AND the prior merge state was pre-merge
#3954 
> Panda print only when crossing TTD the first time

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthMessages.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/BlockPropagationManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/AbstractBlockPropagationManagerTest.java
- gradle.properties
Since there is a Subscribers for each type of message handler in EthMessages, and only on handler, they all get a subscriber id of 1.  This changes the unsubscribe logic to require the caller to specify the message code handler being unsubscribed from, and removes it from the map of handlers.
fixes #3890 
> Only stop block propagation, not tx handling.

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfiguration.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfigurationTest.java
fix an oversight in the Optional<MergeContext> handling when TTD is absent.  Also ensure the unit test mocks the absence of MergeContext not just the absence of TTD.
bugfix for #4172 
> Fix Optional handling when TTD is absent

- besu/src/main/java/org/hyperledger/besu/controller/MergeBesuControllerBuilder.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
> applies merge filtering to peers after 2 finalized

- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/NetworkingOptions.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerRequirement.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerTable.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PingPacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PongPacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/RecursivePeerRefreshState.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/ApiHandler.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetworkTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramerTest.java
Peers discovered through the DNSDaemon are now added to the peerTable. These peers are potentially used (16 are randomly chosen from the peer table) in RecursivePeerRefreshStateas as the initial peers for bonding and then for finding neighbours, etc.
> DNS peers handled the same as boot nodes

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryControllerTest.java
After a Geth<>Besu peerring test we found that sometimes we had "ENR request failed                       id=68f8eb309602c1a6 addr=3.16.90.60:30303      err=“RPC timeout”
Besu does not respond to the ENR request. By investigating we found that sometimes ENR_REQUEST comes before the PONG and so Besu ignores the request.
This PR allows to cache the request if it arrives before the PONG to answer once the bond is done
> fix enr request order

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/CalculatedDifficultyValidationRule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/ProofOfWorkValidationRule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/TimestampMoreRecentThanParent.java
This is a stopgap revert to address a post-merge sync regression caused by #4190.  The correct fix for this will need to wait until after the 22.7.0 release
workaround for #4209 
> Revert: mainnet blockheder validation merge check

- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java
Apply RocksDB LZ4 compression and compare the performance/resource metrics after sync.
> Apply RocksDB LZ4 compression and compare post-sync metrics

- gradle.properties
This PR increases the maximum heap size for the Gradle build. [By default](https://docs.gradle.org/current/userguide/build_environment.html#sec:configuring_jvm_memory) it's set to 512 megabytes but it doesn't seem enough to run the build process from IntelliJ.
Without this proposed property I could see this message in the Build console:
```
Expiring Daemon because JVM heap space is exhausted
Daemon will be stopped at the end of the build after running out of JVM memory
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Daemon is stopping immediately JVM garbage collector thrashing and after running out of JVM memory
```
[updates …
> Increase Gradle max heap size

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthPeersTest.java
Signed-off-by: Gabriel Trintinalia <gabriel.trintinalia@consensys.net>
A ConcurrentModificationExpetion happens when EthPeers reattempts to execute its Pending Requests and one  request causes a peer to disconnect. This happens because RemoveIf on CopyOnWriteArrayList will test the filter for each item first and mark those who need to be removed and then throw the exception if the list was modified by any filter. 
Replacing removeIf with iterator seems to solve the issue.
#3491
> Fix ConcurrentModificationException on ReattemptPendingPeerRequests

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ExecutionEngineJsonRpcMethod.java
Teku is reporting theses errors https://github.com/ConsenSys/teku/issues/6027
which are preceded by "Execution Client is offline":
```
java.io.IOException: -32603: Internal error
at tech.pegasys.teku.ethereum.executionclient.web3j.Web3JClient.lambda$doRequest$0(Web3JClient.java:69)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147)
at …
```
> Log unexpected exceptions in execution engine rpc

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfiguration.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfigurationTest.java
The fallback TTD for mainnet had off-by-one error. We need to set it to `2^256 - 2^10`, but our code was 
```
Difficulty.MAX_VALUE.subtract(UInt256.valueOf(1024L)
````
The problem is that `MAX_VALUE` is `2^256 - 1`, not `2^256`. So we were calculating in the end `2^256 - 1 - 2^10`.
This PR replaces the calculation with the hard coded value as hex in the config and as decimal in the test.
I confirmed the value with the mainnet genesis file for the consensus clients: https://github.com/ethereum/consensus-specs/blob/981b05afb01d5b19be3a5a60ccb12c3582e4c0cf/configs/mainnet.yaml#L16
fixes #4220
> correct fallback ttd to correct value

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockHeaderValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/AttachedProofOfWorkValidationRule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/CalculatedDifficultyValidationRule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/ProofOfWorkValidationRule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/TimestampMoreRecentThanParent.java
* re-enable PoW, Timestamp, and Difficulty block header validation rules regardless of merge configuration.  
* if merge is enabled, use an AttachedBlockHeaderValidationRule version of ProofOfWorkValidationRule
> fix for fast sync regression on post-merge networks

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/DynamicPivotBlockManager.java
* Only change pivot block if it is different than the existing syncTarget pivotBlock
* move logging level to debug
> quieten DynamicPivotBlockManager

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/RetryingGetAccountRangeFromPeerTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/RetryingGetBytecodeFromPeerTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/RetryingGetStorageRangeFromPeerTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/RetryingGetTrieNodeFromPeerTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractRetryingPeerTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/RetryingGetHeadersEndingAtFromPeerByHashTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/RetryingGetNodeDataFromPeerTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotBlockRetriever.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/DownloadHeaderSequenceTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/GetReceiptsForHeadersTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/RetryingGetHeaderFromPeerByHashTask.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ethtaskutils/RetryingMessageTaskTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractRetryingPeerTaskTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotBlockConfirmerTest.java
Currently tasks based on AbstractRetryingPeerTask, execute the actual task maxRetries + 1 times, while devs expect that it will be executed exactly maxRetries times.
Incremented the maxRetries in existing code to reflect the previous behavior of having the actual number of executions equals to maxRetries + 1.
> Fix off-by-one error in AbstractRetryingPeerTask

- build.gradle
- settings.gradle
Cleanup repository references and limit scope of non-mavenCentral
repositories.
> Gradle repository maintenance

- evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCallOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/CallCodeOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/CallOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/DelegateCallOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/StaticCallOperation.java
The four instances of gas in the CALL operations are all implemented
identically.  Refactor the method into the abstract parent.
> Reduce megamorphic call sites in AbstractCallOperation

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/BftPrivacyClusterAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/DeployPrivateSmartContractAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/EnclaveErrorAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/FlexiblePrivacyAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivCallAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivDebugGetStateRootFlexibleGroupAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivDebugGetStateRootOffchainGroupAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivGetCodeAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivGetLogsAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivGetPrivateTransactionAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivacyClusterAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivacyGroupAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivacyReceiptAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivateContractPublicStateAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivateGenesisAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivateLogFilterAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/multitenancy/FlexibleMultiTenancyAcceptanceTest.java
These tests are uniformly failing since about 6 hours ago. Docker container startup error. eg
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:345)
at app//org.testcontainers.containers.GenericContainer.start(GenericContainer.java:326)
at app//org.hyperledger.enclave.testutil.TesseraTestHarness.start(TesseraTestHarness.java:83)
at app//org.hyperledger.besu.tests.acceptance.dsl.privacy.PrivacyNode.start(PrivacyNode.java:194)
at app//org.hyperledger.besu.tests.acceptance.dsl.privacy.PrivacyCluster.startNode(PrivacyCluster.java:182)
at app//org.hyperledger.besu.tests.acceptance.dsl.privacy.PrivacyCluster.lambd …
```
> ignore the tests that use tessera enclave via docker

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/PendingPeerRequest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractRetryingSwitchingPeerTask.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/DetermineCommonAncestorTaskTest.java
Currently a peer that is marked as disconnected can be returned when asking `EthPeers` for available peers, but returning a disconnected peer is not useful and potentially a cause of problems since all tasks will fail on it.
Not sure how much this affect peer selection in the real world, but in unit tests it happens to choose a disconnected peer for request.
In any case it seems reasonable to add this check, and we can evaluate if we also need to require that a peer is fully validated, before returning it as available
> Filter out disconnected peers when fetching available peers

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/BftPrivacyClusterAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/DeployPrivateSmartContractAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/EnclaveErrorAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/FlexiblePrivacyAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivCallAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivDebugGetStateRootFlexibleGroupAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivDebugGetStateRootOffchainGroupAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivGetCodeAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivGetLogsAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivGetPrivateTransactionAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivacyClusterAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivacyGroupAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivacyReceiptAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivateContractPublicStateAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivateGenesisAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivateLogFilterAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/multitenancy/FlexibleMultiTenancyAcceptanceTest.java
- container-tests/tests/src/test/java/org/hyperledger/besu/tests/container/ContainerTestBase.java
- testutil/src/main/java/org/hyperledger/enclave/testutil/TesseraTestHarness.java
* Use a fixed version of Tessera docker image. 
* Enable the ignored privacy tests that use Tessera 
> Reinstate Tessera tests with a fixed version

- .circleci/config.yml
- build.gradle
- container-tests/tests/src/test/java/org/hyperledger/besu/tests/container/ContainerTestBase.java
- testutil/src/main/java/org/hyperledger/enclave/testutil/TesseraTestHarness.java
* Update tessera docker image version to 22.1.6
* Update ubuntu version on xl machine executor in Circle CI config - this update is required for the tessera 22.1.6 docker image to run
> update Tessera version and ubuntu for xl-machine-executor

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/AbstractJsonRpcTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/ExecutionEngineAcceptanceTest.java
Signed-off-by: Pedro Novais <jpvnovais@gmail.com>
Some renaming that came to mind only after the merging  of #4286
> small variable renaming in AbstractJsonRpcTest

- CHANGELOG.md
- datatypes/src/main/java/org/hyperledger/besu/datatypes/Wei.java
- datatypes/src/test/java/org/hyperledger/besu/datatypes/WeiTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/ExecutionEngineJsonRpcMethods.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/JsonRpcMethodsFactory.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadTest.java
After the switch to PoS, info of the imported blocks are not more logged, this PR re-add the log when a block is imported via the NewPayload engine RPC call, and also update the info logged to remove ommers and add base fee.
Sample of the message:
`Imported #12,862,033 / 5 tx / 439,018 (1.5%) gas / base fee 7 wei / (0xb1b6d51e6382a1c88b42344f53d5321ee63bec0226fae502876af55e7109f431) in 0.028s.`
> Log imported block info post merge

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/exception/Logging403ErrorHandler.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketService.java
Open question as to if this is overly broad: This will log the error message for all failed RPC calls, but not the stack trace, unless logging is turned up to debug.
This _seems_ to be the preferred way to do this in Vert.x, but I'm open to solutions that are more narrowly aimed at the CORS handling case.
fixes #4328 
> 4328 quiet cors errors

- besu/src/test/java/org/hyperledger/besu/services/BesuEventsImplTest.java
- consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueBlockCreatorTest.java
- consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueMinerExecutorTest.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/blockcreation/BftBlockCreatorTest.java
- consensus/ibftlegacy/src/test/java/org/hyperledger/besu/consensus/ibftlegacy/blockcreation/BftBlockCreatorTest.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/BlockTransactionSelectorTest.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/PoWMinerExecutorTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionsForSenderInfo.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/AbstractPendingTransactionsSorter.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/BaseFeePendingTransactionsSorter.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/GasPricePendingTransactionsSorter.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ethtaskutils/AbstractMessageTaskTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/BaseFeePendingTransactionsTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/GasPricePendingTransactionsTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/PendingMultiTypesTransactionsTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TestNode.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolTest.java
Ensure when besu evicts transactions by sender, that future nonces are evicted first
related to protocol-misc 629
> Evict Transactions by sender from tail first

- container-tests/tests/src/test/java/org/hyperledger/besu/tests/container/ContainerTestBase.java
- testutil/src/main/java/org/hyperledger/enclave/testutil/TesseraTestHarness.java
Use 22.1.7 docker image for Tessera. 
Not a required update, dependency change only.
https://github.com/ConsenSys/tessera/releases/tag/tessera-22.1.7
> ContainerTests - use tessera 22.1.7

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapsyncMetricsManager.java
Signed-off-by: Matt Nelson <matt.nelson@consensys.net>
Fixes #4346.
> Update snapsync logging for clearer sync status. Issue 4346.

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/RequestManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/RequestManagerTest.java
When handling a top level RLP encoding error received over the wire we
shouldn't loudly complain about it but instead log it debug.
This particular wrapping handles the case where the top level response
is truncated or otherwise corrupt.
> Quieter logging on wire-RLP Errors

- CHANGELOG.md
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractMiningCoordinator.java
There is an issue that prevents the PoWMiner to stop cleanly, with the effect of taking 30 seconds before the timeout expires and Besu can stop.
Basically the miner executor was only shutdown when running, but not when it was idle, this PR always shutdown the executor when the mining is stopped
fixes #4313
> Always shutdown the mining executor on exit

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/BaseFeePendingTransactionsSorter.java
Address a concurrency problem with transaction eviction, where we try to evict a transaction that has been concurrently removed from the dynamic transaction pool set.
* make the static transaction pool comparator (base-fee-only transactions) safe for non-1559 transactions, in case we attempt to remove a non-1559 transaction.
* check to see if removed transaction has a basefee before attempting to remove it from the static (base-fee only) transaction set.
fixes #4343
> Bugfix concurrent legacy transaction eviction in BaseFee txpool

- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BftExtraData.java
To fix https://github.com/hyperledger/besu/security/code-scanning/654
In most cases, calling the default implementation of toString in java.lang.Object is not what is intended when a string representation of an object is required. The output of the default toString method consists of the class name of the object as well as the object's hashcode, which is usually not what was intended.
> [MINOR] add BftExtraData toString

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/checkpointsync/CheckpointDownloaderFactory.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncActions.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/DynamicPivotBlockManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapDownloaderFactory.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapSyncState.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldDownloadState.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldStateDownloadProcess.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldStateDownloader.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapsyncMetricsManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldDownloadStateTest.java
This PR modifies the snapsync so that the heal is done throughout the download of the blocks. As long as we haven't downloaded all the blocks we change the pivot block to get closer to the head. this reduces the number of blocks to full sync
did some tests pre and post merge and also benchmark on mainnet
- without the PR
Start sync 2022-09-09T20:53:47,926
Finish worldstate  2022-09-10T07:14:19,864
Finish all snapsync 2022-09-11T10:08:11,251
Reach the head 2022-09-11T16:23:29,213
- with the PR 
Start sync 2022-09-09T20:56:31,810
Finish worldstate 2022-09-11T14:43:43,065
Finish all snapsync 2022-09-11T14:43:44,865
Reach the head 2022-09-11T14:46:37,118
we saved 1 hour and 30 minutes with my test (aws t3.xlarge)
new logs will be like that 
``` …
```
> waiting blockchain before stopping snapsync

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/controller/MergeBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/TransitionBesuControllerBuilder.java
- consensus/merge/build.gradle
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeReorgTest.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/MiningParameters.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthScheduler.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/MonitoredExecutors.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java
Retry block creation if there is a transient error and we still have time, to mitigate empty block issue, as describe here
https://github.com/hyperledger/besu/issues/4401#issuecomment-1249340589
mitigates #4401 when there is a `org.rocksdb.RocksDBException: TimedOut(LockTimeout)`
> Retry mechanism for block creation

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ExecutionEngineJsonRpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineCallListener.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfiguration.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdated.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineQosTimer.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/ExecutionEngineJsonRpcMethods.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfigurationTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineQosTimerTest.java
Resets engine QoS timer with every call to the engine API instead of only when `ExchangeTransitionConfiguration` is called. `ExchangeTransitionConfiguration` mismatch will only submit a debug log not a warning anymore.
fixes #4404
> Less strict engine QoS timer

- CHANGELOG.md
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyNode.java
- besu/src/test/java/org/hyperledger/besu/PrivacyTest.java
- besu/src/test/java/org/hyperledger/besu/RunnerTest.java
- ethereum/eth/src/jmh/java/org/hyperledger/besu/ethereum/eth/sync/worldstate/WorldStateDownloaderBenchmark.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/configuration/RocksDBCLIOptions.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/configuration/RocksDBConfiguration.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/configuration/RocksDBConfigurationBuilder.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/configuration/RocksDBFactoryConfiguration.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java
- plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBCLIOptionsTest.java
Create a new flag on RocksDB (_--Xplugin-rocksdb-high-spec-enabled_) for high spec hardware to boost performance. 
With this first version, the impact is on memory usage, as we're tuning RocksDB block cache and Memtables size. By high spec here, we mean a VM or machine with more than 16 GiB. Other modifications in future may include other resources' requirements but for now, the only requirement is on RAM.
The results are promising on a 32 GiB AWS VM, as this new flag reduces 95 percentile block processing time by 30%.
Performance improvements may appear in a couple of hours because of cache warm up time, as we can notice with RocksDB block cache hit ratio and RocksDB get time :
[updates are …
> Create a new flag on RocksDB for high spec hardware to boost performance

- CHANGELOG.md
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/configuration/RocksDBCLIOptions.java
With PR #4423, the flag --Xplugin-rocksdb-high-spec-enabled doesn't work with Toml configuration files. This PR fix this issue.
> Add config file support for high spec flag

- CHANGELOG.md
- acceptance-tests/tests/src/test/resources/jsonrpc/engine/test-cases/01_prepare_payload.json
- acceptance-tests/tests/src/test/resources/jsonrpc/engine/test-cases/02_get_payload.json
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeMiningCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/PayloadIdentifier.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/TransitionCoordinator.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/PostMergeContextTest.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/PayloadIdentifierTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdated.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/EngineForkchoiceUpdatedParameter.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadTest.java
If the consensus layer client, send more than once the same forkchoice update with payload attributes, we build more blocks with the same payload id, but the current implementation just keep the latest one built, no matter if it is better or not than the existing ones.
This PR improve that, comparing the blocks with the same payload id, and keeping the best according to the amount of gas used, this could be improved in a next iteration, comparing the actual fee reward of the block.
> Keep the best block built until now instead of the last one

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- besu/src/test/java/org/hyperledger/besu/services/BesuEventsImplTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/NewPooledTransactionHashesMessageProcessor.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactory.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ethtaskutils/AbstractMessageTaskTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/NewPooledTransactionHashesMessageProcessorTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TestNode.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactoryTest.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java
22.7.4 has a regression on initial sync time, due to the fact that imported blocked are sent to the transaction pool even if it is empty until the initial   sync is done, and in 22.7.4 for every transaction in the block getSender is called and that consume a lot of CPU, to fix in PR#4457 I just make the tx pool subscribe to block added events only when the initial sync is done.
Since there were also the incoming transaction handlers active during the initial sync, the same strategy to register them only after the initial sync is done was added.
> Avoid to process transactions during initial sync

- SECURITY.md
At the request of the EF, a besu-only security list was created, and is the first listed email.  The out-of-date Jira location is also removed.
> Update Security Policy contact info

- consensus/common/src/test-support/java/org/hyperledger/besu/consensus/common/bft/BftContextBuilder.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validator/ValidatorContractController.java
* `Mockito#any` is more directly accessible via `ArgumentMatchers#any`
* `DefaultFunctionReturnDecode#decode` is more directly accessible via `FunctionReturnDecoder#decode`
> Access fields/methods more directly

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/RequestManager.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/PeerDenylistManager.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/PeerDenylistManagerTest.java
- The RequestManager commit that lessens the penalty should be somewhat straightforward. A late response is typically already punished with a timeout before (too many of which and we disconnect). Instead of immediately considering a late response a breach of protocol, we just consider it useless (again, too many of which and we disconnect).
- The not banning of maintained/static peers was a bit more difficult. I'm not sure if this is the right^TM way to do it, but a Peer object has no notion of it being static/maintained. And static nodes are also not instantiated in a single call, they are combined with bootnodes. So adding a `isStatic` field to EthPeer also seemed more trouble than it was worth. Therefore I settled on this solution, but there might be a better/simpler/more elegant one. …
> Fix banning (static peers) because of late response in eth/66

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java
The `exceptionally` was holding a pointer to a block and was not released for potentially long time. 
> The block variable was keeping too much memory while waiting for future to finish

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/Scalars.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/EthGraphQLHttpBySpecTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/scalar/AddressScalarTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/scalar/BigIntScalarTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/scalar/Bytes32ScalarTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/scalar/BytesScalarTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/scalar/LongScalarTest.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/graphql_variable_address.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/graphql_variable_bytes.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/graphql_variable_bytes32.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/graphql_variable_long.json
Our current Graph!L scalar parsing interacts poorly with the variables support in the library.  Revise the parsing so it works correctly.
Fixes #4441
> Make GraphQL scalar parsing compatible with variables

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/MainnetBlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/BlockProcessor.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/MainnetBlockValidatorTest.java
Fixes issue where Besu records a block that experienced a StorageException as a bad block, thus preventing it from being retried by the Consensus Layer. Also corrects some response handling which was hiding the issue.
fixes #4512 
> don't add to bad blocks manager on StorageException

- CHANGELOG.md
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetworkTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/peers/PeerTestHelper.java
When regularly checking connections to maintained peers (static nodes), ensure connection to self is not initiated.
> check for self in one more spot

- CHANGELOG.md
- gradle/versions.gradle
Upgrades Apache Commons Text to 1.10.0 to fix [CVE-2022-42889](https://nvd.nist.gov/vuln/detail/CVE-2022-42889)
> Upgrade Apache Commons Text to 1.10.0

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/Scalars.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/EthGraphQLHttpBySpecTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/scalar/AddressScalarTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/scalar/BigIntScalarTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/scalar/Bytes32ScalarTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/scalar/BytesScalarTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/scalar/LongScalarTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadTest.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/graphql_variable_address.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/graphql_variable_bytes.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/graphql_variable_bytes32.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/graphql_variable_long.json
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/MainnetBlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/BlockProcessor.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/MainnetBlockValidatorTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthScheduler.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/MonitoredExecutors.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/handshake/ecies/ECIESHandshaker.java
- gradle.properties
- gradle/versions.gradle
> Release 22.7.7
