- Jenkinsfile
- README.md
- Dont publish snapshots to bintray 
- Fixup docs link in readme
> No snapshots to bintray + fixup docs link in readme

- besu/src/main/java/org/hyperledger/besu/services/BesuConfigurationImpl.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/services/BesuConfiguration.java
Will not be necessary for 1.3
Better to revert this for now as we may want to implement it differently in the future.
[PAN-3127]
> [PAN-3127] remove-enclave-url-plugin

- Jenkinsfile
- build.gradle
Publish jars to Azure artefacts so we can publish snapshots again. Distributions are still going to binary.
> Publish jars to Azure

- MAINTAINERS.md
List of initial maintainers, with process to add and remove maintainers.
> Initial Maintainers

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcMethodsFactory.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcApis.java
Disable json-rpc trace API's.  These API's are currently under development and should not yet be exposed.
> [PIE-1950] Disable json-rpc trace API's

- CHANGELOG.md
- gradle.properties
> Added 1.2.4 changes

- Jenkinsfile
Azure does not allow a re-upload of a bad upload
> Only publish on Azure for SNAPSHOT releases

- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
Signed-off-by: Christopher Hare <chris.hare@consensys.net>
> Fixing Typo in validation error message

- Jenkinsfile
Fix condition on regex so extra docker tags are pushed too
Fix condition on regex so extra docker tags are pushed too
> Fix docker tags

- Jenkinsfile
- build.gradle
Signed-off-by: Joshua Fernandes <joshua.fernandes@consensys.net>
Publish artifacts to bintray only - not azure anymore
Publish artifacts to bintray only - not azure anymore
> removing azure artifacts and process

- README.md
Add LGTM/Semmle badges as compiled by https://lgtm.com/projects/g/hyperledger/besu/ci/
[PAN-3198](https://pegasys1.atlassian.net/browse/PAN-3198)
> add LGTM badges

- CHANGELOG.md
- gradle.properties
> 1.3 RC Changelog updates

- gradle.properties
We are having the build break on artefact upload because we disallow the republishing of non-SNAPSHOT versions.
We have not and are not releasing 1.3.0-RC2 actual.
> We should be building SNAPSHOT releases now

- README.md
We have got the CII badge, we should celebrate it by having it on our README
> Add CII badge to README

- CHANGELOG.md
- gradle.properties
1.3 Changelog updates and version bump
> 1.3 Release

- CHANGELOG.md
> 1.3 Changelog updates

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
Fix `ThreadBesuNodeRunner` `BesuConfiguration` setup.  Construct `BesuConfiguration` as it would normally be constructed given the node's configured home directory.
> Fix ThreadBesuNodeRunner BesuConfiguration setup

- build.gradle
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/handshake/ecies/ECIESEncryptionEngine.java
`ECIESEncryptionEngine` was inspired by the BouncyCastle implementation of `IESEngine`. 
The Bouncy Castle code used `V` (which is redundant in our code), with it being initialised to an empty array, however in `processBlock()` `V` could be set to another value, but as that method was not carried across to Besu, which means in Besu it would always be an empty array.
Although `ECIESEncryptionEngine` has no unit test, the logic is covered by these unit tests:
- `EncryptedMessageTest` 
- `ECIESHandshakeTest`
Remedies two LGTM warnings.
Removes dead code.
> Removing redundant code

- MAINTAINERS.md
I propose to add Ivaylo as a Besu project maintainer. 
Over the past 10 months, his contributions to the Private Transactions feature have added a lot of value to the project. You can see his past contributions [cliking here](https://github.com/hyperledger/besu/commits?author=iikirilov). I have worked close to him and can attest that he is committed to the project and will help to keep this project in a high-quality standard.
Voting ends two weeks from today, midnight UTC on 2019-10-18
https://www.timeanddate.com/countdown/to?year=2019&month=10&day=18
For more information on this process see the [Becoming a Maintainer](https://github.com/hyperledger/besu/blob/master/MAINTAINERS.md#becoming-a-maintainer) section in the MAINTAINERS.md file.
> New Maintainer candidate: Ivaylo Kirilov

- DCO.md
The chat link was not properly formatted.
Signed-off-by: Gari Singh <gari.r.singh@gmail.com>
> Update formatting in DCO

- CHANGELOG.md
- gradle.properties
> Added 1.3.1 PRs

- gradle.properties
> Prepare for 1.3.2-SNAPSHOT

- acceptance-tests/tests/build.gradle
- build.gradle
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonRpcParameter.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TestNodeList.java
- ethereum/referencetests/build.gradle
- gradle/versions.gradle
Upgrade all dependencies versions except RocksDB and PicoCLI.
> Dependency Version Upgrades

- consensus/clique/build.gradle
Signed-off-by: Christopher Hare <chris.hare@consensys.net>
Spotted this duplicate Gradle dependency when browsing through the code,
> Removing duplicate gradle dependency

- Jenkinsfile
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/unsegmented/RocksDBKeyValueStorage.java
`spotlessCheck` wasn't being run in CI. Add it.
> Ensure spotless runs in CI

- besu/src/test/java/org/hyperledger/besu/cli/PasswordSubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/PublicKeySubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/rlp/RLPSubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommandTest.java
> [MINOR] edits to test names

- besu/src/main/java/org/hyperledger/besu/cli/DefaultCommandValues.java
> remove outdated comment

- CHANGELOG.md
- gradle.properties
> Added 1.3.3 changes

- gradle.properties
updating version to 1.3.4-snapshot
> updating version to 1.3.4-snapshot

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/resources/everything_config.toml
Unhide the pruning enabled command.
> Unhide the --pruning-enabled command

- CHANGELOG.md
- gradle.properties
> Updated changelog for 1.3.4

- gradle.properties
> update ver to 1.3.5-snapshot

- README.md
> [MINOR] minor text fix

- .circleci/config.yml
- Jenkinsfile
We are moving to CircleCI for our primary CI/CD solution
> Remove publishing steps from Jenkins Build

- CHANGELOG.md
- gradle.properties
> Added 1.3.5 changes

- .circleci/config.yml
Storing dist artifacts on build
> Storing dist artifacts on build

- .circleci/config.yml
- build.gradle
publish image to azure acr in addition to dockerhub
> publish image to azure acr in addition to dockerhub

- .circleci/config.yml
- build.gradle
> docker login acr fix typo

- besu/src/main/java/org/hyperledger/besu/services/BesuEventsImpl.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/services/BesuEvents.java
> narrow topic type to Hash because it is, in fact, a Hash

- docker/Dockerfile
> add besu to PATH in Docker

- besu/src/test/java/org/hyperledger/besu/PrivacyTest.java
- enclave/src/integration-test/java/org/hyperledger/besu/enclave/EnclaveTest.java
> Clean up vertx instances in Enclave tests

- CHANGELOG.md
- gradle.properties
> Updated changelog for 1.3.6

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContract.java
* Fix error log (it isn't an error when the payload is not found)
* Added the Private TX hash to the tracing log to help to trace problems with private tx processing
> Improving logs for private tx processing

- CHANGELOG.md
Adding in notes about Muir Glacier compatibility
> Adding in notes about Muir Glacier compatibility

- build.gradle
Fixing docker tags to publish latest
> Fixing docker tags to publish latest

- .gitmodules
Specify which minimum commit to check out for reference tests, and make the clone shallow.
> Shallow reference tests git submodule

- enclave/src/integration-test/java/org/hyperledger/besu/enclave/EnclaveTest.java
- enclave/src/main/java/org/hyperledger/besu/enclave/EnclaveFactory.java
> Introduce a 1s connect timeout for Enclave comms

- CHANGELOG.md
Updates the changelog to include the Agharta config added in #251
> Add Agharta fork block to changelog

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/operations/SelfBalanceOperation.java
Use the recipient address for SELFBALANCE calculations.
> self balance recipient address

- CHANGELOG.md
- gradle.properties
> Added 1.3.7 changes

- CHANGELOG.md
> Added Wiki link to changelog

- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLDataFetcherContext.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/JsonRpcMethodsFactory.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/AbstractEthGraphQLHttpServiceTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueriesLogCacheTest.java
Refactor uses of BlockchainQueries so that they use a single instance
instead of creating one every place they need it.
> Single BlcokchainQueries

- .circleci/config.yml
Enables webhook reporting to the consumer created in hyperledger/hyperledger-rocket-chat-hubot#32 for announcements of build failure in rocket chat
> webhook notifications for rocket-chat

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
Update upnp nat manager port forward description from pantheon (which was misspelled) to besu 
> Update upnp nat manager port forward description.

- gradle.properties
> Prepare for next release

- CHANGELOG.md
> Added 253 PR to changelog

- enclave/src/main/java/org/hyperledger/besu/enclave/types/ReceiveResponse.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetPrivateTransactionTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionReceiptTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContractTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/PrivacyControllerTest.java
> fix AT failure because of additional field sent by Orion

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateTransactionValidator.java
Signed-off-by: Christopher Hare <chris.hare@consensys.net>
When submitting Private Transaction to Besu running in a container, there are nothing in logs (at any level) to help diagnose why a Private Transaction is found to be invalid.
This PR adds DEBUG level logging to record why a Private Transaction fails validation
> Debug logging on Private Transaction failure

- CHANGELOG.md
Update changelog for general and Plugins API changes to Tuweni.
> Changelog updates for Tuwneni

- CHANGELOG.md
> Added priv_call to changelog

- CHANGELOG.md
- gradle.properties
> Release 1.4.0-beta1

- gradle.properties
> Prepare next release

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/diff/DiffNode.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/diff/StateDiffGenerator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/Action.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/FlatTrace.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/FlatTraceGenerator.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockByHashTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockByNumberTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceTransactionTest.java
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs/flat/trace_replayBlockTransactions_traceOnly_0xA.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs/flat/trace_replayBlockTransactions_traceOnly_0xB.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs/flat/trace_replayBlockTransactions_traceOnly_0xC.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs/flat/trace_replayBlockTransactions_traceOnly_0xD.json
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs/flat/trace_replayBlockTransactions_traceOnly_0xE.json
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/AbstractWorldUpdater.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/WorldUpdater.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/debug/TraceFrame.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/DebugOperationTracer.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/ExceptionalHaltReason.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DefaultMutablePrivateWorldStateUpdater.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DefaultMutableWorldState.java
- Flat trace
* Support all call types
* Correct input for new tests
* Correctly report out of gas
* Report null result when no result but no error
- Remove need to keep messageFrame directly in traceframe
- Clean up StateDiffGenerator style
- Tighten type of updated accounts
> Tracing cleanup and fixes

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionLogsIndexer.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueriesLogCacheTest.java
> Transaction log indexing - Renamed .index to .cache.

- .circleci/config.yml
- .gitmodules
- CHANGELOG.md
- gradle.properties
> Allow for 1.3.x releases

- CHANGELOG.md
Changelog entry for multi-tenancy feature
> Changelog entry for multi-tenancy feature

- CHANGELOG.md
> Fixed link

- CHANGELOG.md
- gradle.properties
Signed-off-by: Joshua Fernandes <joshua.fernandes@consensys.net>
v 1.4.0-rc1
> updating version to 1.4.0-rc1

- gradle.properties
updating version to 1.4.1-snapshot
> updating verion to 1.4.1-snapshot

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
- besu/src/main/java/org/hyperledger/besu/Runner.java
- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/GenerateLogBloomCache.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- besu/src/test/resources/everything_config.toml
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminGenerateLogBloomCache.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/AutoTransactionLogBloomCachingService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionLogBloomCacher.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminGenerateLogBloomCacheTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueriesLogCacheTest.java
Changes class names, variables, and CLI flags as needed.
> Rename logs bloom indexer to log bloom cache to match CLI flag.

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionLogBloomCacher.java
Make sure we cache the current cache segment with all of the data from
the beginning of the segment.  Use a flip file approach since it will be
a partial file until done.
> LogBloomCache - make sure the current segment is filled

- gradle.properties
> Release 1.4.0-RC2

- gradle.properties
> Prepare for 1.4.0-RC3 release

- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
Improved detection of kubernetes. Passing the kubernetes detector before docker
Bounty 4 - https://github.com/hyperledger/besu/pull/410
Conversation - https://github.com/hyperledger/besu/pull/410#discussion_r381302813
> [BOUNTY-4][FIX] Change order of nat detector

- CHANGELOG.md
- gradle.properties
> Added 1.4.0 changes

- CHANGELOG.md
updating the changelog with 1.4.0 details
> updating the changelog with 1.4.0 details

- MAINTAINERS.md
I propose to add Stefan as a Besu project maintainer. 
Over the past few months, his contributions to the Private Transactions feature have added a lot of value to the project. You can see his past contributions [cliking here](https://github.com/hyperledger/besu/commits?author=pinges). I have worked close to him and can attest that he is committed to the project and will help to keep this project in a high-quality standard.
Voting ends two weeks from today, midnight UTC on 2020-03-02 [countdown](https://www.timeanddate.com/countdown/generic?iso=20200302T00&p0=22&msg=Stefan+Pingel+Maintainer+Voting&font=serif&csz=1)
For more information on this process see the [Becoming a Maintainer](https://github.com/hyperledger/besu/blob/master/MAINTAINERS.md#becoming-a-maintainer) section in the …
> [MAINTAINERS] New maintainer candidate: Stefan Pingel

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/transaction/PrivacyTransactions.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/transaction/RemoveFromOnChainPrivacyGroupTransaction.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/privacy/PrivacyRequestFactory.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/OnChainPrivacyAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/contracts/PrivacyGroupTest.java
> [PRIV] add remove from privacy group acceptance test

- CHANGELOG.md
- https://github.com/hyperledger/besu/pull/430
- https://github.com/hyperledger/besu/pull/440
> Add changelog entries.

- besu/src/test/java/org/hyperledger/besu/PrivacyTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/privx/PrivxFindOnChainPrivacyGroup.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/privx/PrivxFindOnChainPrivacyGroupTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/MultiTenancyPrivacyController.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/PrivateTransactionDataFixture.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/PrivacyBlockProcessorTest.java
test for privx_findOnChainPrivacyGroup
test for OnChainPrivacyPrecompiledContract
test that rehydration occurs in PrivacyBlockProcessor
> [PRIV] tests for onchain privacy

- CHANGELOG.md
> Updating changelog for pull request #554

- besu/src/main/java/org/hyperledger/besu/Runner.java
Signed-off-by: Horacio Mijail Anton Quiles <hmijail@gmail.com>
> Wait for the service to start, not to stop

- CHANGELOG.md
- docs/Private-Txns-Migration.md
Updated changelog and migration doc for privacy issue
> Updated changelog and migration doc for privacy issue

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockByHash.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethService.java
Add eht_getBlockByHash to retesteth.  Fixes #523.
> Add eth_getBlockByHash to retesteth

- CHANGELOG.md
This adds a changelog entry for pull request #608.
> Add CHANGELOG entry for eth65 addition

- CHANGELOG.md
Signed-off-by: David Mechler <david.mechler@consensys.net>
> Update changelog for block added and reorg events #637

- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/TransactionSmartContractPermissioningController.java
Correct a misleading comment.
This is purely editorial.
> Correct a source code comment

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/priv/PrivConditions.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/priv/PrivGetPrivateTransactionReturnsNull.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyAcceptanceTestBase.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/transaction/PrivacyTransactions.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/privacy/PrivacyRequestFactory.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/PrivGetPrivateTransactionAcceptanceTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetPrivateTransaction.java
Fix priv_getPrivateTransaction return value.
> Fix priv_getPrivateTransaction return

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/storage/PrivateStateKeyValueStorage.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/unsegmented/RocksDBKeyValueStorage.java
- plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/unsegmented/RocksDBColumnarKeyValueStorageTest.java
- services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/InMemoryKeyValueStorage.java
- services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/LimitedInMemoryKeyValueStorage.java
- services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/SegmentedKeyValueStorage.java
- services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/SegmentedKeyValueStorageAdapter.java
Some of these are just cosmetic but I think I found some bugs in there.
> Key Value Tweaks

- CHANGELOG.md
Added eth/65 issue to changelog as known issue
> Added eth/65 issue to changelog as known issue

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactory.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactoryTest.java
This adds a unit test to cover #732
> Fix disconnect pending transaction tracker

- besu/src/main/java/org/hyperledger/besu/cli/options/EthProtocolOptions.java
- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- besu/src/test/java/org/hyperledger/besu/cli/options/EthProtocolOptionsTest.java
- besu/src/test/java/org/hyperledger/besu/services/BesuEventsImplTest.java
- ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthGetFilterChangesIntegrationTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocol.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocolConfiguration.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthServer.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactory.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthServerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ethtaskutils/AbstractMessageTaskTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TestNode.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactoryTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolTest.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/NetworkRunner.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramer.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java
Add a flag to control if Eth65 subprotocol is used.
> Add a feature flag to enable Eth65

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/PrivacyQueries.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/PrivacyQueriesTest.java
> Using PMT index on private logs tx index (fixes #756)

- CHANGELOG.md
- KNOWN_ISSUES.md
Added NAT and service start bug fixes and new known issue to changelog
> Added NAT and service start bug fixes and new known issue to changelog

- CHANGELOG.md
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/CoinbaseFeePriceCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/TransactionPriceCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/fees/CoinbaseFeePriceCalculatorTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/fees/TransactionPriceCalculatorTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessorTest.java
- Created `TransactionPriceCalculator` to compute the transaction gas price.
- Created `CoinbaseFeePriceCalculator` to compute the coinbase reward.
- Updated `MainnetTransactionProcessor` to apply new consensus rules:
- Updated transaction gas price for EIP-1559 transactions.
- Updated coinbase reward for EIP-1559 transactions.
- Updated `MainnetProtocolSpecs` to build the correct TransactionProcessor for EIP-1559 definition.
- #601 
- #605 
> [EIP-1559] Step 9 - Update transaction processing with EIP-1559 rules.

- CHANGELOG.md
Added splunk logging to changelog
> Added splunk logging to changelog

- CHANGELOG.md
> native encryption changelog entries

- CHANGELOG.md
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/CoinbaseFeePriceCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/fees/CoinbaseFeePriceCalculatorTest.java
Fix revert CoinbaseFeePriceCalculator returning long instead of Wei …
> Fix revert CoinbaseFeePriceCalculator returning long instead of Wei

- CHANGELOG.md
> added help msg to changelog

- gradle/versions.gradle
* Update versions of jackson and log4j (direct dependencies)
* Update versions of commons-codec and snakeyaml (indeirect deps)
* Remove version of commons-cli (unused)
> Version Updates

- CHANGELOG.md
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/FeeMarket.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/fees/EIP1559BaseFeeTest.java
Update hard block gas limit to 20M.
> [EIP-1559] Update hard block gas limit to 20M

- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockTransactionSelector.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/BlockTransactionSelectorTest.java
For EIP-1559 blocks, we need to compute the actual basefee from the parent block data and set it to the block header.
#815 
> [EIP-1559] [MINING] Compute base fee and set block header field when creating new block.

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/FeeMarket.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/FeeMarketConfig.java
Change slack coefficient type from double to long.
> Change slack coefficient type from double to long.

- config/src/main/java/org/hyperledger/besu/config/experimental/ExperimentalEIPs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/EIP1559.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/FeeMarket.java
#PR description
Make all EIP-1559 protocol parameters configurable.
#818 
> Make all EIP-1559 protocol parameters configurable.

- config/src/main/java/org/hyperledger/besu/config/experimental/ExperimentalEIPs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/FeeMarket.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/FeeMarketConfig.java
Derive gasIncrementAmount from MaxGasEIP1559 and DecayRange.
#844 
> Derive gasIncrementAmount from MaxGasEIP1559 and DecayRange.

- crypto/src/main/java/org/hyperledger/besu/crypto/KeyPairUtil.java
feat: add `public` in key pair loading for clarity purpose
#548 
Signed-off-by: Alexandre PARIS-VERGNE <alexpv14@gmail.com>
> Indicate that it is the node public key displayed in the log

- CHANGELOG.md
capture some fixed bugs and other improvements.
> Chagelog updates

- CHANGELOG.md
- KNOWN_ISSUES.md
Updated known issues for 1.4.5
> Updated known issues for 1.4.5

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
> --node-private-key-file dependency check and warning log

- gradle.properties
Signed-off-by: Joshua Fernandes <joshua.fernandes@consensys.net>
bumping version to 1.4.6-snapshot
> bumping version to 1.4.6-snapshot

- KNOWN_ISSUES.md
> clarify pruning issue

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
> [#846] Log selected security module

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
The old tests are ignored as this expected to be a temporary measure while pruning database issues are investigated
> completely disable pruning by default for now

- KNOWN_ISSUES.md
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/unsegmented/RocksDBColumnarKeyValueStorageTest.java
> disable pruning and update KNOWN_ISSUES with new issue

- build.gradle
> fix add-opens tpyo

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolReplacementHandler.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolReplacementRule.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionReplacementByPriceRule.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolReplacementHandlerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionReplacementByPriceRuleTest.java
Create a handler responsible of the replacement of transactions in the transaction pool.
This PR is required to deal properly with #905 and #906. 
> Introduce transaction replacement handler.

- KNOWN_ISSUES.md
#929 fixes this issue so we can remove it from the known issues
> remove pruning known issue

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Util.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
Print the "address" of the node on startup (#547)
feat: add log to display public address of the node on startup
fixes #547 
Signed-off-by: Alexandre PARIS-VERGNE <alexpv14@gmail.com>
> feat: add log to display public address of the node on startup

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/util/CommandLineUtils.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandLineUtilsTest.java
> [#939] Update cli dependency warning log message

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateTransactionProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/MessageFrame.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/operations/ReturnStack.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/MessageFrameTestFixture.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/VMReferenceTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/operations/BeginSubOperationTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/operations/JumpSubOperationTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/operations/ReturnSubOperationTest.java
Reverts hyperledger/besu#950
The static instance field makes unit tests flakey.
> Revert "make ReturnStack into singleton class"

- CHANGELOG.md
Added eth_estimateGas fix and logs query known issue to changelog
> Added eth_estimateGas fix and logs query known issue to changelog

- CHANGELOG.md
- docs/1_5_Upgrade.md
> Cherry-pick changelogs into release branch

- CHANGELOG.md
Added node address printing on startup to changelog
> Added node address printing on startup to changelog

- CHANGELOG.md
> Add changelog entry for price bump mechanism.

- CHANGELOG.md
> Changelog for PR #969.

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLConfiguration.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/handlers/TimeoutHandler.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/handlers/TimeoutOptions.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcConfiguration.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/timeout/TimeoutHandlerTest.java
* Use seconds for timeout configuration
* Add units to variable names
* Change timeout to 5 minutes
> Use seconds for Timeout Configuration

- ethereum/core/src/integration-test/java/org/hyperledger/besu/ethereum/worldstate/PrunerIntegrationTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/Pruner.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/worldstate/PrunerTest.java
PrunerTest has been highly intermittent today and this change looks suspiciously like the cause. Reverting to get back to green builds while further investigation happens on how to improve the test.
Reverts https://github.com/hyperledger/besu/commit/303c3a1f85c72f73fb13d5d6cba23afa72e7ada5
> Revert "make mark/sweep prepare async with main thread (#947)"

- CHANGELOG.md
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
- config/src/main/resources/classic.json
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
- config/src/test/resources/valid_config_with_etc_forks.json
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManagerTest.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/FindNeighborsPacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/NeighborsPacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PingPacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PongPacketData.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryPacketSedesTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/FindNeighborsPacketDataTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/MockPacketDataFactory.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/NeighborsPacketDataTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryControllerTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PingPacketDataTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PongPacketDataTest.java
Cherry pick #1005, #1006, and #1014
> Cherrypick 1.4.6 rc2

- CHANGELOG.md
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
- config/src/main/resources/classic.json
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
- config/src/test/resources/valid_config_with_etc_forks.json
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManagerTest.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/FindNeighborsPacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/NeighborsPacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryController.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PingPacketData.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PongPacketData.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryPacketSedesTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/FindNeighborsPacketDataTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/MockPacketDataFactory.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/NeighborsPacketDataTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryControllerTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PingPacketDataTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PongPacketDataTest.java
Cherrypick #1005, #1006, and #1014
> Cherrypick networking stability fixes 

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
Cherry-pick #1073 
Pruning is false by default in all cases. See #896
> [MINOR] pruning-enabled is false by default in all cases

- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
> [MINOR] typo 

- docker/Dockerfile
- docker/tests/01/goss.yaml
- Setting up the besu user:group for the docker container and following best security practices
- updating base container to openjdk 11.0.7
> setting up the besu user:group for the docker container

- CHANGELOG.md
> Fix typo changelog

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
Thanks to @NicolasMassart for finding the issue
> Default to FULL Sync for Dev network

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/authentication/TomlUserTest.java
Replace JSON RPC and JsonRPC with JSON-RPC
> [MINOR] Use JSON-RPC consistently

- enclave/src/integration-test/java/org/hyperledger/besu/enclave/EnclaveTest.java
> [MINOR] typo in test name

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/RetestethSubCommand.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateTransactionLocator.java
* Replace p2p with P2P
* Couple of other typos
> [MINOR] use P2P consistently in help

- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/Quantity.java
typo in comment in Quantity
and resulting update to knownHash in plugin-api/build.gradle
> typo in comment and resulting update to plugin-api hash

- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryTimestampsTest.java
Ignore test which is failing and thus impacting other work. This test is being investigated as per #1157
> Ignore intermittently failing test

- consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/CliqueProtocolSchedule.java
- consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/CliqueProtocolScheduleTest.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/IbftProtocolSchedule.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/IbftProtocolScheduleTest.java
IllegalArgumentException if epoch length zero or negative.
See #836
> IBFT/Clique config must have epoch length > 0

- CHANGELOG.md
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/multitenancy/MultiTenancyAcceptanceTest.java
- enclave/src/main/java/org/hyperledger/besu/enclave/EnclaveConfigurationException.java
- ethereum/core/src/integration-test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContractIntegrationTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractPrecompiledContract.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/OnChainPrivacyPrecompiledContract.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContract.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/PrivateTransactionDataFixture.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContractTest.java
- gradle/versions.gradle
- testutil/src/main/java/org/hyperledger/orion/testutil/OrionConfiguration.java
- testutil/src/main/java/org/hyperledger/orion/testutil/OrionTestHarness.java
- testutil/src/main/java/org/hyperledger/orion/testutil/OrionTestHarnessFactory.java
* Add strict check for privateFrom in private txs (backporting from master)
> Add strict check for privateFrom in private txs (#976)

- gradle/versions.gradle
This PR upgrades all Tuweni dependencies from 1.0.0 to 1.1.0.
> Upgrade Tuweni dependencies to 1.1.0

- CHANGELOG.md
> Added known issues

- CHANGELOG.md
Backporting:
- https://github.com/hyperledger/besu/pull/1193
- https://github.com/hyperledger/besu/pull/1218
> 1.5.0 backport (known issues and changelog)

- CHANGELOG.md
> changelog entry for hidden CLI option

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/priv/PrivConditions.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/priv/PrivGetExecutedTransactionReceiptSuccess.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/priv/PrivGetFailedTransactionReceiptSuccess.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/multitenancy/MultiTenancyAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/PrivacyReceiptAcceptanceTest.java
Added some tests to verify existing functionality around generation of private transaction receipts.
Part of #1117
> Tests for existing private receipt functionality.

- besu/src/main/java/org/hyperledger/besu/Runner.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/NetServices.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/Endpoint.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/VertxPeerDiscoveryAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/peers/EnodeURL.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/NettyConnectionInitializer.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PacketTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerTableTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PingPacketDataTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PongPacketDataTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetworkTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/P2PNetworkTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/peers/EnodeURLTest.java
- util/src/main/java/org/hyperledger/besu/util/IllegalPortException.java
- util/src/main/java/org/hyperledger/besu/util/NetworkUtility.java
This change is not intended to change any functionality.
> Migrate some OptionalInt's to Optional<Integer>s

- CHANGELOG.md
Add :
- https://github.com/hyperledger/besu/pull/1156
- https://github.com/hyperledger/besu/pull/1149
> Update CHANGELOG.md for 1.5.1 release

- CHANGELOG.md
> changelog for 1144 in 1.5.1

- MAINTAINERS.md
At this time I do not have the time to continue with maintainer duties.
> I, Edward Evans formally resign my maintainership

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/BesuNode.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/cluster/Cluster.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeConfiguration.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeConfigurationBuilder.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyNode.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/AbstractPreexistingNodeTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/database/DatabaseMigrationAcceptanceTest.java
Refactors prior to Backup/Restore acceptance tests
* Allow multiple extra commands on the command line
* Extra commands appear at the end of the command line
* Pull node setup out of DB migration test
> Acceptance Test refactors for command tests

- ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/report/NodeStatsReport.java
Fix typo issue for `uptime` field
- Run with eip1559 ethstats server
> Fix typo issue for ethstats

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/PrivacyClusterAcceptanceTest.java
> [MINOR] fixed typo in test

- CHANGELOG.md
Add some missed changelog entries.
> changelog entries

- CHANGELOG.md
Added changelog entry for #1252
> [CHANGELOG] for 1252

- .github/pull_request_template.md
Updated PR template to add changelog checkbox
> Updated PR template to add changelog checkbox

- CHANGELOG.md
> Update CHANGELOG.md for 1239

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/options/EthstatsOptions.java
- errorprone-checks/build.gradle
- errorprone-checks/src/main/java/org/hyperledger/errorpronechecks/ExperimentalCliOptionMustBeHidden.java
- errorprone-checks/src/test/java/org/hyperledger/errorpronechecks/ExperimentalCliOptionMustBeHiddenTest.java
- errorprone-checks/src/test/resources/org/hyperledger/errorpronechecks/ExperimentalCliOptionNotHiddenNegativeCases.java
- errorprone-checks/src/test/resources/org/hyperledger/errorpronechecks/ExperimentalCliOptionNotHiddenPositiveCases.java
- Fix experimental cli option must be hidden
- Add errorprone check
- Refactor ethstats experimental cli options
> Fix experimental cli option must be hidden

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/DefaultPrivacyController.java
remove an unnecessary method call
> remove unnecessary method call

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- besu/src/test/java/org/hyperledger/besu/services/BesuEventsImplTest.java
- besu/src/test/resources/everything_config.toml
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/blockheaders/NewBlockHeadersSubscriptionServiceTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/ProtocolContext.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchain.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/ExecutionContextTestFixture.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/InMemoryStorageProvider.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchainTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/worldstate/PrunerTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/DetermineCommonAncestorTask.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncTargetManagerTest.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/BlockchainModule.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java
fixes #1283
You can pull the changes down and run `DefaultBlockchainTest` to see sample output.
> Reorg Logging

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivCall.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetLogs.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivUtil.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivCallTest.java
Check onchain group membership at given block number.
See #881 
No changelog yet - part of a bigger feature
> check onchain group membership for priv_call

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/PublicKeySubCommand.java
When running from CLI instantiate a config service immediately that
always queries the values from the CLI results.
> Earlier BesuConfigurationService initialization

- CHANGELOG.md
> Added changelog entry for debug_batchSendRawTransaction endpoint

- CHANGELOG.md
Added a note about new version of web3js-eea
> [CHANGELOG] added note about web3js-eea

- .circleci/config.yml
updating base docker containers
> updating base docker containers

- CHANGELOG.md
Added a new section to highlight deprecated items scheduled for removal
> add deprecated section to changelog

- CHANGELOG.md
Signed-off-by: Edward Mack <ed@edwardmack.com>
Update `CHANGELOG.md` to include ECIP-1099 addition to 20.10.0-RC2 section.
> Update change log to add ECIP-1099 entry to 20.10.0-RC2

- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/eea/EeaSendRawTransactionTest.java
fix typo and refactor to remove some code duplication
> [MINOR] refactor and fix typo

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/resources/everything_config.toml
> separated --host-whitelist to a hidden option

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivacyGroupUtil.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/PrivacyGroupUtilTest.java
Removed duplicated code from test. See #551
> [MINOR] remove dupe

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/controller/MainnetBesuControllerBuilder.java
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
- config/src/main/resources/classic.json
- config/src/main/resources/mordor.json
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
Change genesis config option `ecip1099Block` to `thanosBlock` based on comments [PR1421](https://github.com/hyperledger/besu/pull/1421#issuecomment-707642050)
> rename genesis config option Ecip1099Block to ThanosBlock

- ethereum/api/src/main/resources/schema.graphqls
- ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/graphql_pending.json
> Revert "Update graphql pending to allow txn sorting"

- CHANGELOG.md
- KNOWN_ISSUES.md
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/eth/ExpectSuccessfulEthGetTransactionReceipt.java
- build.gradle
- docker/graalvm/Dockerfile
- docker/openjdk-11/Dockerfile
- docker/openjdk-latest/Dockerfile
- docs/tracing/README.md
- docs/tracing/docker-compose.yml
- docs/tracing/otel-collector-config.yml
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/AbstractCallOperation.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/MessageFrame.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/operations/AbstractCreateOperation.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocolConfiguration.java
- ethereum/evmtool/build.gradle
- gradle/versions.gradle
Applies 4 cherry picks and a changelog revision to the RC2 branch
Cherry pick #1410 
Cherry pick #1459 
Cherry pick #1465 
Cherry pick #1468
> 20.10.0-RC2 cherry picks

- CHANGELOG.md
> Changelog for `miner_changeTargetGasLimit`

- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/state/cache/PendingBlockCacheTest.java
Fix https://app.circleci.com/pipelines/github/hyperledger/besu/5831/workflows/ca52dae4-0f77-4e04-8939-60560e8b6127/jobs/28143
> fix shouldReplaceLowestPriorityBlockWhenCacheFull flaky test

- CHANGELOG.md
> Add RC2 download link

- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/state/PendingBlocksManagerTest.java
The cache is based on the timestamp to sort blocks but during the tests it could happen that several blocks could have the same timestamp.
> Fix shouldReplaceLowestPriorityBlockWhenCacheIsFull flaky test

- .circleci/config.yml
adding contexts to ci for dockerhub's login policy
> adding contexts to ci for dockerhub's login policy

- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/EventMultiplexer.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/TomlConfigFileParser.java
- nat/src/main/java/org/hyperledger/besu/nat/NatService.java
A few logging statements had errors in the log statement.  Either the
parameter wasn't used or it was expecting a formatted logger for errors.
> Cleanup logging statements

- CHANGELOG.md
- KNOWN_ISSUES.md
- gradle.properties
Changelog for the 20.10.0 release.
> 20.10.0 changelog

- CHANGELOG.md
> Update deprecated section to include quickstart

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/TimestampMoreRecentThanParent.java
added more detail about what the problem is
> [MINOR] altered block header timestamp trace log msg to be more helpful

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionsMessageSender.java
Added a trace level log message to aid in transaction propagation detection
> [MINOR] added log msg about transaction propagation

- README.md
Makes the change discussed in https://github.com/hyperledger/besu/pull/1460, with a signoff.
> Clarify "Install Besu" line in README

- CHANGELOG.md
> [MINOR] Quorum -> GoQuorum

- CHANGELOG.md
> Add download link for 20.10.1 to changelog

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
To match docs change, remove "peer" after P2P.
> [MINOR] P2P peer -> P2P

- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/config/EthNetworkConfig.java
- besu/src/test/java/org/hyperledger/besu/RunnerTest.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- ethereum/p2p/build.gradle
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/config/DiscoveryConfiguration.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
- gradle/versions.gradle
DNS discovery for goerli, rinkeby and mainnet to help speed up discovery of peers
> Add DNS discovery 

- .circleci/config.yml
- build.gradle
Looking to apply a fix for #1606, testing it with a Windows build.
fixes #1606
> Fix Windows bat file, add a CircleCI build step for it

- .circleci/config.yml
Roll back changes made in #1608
> rollback circle CI changes

- config/src/main/java/org/hyperledger/besu/config/experimental/ExperimentalEIPs.java
> [MINOR] fixed typo

- .circleci/config.yml
- build.gradle
Until we get the AWS creds right, disable those commands
> comment out aws creds

- .circleci/config.yml
Restores windows sanity check we speculatively removed during CI
troubleshooting.
> Restore windows CircleCI sanity check

- CHANGELOG.md
> Add known issues to latest releases in changelog.

- enclave/src/integration-test/java/org/hyperledger/besu/enclave/GoQuorumEnclaveTest.java
- enclave/src/main/java/org/hyperledger/besu/enclave/GoQuorumEnclave.java
- enclave/src/main/java/org/hyperledger/besu/enclave/types/GoQuorumSendSignedRequest.java
This method is needed to use the to be implemented eth_sendRawPrivateTransaction.
> add sendSignedTransaction method to QuorumEnclave

- CHANGELOG.md
> 20.10.3 changlog

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocolConfiguration.java
> Enable eth65

- CHANGELOG.md
> Add download link and 20.10.4 template

- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validation/CommitValidator.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validation/CommitValidatorTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validation/QbftNode.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validation/QbftNodeList.java
> Added validation for QBFT Commit message

- besu/src/main/java/org/hyperledger/besu/controller/IbftBesuControllerBuilder.java
- config/src/main/java/org/hyperledger/besu/config/BftFork.java
- config/src/main/java/org/hyperledger/besu/config/TransitionsConfigOptions.java
Rename IbftFork to BftFork so it can be reused in QBFT
> Rename IbftFork to BftFork so it can be reused in QBFT

- .github/issue_template.md
Updated links in github issue template
> updated links in issue template

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
Fix typo in word originalProtocolSpec
> Fix typo in ProtocolScheduleBuilder

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
Ensure that gas price is greater than base fee for frontier transactions.
> Ensure that gas price is greater than base fee for frontier transactions

- besu/src/main/java/org/hyperledger/besu/cli/DefaultCommandValues.java
Removed unused variables:
- DEFAULT_MAX_REFRESH_DELAY = 3600000;
- DEFAULT_MIN_REFRESH_DELAY = 1;
> Removed unused variables in DefaultCommandValues

- CODE_OF_CONDUCT.md
Add a link to the main code-of-conduct page.  For repolint conformance.
> Add CoC link

- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/messagewrappers/Proposal.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/payload/RoundChangePayload.java
Update the QBFT message RLP encoding to match the agreed upon interop format
> qbft rlp encoding to match interop format

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketService.java
- metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/MetricsHttpService.java
Where vertx allows turn on gzip compression for HTTP.
> Use Http Compression

- build.gradle
Revise the artifactory artifact-id so the download name is correct.
> Revise Artifactory Name

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/RunnerBuilderTest.java
- besu/src/test/java/org/hyperledger/besu/RunnerTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceRpcApisTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkId.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TestNode.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/VertxPeerDiscoveryAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgentTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryTestHelper.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/MockPeerDiscoveryAgent.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetworkTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/NetworkingServiceLifecycleTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/P2PNetworkTest.java
- gradle/versions.gradle
Signed-off-by: David Mechler <david.mechler@consensys.net>
Add the forkId info the the ETH field and add field to ENRs
#1696
> Add ETH field to ENR

- README.md
Updated link to license behind the badge
> [minor] updated link to license

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/BerlinGasCalculator.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/GeneralStateReferenceTestTools.java
- ethereum/referencetests/build.gradle
Upgrade to Berlin reference tests and activate berlin in those tests.
> Update Reference Tests

- besu/src/test/java/org/hyperledger/besu/ForkIdsTest.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MutableProtocolSchedule.java
Update ForkId list for Berlin, and add a test checking the forkId at
each milestone.
> Update ForkId list for Berlin

- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockTransactionSelector.java
When mining a block, the transaction receipt for GoQuorum private transactions needs to be manually assembled.
> GoQuorum private tx when mining

- CHANGELOG.md
> 21.1.0 changelog update

- gradle/versions.gradle
Update orion version and retrieve from cloudsmith
> update orion version

- CHANGELOG.md
> Add download link - release 21.1.1

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetPrecompiledContractRegistries.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/BLS12G1AddPrecompiledContractTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/BLS12G1MulPrecompiledContractTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/BLS12G1MultiExpPrecompiledContractTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/BLS12G2AddPrecompiledContractTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/BLS12G2MulPrecompiledContractTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/BLS12G2MultiExpPrecompiledContractTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/BLS12MapFp2ToG2PrecompiledContractTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/BLS12MapFpToG1PrecompiledContractTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/BLS12PairingPrecompiledContractTest.java
Don't register the BLS12 precompiles for berlin.
> Don't Register BLS12 precompiles for Berlin

- CHANGELOG.md
Signed-off-by: SajZ <sajida.zouarhi@gmail.com>
Bug fixes + additional improvement.
> Update CHANGELOG.md for 21.1.2

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/goquorum/GoQuorumBlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/goquorum/GoQuorumPrivateStateUtil.java
> fix a problem where the private world state is not found in GoQuorum mode

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/MainnetBlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/goquorum/GoQuorumBlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/goquorum/GoQuorumPrivateStateUtil.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/MainnetBlockValidatorTest.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/NoRewardProtocolScheduleWrapper.java
Refactors the logic around getPrivateWorldState to make it a bit clearer.
> Get private world state refactor

- .github/workflows/repolinter.yml
This saves the repolinter report for easy download, and enables manual running
Signed-off-by: Ry Jones <ry@linux.com>
> Update Repolinter action

- CHANGELOG.md
> update CHANGELOG.md for 21.1.3 release

- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BftBlockInterface.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/statemachine/IbftRound.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/validation/MessageValidatorFactory.java
- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/validation/RoundChangeCertificateValidator.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/validation/ProposalBlockConsistencyValidatorTest.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/validation/RoundChangeCertificateValidatorTest.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftRound.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validation/ProposalValidator.java
Make BftBlockInterface#replaceRoundInBlock non-static
> Make BftBlockInterface#replaceRoundInBlock non-static

- MAINTAINERS.md
Tim requested to be moved to Emeritus status.
> Move Tim Beiko to Emeritus Maintainer

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/util/CommandLineUtils.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandLineUtilsTest.java
Updates the dependent CLI option validation to handle options that can be dependent on multiple main options.
Fixes #2038.
> Updated CLI option validation to handle dependent options with multiple main options.

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
Adds configuration validation checks to case where a GoQuorum genesis file is specified, but GoQuorum compatibility is not enabled.
Fixes #2077
> Added error handling for GoQuorum genesis file without GoQuorum compatibility enabled

- gradle/check-licenses.gradle
- gradle/versions.gradle
Update configuration of license cheks to keep up to date with current
versions of gradle. Also, add a couple of license mappings and
sort the entries.
> Update license checks

- besu/src/test/java/org/hyperledger/besu/ForkIdsTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/ForkIdBackwardCompatibilityTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java
> forkid rename

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/AbstractPeerConnection.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/AbstractHandshakeHandler.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/ApiHandler.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramer.java
No functional changes. Just wanted to make it cleaner so I could observe logs easier.
> Clean Up P2P Debug Logging

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PoWSolver.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java
Signed-off-by: Gary Schulte <gary@Garys-MacBook-Pro.local>
it appears that [#1882] inadvertently broke retesteth no-op PoW mining.  This is a quickie PR to get it moving again.
> fix besu retesteth PoW mining

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/TransactionTracer.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/TransactionTracerTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/BerlinGasCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/FrontierGasCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/TangerineWhistleGasCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/GasCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/StandardJsonTracer.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DefaultMutableWorldState.java
This is a testless PR because we want to improve the tracing functionality as it will be the release that will upgrade on mainnet. Testing issue to follow.
fixes #2040
> Tracing Fixes - Mark Transaction Boundaries for Standard Tracing and CallOperation Gas Costs

- CHANGELOG.md
> update changelog for 21.1.4

- CHANGELOG.md
> add download link

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchive.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/AbstractBlockPropagationManagerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/BonsaiBlockPropagationManagerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/ChainHeadTrackerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/ForestBlockPropagationManagerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncActionsTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncChainDownloaderTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotBlockConfirmerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotBlockRetrieverTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncChainDownloaderTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncDownloaderTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncTargetManagerTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/PersistBlockTaskTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/worldstate/WorldDownloadStateTest.java
Added parameterized tests to be able to test the code with Bonsai and Forest
> Added parameterized tests to test Bonsai And Forest

- besu/src/main/java/org/hyperledger/besu/cli/subcommands/RetestethSubCommand.java
add eip-1559 support to retesteth command via flag
> Retesteth 1559

- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigOptionsTest.java
move `eip1559Block` to `aleutBlock`
> Update Aleut genesis block.

- build.gradle
- consensus/qbft/build.gradle
Update qbft reference test submodule with SPDX header
> Update qbft reference test submodule with SPDX header

- CHANGELOG.md
> Prepare changelog for release 21.1.5

- CHANGELOG.md
> Add downlink for 21.1.5 release

- .circleci/config.yml
Removing the container test build step until the privacy issue is resolved.
> Removed container test build step.

- MAINTAINERS.md
Gary has provided [significant commits](https://github.com/hyperledger/besu/commits?author=garyschulte) that have improved the quality of Besu.
Voting ends 2 weeks from the publication of this PR.
For more information on this process see the Becoming a Maintainer section in the MAINTAINERS.md file.
> Add Gary Schulte as Maintainer

- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/ProofOfWorkValidationRule.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/ProofOfWorkValidationRuleTest.java
Prevents EIP1559 blocks from being mined before fork
- [x I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
> Prevents EIP1559 blocks from being mined before fork

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/StandardJsonTracer.java
Fix a crash with tracer on Staticcall and callcode
- Ropsten 
>curl --location --request POST 'http://127.0.0.1:8545' --header 'Content-Type: application/json' --data-raw '{"jsonrpc":"2.0","method":"debug_standardTraceBlockToFile","params":["0x0d9db1248c91a8a2f9b37442d50e7c38b2344853f35b1862e1cf6275ce792467", {"disableMemory":true}],"id":1}'
- Test with some FuzzyVM tests
> Fix tracer crash

- CHANGELOG.md
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/contractvalidation/PrefixCodeRule.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetContractCreationProcessorTest.java
Implement EIP 3541 as defined here https://github.com/ethereum/EIPs/pull/3541
> Implement eip 3541

- .circleci/config.yml
> parallelism 6

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ConsensusNewBlock.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/ConsensusNewBlockParameter.java
fix consensus_newBlock transaction decoding
> fix newblock transaction decoding RPC

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ConsensusNewBlock.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/ConsensusNewBlockParameter.java
Reverts hyperledger/besu#2256.  revert so Proto can get cred for his commit :)
> Revert "fix newblock transaction decoding RPC"

- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockTransactionSelector.java
add ACCESS_LIST to BlockTransactionSelector transaction size check switch statement 
fixes #2220
> add ACCESS_LIST to BlockTransactionSelector

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
Tidy up the way PermissioningConfiguration get propagated between BesuCommand and BesuNode
Duplicate of https://github.com/hyperledger/besu/pull/2155
> Refactor permissioning config

- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java
> [MINOR] update deprecated calls

- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/resources/classic.json
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
- config/src/test/resources/all_forks.json
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
Add more testing to ensure new fork blocks are configured properly.
> Fork Block Testing

- CHANGELOG.md
- besu/src/test/java/org/hyperledger/besu/ForkIdsTest.java
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
- config/src/main/resources/classic.json
- config/src/main/resources/kotti.json
- config/src/main/resources/mordor.json
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminNodeInfoTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecFactory.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
Adds the blocks and the changes for the Magneto hard fork.
Fixes #2314
> Magneto hard fork

- MAINTAINERS.md
Vijay has helped the Besu project through contributions to [user questions](https://chat.hyperledger.org/channel/besu?msg=pEvzRqPLYBvDtbX8m), documentation and [managing issues on the project](https://chat.hyperledger.org/channel/besu?msg=sazaeBhiNpY2Nc5Xk).
Voting ends 2 weeks from the publication of this PR.
For more information on this process see the Becoming a Maintainer section in the MAINTAINERS.md file.
As for the maintainer addition, this PR being a significant change to the process, I require the same rules to be followed:
> Add Vijay Michalik to maintainers

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/Runner.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessor.java
- gradle/versions.gradle
- metrics/core/build.gradle
- metrics/core/src/main/java/org/hyperledger/besu/metrics/opentelemetry/MetricsOtelGrpcPushService.java
- metrics/core/src/main/java/org/hyperledger/besu/metrics/opentelemetry/OpenTelemetryCounter.java
- metrics/core/src/main/java/org/hyperledger/besu/metrics/opentelemetry/OpenTelemetrySystem.java
- metrics/core/src/main/java/org/hyperledger/besu/metrics/opentelemetry/OpenTelemetryTimer.java
- services/pipeline/src/main/java/org/hyperledger/besu/services/pipeline/Pipeline.java
Upgrades Otel to 1.2.0.
Fixes #2312
> Upgrade OpenTelemetry to 1.2.0

- build.gradle
Ignore (new) spam label since this test doesn't work well for EthSigner/Besu
> GoQuorum ATs: ignore spam test

- build.gradle
Ignore new multiple private states (mps) tests
> GoQuorum ATs: ignore multiple private states tests

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulatorTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/GeneralStateReferenceTestTools.java
- ethereum/referencetests/build.gradle
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/GeneralStateTestCaseSpec.java
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/StateTestVersionedTransaction.java
update referencetests to latest develop branch
get 1559 test cases passing
fix transaction encoding of 2718 typed transactions
fixes #2229 
fixes #2285
> update referencetests to latest develop branch

- CHANGELOG.md
Added Tessera/Orion info to changelog
> Orion info in changelog

- CHANGELOG.md
- gradle.properties
update CHANGELOG for 21.1.7 release
> update CHANGELOG for 21.1.7 release

- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockTransactionSelector.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java
Add trace logging for pending transactions behavior.
fixes #2353
> pending tx logging

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/OpenTelemetryAcceptanceTest.java
Fixes a flaky acceptance test checking OpenTelemetry traces are reported.
Fixes #2299
> Fix flaky OpenTelemetry acceptance test

- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/AbstractEthGraphQLHttpServiceTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/TransactionEncoder.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/TestCodeExecutor.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/TransactionBuilderTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/fees/TransactionPriceCalculatorTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulatorTest.java
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/StateTestVersionedTransaction.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionType.java
> Better Error Messages and Default ChainId For More Tx Types

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcErrorConverter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionInvalidReason.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolTest.java
Adds validation for the case where a GoQuorum transaction has a value.
> Added validation for GoQuorum transactions with value.

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecFactory.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/GeneralStateReferenceTestTools.java
- ethereum/referencetests/build.gradle
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/BlockchainReferenceTestCaseSpec.java
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/GeneralStateTestCaseSpec.java
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestEnv.java
* update ref tests to latest develop
* add London to the list of forks tested
* handle missing baseFee for legacy tests
* ignore `transactionSequence` for blockchain test cases (per-transaction block inclusion/exclusion reason)
* remove aleut spec
> update to latest reference tests develop branch

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/options/stable/EthstatsOptions.java
- besu/src/main/resources/org/hyperledger/besu/cli/launcher.json
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/resources/everything_config.toml
Remove experimental flag for ethstats
> Remove experimental flag for ethstats

- gradle.properties
> Fix version for release 21.7.0 branch

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramer.java
Signed-off-by: Justin Florentine <justin.florentine@consensys.net>
RC-2 fix from release branch into master
fixes #2004
> dialing down logging of invalid HELO to debug (#2448)

- config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigOptionsTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/GenesisState.java
- ethereum/referencetests/build.gradle
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/BlockchainReferenceTestCaseSpec.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestSetChainParams.java
* fix location of genesis config for baseFee (move from `config` to root)
* move unit tests out of GenesisConfigOptions and into GenesisConfigFile
* update reference tests to latest develop
* remove test cases for defunct test nets aleut, baikal
* 
fixes #2443
> fix baseFee config in genesis config file

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthFeeHistory.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthJsonRpcMethods.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthFeeHistoryTest.java
> don't retreive full blocks just to get gasUsed

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
> QBFT release changelog entry

- .circleci/config.yml
- build.gradle
> enable quorum ATs

- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- build.gradle
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLDataFetchers.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/TransactionAdapter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/GoQuorumEthGetQuorumPayload.java
- ethereum/api/src/main/resources/schema.graphqls
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/goquorum/GoQuorumEthGetQuorumPayloadTest.java
Updates the GraphQL schema + adapter to handle GoQuorum transaction fields
> GraphQL schema + adapter updates to handle GoQuorum transaction fields

- .circleci/config.yml
- CHANGELOG.md
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/PermissioningPluginTest.java
- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/util/CommandLineUtils.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandLineUtilsTest.java
- build.gradle
- container-tests/tests/src/test/java/org/hyperledger/besu/tests/container/ContainerTestBase.java
- container-tests/tests/src/test/java/org/hyperledger/besu/tests/container/ContainerTests.java
- container-tests/tests/src/test/java/org/hyperledger/besu/tests/container/helpers/ContractOperations.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLDataFetchers.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/TransactionAdapter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractBlockParameterOrBlockHashMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/GoQuorumEthGetQuorumPayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/GoQuorumJsonRpcPrivacyMethods.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivacyApiGroupJsonRpcMethods.java
- ethereum/api/src/main/resources/schema.graphqls
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/goquorum/GoQuorumEthGetQuorumPayloadTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/OnChainPrivacyPrecompiledContract.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContract.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateTransactionSimulator.java
> Cherrypick g cprivacy

- CHANGELOG.md
Co-authored-by: Usman Saleem <usman@usmans.info>
> QBFT release changelog entry (#2487)

- build.gradle
Signed-off-by: Ricardo Silva <ricardo.silva@consensys.net>
Update tags used for Quorum Acceptance Tests to support new tests added on https://github.com/ConsenSys/quorum-acceptance-tests/pull/117.
matches changes on https://github.com/ConsenSys/quorum-acceptance-tests/pull/117
> build gradle: Update tags for Quorum Acceptance Tests

- build.gradle
Enabled the 'get-quorum-payload' GoQuorum ATs.
> Enabled the 'get-quorum-payload' GQ ATs.

- build.gradle
Fixed conditions to tags for Quorum Acceptance Tests. Now it runs all tests as expected and new one.
> Fix tags for Quorum Acceptance Tests

- CHANGELOG.md
> update changelog with 21.7.1 download link

- container-tests/tests/src/test/java/org/hyperledger/besu/tests/container/ContainerTestBase.java
Update to Tessera 21.7.0 in container tests setup
> ATs: update Tessera docker image version

- besu/src/main/java/org/hyperledger/besu/controller/BftBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/IbftBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/QbftBesuControllerBuilder.java
Introduced an abstract `BftBesuControllerBuilder` with supplier methods that enable concrete implementations to provide the desired concrete `ExtraDataCodec` and `BftBlockInterface`.
> Added abstract BftBesuControllerBuilder

- config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
- config/src/main/java/org/hyperledger/besu/config/experimental/ExperimentalEIPs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/BaseFee.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/EIP1559.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/FeeMarket.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/LondonFeeMarket.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/fees/EIP1559Test.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/EIP1559BlockHeaderGasPriceValidationRuleTest.java
We need to clean the ExperimentalEIPs class by removing this flags
This was configurable when developing the EIP now the values have been defined in the spec and cannot change via a flags without creating a consensus bug issue on the mainnet
> EIP1559 Cleanup : remove experimental flags 

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/cluster/Cluster.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/generated/CrossContractReader.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/generated/EventEmitter.java
- besu/src/main/java/org/hyperledger/besu/cli/custom/RpcAuthFileValidator.java
- build.gradle
- container-tests/tests/src/test/java/org/hyperledger/besu/tests/container/ContainerTestBase.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/ApiConfiguration.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugAccountAt.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugGetBadBlocks.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/JsonRpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceTransaction.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivacyApiGroupJsonRpcMethods.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/logs/LogsSubscriptionService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionReceiptWithMetadata.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/LondonGasCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/GasCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/MessageFrame.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/ChainHeadPrivateNonceProviderTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/LegacyForkIdManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/task/WaitForPeerTaskTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/task/WaitForPeersTaskTest.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/NetworkRunner.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/AllowlistPersistor.java
- ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/PermissioningConfigurationBuilder.java
- nat/src/main/java/org/hyperledger/besu/nat/kubernetes/KubernetesNatManager.java
- pki/src/main/java/org/hyperledger/besu/pki/crl/CRLUtil.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/SyncStatus.java
- privacy-contracts/src/main/java/org/hyperledger/besu/privacy/contracts/generated/DefaultOnChainPrivacyGroupManagementContract.java
- privacy-contracts/src/main/java/org/hyperledger/besu/privacy/contracts/generated/OnChainPrivacyGroupManagementProxy.java
Update spotless to 5.14.2 and java-google-format to 1.10.0.
Both of these are needed to support Java 16 and Gradle 7.x.
> Update Spotless and google-java-format

- CHANGELOG.md
Add changelog entries for recent mining work
> Add CHANGELOG entries for recent mining work

- besu/src/main/java/org/hyperledger/besu/controller/QbftBesuControllerBuilder.java
- config/src/main/java/org/hyperledger/besu/config/BftConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/QbftConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
Qbft specific config with validator contract address option
> Qbft validator contract config

- .circleci/config.yml
- .github/issue_template.md
- .github/pull_request_template.md
- .github/workflows/repolinter.yml
- build.gradle
- ethereum/evmtool/build.gradle
Switch from `master` to `main` for the default branch
* Update CircleCI configuration
* Update Gradle snapshot detection
* Update issue templates
> Update Repo for `main` branch

- gradle.properties
> Release 21.7.2

- CHANGELOG.md
- gradle.properties
update the changelog and next version post-hotfix release
> update version and changelog to reflect 21.7.2 hotfix release

- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/services/PermissioningService.java
- plugin-api/src/main/java/org/hyperledger/besu/plugin/services/permissioning/NodeConnectionPermissioningProvider.java
- plugin-api/src/main/java/org/hyperledger/besu/plugin/services/permissioning/NodeMessagePermissioningProvider.java
Add some code snippets into java docs for permissioning plugin implementation
> Permissioning - improve java docs

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivDebugGetStateRootOnchainGroupAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivateGenesisAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/web3j/privacy/OnChainPrivacyAcceptanceTest.java
AcceptanceTests: Confirm transaction has been mined before checking against privCall
> AcceptanceTests: Confirm transaction has been mined

- consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/BlockHeaderValidationRulesetFactory.java
- consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/CliqueProtocolSchedule.java
- consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/CliqueProtocolScheduleTest.java
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BftProtocolSchedule.java
- consensus/ibftlegacy/src/main/java/org/hyperledger/besu/consensus/ibftlegacy/IbftProtocolSchedule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSpecBuilder.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/BaseFeeMarket.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/LondonFeeMarket.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/BaseFeeMarketBlockHeaderGasPriceValidationRule.java
address clique BlockHeaderValidator configuration issue for london fee market
fixes #2680
> address clique london HeaderValidator config

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/OnChainPrivacyPrecompiledContract.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContract.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/OnchainPrivacyGroupContract.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/OnChainPrivacyPrecompiledContractTest.java
Read-only access to the on-chain privacy group contract is centralized to happen in `OnchainPrivacyGroupContract` only. 
fixes #1303
> DRY onchain management proxies

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/BlockPropagationManager.java
Add logs for block propagation manager
> Add logs for block propagation manager

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- build.gradle
> [MINOR] Fixed typos

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ExecutionEngineJsonRpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineSyncCheckpointSet.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineTerminalTotalDifficultyUpdated.java
* Stub out additional [minimum merge spec](https://gist.github.com/mkalinin/e26f1fe70df83a25834cc6a62b6afdac)  endpoints
> Add additional minimum merge spec stubs  #474

- CHANGELOG.md
Moved QBFT experimental features to the "Early access features" section
> CHANGELOG: moved experimental features

- CHANGELOG.md
- gradle.properties
bump build version and changelog to reflect next quarterly release candidate
> prepare for 21.10.0-RC1

- gradle.properties
add missing -SNAPSHOT to gradle.properties build version
> fix RC1-SNAPSHOT release version 🤦‍♂️

- besu/src/test/java/org/hyperledger/besu/PrivacyReorgTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivFindPrivacyGroup.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/eea/RestrictedOffchainEeaSendRawTransactionTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/eea/RestrictedOnchainEeaSendRawTransactionTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivDebugGetStateRootTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivFindPrivacyGroupTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PluginPrivacyController.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivacyController.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivacyGroupUtil.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/RestrictedDefaultPrivacyController.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/RestrictedMultiTenancyPrivacyController.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/RestrictedDefaultPrivacyControllerTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/RestrictedMultiTenancyPrivacyControllerTest.java
We are treating "offchain" as a single word.
Rename refactor. See #2750 for "onchain" change
> Rename: OffChain -> offchain

- CHANGELOG.md
Fix changelog to have bug fix under correct version
> Fix changelog to have bug fix under correct version

- .circleci/config.yml
Remove benchmark from workflow
> Remove benchmark from workflow

- gradle.properties
> Release 21.10.0-RC1

- gradle.properties
> r 21.10.0 RC2 SNAPSHOT

- CHANGELOG.md
Update changelog for 21.10.0-RC2
> changelog for 21.10.0-RC2

- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/CliqueBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/MergeBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/TransitionBesuControllerBuilder.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/MergeBlockProcessor.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/MergeBlockValidator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionProtocolSchedule.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionUtils.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeMiningCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/TransitionCoordinator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineConsensusValidated.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExecutePayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EnginePreparePayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/ExecutionBlockResult.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/MiningParameters.java
fix various issues found during m2/m3 testing:
* fix baseFeePerGas serialization in EngineBlockResult
* fix terminal total difficulty determination for non-PoW consensus
* fix for protocolSchedule on transition (m3)
* persist chaindata on consensusValidated
> errata discovered during m2/m3 testing

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
fix forkchoiceupdate finalized root check
> fix equality for finalized head check in forkChoiceUpdated

- README.md
> Fixed build badge: image

- CHANGELOG.md
- besu/src/test/java/org/hyperledger/besu/ForkIdsTest.java
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
- config/src/main/resources/mainnet.json
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigOptionsTest.java
- config/src/test/resources/all_forks.json
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetDifficultyCalculators.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecFactory.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolScheduleTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/ForkIdTestUtil.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestProtocolSchedules.java
- ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestSetChainParams.java
Quarterly release for 21.10.0.  In addition to the cumulative release candidates (RC1, RC2, RC3, RC4):
* cherry-pick merge of arrow-glacier
* update CHANGELOG.md for quarterly release
> Quarterly release branch update and cherry-pick

- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/statemachine/BaseBftController.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftRound.java
- Added some extra information on QBFT logs to help analysis
N/A
> Improved QBFT logs

- CHANGELOG.md
- gradle.properties
gradle.properties to 21.10.2-SNAPSHOT version
and added placeholder in changelog
> Prepare for 21.10.2-SNAPSHOT

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/config/DiscoveryConfiguration.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/PeerReputationManager.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramer.java
* update sepolia bootnode to reflect EF's new sepolia boot node
* add peer details to debug logging
> Update Sepolia bootnode, peer logging

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/config/DiscoveryConfiguration.java
fix incorrect discovery port on geth sepolia config
> Fix sepolia copypasta

- CHANGELOG.md
added download link and hash for 21.10.1
> [MINOR] add download link for 21.10.1

- evm/src/main/java/org/hyperledger/besu/evm/operation/SarOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/ShlOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/ShrOperation.java
Reduce shift calculations to shifts that may have an actual result.
> Shift Optimization

- config/src/main/java/org/hyperledger/besu/config/QbftConfigOptions.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validator/ForkingValidatorProvider.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validator/ForkingValidatorProviderTest.java
Cleanup for https://github.com/hyperledger/besu/issues/3038 (following the first related PR https://github.com/hyperledger/besu/pull/3043)
> 3038 clean up

- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/NetworkingOptions.java
- besu/src/test/java/org/hyperledger/besu/cli/options/NetworkingOptionsTest.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/config/NetworkingConfiguration.java
> [MINOR] typo - connection

- CHANGELOG.md
- gradle.properties
> 21.10.2 release

- CHANGELOG.md
- gradle.properties
> Prepare for 21.10.3-SNAPSHOT

- besu/src/test/java/org/hyperledger/besu/PrivacyReorgTest.java
Fixes flakey tests e.g. https://app.circleci.com/pipelines/github/hyperledger/besu/11940/workflows/7dc4c157-f51b-4ba7-aaa8-3baec6b5a038/jobs/65476/tests
> fix flakey test caused by random payload

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/PayloadIdentifier.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/PayloadIdentifierTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ExecutionEngineJsonRpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayload.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadTest.java
upstream changes to merge feature branch related to PR feedback from #3107
> remove random from payload Identifier

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdated.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/ExecutionUpdateForkChoiceResult.java
Fixes the issue mentioned in an issue of Teku: https://github.com/ConsenSys/teku/issues/4700
> Merge: Return full payload id when engine_forkchoiceUpdatedV1 is called

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeMiningCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/PayloadIdentifier.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/TransitionCoordinator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ExecutionEngineJsonRpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExecutePayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdated.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/ExecutionPayloadAttributesParameter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/ExecutionPayloadParameter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/BlockResultFactory.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/EngineExecutionResult.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/EngineGetPayloadResult.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/EngineUpdateForkChoiceResult.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/ExecutionBlockResult.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadTest.java
* json-rpc encoding changes
* execution-specific error responses
* add latestValidHash to `engineExecutePayload`
* add invalid blocks to badBlocks on failed validation and/or processing
addresses #3138
> Kintsugi v3/json rpc encoding

- config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/MergeContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeBlockCreator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
address errata discovered with teku interop:
fix baseFeePerGas genesis parsing 
remove mixHash writing from MergeBlockCreator
use evictingQueue for payloads
> address errata discovered with teku interop

- CHANGELOG.md
- MAINTAINERS.md
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/EnclaveErrorAcceptanceTest.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/DefaultCommandValues.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/resources/everything_config.toml
- build.gradle
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
- config/src/test/resources/all_forks.json
- config/src/test/resources/preMerge.json
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/MigratingMiningCoordinator.java
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/blockcreation/BftMiningCoordinator.java
- consensus/common/src/test/java/org/hyperledger/besu/consensus/common/MigratingMiningCoordinatorTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/tls/TlsConfiguration.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/BlockAddedObserver.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockHeader.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecFactory.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/BlockHeaderTestFixture.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/operations/RandomOperationTest.java
- evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java
- evm/src/main/java/org/hyperledger/besu/evm/frame/BlockValues.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/RandomOperation.java
- gradle/versions.gradle
merge of eip-4399 from main into merge branch
plus tls configs
> Merge main eip 4399

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/NetServicesAcceptanceTest.java
moved common code to a Before method
> [MINOR] add common code to before method

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
Update dependency check for TLS / cipher-suite and added test
> Fixed typo in option name in CLI dependency check: tls-cipher-suite

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/BlockPropagationManager.java
Revert deletion of the lowest announced block detection
> Revert deletion of the lowest announced block detection

- CHANGELOG.md
> Update CHANGELOG for 22.1.0-RC1 release and prepare it for next RC

- .circleci/config.yml
- CHANGELOG.md
- build.gradle
- gradle/versions.gradle
- settings.gradle
Security update: upgrade log4j2 to 2.17.0
> Update Log4J2 to 2.17.0

- gradle.properties
> Release 21.10.5

- gradle.properties
> Snapshot 21.10.6

- acceptance-tests/tests/build.gradle
- consensus/merge/build.gradle
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/MergeValidationRulesetFactory.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/headervalidationrules/ConstantOmmersHashRule.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/headervalidationrules/NoDifficultyRule.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/headervalidationrules/NoNonceRule.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/headervalidationrules/ConstantOmmersHashValidationTest.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/headervalidationrules/NoDifficultyValidationTest.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/headervalidationrules/NoNonceValidationTest.java
Kintsugi header validation rules.
fixes #3140
> 3140 header validation rules

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeMiningCoordinator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExecutePayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/ExecutionPayloadParameter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/EngineExecutionResult.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExecutePayloadTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/TransactionDecoder.java
merge `engine_executePayload` into main from merge feature branch
partially adresses #2965
> Merge executePayload to main from merge branch

- gradle/versions.gradle
Upgrade Splunk Javalogging library to latest version
> Upgrade version of splunk javalogging library

- gradle/versions.gradle
> Rollback rocksdb version

- CHANGELOG.md
- gradle.properties
- gradle/versions.gradle
> Release 21.10.6

- gradle.properties
> 21.10.7-SNAPSHOT

- CHANGELOG.md
Added download links and release notes for 21.10.6
> added release notes for 21.10.6

- besu/src/main/java/org/hyperledger/besu/Runner.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolEvictionService.java
Factor out timer from BesuRunner into TransactionPoolEvictionService so that BesuRunner does not contain inner details of the transaction pool implementation.
> factor out timer from BesuRunner into TransactionPoolEvictionService

- gradle/versions.gradle
The referenced issue has been fixed and bls12-381 has been updated
https://github.com/hyperledger/besu/issues/2668
> remove old comment re bls12-381 version

- gradle.properties
21.10.8-SNAPSHOT version in case we need it
> 21.10.8-SNAPSHOT

- CHANGELOG.md
> added changelog and links for 21.10.7 release

- CHANGELOG.md
- gradle.properties
> Release 21.10.9 SNAPSHOT version

- CHANGELOG.md
Changelog entry and download links for 21.10.8
> Release 21.10.8

- gradle/versions.gradle
> vertx 4.2.3

- CHANGELOG.md
> added 21.10.9 to main changelog

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/NettyConnectionInitializer.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/NettyTLSConnectionInitializer.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/NettyTLSConnectionInitializerTest.java
- ethereum/p2p/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Added a test to ensure all required handlers are correctly added to the channel pipeline when using TLS.
> Test for TLS channel pipeline handlers

- CHANGELOG.md
- gradle.properties
> Release 22.1.0-RC3

- CHANGELOG.md
- gradle.properties
Prepare for version 22.1.0-RC4-SNAPSHOT
> Prepare for version 22.1.0-RC4-SNAPSHOT

- CHANGELOG.md
- gradle/versions.gradle
https://github.com/hyperledger/besu-native/releases/tag/0.4.3
> Update besu-native to 0.4.3

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExecutePayload.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExecutePayloadTest.java
- ethereum/eth/build.gradle
- util/src/main/java/org/hyperledger/besu/util/Log4j2ConfiguratorUtil.java
- util/src/main/java/org/hyperledger/besu/util/Slf4jLambdaHelper.java
- util/src/test/java/org/hyperledger/besu/util/Slf4jLambdaHelperTest.java
update main with merge specific changes:
* slf4j lambda shim
* execute payload bugfix from kintsugi consensus issue
> backport merge updates to main

- besu/src/test/java/org/hyperledger/besu/BesuInfoTest.java
- besu/src/test/java/org/hyperledger/besu/PrivacyTest.java
- besu/src/test/java/org/hyperledger/besu/RunnerTest.java
- besu/src/test/java/org/hyperledger/besu/chainexport/RlpBlockExporterTest.java
- besu/src/test/java/org/hyperledger/besu/chainimport/RlpBlockImporterTest.java
- besu/src/test/java/org/hyperledger/besu/cli/EnvironmentVariableDefaultProviderTest.java
- besu/src/test/java/org/hyperledger/besu/cli/PasswordSubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/PublicKeySubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/ValidateConfigSubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/config/EthNetworkConfigTest.java
- besu/src/test/java/org/hyperledger/besu/cli/converter/FractionConverterTest.java
- besu/src/test/java/org/hyperledger/besu/cli/converter/PercentageConverterTest.java
- besu/src/test/java/org/hyperledger/besu/cli/operator/OperatorSubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/options/EthProtocolOptionsTest.java
- besu/src/test/java/org/hyperledger/besu/cli/options/MetricsCLIOptionsTest.java
- besu/src/test/java/org/hyperledger/besu/cli/options/NetworkingOptionsTest.java
- besu/src/test/java/org/hyperledger/besu/cli/options/OptionParserTest.java
- besu/src/test/java/org/hyperledger/besu/cli/options/SynchronizerOptionsTest.java
- besu/src/test/java/org/hyperledger/besu/cli/options/TransactionPoolOptionsTest.java
- besu/src/test/java/org/hyperledger/besu/services/PicoCLIOptionsImplTest.java
- besu/src/test/java/org/hyperledger/besu/util/LocalPermissioningConfigurationValidatorTest.java
- besu/src/test/java/org/hyperledger/besu/util/StringUtilsTest.java
Signed-off-by: Swarnim Pratap Singh swarnimpratap132@gmail.com
Changes remaining classes to MockitoJunitRunner test classes as much as possible in the main directory in besu/src/test/java/org/hyperledger/besu
Only class files of ForkIdsTest(running with Parameterized.class) and PrivacyReordTest(Test failed with MockitoJunitRunner) were not converted
fixes #2951
> Changed almost all test classes to MockitoJunitRunner

- CHANGELOG.md
- gradle.properties
- gradle/versions.gradle
> Release 22.1.0 rc4

- besu/src/test/java/org/hyperledger/besu/cli/launcher/LauncherTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcApis.java
Fix a launcher issue found on JSON RPC configuration step
> Fix launcher JSON RPC issue

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/AcceptanceTestBase.java
Resolving code smells in SonarCloud 
https://sonarcloud.io/project/issues?id=hyperledger_besu&open=AXx2E1kxws9Ez90CDXKp&resolved=false
Changing method name in AcceptanceTestBase from log_eraser to logEraser
> Resolving code smells in SonarCloud

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/PipelineChainDownloader.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/SyncTargetManager.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/PipelineChainDownloaderTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncTargetManagerTest.java
> findSyncTarget always called with Optional.empty

- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminAddPeer.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminAddPeerTest.java
- ethereum/mock-p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/testing/MockNetwork.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/NoopP2PNetwork.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/P2PNetwork.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/peers/DefaultPeer.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/peers/EnodeURLImpl.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/peers/MaintainedPeers.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramer.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetworkTest.java
- util/src/main/java/org/hyperledger/besu/util/Subscribers.java
> fixed method name and some 'finals'

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/headervalidationrules/MergeUnfinalizedValidationRule.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Block.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockHeader.java
add block details to MergeUnfinalizedValidationRule header validation rule
#3375
> Add block details to finalization validation warning

- besu/src/main/java/org/hyperledger/besu/controller/MergeBesuControllerBuilder.java
- besu/src/test/java/org/hyperledger/besu/controller/MergeBesuControllerBuilderTest.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeMiningCoordinator.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExecutePayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkChoiceUpdated.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/ExecutionEngineJsonRpcMethods.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/Blockchain.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/BlockchainStorage.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchain.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/MutableBlockchain.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueStoragePrefixedKeyBlockchainStorage.java
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestBlockchain.java
> Persist last finalized block hash

- consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/validation/MessageValidator.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/statemachine/RoundChangeManagerTest.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/validation/MessageValidatorTest.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeMiningCoordinator.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/TransitionCoordinator.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeReorgTest.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validation/ProposalPayloadValidator.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validation/RoundChangeMessageValidator.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validation/ProposalPayloadValidatorTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validation/ProposalValidatorTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validation/RoundChangeMessageValidatorTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExecutePayload.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExecutePayloadTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/BlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/MainnetBlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/goquorum/GoQuorumBlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockImporter.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/ForwardSyncStep.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardsSyncContextTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/ForwardSyncStepTest.java
> refactor MergeCoordinator executeBlock to return validation reason

- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
> Merge: add terminal block number and hash to genesis config options

- .circleci/config.yml
- build.gradle
- gradle.properties
> Publish kintsugi final image

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/VertxPeerDiscoveryAgent.java
https://github.com/hyperledger/besu/issues/3335
> fix NPE, issue 3335

- CHANGELOG.md
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/MigratingMiningCoordinator.java
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/blockcreation/BftMiningCoordinator.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/blockcreation/PkiQbftBlockCreator.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractMiningCoordinator.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockCreator.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockMiner.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/MiningCoordinator.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/NoopMiningCoordinator.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/PoWMinerExecutor.java
Code originally written by garyschulte on the merge branch.
> Merge: extend block creation and mining to support The Merge

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncException.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncStep.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardsSyncContext.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/ForwardSyncStep.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChainTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncStepTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncTaskTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardsSyncContextTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/ChainForTestCreator.java
Code originally written by gezero on the merge branch
> Merge: port of backward sync

- CONTRIBUTING.md
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncChainDownloaderTest.java
Fixed a typo
And a discord link
> one more discord link and a typo

- .circleci/config.yml
- datatypes/src/main/java/org/hyperledger/besu/datatypes/Address.java
This will make it easier for PR authors (especially community members) to see what's failed.
See #3456
> Separate CI steps for DCO and spotless checks

- CHANGELOG.md
- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/support/IntegrationTestHelpers.java
- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/support/TestContextBuilder.java
- consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/QbftGossip.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftBlockHeightManagerTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftControllerTest.java
This is the changlelog update that publicises that QBFT consensus algorithm is now production ready.
Also fixing some typos (fixes #3452)
> QBFT out of early access

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/controller/IbftBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/QbftBesuControllerBuilder.java
- consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BftExecutors.java
- consensus/ibft/src/integration-test/java/org/hyperledger/besu/consensus/ibft/support/TestContextBuilder.java
- consensus/qbft/src/integration-test/java/org/hyperledger/besu/consensus/qbft/support/TestContextBuilder.java
BFT executor threads include IBFT or QBFT to help with the IBFT -> QBFT migration.
> Add some thread names for debugging clarity

- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/operations/PrevRanDaoOperationTest.java
- evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/PrevRanDaoOperation.java
> Renamed OP code RANDOM to PREVRANDAO

- acceptance-tests/tests/src/test/resources/log4j2.xml
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivacyGroupUtil.java
> [MINOR] remove orion refs

- CHANGELOG.md
- gradle.properties
> Release 22.1.1

- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetContractCreationProcessorTest.java
- evm/src/main/java/org/hyperledger/besu/evm/contractvalidation/ContractValidationRule.java
- evm/src/main/java/org/hyperledger/besu/evm/contractvalidation/MaxCodeSizeRule.java
- evm/src/main/java/org/hyperledger/besu/evm/contractvalidation/PrefixCodeRule.java
- evm/src/main/java/org/hyperledger/besu/evm/frame/ExceptionalHaltReason.java
- evm/src/main/java/org/hyperledger/besu/evm/processor/ContractCreationProcessor.java
For each contract validation error return a relevant error instead of
the incorrect "INSUFFICIENT_GAS" error.
> Improve contract validation errors

- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/NativeLibraryOptions.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ExecutionEngineJsonRpcMethod.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardsSyncContext.java
Fixed 4 code smells introduced recently to make sonar happy.
Also minor change to shorten help message for --X-alg-native-enabled CLI options
> [MINOR] addressed some sonar code smells

- gradle/versions.gradle
Updated some but not all dependencies.
> updated several dependencies

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastImportBlocksStep.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/worldstate/CompleteTaskStep.java
> Log initial sync stats every 10 secs at max to avoid spamming logs 

- gradle/versions.gradle
* log4j
* jackson databind
* guava
* dagger
> Updated dependencies including log4j

- gradle/versions.gradle
> upgrade vertx

- CHANGELOG.md
> add trace_callMany to CHANGELOG

- ethereum/stratum/build.gradle
- ethereum/stratum/src/main/java/org/hyperledger/besu/ethereum/stratum/Stratum1EthProxyProtocol.java
- ethereum/stratum/src/main/java/org/hyperledger/besu/ethereum/stratum/Stratum1Protocol.java
Adds conditionals around assumptions on type of MiningCoordinator
fixes #3541
> check types before providing a PowMiningCoordinator

- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/test/java/org/hyperledger/besu/RunnerBuilderTest.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/TransitionCoordinator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PoWSolver.java
- ethereum/stratum/src/main/java/org/hyperledger/besu/ethereum/stratum/GetWorkProtocol.java
- ethereum/stratum/src/main/java/org/hyperledger/besu/ethereum/stratum/StratumServer.java
This PR addresses a couple bits of additional plumbing to ensure transitionCoordinator correctly routes stratum ethash observers
#3541
> Stratum mining errata

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfiguration.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfigurationTest.java
Super simple PR to remove zero blocknumber requirement CL TransitionConfiguration
#3560
> remove requirement for CL to have zero blocknumber

- .github/issue_template.md
Added some suggestions for extra info that may be relevant especially for smart contract related issues.
> added extra info to issue template

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/CheckpointRangeHeaders.java
Added some debug logging to clarify the state when the IllegalArgumentException is thrown while downloading headers.
Related to #3336
> Added debug logging.

- config/src/main/resources/kiln.json
The TTD for Kiln has been updated. This PR adds the new one to the Kiln genesis file
> Update TTD for Kiln

- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketRequestHandlerTest.java
> WebSocket batch test - remove Ignore

- gradle.properties
Signed-off-by: Frank Li <b439988l@gmail.com>
Change snapshot version to 21.1.3
> change snapshot version

- CHANGELOG.md
Added 22.1.3 section to changelog
> added download links for 22.1.2 and moved bonsai change to 22.1.3

- CHANGELOG.md
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/BesuNode.java
constants for strings and check some optionals.
Also changed the engineHttpUrl() method to use the engine host
> address some sonar cloud bugs

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/TraceTypeParameter.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/TraceTypeParameterTest.java
so that logging can work properly
See https://github.com/hyperledger/besu/issues/3528
> [MINOR] added toString for TraceTypeParameter

- .github/pull_request_template.md
Signed-off-by: bgravenorst <byron.gravenorst@consensys.net>
Updated the GitHub PR template to include a documentation checklist item.
Fixes #3628
> Update the PR template to include a documentation checklist item.

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/authentication/EngineAuthService.java
> handle jwt keys with either 0x or not

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/PeerReputationManager.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/permissions/PeerPermissionsDenylist.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgentTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryControllerTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/P2PNetworkTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/P2PPlainNetworkTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/PeerReputationManagerTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/permissions/PeerPermissionsDenylistTest.java
internal variables only. no external changes required.
> Rename blacklist -> denylist

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/WaitForPeersTask.java
> clarify logging of wait for peers

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractRetryingPeerTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncTargetManager.java
Clarify messages around "no useful peers found" 
> useful peers log message changes

- gradle.properties
> prepare for release 22.1.3

- CHANGELOG.md
- gradle.properties
> update after releasing 22.1.3

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
This PR continues to group the CLI options together.
- JSON-RPC HTTP
- JSON-RPC WebSockets
- Metrics
- Miner
- Privacy
- Permissions
- Tx pool
fixes #2757
> Add group heading to command options

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastImportBlocksStep.java
> Improve code readability

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncPhase.java
> added issue 3646 to changelog
