hyperledger/besu

- CHANGELOG.md
- gradle.properties
> snapshot version

- CHANGELOG.md
- gradle.properties
* Add download links
* update version number
* update changelog
* one critical change was missed (was not included in original pr)
* add note about Java 17 migration.
> Prep for 22.4.0-RC2

- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/SynchronizerOptions.java
- besu/src/test/java/org/hyperledger/besu/cli/options/SynchronizerOptionsTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/DefaultSynchronizer.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/SyncMode.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/SynchronizerConfiguration.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/DynamicPivotBlockManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapDownloaderFactory.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapSyncConfiguration.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldStateDownloadProcess.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldStateDownloader.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/DynamicPivotBlockManagerTest.java
We start adding the flags for the snapsync. Most are experimental flags because normally the user doesn't have to change the values. But it can be used to change the values if needed or to tune performance.
> Add flag for snapsync

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/exceptions/PeerChannelClosedException.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramer.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramerTest.java
Signed-off-by: Frank Li <b439988l@gmail.com>
Catch an NPE using optionals and complete the future nicely with an exception
Fixes #3637 
> Fix NPE in DeFramer

- ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/EthStatsService.java
- ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/util/NetstatsUrl.java
- ethereum/ethstats/src/test/java/org/hyperledger/besu/ethstats/util/NetstatsUrlTest.java
- Fix a problem in the retry mechanism meant that we could send a large number of requests at the same time.
- Setting the default port to 3000 if it is not put in the flag
fixes #3570
> fix ethstats issue

- gradle.properties
> Release 22.4.0-RC2

- gradle.properties
> update version to 22.4.0-RC3-SNAPSHOT

- CHANGELOG.md
- gradle.properties
> update version and changelog

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/perm/PermissioningJsonRpcRequestFactory.java
- consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueMiningCoordinatorTest.java
- consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/blockcreation/BftMiningCoordinatorTest.java
- consensus/common/src/test/java/org/hyperledger/besu/consensus/common/validator/blockbased/VoteTallyCacheTestBase.java
- ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/frontier/EthGetFilterChangesIntegrationTest.java
- ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/london/EthGetFilterChangesIntegrationTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/authentication/TomlUser.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermAddNodesToAllowlistTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermAddNodesToWhitelistTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermGetNodesAllowlistTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermGetNodesWhitelistTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermRemoveNodesFromAllowlistTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermRemoveNodesFromWhitelistTest.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/IncrementingNonceGeneratorTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/privacy/FlexiblePrivacyControllerTest.java
- ethereum/trie/src/test/java/org/hyperledger/besu/ethereum/trie/TrieIteratorTest.java
- changed some Longs to long where they were statically intialized
- changed random.nextLong() to random.nextInt(Integer.MAX_VALUE) to avoid the edge case of long minimum value which gives a negative value when passed into abs()
- replace deprecated Lists.emptyList() with Collections.emptyList()
> [MINOR] code cleanup - Lists.emptyList

- CHANGELOG.md
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldDownloadState.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldDownloadStateTest.java
- gradle.properties
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDbSegmentIdentifier.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java
- plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/unsegmented/RocksDBColumnarKeyValueStorageTest.java
- services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/SegmentedKeyValueStorage.java
- services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/SegmentedKeyValueStorageAdapter.java
> Release 22.4.0

- CHANGELOG.md
- gradle.properties
- Preparing for next release
- 22.4.0 changelog
> Preparing for next version and 22.4.0 Changelog

- acceptance-tests/tests/build.gradle
- besu/build.gradle
- ethereum/p2p/build.gradle
- gradle/check-licenses.gradle
- gradle/versions.gradle
add constraint to upgrade jnr-posix transitive dependency
> add constraint for jnr-posix dependency

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/worldstate/CodeNodeDataRequest.java
add  a check in CodeNodeDataRequest to ensure code is not only present, but matches the expected hash.  This is necessary for bonsai databases since the code is stored by account hash rather than code hash.
> Add code hash check to fast sync

- CHANGELOG.md
Copied from 22.4.0-RC1 for visibility
> added missing breaking change to 22.4.0

- .circleci/config.yml
fix branch filter for dockerManifest task in circleci to reference `main` rather than `master`
> Circle-ci branch filter for dockerManifest 

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
Add P2P Discovery Options to group related options
* Reworking of #3692 - thanks to @sandrawangyx 
> Group headings for P2P discovery

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PandaPrinter.java
> settle down panda

- docker/openjdk-11-debug/Dockerfile
> removes verbose memory tracking, and adds jdk to include jcmd and tools

- gradle.properties
> Release 22.4.1

- gradle.properties
Prepare for version 22.4.2-SNAPSHOT
> Prepare for version 22.4.2-SNAPSHOT

- CHANGELOG.md
Added breaking change info for added column families.
See #3638 and #3532
> [CHANGELOG] breaking change info on column families

- besu/src/main/java/org/hyperledger/besu/controller/BesuController.java
- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/CliqueBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/ConsensusScheduleBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/IbftBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/IbftLegacyBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/MainnetBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/MergeBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/QbftBesuControllerBuilder.java
- besu/src/test/java/org/hyperledger/besu/controller/BesuControllerBuilderTest.java
- besu/src/test/java/org/hyperledger/besu/controller/MergeBesuControllerBuilderTest.java
- besu/src/test/java/org/hyperledger/besu/controller/QbftBesuControllerBuilderTest.java
DRY up the usage of genesisConfigOverrides 
> Bugfix treatment of genesis overrides.  

- gradle.properties
> Release 22.4.2

- gradle.properties
Prepare for version 22.4.3-SNAPSHOT
> Prepare for version 22.4.3-SNAPSHOT

- CHANGELOG.md
> Update changelog for 22.4.3-SNAPSHOT

- ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/frontier/EthGetFilterChangesIntegrationTest.java
- ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/london/EthGetFilterChangesIntegrationTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/NewPooledTransactionHashesMessageProcessor.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactory.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/NewPooledTransactionHashesMessageProcessorTest.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolTest.java
> does not require being in sync to accept remote transactions

- config/src/main/resources/ropsten.json
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
> ropsten ttd selected by ef

- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactory.java
See ##3526
Signed-off-by: Sharad Gulati sharad.develop@gmail.com
Signed-off-by: Sharad Gulati <sharad.develop@gmail.com>
Better error reporting when unable to write to path. Added exception message details to error message, when read db fails
fixes #3526 
> Added exception message details to error message, when read db fails

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotSelectorFromFinalizedBlock.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/TransitionPivotSelector.java
> init optional and logging fixes

- CHANGELOG.md
- gradle.properties
> updates version to prep for q3

- besu/src/main/java/org/hyperledger/besu/cli/util/CommandLineUtils.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandLineUtilsTest.java
Add tests on options configured through ENV
Follow-up PR to address comments from https://github.com/hyperledger/besu/pull/3969
> Additional testings on ignored option warning 

- acceptance-tests/test-plugins/build.gradle
- acceptance-tests/tests/build.gradle
- besu/build.gradle
- build.gradle
- consensus/qbft/build.gradle
- crypto/build.gradle
- errorprone-checks/build.gradle
- ethereum/api/build.gradle
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/MultiTenancyRpcMethodDecoratorTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/MultiTenancyUserUtilTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivCreatePrivacyGroupTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivDeletePrivacyGroupTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivDistributeRawTransactionTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivFindPrivacyGroupTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetPrivateTransactionTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionCountTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivGetTransactionReceiptTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/privx/PrivxFindFlexiblePrivacyGroupTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivacyApiGroupJsonRpcMethodsTest.java
- ethereum/evmtool/build.gradle
- ethereum/p2p/build.gradle
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/handshake/ecies/ECIESEncryptionEngine.java
- ethereum/rlp/build.gradle
- gradle/versions.gradle
- pki/build.gradle
- settings.gradle
- testutil/build.gradle
> Version Upgrades for 22.7.0-RC1

- CHANGELOG.md
- config/src/main/resources/sepolia.json
Adds the correct TTD and DNS config to the Sepolia config file
fixes #4021 
> Add Sepolia TTD and DNS

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/SyncTargetManager.java
> turns down logging output to debug

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java
add info logging on engine api endpoints to increase the visibility of the EL/CL interactions
> add additional engine info logging 

- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactory.java
Replaces https://github.com/hyperledger/besu/pull/3989
> Log message when path unavailable

- CHANGELOG.md
- gradle.properties
> 22.7.0-RC1 non-snapshot version

- CHANGELOG.md
- gradle.properties
> 22.7.0-RC2-snapshot

- CHANGELOG.md
Added download links for 22.7.0-RC1
> CHANGELOG added 22.7.0-RC1 download links

- CHANGELOG.md
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionProtocolSchedule.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/TransitionProtocolScheduleTest.java
> Fix transition protocol schedule

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcService.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/JsonRpcJWTTest.java
fixes the parsing of host headers. adds test coverage for this case on both http and websockets.
#4082 
> host header parse error

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java
There was an error during the merge from main, that readded some deleted code, fixing it
> Fix PR 4098

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdated.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java
revamps some of the engine logging for better visibility
> logging additions for better engine visibility

- gradle.properties
22.7.0-RC2 release
Release 22.7.0-RC2 of Hyperledger Besu
> 22.7.0 rc2 release

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/TrieLogLayer.java
Small change to allow using the TrieLogLayer class outside its package.
> Allow creating the Trie Log Layer objects outside of its package

- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramer.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/wire/messages/DisconnectMessage.java
Fixing https://github.com/hyperledger/besu/issues/4071
> fix 1 byte long disconnect reason

- config/src/main/resources/goerli.json
- config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
> add goerli ttd

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
Replaces recursive implementation of isDescendentOf with a loop.
fixes #4169 
> 4169 dont recurse

- CHANGELOG.md
- gradle.properties
> Release 22.7.0-RC3

- CHANGELOG.md
- gradle.properties
Prepare for version 22.7.0-SNAPSHOT
> Prepare for version 22.7.0-SNAPSHOT

- CHANGELOG.md
- gradle.properties
Set versions for next release - 22.7.1-SNAPSHOT
- [ X I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
> Update for next release

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputation.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputationTest.java
> [MINOR] typo

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/RequestManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractGetHeadersFromPeerTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/BlockPropagationManager.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/PipelineChainDownloader.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/DownloadHeaderSequenceTask.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/NewPooledTransactionHashesMessageProcessor.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionsMessageProcessor.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramer.java
added the peer that caused the breach in some places and added "BREACH_OF_PROTOCOL" to the debug logging
> Improve logging for BREACH_OF_PROTOCOL

- CHANGELOG.md
- gradle.properties
> upreved to new snapshot

- CHANGELOG.md
> [CHANGELOG] moved 4279 to 22.7.2

- util/src/main/java/org/hyperledger/besu/util/Subscribers.java
PR to change logging for more graceful usage on #4323. To access stack trace, use DEBUG for subscriber. 
Fixes #4323 
> Fixing sub logging and moving stack trace to debug.

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayload.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/BlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/MainnetBlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/BlockProcessor.java
so it can decide how to present it to the CL
fixes #4349
> adds means to report causing exception up to RPC layer 

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/MergeBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/controller/TransitionBesuControllerBuilder.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PandaPrinter.java
- consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/PandaPrinterTest.java
Will not show ready for merge on startup when local stored chain is past ttd.
Uses block observer to determine state change
> refactors to rely on blocks added, and behave like singleton

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapsyncMetricsManager.java
Signed-off-by: Matt Nelson <matt.nelson@consensys.net>
Changes previous fix (#4347) for #4346 
> Wording tweaks for edge cases in PR #4347

- gradle.properties
> release versioning

- CHANGELOG.md
- gradle.properties
> prep for 22.7.3

- acceptance-tests/tests/build.gradle
- build.gradle
Update the greclipse version in spotless as directed by build errors to reduce random formatting errors.
Also, update formatting to new version
> Update spotless config

- CHANGELOG.md
- gradle.properties
> Feature/prep 22.7.3

- evm/src/main/java/org/hyperledger/besu/evm/frame/Memory.java
Move from a perfect fit memory expansion model to an exponential expansion model.
> Revise Memory Expansion

- CHANGELOG.md
- gradle/versions.gradle
Bump besu-native to 0.6.1 in order to get bls12-381 lib for linux arm64
> Bump besu-native to 0.6.1

- CHANGELOG.md
> update CHANGELOG for 4349

- gradle.properties
> Release 22.7.3

- CHANGELOG.md
- gradle.properties
Prepare for version 22.7.4-SNAPSHOT
> Prepare for version 22.7.4-SNAPSHOT

- CHANGELOG.md
> post-22.7.3 changelog

- CHANGELOG.md
- gradle.properties
- Remove records that track transactions by sender when they are empty to same memory in the transaction pool [#4415](https://github.com/hyperledger/besu/pull/4415)
- Add Toml configuration file support for _--Xplugin-rocksdb-high-spec-enabled_ flag
> adding new release version

- CHANGELOG.md
- gradle.properties
> updated version and CHANGELOG for next dev cycle

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/cache/TransactionLogBloomCacher.java
> these don't need to be at info

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/config/NetworkName.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
> Add Mainnet to merged networks

- crypto/build.gradle
- datatypes/build.gradle
- ethereum/rlp/build.gradle
- evm/build.gradle
- plugin-api/build.gradle
- util/build.gradle
Signed-off-by: Mustafa Uzun <mustafa.uzun@limechain.tech>
Add java modules support:
./crypto - org.hyperledger.besu.internal.crypto
./ethereum/rlp - org.hyperledger.besu.internal.rlp 
./util - org.hyperledger.besu.internal.util
./datatypes - org.hyperledger.besu.datatypes
./evm - org.hyperledger.besu.evm
./plugin-api - org.hyperledger.besu.plugin.api
> Java modules support

- besu/src/main/java/org/hyperledger/besu/chainimport/JsonBlockImporter.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/RestrictedDefaultPrivacyController.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncState.java
* Fix some minor spacing issues.
* Fix a string concatenation & numeric addition order of operations issue.
The following example will result in a block number of 11 being printed, instead of 2.
```java
public class Main
{
public static void main(String[] args) {
long blockNumber = 1;
System.out.println("Invalid block number: " + blockNumber + 1);
}
}
```
```
Invalid block number: 11
```
> Fix a few output string issues

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/MainnetBlockValidator.java
Signed-off-by: Matt Nelson <matt.nelson@consensys.net>
Changes logging level to info around bad block production in MainnetBlockValidator. If we think this should be just info for one of the logs, feel free to change. 
Fixes #4450 
> Fixing logging per issue 4450.

- CHANGELOG.md
- gradle.properties
> uprev version to 22.10.RC1

- gradle.properties
> Release 22.10.0-RC1

- gradle.properties
Prepare for version 22.10.0-RC2-SNAPSHOT
> Prepare for version 22.10.0-RC2-SNAPSHOT

- CHANGELOG.md
> update changelog for 22.10.0-RC2

- gradle.properties
update cherry-pick version to 22.7.6
> Update cherry-pick version for 22.7.6

- CHANGELOG.md
> update changelog for 22.7.6

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/resources/everything_config.toml
Deprecated since 22.1.3 https://github.com/hyperledger/besu/blob/main/CHANGELOG.md#2213
> hide deprecated option tx-pool-max-hashes

- CHANGELOG.md
- consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/jsonrpc/methods/CliqueGetSignerMetricsTest.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/jsonrpc/methods/IbftDiscardValidatorVoteTest.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/jsonrpc/methods/IbftGetSignerMetricsTest.java
- consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/jsonrpc/methods/IbftProposeValidatorVoteTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftDiscardValidatorVoteTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftGetSignerMetricsTest.java
- consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftProposeValidatorVoteTest.java
- ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/frontier/EthGetBlockByNumberIntegrationTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonRpcParameter.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockByHashTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockByNumberTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetMinerDataByBlockHashTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetMinerDataByBlockNumberTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetUncleByBlockHashAndIndexTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivCreatePrivacyGroupTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/request/SubscriptionRequestMapperTest.java
Signed-off-by: mark-terry <mark.terry@consensys.net>
Increase level of detail in RPC parameter error logging to improve usability.
Fixes #4326 
> RPC parameter error improvements. Test updates.

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java
This improves the "number of peers" metric.
> improve number of peers metric

- MAINTAINERS.md
Proposing @ahamlat  as a new Besu maintainer - has done significant performance analysis, configuration, and [commits](https://github.com/hyperledger/besu/pulls?q=is%3Apr+author%3Aahamlat+is%3Aclosed+review%3Aapproved) improving the quality, stability, and performance of Besu.
Voting ends 2 weeks from the publication of this PR or once more than 50% of the current maintainers approve.
For more information on this process see the Becoming a Maintainer section in the MAINTAINERS.md file.
NOTE: I suggest viewing the diff with "ignore whitespace changes" to more clearly see the addition.  Intellij auto-resized the whole table.
> Add Ameziane as maintainer

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcApis.java
Add the invalid api declared rpc-http-apis / rpc-ws-apis to the error message returned to the user.
Fixes #3418
> Add more details to  rpc http/ws apis error message

- CHANGELOG.md
- gradle.properties
> release 22.10.0-RC2

- CHANGELOG.md
- gradle.properties
> prepare for 22.10.0

- CHANGELOG.md
Signed-off-by: mark-terry <mark.terry@consensys.net>
Restores changelog entries that were removed.
> Restore changelog subtraction.

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLDataFetchers.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/BlockAdapterBase.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/LogAdapter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/PendingStateAdapter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/TransactionAdapter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugAccountRange.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugStorageRangeAt.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetProof.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceCallMany.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetProofTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/AbstractTrieLogManager.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/LayeredTrieLogManager.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/SnapshotTrieLogManager.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/TrieLogManager.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/GoQuorumKeyValueStorageProvider.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueStorageProvider.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/InMemoryKeyValueStorageProvider.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiSnapshotWorldStateArchiveTest.java
review feedback from #4531 which failed to get pushed prior to the auto-merge
> latent review feedback from pr 4531

- CHANGELOG.md
- gradle.properties
> Release 22.10.0

- CHANGELOG.md
- gradle.properties
> Preparing for next release

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/AbstractTrieLogManager.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/SnapshotTrieLogManager.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiSnapshotIsolationTests.java
squash commit of #4666  for 22.10.1-alpha
> Release 22.10.1 alpha, bonsai snapshot fix

- gradle.properties
add SNAPSHOT to version to avoid overwriting latest tags
> 22.10.1-alpha release - add SNAPSHOT to version

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/MainnetBlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiLayeredWorldState.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchive.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/MutableWorldState.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/MainnetBlockValidatorTest.java
merge bugfix commit from #4468
> bugfix for 22.10.1 alpha

- CHANGELOG.md
> Update artifact checksums after rebuilding the release

- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/MainnetBlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiLayeredWorldState.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchive.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/MutableWorldState.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/MainnetBlockValidatorTest.java
Fix for MainnetBlockValidator mutating the bonsai persisted worldstate on validation.
> Bonsai Fix for MainnetBlockValidator

- gradle/verification-metadata.xml
Ignore javadocs and sources verification to avoid IDE errors
> Skip javadocs and sources checksum

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
Signed-off-by: Bakuchi <49754494+massun-onibakuchi@users.noreply.github.com>
maybe I found a typo in error message
fix a minor typo in `NONCE_TOO_FAR_IN_FUTURE_FOR_SENDER `
> fix typo in error message.

- evm/src/main/java/org/hyperledger/besu/evm/EVM.java
- evm/src/main/java/org/hyperledger/besu/evm/frame/MessageFrame.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/MulOperation.java
Move mul from UInt256 wrapping to direct BigInteger math.
> Mul speedup

- gradle.properties
> Release 22.10.1

- CHANGELOG.md
- gradle.properties
Prepare for version 22.10.2-SNAPSHOT
> Prepare for version 22.10.2-SNAPSHOT

- CHANGELOG.md
add changelog description for 22.10.2 hotfix
> prep changelog for 22.10.2

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/CachedMerkleTrieLoader.java
ensure storage caching subscribes before accessing worldstate at all
#4765 
> subscribe prior to getting stateTrieNode in cacheStorageNodes

- gradle.properties
> Release 22.10.2

- CHANGELOG.md
- gradle.properties
Prepare for version 22.10.3-SNAPSHOT
> Prepare for version 22.10.3-SNAPSHOT

- CHANGELOG.md
- gradle.properties
> Release 22.10.3

- CHANGELOG.md
- gradle.properties
Update version for 22.10.4-SNAPSHOT
> Prepare for version 22.10.4-SNAPSHOT

- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCallTest.java
Signed-off-by: Gabriel Trintinalia <gabriel.trintinalia@gmail.com>
Fix typos
> Fix typo on EthCallTest methods

- ethereum/verkletrie/src/main/java/org/hyperledger/besu/ethereum/verkletrie/bandersnatch/fp/Element.java
Signed-off-by: kevaundray <kevtheappdev@gmail.com>
> Fix typo in verkle trie comment

- .github/workflows/release.yml
Fix docker release workflow login so it works with any symbols.
> Fix docker release workflow login

- CHANGELOG.md
Add changelog download sha for 22.10.3 release
> Add changelog download sha for 22.10.3 release

- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/chain/ChainDataPrunerTest.java
Signed-off-by: Zhenyang Shi <wcgcyx@gmail.com>
Switch to blocking executor in chain pruner test so pruning happened in the same thread.
fixes #4830 
> Use blocking executor in test

- evm/src/test/java/org/hyperledger/besu/evm/operations/BaseFeeOperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/BlockHashOperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/ChainIdOperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/ConstantinopleSStoreOperationGasCostTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/Create2OperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/CreateOperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/ExtCodeHashOperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/JumpOperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/LondonSStoreOperationGasCostTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/PrevRanDaoOperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/Push0OperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/RelativeJumpOperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/RevertOperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/SStoreOperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/SarOperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/ShlOperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/ShrOperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/testutils/FakeBlockValues.java
- evm/src/test/java/org/hyperledger/besu/evm/testutils/TestCodeExecutor.java
- evm/src/test/java/org/hyperledger/besu/evm/testutils/TestMessageFrameBuilder.java
- evm/src/test/java/org/hyperledger/besu/evm/toy/ToyAccount.java
- evm/src/test/java/org/hyperledger/besu/evm/toy/ToyWorld.java
Move the EVM individual operation tests into the EVM module.
> Move EVM operation Tests

- CHANGELOG.md
- gradle.properties
merge changelog, update gradle properties 
> prep for 23.1.0-beta

- gradle.properties
> Release 23.1.0-BETA

- gradle.properties
Prepare for version 23.1.0-RC1-SNAPSHOT
> Prepare for version 23.1.0-RC1-SNAPSHOT

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/ShanghaiGasCalculator.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/CreateOperationTest.java
Enable EOF into shanghai by wiring it into protocol specs.
> Enable EOF in Shanghai

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetContractCreationProcessorTest.java
- evm/src/main/java/org/hyperledger/besu/evm/EVM.java
- evm/src/main/java/org/hyperledger/besu/evm/EvmSpecVersion.java
- evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java
Move the EOF changes from Shanghai into the Cancun fork.
> Move EOF to Cancun

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Withdrawal.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/WithdrawalDecoder.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/WithdrawalEncoder.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/encoding/WithdrawalDecoderTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/encoding/WithdrawalEncoderTest.java
Add withdrawals type with rlp encoding and decoding
> Withdrawals type

- besu/src/main/java/org/hyperledger/besu/controller/BesuController.java
- besu/src/main/java/org/hyperledger/besu/controller/IbftLegacyBesuControllerBuilder.java
Add IBFT1 deprecation warning.
fix #4851
related to #4839
> Ibft1 deprecation warning

- gradle.properties
> Release 23.1.0-RC1

- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/TransactionPoolOptions.java
> [MINOR] fixed test for absent deprecated tx-pool-future-max-by-account

- datatypes/src/main/java/org/hyperledger/besu/datatypes/GWei.java
- datatypes/src/test/java/org/hyperledger/besu/datatypes/GWeiTest.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalParameter.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdatedTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/EnginePayloadAttributesParameterTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalParameterTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalParameterTestFixture.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreatorTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Withdrawal.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/WithdrawalDecoder.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/WithdrawalEncoder.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/WithdrawalsProcessor.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/encoding/WithdrawalDecoderTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/encoding/WithdrawalEncoderTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessorTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/WithdrawalsProcessorTest.java
- ethereum/rlp/src/main/java/org/hyperledger/besu/ethereum/rlp/AbstractRLPInput.java
- ethereum/rlp/src/main/java/org/hyperledger/besu/ethereum/rlp/RLPInput.java
- ethereum/rlp/src/main/java/org/hyperledger/besu/ethereum/rlp/RLPOutput.java
Withdrawls - Change Amount type to GWei instead of Wei
#4920 
https://github.com/ethereum/execution-apis/pull/354
> Withdrawls - Change Amount type to GWei instead of Wei

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV1.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV2.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/WithdrawalsValidator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/WithdrawalsValidatorProvider.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/EnginePayloadParameter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/ExecutionEngineJsonRpcMethods.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalParameterTestFixture.java
Spec: https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md
Part of https://github.com/hyperledger/besu/issues/4776
> Implement engine_newPayload Withdrawals validation

- build.gradle
- ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/BlockDataGenerator.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/TransactionBuilderTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidatorTest.java
- gradle.properties
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionType.java
Adds the new enumeration for the 4844 blob data transaction type, and fixes many tests which surprisingly broke due to that.
> 4844 new tx type

- evm/src/main/java/org/hyperledger/besu/evm/frame/MessageFrame.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/DataHashOperation.java
fix existing javadoc regressions in main ahead of enabling javadoc_17 action required
> fix javadoc regressions in main

- besu/src/test/java/org/hyperledger/besu/PrivacyReorgTest.java
- besu/src/test/java/org/hyperledger/besu/PrivacyTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpServiceCorsTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceCorsTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceRpcApisTest.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContractTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/peers/StaticNodesParserTest.java
> [MINOR] update some tests from junit 4 to 5

- CHANGELOG.md
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/BlockchainReferenceTestCaseSpec.java
- ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/core/TransactionTest.java
- ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
- ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/GeneralStateReferenceTestTools.java
- testutil/src/main/java/org/hyperledger/besu/testutil/JsonTestParameters.java
* Do not check state on failed TXes
* Exclude EIPTests from test set
> Update Reference Tests to 11.3

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeCapabilities.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeCapabilitiesTest.java
See https://github.com/ethereum/execution-apis/issues/373
> Params should be single item of array type, not outer array of strings

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/BlobsBundleV1.java
> Fix getBloblsBundleV1 response

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
> Correctly set the fee market Cancun

- .github/pull_request_template.md
Update Github pull request template to add option to advise to run non-mainnet test if required.
Related to #4921 
> Update GitHub pull request template (non-mainnet AT)

- CHANGELOG.md
- gradle.properties
> Release 23.1.0-RC2

- gradle.properties
Prepare for version 23.1.1-SNAPSHOT
> Prepare for version 23.1.1-SNAPSHOT

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/DefaultCommandValues.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcConfiguration.java
* default global max rpc batch size to 1000 for now
cherry pick of #5104
> cherry pick global max rpc batch size 

- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommand.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/StateTestSubCommand.java
- ethereum/evmtool/src/test/java/org/hyperledger/besu/evmtool/EvmToolSpecTests.java
- ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/badcode.json
- ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/revert.json
- evm/src/main/java/org/hyperledger/besu/evm/tracing/StandardJsonTracer.java
Fix a formatting error in standard trace that produced non-parsable JSON. Add unit tests to cover those cases.
Fixes #5117 
> Fix error output in standard trace

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncTargetManager.java
Improve Full Sync `"No sync target"` log message and make it consistent with the other syncs
> Match FullSync no target message with SnapSync no target message

- CHANGELOG.md
Update changelog in main to reflect releases for 23.1.0 and 23.1.1-RC1
> update changelog in main to reflect current releases

- CHANGELOG.md
- gradle.properties
Candidate 1 for 23.1.1 burn-in.  This candidate is without the bonsai refactor from #5123 
> Burn-in candidate #1 of 23.1.1 

- gradle.properties
> Release 23.1.1

- gradle.properties
Prepare for version 23.1.2-SNAPSHOT
> Prepare for version 23.1.2-SNAPSHOT

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/AbstractJsonRpcTest.java
Assert on objects but use prettyString for failure message
> Fix flaky engine api acceptance test

- CHANGELOG.md
update changelog with download links and new block for 23.1.2-SNAPSHOT
> Post 23.1.1 update changelog

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/CreateAccountAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/GossipTransactionAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/MetricsAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/OpenTelemetryAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/RpcApisTogglesAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/RunHelpTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/BadCLIOptionsPluginTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/BesuEventsPluginTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/PermissioningPluginTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/PicoCLIOptionsPluginTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/RpcEndpointServicePluginTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/contracts/PrivacyGroupTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/contracts/PrivacyProxyTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/pubsub/NewPendingTransactionAcceptanceTest.java
> [MINOR] use junit 5 for plugin and some other ATs

- besu/src/main/java/org/hyperledger/besu/Besu.java
Based on https://github.com/hyperledger/besu/pull/5202
Getting a fix onto main while we work on a valid acceptance test.
> Fix console logging

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/DeploySmartContractAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/DeployTransactionAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthGetWorkAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthSendRawTransactionTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EventEmitterAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/JsonRpcHttpAuthenticationAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/JsonRpcWebsocketAuthenticationAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/NetServicesAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/RevertReasonAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/Web3Sha3AcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/admin/AdminAddPeerAcceptanceTest.java
Updated to junit 5 for non-parameterized tests
> [MINOR] junit5 for RPC ATs

- ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
* Upgrade reference tests to v12.
* Extend the UncleFromSideChain exception to all future forks
> Reference Test v12

- .circleci/config.yml
- .github/workflows/checks.yml
- .github/workflows/codeql.yml
- .github/workflows/dco-merge-group.yml
- .github/workflows/dco.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/pr-checklist-on-open.yml
- .github/workflows/release.yml
- .github/workflows/repolinter.yml
same as #5232 but with additional self-hosted runner config
> Mainnet AT reduce parallelism and self-hosted runners

- CHANGELOG.md
- gradle.properties
> Release 23.1.2

- CHANGELOG.md
- gradle.properties
Prepare for version 23.1.3-SNAPSHOT
> Prepare for version 23.1.3-SNAPSHOT

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/services/BlockchainServiceImpl.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/AddedBlockContext.java
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/BlockContext.java
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/PropagatedBlockContext.java
- plugin-api/src/main/java/org/hyperledger/besu/plugin/services/BlockchainService.java
Introduces a new feature to the plugin API, enabling third-party plugins to access the blockchain service and retrieve information about a specific block based on its number.
> Plugin API -  Blockchain Service 

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/PluginJsonRpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/services/exception/PluginRpcEndpointException.java
> Add plugin RPC exception type

- besu/src/main/java/org/hyperledger/besu/services/BlockchainServiceImpl.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/services/BlockchainService.java
Add unstable annotation to the BlockchainService
> [MINOR] Add unstable annotation to the BlockchainService

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilder.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/authentication/EngineAuthService.java
Add a log to print the path where we loaded the engine jwt for better ux.
> [MINOR] Add log to show where we're reading the jwt from

- CHANGELOG.md
- gradle.properties
> 23.1.3 bump

- util/src/main/java/org/hyperledger/besu/util/platform/PlatformDetector.java
> Add javadoc

- gradle.properties
Update main version to 23.4.0-SNAPSHOT ready for the next release so we can use 23.1.3-SNAPSHOT on the [release-23.1.x](https://github.com/hyperledger/besu/tree/release-23.1.x) branch
> Update version to 23.4.0-SNAPSHOT

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java
Think this was renamed to engine_newPayloadV1 so not actually used by anything currently
Fixes https://github.com/hyperledger/besu/issues/5336
> [MINOR] Remove ENGINE_EXECUTE_PAYLOAD

- CHANGELOG.md
- gradle.properties
> Burn-in release 23.4.0-RC1

- CHANGELOG.md
- gradle.properties
Prepare for version 23.4.0-RC2-SNAPSHOT
> Prepare for version 23.4.0-RC2-SNAPSHOT

- gradle.properties
> uprevving to 23.4.0 for release

- CHANGELOG.md
- gradle.properties
SNAPSHOT version, CHANGELOG updates, download links and artifact hashes.
> Release 23.4.1-SNAPSHOT

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/handlers/JsonRpcExecutorHandler.java
allow custom module for json mapper
> allow custom module for json mapper

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotSelectorFromSafeBlock.java
Add a info log so users can better understand why besu isn't doing anything when it's actually waiting on CL to send a FCU. 
Fixes #5416
> Add info log to indicate Besu is waiting on CL to be synced

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotSelectorFromSafeBlock.java
Following the suggestion (https://github.com/hyperledger/besu/pull/5452#discussion_r1193426313) and changing to a more user-friendly message.
FIxes #5416
> Change to more user-friendly message

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineGetPayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadV1.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadV2.java
at INFO level, instead of only logging this
```
Fetch block proposal by identifier: 0x0068a2d68ca65973, hash: 0x450b0b3269e8a90df99e41bd2436ac69e45b66d24c7a79e5c96448892becb137, number: 9017061, coinbase: 0x3826539cbd8d68dcf119e80b994557b4278cec9f, transaction count: 72
```
this is logged, additions are: the start of the block creation, and when the proposal is fetched the gas used and the reward.
```
Start building proposals for block 9017061 identified by 0x0068a2d68ca65973
Fetch block proposal by identifier: 0x0068a2d68ca65973, hash: 0x450b0b3269e8a90df99e41bd2436ac69e45b66d24c7a79e5c96448892becb137, number: 9017061, coinbase: 0x3826539cbd8d68dcf119e80b994557b4278cec9f, transaction count: 72, gas used: 38.80%, reward: 19.00 finney
```
at DEBUG level every time a better block is found …
> Log more info about proposed blocks

- CHANGELOG.md
- gradle.properties
> Release 23.4.1

- .circleci/config.yml
- acceptance-tests/tests/build.gradle
Run all ATs on PRs, but split into 
* mainnet
* Clique + BFT
* Privacy + Permissioning
> run non-mainnet ATs on PRs, split into sub groups

- besu/src/main/resources/log4j2.xml
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/cache/CachedWorldStorageManager.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/storage/BonsaiSnapshotWorldStateKeyValueStorage.java
PR adds debug logging to worldstate access path, and a warning when we try to access closed worldstate.
Added in response to #5456, and seems suitable to add to main.
> Log worldstate availability

- CHANGELOG.md
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ExecutionEngineJsonRpcMethod.java
Moved newPayload logging to trace
> logging cleanup, giant new payload.

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineGetPayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeCapabilities.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfiguration.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadBodiesByHashV1.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadBodiesByRangeV1.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EnginePreparePayloadDebug.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/EnginePayloadParameter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonRpcParameter.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV3Test.java
> fix spotless

- errorprone-checks/build.gradle
- errorprone-checks/src/test/java/org/hyperledger/errorpronechecks/BannedMethodTest.java
- errorprone-checks/src/test/java/org/hyperledger/errorpronechecks/DoNotCreateSecureRandomDirectlyTest.java
- errorprone-checks/src/test/java/org/hyperledger/errorpronechecks/DoNotInvokeMessageDigestDirectlyTest.java
- errorprone-checks/src/test/java/org/hyperledger/errorpronechecks/DoNotReturnNullOptionalsTest.java
- errorprone-checks/src/test/java/org/hyperledger/errorpronechecks/ExperimentalCliOptionMustBeCorrectlyDisplayedTest.java
- errorprone-checks/src/test/java/org/hyperledger/errorpronechecks/MethodInputParametersMustBeFinalTest.java
- errorprone-checks/src/test/java/org/hyperledger/errorpronechecks/PrivateStaticFinalLoggersTest.java
> [MINOR] errorprone-checks - migrate to junit5

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/CancunTargetingGasLimitCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/CancunFeeMarket.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/CancunGasCalculator.java
Increase blob throughput according to spec
#5590
> [4844] Increase blob throughput

- enclave/build.gradle
- enclave/src/test/java/org/hyperledger/besu/enclave/EnclaveFactoryTest.java
EnclaveFactoryTest
Added dependency for junit.jupiter (junit5)
Removed dependency on junit 4
Migrated test from junit4 to junit5
https://github.com/hyperledger/besu/issues/5566
> EnclaveFactoryTest - migrate tests from Junit4 to Junit5

- metrics/core/build.gradle
- metrics/core/src/test/java/org/hyperledger/besu/metrics/RunnableTimedCounterTest.java
- metrics/core/src/test/java/org/hyperledger/besu/metrics/noop/NoOpMetricsSystemTest.java
- metrics/core/src/test/java/org/hyperledger/besu/metrics/opentelemetry/OpenTelemetryMetricsSystemTest.java
- metrics/core/src/test/java/org/hyperledger/besu/metrics/prometheus/MetricsHttpServiceTest.java
- metrics/core/src/test/java/org/hyperledger/besu/metrics/prometheus/PrometheusMetricsSystemTest.java
metrics Tests
Added dependency for junit.jupiter (junit5) and Removed dependency on junit 4
Migrated test from junit4 to junit5
https://github.com/hyperledger/besu/issues/5562
> metrics - migrate tests from Junit4 to Junit5

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/CancunTargetingGasLimitCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/CancunFeeMarket.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/CancunGasCalculator.java
Increase blob sidecar size
fixes #5590
> [4844] Increase blob sidecar size

- gradle.properties
> Release 23.4.2

- gradle.properties
Prepare for version 23.4.3-SNAPSHOT
> Prepare for version 23.4.3-SNAPSHOT

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/BlobsBundleV1.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadV3Test.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/blobs/BlobsWithCommitments.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/TransactionBuilderTest.java
Ensure blobs proofs commitments have the same size
fixes #5488
> Ensure that blobs, proofs and  commitments have the same number of elements

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/storage/BonsaiWorldStateKeyValueStorage.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateKeyValueStorageTest.java
During the snapsync we can have a nullpointer because of a clear we are doing when we are starting from scratch
> Reload flat db strategy on clear

- gradle.properties
> Release 23.4.3

- gradle.properties
Prepare for version 23.4.4-SNAPSHOT
> Prepare for version 23.4.4-SNAPSHOT

- gradle.properties
> Release 23.4.4

- gradle.properties
prepare for version 23.4.5-SNAPSHOT
> Prepare for version 23.4.5-SNAPSHOT

- acceptance-tests/tests/src/test/resources/jsonrpc/engine/eip6110/test-cases/06_eip6110_get_payload.json
Update the acceptance test with the right hash value since the header now also has dataGasUsed
> [4844] Acceptance Test - Update block hash with correct value 

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV3.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/EnginePayloadParameter.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java
- Swap parameters order and 
- remove unused method
- move the method to a more relevant class
> [4844] Swap parameters order and remove unused method

- CHANGELOG.md
- gradle.properties
> Release 23.7.0

- CHANGELOG.md
- gradle.properties
Prepare for version 23.7.1-SNAPSHOT
> Prepare for version 23.7.1-SNAPSHOT

- CHANGELOG.md
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/TransactionEncoder.java
- ethereum/p2p/build.gradle
- gradle.properties
RC burn-in release of 23.7.1:
* cherry pick of #5734 performance regression fix
* changelog revision to reflect 23.7.0 not released
* change rev to 23.7.1-RC
>  23.7.1-RC burn in

- gradle.properties
bump version after 23.7.1-RC2 burn-in
> Release 23.7.1

- CHANGELOG.md
- gradle.properties
title says it all, update version for 23.7.2-SNAPSHOT
> update changelog and version for 23.7.2-SNAPSHOT

- build.gradle
Another small PR to allow running checkSpdxHeader task on Windows
> Make checkSpdxHeader task cross platform

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV2.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV2Test.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV3Test.java
Validate blobGasUsed and excessblobGas pre-Cancun.
> EngineNewPayloadV2  -  Reject non-null Blob fields 

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
Adding missing information to the toString() method of Transaction
> add versioned hashes and number of blobs to toString()

- CHANGELOG.md
- gradle.properties
Post burn-in release of 23.7.2
> Release 23.7.2

- gradle.properties
> Bump version to 23.7.3-SNAPSHOT

- README.md
Fixes #5858
Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>
> docs(readme): fix broken link to installation of binaries page

- .github/workflows/checks.yml
- .github/workflows/codeql.yml
- .github/workflows/dco-merge-group.yml
- .github/workflows/dco.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/pr-checklist-on-open.yml
- .github/workflows/release.yml
- .github/workflows/repolinter.yml
Use the -8 and -16 large runners from HL org for the current github actions
> Move to Hyperledger large runners for current github actions

- CHANGELOG.md
- gradle.properties
> Bump version to 23.10.1-SNAPSHOT

- CHANGELOG.md
- gradle.properties
> Set version to 23.10.0-RC

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV2.java
more hive tests for engine api
> hive tests explicitly attempt zero

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
Noticed that these lines of code were duplicated.
> remove code duplication

- KNOWN_ISSUES.md
> docs: fix typo

- CHANGELOG.md
> [CHANGELOG] fix links to issue 5772

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceCallMany.java
fix incorrect argument passing code in blockParameter function of TraceCallMany class. only need to change one line of code
fixed #6033
> fix incorrect argument passing in blockParameter of TraceCallMany class

- README.md
- Adds X (Twitter) hyperlink to README for increased visibility and community engagement for the Hyperledger Besu account.
- Fixes roadmap hyperlink as previous one is broken.
> Add X (Twitter) to README, Fix Roadmap Hyperlink

- gradle.properties
Bump 23.10.1-RC to 23.10.1 on release branch
> Bump 23.10.1-RC to 23.10.1

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
Allow plugins ATs to utilize RpcEndpointService
> [MINOR] add RpcEndpointService to thread runner

- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestEnv.java
t8n changed how they name this field 
fixes #6092
> renamed env field

- CHANGELOG.md
- ethereum/referencetests/build.gradle
v13 of the official Ethereum Reference Tests.
> Reference Tests v13

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
This reverts part of the logging changes in #6127 
On a public network transactions are dropped for a variety of reasons and very frequently, and this blows the logs up.  E.g.:
```
{"@timestamp":"2023-11-07T00:05:18,003","level":"WARN","thread":"nioEventLoopGroup-3-9","class":"TransactionPool","message":"Discard invalid transaction 0x3124130967cb066ab9a6c5807a96f3147d354ae09f1bb8cda6b95c39033756f1={MessageCall, 51156, 0xa76a91f8b0d7ef28d2b76a703bc0770ba8996bfc, EIP1559, mf: 12 wei, pf: 2 wei, gl: 800000, v: 0 wei, to: 0x9d51bca23612851f98ced6d4f7aac75356d45f58}, reason GAS_PRICE_TOO_LOW","throwable":""}
{"@timestamp":"2023-11-07T00:05:18,004","level":"WARN","thread":"nioEventLoopGroup-3-9","class":"TransactionPool","message":"Discard invalid transaction …
```
> Revert "Discard invalid transaction" warning logs

- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/GasPricePendingTransactionsTest.java
Create instance of the correct class in gas price TX test
No issue raised for this
> Gas price pending TX test using wrong class

- CHANGELOG.md
- build.gradle
- gradle.properties
- settings.gradle
> update version for snapshot

- gradle.properties
> uprev to 23.10.2

- CHANGELOG.md
> Changelog23.10.2

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthFeeHistory.java
This PR does not change anything, just breaks the code into smaller pieces
> Refactor: improve readability of EthFeeHistory

- .github/workflows/checks.yml
- .github/workflows/codeql.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/release.yml
- .github/workflows/repolinter.yml
- .github/workflows/sonarcloud.yml
https://github.com/actions/checkout/releases/tag/v4.0.0
> [MINOR] update GHA checkout action to v4

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputation.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputationTest.java
This PR reverts #6187. The PR causes syncing problems by not removing useless peers.
> Revert PR https://github.com/hyperledger/besu/pull/6187

- .circleci/config.yml
This PR makes the ATs to run sequentially so we reduce the parallelism and get the build working again. This might result in a longer time for ATs to complete but right now Unit tests still take longer.
> Run ATs sequentially

- acceptance-tests/test-plugins/build.gradle
- acceptance-tests/test-plugins/src/test/java/org/hyperledger/besu/services/BesuPluginContextImplTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/AbstractJsonRpcTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/DebugReplayBlockAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/DebugSetHeadAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthEstimateGasAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthGetBlockByNumberAndHashShanghaiAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/ExecutionEngineCancunBlockBuildingAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/ExecutionEngineEip6110AcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/ExecutionEngineParisAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/ExecutionEngineShanghaiAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/ipc/Web3JSupportAcceptanceTest.java
> plugin and jsonrpc ATs to junit 5

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/AbstractPreexistingNodeTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/LoggingTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/backup/BackupRoundTripAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/bootstrap/ClusterAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/bootstrap/ClusterNoDiscoveryAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/bootstrap/ClusterThreadNodeRunnerAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/bootstrap/P2pDisabledAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/bootstrap/StaticNodesAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/config/BootNodesGenesisSetupTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/crypto/SECP256R1AcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/database/DatabaseMigrationAcceptanceTest.java
this is #6249 without clique/bft ATs
fixes #6265
> Non bft group ats junit 5

- gradle.properties
set release version to 23.10.3
> release 23.10.3

- besu/src/main/java/org/hyperledger/besu/cli/subcommands/operator/GenerateBlockchainConfig.java
- besu/src/test/java/org/hyperledger/besu/cli/subcommands/operator/OperatorSubCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/subcommands/rlp/RLPSubCommandTest.java
> [MINOR] made directory structure of subcommands tests match source

- evm/src/main/java/org/hyperledger/besu/evm/EvmSpecVersion.java
- evm/src/test/java/org/hyperledger/besu/evm/fluent/EVMExecutorTest.java
> finalized cancun spec

- evm/src/main/java/org/hyperledger/besu/evm/EvmSpecVersion.java
- evm/src/test/java/org/hyperledger/besu/evm/fluent/EVMExecutorTest.java
- gradle.properties
small cherry-pick to mark Cancun as finalized
> Rel 24.1.0-RC2 cherry pick - cancun

- CHANGELOG.md
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/BonsaiWorldStateProvider.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/worldview/BonsaiWorldState.java
- gradle.properties
Hotfix release to address production issue with bonsai state rolling and repeated selfdestruct, see also #6359 
#6357
> Hotfix 23.10.3-hotfix Log/Address Trielog rolling failure

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/clique/CliqueDiscardRpcAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/clique/CliqueGetSignersRpcAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/clique/CliqueMiningAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/clique/CliqueProposalRpcAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/clique/CliqueProposeRpcAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/clique/CliqueZeroValidatorsAcceptanceTest.java
> migrate clique tests fully to junit5

- README.md
> [MINOR] readme - fixed link to logging docs

- CHANGELOG.md
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/BonsaiWorldStateProvider.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/worldview/BonsaiWorldState.java
- gradle.properties
* trigger a BWS if we do not have a valid worldstate available during fcU raise log rolling failure loglevel to error from debug
* fixing on selfdestruct
> merges in 23.10.3-hotfix

- SUPPORT.md
fix `Hyperlegder` to `Hyperledger`
> Fix typo in SUPPORT.md

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/util/ConfigOptionSearchAndRunHandler.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/resources/everything_config.toml
Remove  deprecated `--privacy-onchain-groups-enabled` option
fixes #6410
> Remove  deprecated `--privacy-onchain-groups-enabled` option

- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommand.java
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestProtocolSchedules.java
- evm/src/main/java/org/hyperledger/besu/evm/code/CodeV1Validation.java
- evm/src/main/java/org/hyperledger/besu/evm/code/EOFLayout.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCreateOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/RetFOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/processor/ContractCreationProcessor.java
- evm/src/main/java/org/hyperledger/besu/evm/tracing/StandardJsonTracer.java
- evm/src/test/java/org/hyperledger/besu/evm/code/EOFLayoutTest.java
Update a few EOF features based on updated spec
* Add a prague reference test target
* Run evmtool from prestate when no code specified
* RETF and dangling immediate arg fixes
> EOF Spec Updates

- gradle.properties
> prep for release 24.1.1

- CHANGELOG.md
- besu/src/main/resources/log4j2.xml
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncContext.java
- gradle.properties
release version of 24.1.1 including:
- 24.1.1-RC commits
- RC2 cherry picks of:
- #6455 
- #6458
- updated changelog
> Release 24.1.1

- CHANGELOG.md
fix changelog:
* 24.1.1 entries 
* 24.1.0 download links
> Fix 24.1.1 changelog

- CHANGELOG.md
updated download links/shas to match https://github.com/hyperledger/besu/releases/tag/24.1.1
including errata section
Also added links for non-maintainer contributors to the latest release
> [CHANGELOG] updated download links and added contributor thanks

- ethereum/eth/src/main/java/org/hyperledger/besu/consensus/merge/ForkchoiceEvent.java
Remove repeated field in toString()
> remove repeated part of toString()

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/options/stable/PermissionsOptions.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- besu/src/test/java/org/hyperledger/besu/cli/options/PermissionsOptionsTest.java
Move permission options to its own class
see #6428
> [Refactor ] Move permission options to its own class

- besu/src/main/java/org/hyperledger/besu/cli/config/ProfileName.java
- config/src/main/resources/profiles/staker.toml
Add staker profile
Use:
`besu --profile=staker`
More: [#6409](https://github.com/hyperledger/besu/issues/6409)
fixes [#6325](https://github.com/hyperledger/besu/issues/6325)
see: [#6323](https://github.com/hyperledger/besu/issues/6323)
> [minor] Add staker profile

- besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogHelper.java
- besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogSubCommand.java
Indicate pruning has begun before the subcommand starts processing
> [MINOR] Move log before where the subcommand hangs

- evm/src/main/java/org/hyperledger/besu/evm/ClassicEVMs.java
Add missed javadoc for `ClassicEVM` from #6524
> Add missing javadoc

- CHANGELOG.md
- gradle.properties
> uprev artifact name

- CHANGELOG.md
- evm/src/main/java/org/hyperledger/besu/evm/ClassicEVMs.java
- gradle.properties
> Uprev24.1.2

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
> use terminal width for usage message

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- datatypes/src/main/java/org/hyperledger/besu/datatypes/StorageSlotKey.java
- errorprone-checks/build.gradle
- errorprone-checks/src/main/java/org/hyperledger/errorpronechecks/PreferCommonAnnotations.java
- errorprone-checks/src/test/java/org/hyperledger/errorpronechecks/PreferCommonAnnotationsTest.java
- errorprone-checks/src/test/resources/org/hyperledger/errorpronechecks/PreferCommonAnnotationsNegativeCases.java
- errorprone-checks/src/test/resources/org/hyperledger/errorpronechecks/PreferCommonAnnotationsPositiveCases.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/EngineJsonRpcService.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSendRawTransaction.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceFilter.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/worldview/BonsaiWorldStateUpdateAccumulator.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/chain/ChainDataPrunerTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTask.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryControllerTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/NetworkingServiceLifecycleTest.java
- evm/src/main/java/org/hyperledger/besu/evm/precompile/KZGPointEvalPrecompiledContract.java
- evm/src/test/java/org/hyperledger/besu/evm/fluent/EVMExecutorTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/Create2OperationTest.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/CreateOperationTest.java
- metrics/core/src/main/java/org/hyperledger/besu/metrics/opentelemetry/DebugMetricReader.java
We have a mix of org.jetbrains.annotations.NotNull and javax.annotations.Nonnull. Change all to the latter. Add an errorprone check to enforce this.
> Remove uses of org.jetbrains annotations

- CHANGELOG.md
- gradle.properties
> bump to 24.2.0-SNAPSHOT

- evm/src/main/java/org/hyperledger/besu/evm/processor/ContractCreationProcessor.java
Remove duplicated call to the addCreate method. The method is already called here  https://github.com/hyperledger/besu/blob/5c295c5aa6c277287bf3c8d6679a9cca36427838/evm/src/main/java/org/hyperledger/besu/evm/processor/ContractCreationProcessor.java#L125
> Remove duplicated addCreate call

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
Just some more code that can be removed
> Cleanup after refactoring `TransactionSelectionService`

- CHANGELOG.md
- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/cli/options/unstable/SynchronizerOptions.java
- besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapSyncConfiguration.java
> revert 6499 flat-db-healing-enabled false by default

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeConfigurationBuilder.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/AbstractPreexistingNodeTest.java
This reverts commit 647750c201dcd06fac51028bfb93e6242c2e222b.
> Revert "Acceptance tests to use bonsai (#6619)"

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/DefaultProtocolSchedule.java
Signed-off-by: Simon Dudley <simon.dudley@consensys.net>
> [MINOR] Remove unused method

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
Add privacy and permissioning services to thread plugin context
fixes #6691
> [minor] Add privacy and permissioning services to thread plugin context

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthSendRawTransactionAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/pubsub/NewPendingTransactionAcceptanceTest.java
Hopefully this fixes #6719 and #6718
> add check for sync status to fix flaky tests

- CHANGELOG.md
- datatypes/src/main/java/org/hyperledger/besu/datatypes/Address.java
> chore: remove repetitive words

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
Very minor PR to add some javadoc comments to 2 methods
N/A
> Add comments to a couple of the the EthPeer methods to clarify their behaviour

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/request/StorageRangeDataRequest.java
Refactor StorageRangeDataRequest to fix unused variable. Reporting during update of errorprone plugin.
> Refactor StorageRangeDataRequest to fix nodes saved variable

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/PermissioningPluginTest.java
> Fix permissioning plugin test

- .github/workflows/artifacts.yml
- .github/workflows/pre-review.yml
- build.gradle
- resume publishing jars to artifactory on prerelease
- stop publishing distributions to artifactory
> Artifactory publish

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthSendRawTransactionAcceptanceTest.java
> disable not ignore

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningV2AcceptanceTest.java
The `permissioningUpdatesPropagateThroughNetwork` test fails occasionally, this may fix it
> Flaky test v2 perm

- .github/workflows/artifacts.yml
ci: Fix Publish GH workflow Artifactory secrets
> ci: Fix Publish GH workflow Artifactory secrets

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncAlgorithm.java
- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncContextTest.java
- gradle.properties
Simple series of Extract Method operations.
Tidy up couple of things from #6749
> Refactor BackwardsSyncAlgorithm.pickNextStep for readability

- .github/workflows/develop.yml
Hoping that removing this will default draft to false
https://github.com/softprops/action-gh-release/issues/379
> Update develop release action to try to fix draft instead of pre-release

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthSendRawTransactionAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/pubsub/NewPendingTransactionAcceptanceTest.java
Make the tests more robust, ensuring that the miner has started mining blocks and the the following nodes are correctly syncing from the miner, since otherwise what could happen is that the following nodes are still not aware that the miner is ahead of them, the tx is sent, then they start syncing with the miner but since they could be many block behind, then the txpool is disabled and the sent tx is lost before it could be broadcasted.
fixes #6816
> Fix two flacky acceptance tests

- .github/issue_template.md
Fixes previously 404 link in the issue template
> update broken link, issue template

- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncAlgSpec.java
> flaky test - BackwardSyncAlgSpec - increase timeout

- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/LegacyFeeMarketBlockTransactionSelectorTest.java
> disable flaky test - LegacyFeeMarketBlockTransactionSelectorTest

- build.gradle
> Fix besu-untuned start script

- besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/SnapServer.java
fixes bug where disabling snap server disables snap protocol
> Snap protocol always enabled

- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockCreationTiming.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockMiner.java
> Fix and reformat produced block timing log

- .github/workflows/artifacts.yml
The changes in https://github.com/hyperledger/besu/pull/6705 broke the release process
and https://github.com/hyperledger/besu/pull/6856 maybe never worked
> Fix permissions for publish and gradle issue for publishArtifactory

- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockMiner.java
Change block miner log to include all the performance number on one line with Info level.
> Change Blockminer log

- testutil/src/main/java/org/hyperledger/besu/testutil/JsonTestParameters.java
> chore: remove repetitive word

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/clique/CliqueMiningAcceptanceTest.java
improve checking for nodes in sync before sending transactions
fixes #6974
> Flaky test clique mining

- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockCreationTiming.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockSelectionContext.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/TransactionEvaluationContext.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/TransactionSelectionResults.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/AbstractTransactionSelector.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlobPriceTransactionSelector.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlockSizeTransactionSelector.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/MinPriorityFeePerGasTransactionSelector.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/PriceTransactionSelector.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/ProcessingResultTransactionSelector.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreatorTest.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockTransactionSelectorTest.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/LegacyFeeMarketBlockTransactionSelectorTest.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/LondonFeeMarketBlockTransactionSelectorTest.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/MinPriorityFeePerGasTransactionSelectorTest.java
Apply Hyperledger license header to `ethereum/blockcreation/`
See #6785
> Apply Hyperledger license header to `ethereum/blockcreation/`

- ethereum/ethstats/src/test/java/org/hyperledger/besu/ethstats/util/EthStatsConnectOptionsTest.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/B11rSubCommand.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/BenchmarkSubCommand.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolComponent.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/JsonUtils.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nExecutor.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nServerSubCommand.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nSubCommand.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/benchmarks/AltBN128Benchmark.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/benchmarks/BenchmarkExecutor.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/benchmarks/ECRecoverBenchmark.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/benchmarks/ModExpBenchmark.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/benchmarks/Secp256k1Benchmark.java
- ethereum/evmtool/src/test/java/org/hyperledger/besu/evmtool/EvmToolSpecTests.java
- ethereum/evmtool/src/test/java/org/hyperledger/besu/evmtool/T8nServerSubCommandTest.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/exceptions/PeerChannelClosedException.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/plain/MessageHandler.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/plain/MessageType.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/plain/PlainFramer.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/plain/PlainHandshaker.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/plain/PlainMessage.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxFrameConstants.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/framing/FramerProvider.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/handshake/HandshakerProvider.java
- ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/wire/ShouldConnectCallback.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/FileBasedPasswordProvider.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/P2PPlainNetworkTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/plain/MessageHandlerTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/NettyTLSConnectionInitializerTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/rlpx/wire/PeerInfoTest.java
Apply Hyperledger license header to ethereum/ethstats and ethereum/evmtool
#6785
> Apply Hyperledger license header to ethereum/ethstats and ethereum/evmtool

- evm/src/main/java/org/hyperledger/besu/collections/undo/UndoMap.java
- evm/src/main/java/org/hyperledger/besu/collections/undo/UndoNavigableMap.java
- evm/src/main/java/org/hyperledger/besu/collections/undo/UndoTable.java
- evm/src/main/java/org/hyperledger/besu/evm/ClassicEVMs.java
- evm/src/main/java/org/hyperledger/besu/evm/contractvalidation/PrefixCodeRule.java
- evm/src/main/java/org/hyperledger/besu/evm/fluent/SimpleBlockValues.java
- evm/src/main/java/org/hyperledger/besu/evm/frame/MessageFrame.java
- evm/src/main/java/org/hyperledger/besu/evm/frame/TxValues.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/ByzantiumGasCalculator.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/ConstantinopleGasCalculator.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/DieHardGasCalculator.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/FrontierGasCalculator.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/HomesteadGasCalculator.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/IstanbulGasCalculator.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/PetersburgGasCalculator.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/SpuriousDragonGasCalculator.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/TangerineWhistleGasCalculator.java
- evm/src/main/java/org/hyperledger/besu/evm/internal/EvmConfiguration.java
- evm/src/main/java/org/hyperledger/besu/evm/internal/OverflowException.java
- evm/src/main/java/org/hyperledger/besu/evm/internal/UnderflowException.java
- evm/src/main/java/org/hyperledger/besu/evm/precompile/KZGPointEvalPrecompiledContract.java
- evm/src/main/java/org/hyperledger/besu/evm/tracing/AccessListOperationTracer.java
- evm/src/main/java/org/hyperledger/besu/evm/tracing/EstimateGasOperationTracer.java
build: Add default constructor and javadoc for :evm subproject
> build: Add default constructor and javadoc for :evm subproject

- CHANGELOG.md
changelog - Java 17 and Java 21 upcoming changes
> changelog - Java 17 and Java 21 upcoming changes

- CHANGELOG.md
> added known issues to changelog

- .github/workflows/develop.yml
- .github/workflows/docker.yml
This reverts commit 2a39f2ccca86e098fee316c550dffd6437880373 due to github workflow failure https://github.com/hyperledger/besu/actions/runs/9026355992/job/24803532413
> Revert "Use github arm64 runners (#7054)"

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/blockhash/PragueBlockHashProcessor.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/BlockHashOperation.java
> Fix eip 2935 reftests

- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/PragueGasCalculator.java
Add the BLS precompiles to the warm account list for EIP-2929 gas costs.
> Add BLS precompiles to warm list

- README.md
Downloads now from gh not jfrog
> [MINOR] update download link in readme

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/RpcErrorType.java
Improves logging when tx pool is not enabled.
> Improve tx pool logging when not enabled.

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalRequestParameter.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/CachingBlockHashLookup.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessorTest.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/FrontierGasCalculator.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/GasCalculator.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/PragueGasCalculator.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/AuthOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/BlockHashOperation.java
- evm/src/test/java/org/hyperledger/besu/evm/operations/AuthOperationTest.java
- corrects gas checking in AUTH / AUTHCALL
- fixes bug in engine api v4
- corrects gas pricing in BLOCKHASH
> Pectra-devnet-0 discoveries

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalRequestParameter.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/WithdrawalRequest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/WithdrawalRequestEncoder.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/WithdrawalRequestContractHelper.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/WithdrawalRequestContractHelperTest.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/WithdrawalRequest.java
Rename methods and variables for consistency. 
Relates to https://github.com/hyperledger/besu/pull/7122
> [MINOR] WithdrawalRequest - Rename methods and variables to match Json

- CHANGELOG.md
changelog and download links for 24.5.2
fixes #7119
> [CHANGELOG] 24.5.2 changelog

- CHANGELOG.md
Update changelog for 24.6.0 release
> Update changelog for 24.6.0

- gradle/wrapper/gradle-wrapper.properties
> Update gradle to 8.8

- .github/workflows/docker.yml
> changed arm runner

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningOutOfSyncAcceptanceTest.java
- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodesSmartContractPermissioningStaticNodesAcceptanceTest.java
- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSDaemonTest.java
disable flaky permissioning tests
fixes #7108 
fixes #7155
> disable flaky test

- .github/ISSUE_TEMPLATE/release-checklist.md
new template for creating an issue to track Release action items.
> Issue Template for Release managers

- evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCreateOperation.java
Fail earlier with the initcode size check
> check initcode size earlier

- CHANGELOG.md
Add next release to the changelog, this commit serves as a bookend for 24.7.0 release
See the latest [release process](https://wiki.hyperledger.org/display/BESU/Release+Process) for more detail
> Add next release version after 24.7.0

- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nExecutor.java
Execute requests before persisting the block. 
Fix [multiple_block_above_max_withdrawal_requests_from_eoa]
> Fix t8n eip7002 test - Execute Requests before block persist

- CHANGELOG.md
Update changelog as requested in https://github.com/hyperledger/besu/pull/7309
https://github.com/hyperledger/besu/issues/6612
> 6612 update changelog with removed syncmodes

- CHANGELOG.md
Part of https://github.com/hyperledger/besu/issues/7384
> Rotate changelog for 24.7.1

- besu/src/main/java/org/hyperledger/besu/cli/options/stable/DataStorageOptions.java
> Add comments to make deprecated trie log pruning option names clear

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugAccountRange.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermAddAccountsToAllowlist.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermRemoveAccountsFromAllowlist.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermAddAccountsToAllowlistTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/permissioning/PermRemoveAccountsFromAllowlistTest.java
Updating code paths already updated to include the index of the parameter in the exception message when thrown
https://github.com/hyperledger/besu/issues/5098
> 5098: branch 10 Update already merged RpcErrorTypes to include index in exception message

- CHANGELOG.md
- ethereum/evmtool/src/main/docker/Dockerfile
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmTool.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommand.java
- ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/create-eof-error.json
- ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/eof.json
- ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/initcode-error.json
A few fixes that re-enable docker support for evm tool
* evmtool is the entrypoint
* turn off some noisy logging
* ensure EOF respects the create flag
> EVMTool Docker Support

- besu/src/main/java/org/hyperledger/besu/controller/TransitionBesuControllerBuilder.java
- besu/src/main/java/org/hyperledger/besu/services/RlpConverterServiceImpl.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateStateGenesisAllocator.java
- evm/src/main/java/org/hyperledger/besu/evm/EvmSpecVersion.java
- evm/src/main/java/org/hyperledger/besu/evm/fluent/EVMExecutor.java
- nat/src/main/java/org/hyperledger/besu/nat/kubernetes/KubernetesNatManager.java
> chore: fix some typos

- besu/src/test/java/org/hyperledger/besu/cli/TxPoolOptionsTest.java
Disables TxPoolOptionsTest.txpoolForcePriceBumpToZeroWhenZeroBaseFeeMarket 
https://github.com/hyperledger/besu/issues/7451
> 5098: Disable Flaky Test - TxPoolOptionsTest

- CHANGELOG.md
Attribute changes to the upcoming 24.8.0 release, create release-next
> Bump changelog ahead of 24.8.0

- acceptance-tests/tests/simple-permissioning-smart-contract/README.md
https://truffleframework.com/ is not accessible.
> chore:fix truffle website direction

- CHANGELOG.md
> Update changelog ahead of 24.9.0

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeFactory.java
Removed unused methods from PKS backed QBFT tests which has been removed
> [MINOR] qbft tls cleanup in AT

- CHANGELOG.md
update changelog to reflect 24.9.0-RC2 contents
> Bump changelog to reflect 24.9.0-RC2

- CHANGELOG.md
Remove character accidentally added in CHANGELOG
> Remove character accidentally added in CHANGELOG

- besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
- besu/src/main/java/org/hyperledger/besu/cli/options/MiningOptions.java
Added help for setting up Stratum mining
fixes #7514 
This PR is in response to this [#7514](https://github.com/hyperledger/besu/issues/7514)
[@non-fungible-nelson](https://github.com/macfarla) please review when you have some time.
> Added help for setting up Stratum mining

- CHANGELOG.md
Deprecate 24.9.0 release, update changelog to reflect 24.9.1
> Deprecate 24.9.0, create 24.9.1 release

- README.md
> [README] removed hyperledger from discord refs

- docs/tracing/README.md
Hi, opentelemetry's website url has been updated
> tracing:fix opentelemetry

- build.gradle
- ethereum/referencetests/build.gradle
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/BlockchainReferenceTestCase.java
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestProtocolSchedules.java
- ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/VerkleReferenceTestCaseSpec.java
- ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
- ethereum/referencetests/src/reference-test/templates/BlockchainReferenceTest.java.template
- ethereum/referencetests/src/reference-test/templates/VerkleSpecTest.java.template
Adds support for running verkle execution spec tests into verkle branch. It pulls the artifact from github and generates tests using `./gradlew :ethereum:referencetests:verkleSpecTests`.
> Add support for running verkle execution spec tests

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/BesuNode.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeConfiguration.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeConfigurationBuilder.java
- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeFactory.java
> Add suport for requested plugins (`--plugins` option) in acceptance tests

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClearEmptyAccountStrategy.java
> add comment

- ethereum/referencetests/build.gradle
- gradle/versions.gradle
This should fix reference tests and bring in some fixes from besu-verkle-trie
> Upgrade verkle reference tests and besu-verkle-trie dependency

- CHANGELOG.md
Release Tracker https://github.com/hyperledger/besu/issues/7710
> Rotate CHANGELOG for 24.10.0 release

- CHANGELOG.md
addresses but doesn't yet complete #7761
> communicate out option removal

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/peervalidation/AbstractPeerBlockValidator.java
Remove unused constructor from AbstractPeerBlockValidator
> 7311: Remove unused constructor from AbstractPeerBlockValidator

- CONTRIBUTING.md
- MAINTAINERS.md
- README.md
- SUPPORT.md
follows on from #7827 - same link in a few spots
> update discord invite link

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
> Fully initialize MetricCategoryRegistry for acceptance tests

- platform/build.gradle
Add more subprojects that are useful for plugins to the BOM
> Add more subprojects to BOM

- .github/workflows/stale-issues.yml
Adopts https://github.com/marketplace/actions/close-stale-issues action to manage old issues and prs.
> adds action to manage stale issues

- acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestMetricsPlugin.java
- plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorageTest.java
- testfuzz/src/main/java/org/hyperledger/besu/testfuzz/javafuzz/FuzzTarget.java
> chore: fix some typos in comments

- docs/trace_rpc_apis.md
"ope.ex.mem" should be "**op.ex.mem**" — The abbreviation for "opcode execution" should be "op" rather than "ope."
Corrected.
> Typo Update trace_rpc_apis.md

- consensus/qbft/build.gradle
Remove unused dependencies from qbft gradle module
> remove unused dependencies from qbft

- besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
- besu/src/main/java/org/hyperledger/besu/services/SynchronizationServiceImpl.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/services/sync/SynchronizationService.java
Expose start and stop synchronisation to plugin API
> Expose  synchronisation control to plugin aPI

- CHANGELOG.md
- acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/BadCLIOptionsPlugin.java
- acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestBesuEventsPlugin.java
- acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestBlockchainServiceFinalizedPlugin.java
- acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestInProcessRpcServicePlugin.java
- acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestMetricsPlugin.java
- acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestPermissioningPlugin.java
- acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestPicoCLIPlugin.java
- acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestPrivacyServicePlugin.java
- acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestRpcEndpointServicePlugin.java
- besu/src/main/java/org/hyperledger/besu/services/BesuPluginContextImpl.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/BesuPlugin.java
- plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBPlugin.java
- services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/InMemoryStoragePlugin.java
This reverts commit f08147acef874ad4e5493854096304ee7526c5fc.
#	plugin-api/build.gradle
> Revert "revert to unchanged plugin interface signature (#7938)"

- CHANGELOG.md
Update CHANGELOG.md for 24.12.0 release
> Update CHANGELOG.md for 24.12.0 release

- datatypes/src/main/java/org/hyperledger/besu/datatypes/AccountOverride.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCallTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java
see https://github.com/hyperledger/besu/pull/7999
> [Minor refactoring] - Use unsigned long parameter for nonce in AccountOverride

- CHANGELOG.md
This PR updates the changelog for a hotfix branch.  The hotfix branch addresses an artifact publishing problem in the 24.12.0 release.
> Bump changelog for 24.12.1 hotfix release

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
Address comment of https://github.com/hyperledger/besu/pull/8139#pullrequestreview-2561237429
> [Small improvement] -  Transaction simulator - Use `orElseGet`

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/CodeDelegationProcessorTest.java
- evm/src/main/java/org/hyperledger/besu/evm/account/AbstractCodeDelegationAccount.java
- evm/src/main/java/org/hyperledger/besu/evm/account/Account.java
- evm/src/main/java/org/hyperledger/besu/evm/account/AccountState.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCallOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractExtCallOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractExtCodeOperation.java
- evm/src/main/java/org/hyperledger/besu/evm/worldstate/CodeDelegationGasCostHelper.java
> 7702: rename methods and variables, clarify comments

- .github/workflows/verify_artifacts.py
> fixes syntax errors

- .github/pull_request_template.md
This is easy for new contributors to miss.
> add spotless to PR checklist

- besu/src/test/java/org/hyperledger/besu/ForkIdsNetworkConfigTest.java
- config/src/main/resources/holesky.json
- config/src/main/resources/sepolia.json
https://github.com/ethereum/EIPs/pull/9322/files
> Update prague timestamps for Holesky and Sepolia

- CHANGELOG.md
Spotted several errors in changelog :)
> [CHANGELOG] fixed changelog errors

- platform/build.gradle
Workaround for https://github.com/netplex/json-smart-v2/issues/240
> Hotfix for gradle compile issue by locking in json-smart version

- .github/workflows/acceptance-tests.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pre-review.yml
- .github/workflows/reference-tests.yml
> [build] run workflows on merge group event

- CHANGELOG.md
> [CHANGELOG] pectra testnet hotfix

- CHANGELOG.md
> Update CHANGELOG for 25.2.2 hot fix

- besu/src/main/java/org/hyperledger/besu/cli/options/PluginsConfigurationOptions.java
> fix : show '--plugins' option

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/TransactionTracer.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/debug/TraceOptions.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/DebugOperationTracer.java
Requested on one of the PRs against the verkle branch to do this modification on the main branch instead first: https://github.com/hyperledger/besu/pull/8336#discussion_r2013606854
> Refactor TraceOptions to become a record

- CHANGELOG.md
> Changelog for release 25.4.0

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessor.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/systemcall/SystemCallProcessor.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockContextProcessorTest.java
> Return BlockProcessingResult with error instead of throwing exception

- CHANGELOG.md
> Update CHANGELOG for release 25.4.1

- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
traceStartBlock seems to be duplicated.
> chore: remove duplicate trace start block

- build.gradle
I think the inclusion of these file was broken from a while, updated to the current locations
> Fix README.md and dependency license report into distribution artifacts

- acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
> Thread besu node runner modification in order to register correctly the plugin

- config/src/main/java/org/hyperledger/besu/config/BlobScheduleOptions.java
- config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
- config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
- datatypes/src/main/java/org/hyperledger/besu/datatypes/HardforkId.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecFactory.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
- ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/MainnetGenesisFileModule.java
> [fusaka-devnet-0] feat: add bpo definitions

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolConfiguration.java
> [fusaka-devnet-0] Bump tx pool blob

- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockTransactionSelectorTest.java
> Disabled London fee market flaky test 

- CHANGELOG.md
> add missing CHANGELOG entry for #8697

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolConfiguration.java
Increase the default for blob prioritized transactions
> chore: increase the default for blob prioritized transactions

- ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSDaemonTest.java
Still flaky: https://github.com/hyperledger/besu/issues/8373
> test: disable flaky testDNSDaemonPeriodic

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSpecBuilder.java
Remove blob schedule from gas calculator builder
> chore: remove blob schedule from gas calculator builder

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolConfiguration.java
> [fusaka-devnet-0] increase max number of blobs kept in the pool

- CHANGELOG.md
> [CHANGELOG] group items and some light editing

- platform/build.gradle
> Add services subprojects to BOM

- acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/PermissioningPluginTest.java
> disable flaky PermissioningPluginTest

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocolConfiguration.java
- evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java
> [fusaka-devnet-1] enable eth/69 on devnet 1

- evm/src/test/java/org/hyperledger/besu/evm/precompile/Benchmarks.java
from here https://github.com/ethereum/EIPs/pull/9855
> add extra modexp benchmarks

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetBlobsV1.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetBlobsV2.java
> [fusaka-devnet-1] Add engine_getblobsV2 to RpcMethod list

- ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/state-test/pay-opcode.json
- evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java
> feat: move pay opcode to future eips

- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlockRlpSizeTransactionSelector.java
- ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlockRlpSizeTransactionSelectorTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/MainnetBlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/BlockSizeBlockValidator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/referencetests/build.gradle
- ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/GeneralStateReferenceTestTools.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/GasCalculator.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/OsakaGasCalculator.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java
> [fusaka-devnet-2] EIP-7934 block size limit

- evm/src/main/java/org/hyperledger/besu/evm/EVM.java
- evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java
- evm/src/main/java/org/hyperledger/besu/evm/operation/CountLeadingZerosOperation.java
- evm/src/test/java/org/hyperledger/besu/evm/operation/CountLeadingZerosOperationTest.java
> [berlinterop-devnet-2] add clz opcode

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonRpcParameter.java
Should be no need to reserialize to json string just a map from one type to another!
> Remove redundant serialization of params

- evm/src/main/java/org/hyperledger/besu/evm/operation/CountLeadingZerosOperation.java
> [berlin-interop-devnet] Use UInt256 implementation

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/CancunTargetingGasLimitCalculator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/OsakaTargetingGasLimitCalculator.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/CancunTargetingGasLimitCalculatorTest.java
> [berlinterop-devnet-2] Fix max blob per transaction for prague

- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
- consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineGetPayload.java
> More PoS block proposal logs

- evm/src/main/java/org/hyperledger/besu/evm/operation/ExtCodeCopyOperation.java
> [fusaka-devnet-2] EIP-7907 - Fix ExtCodeCopy cost

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/BonsaiAccount.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/worldview/BonsaiWorldState.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/worldview/BonsaiWorldStateUpdateAccumulator.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/common/PathBasedAccount.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/BonsaiAccountTest.java
- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/messages/snap/AccountRangeMessage.java
- evm/src/main/java/org/hyperledger/besu/evm/account/AccountState.java
> [fusaka-devnet-2] Add codesize index

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/BonsaiWorldStateProvider.java
> [fusaka-devnet-2] Add exception to log

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetBlobsV2.java
> [fusaka-devnet-2] fix: return null if any missing blobs (getBlobsV2)

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetBlobsV2.java
> [fusaka-devnet-2] chore: remove log get blobs v2

- ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/BaseTransactionPoolTest.java
Fix failures in unit tests due to the usage of `BlobUtils` from Web3j and the loading of the trusted setup, replacing `BlobUtils` that has no way to unload the trusted setup, with our `BlobTestFixture` that instead has already everything needed and also makes the code simpler.
fixes regressing introduced by https://github.com/hyperledger/besu/pull/8857
> Fix failing unit tests due to trusted setup already loaded exception

- .github/workflows/verify_artifacts.py
When preparing the release 25.7.0, the step verify_artifacts failed to execute during the Draft release github action : https://github.com/hyperledger/besu/actions/runs/16042928540.
This is related to the changes made in Maven artifact names. This PR fixes the issue :
```
python3.11 .github/workflows/verify_artifacts.py --besu_version="25.7.0"
25.7.0
['https://hyperledger.jfrog.io/hyperledger/besu-maven/org/hyperledger/besu/evm/25.7.0/evm-25.7.0.module', 'https://hyperledger.jfrog.io/hyperledger/besu-maven/org/hyperledger/besu/evm/25.7.0/evm-25.7.0.pom', 'https://hyperledger.jfrog.io/hyperledger/besu-maven/org/hyperledger/besu/evm/25.7.0/evm-25.7.0.jar', 'https://hyperledger.jfrog.io/hyperledger/besu-maven/org/hyperledger/besu/plugin-api/25.7.0/plugin-api-25.7.0.module', …
```
> Fix verify_artifacts step in Draft Release github process

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/OsakaTargetingGasLimitCalculator.java
fix issue #8844 as per fusaka-devnet-3 changes
> chore: update blob base cost

- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/FrontierGasCalculator.java
- evm/src/test/java/org/hyperledger/besu/evm/precompile/P256VerifyPrecompiledContractTest.java
fix [8915](https://github.com/hyperledger/besu/issues/8915) as per fusaka-devnet-3 changes
> chore: double P256VERIFY cost

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocolConfiguration.java
> [fusaka-devnet-2] Start with eth/69

- .github/workflows/develop.yml
add some spaces and don't set one env from another - adds to #8876
> verify docker container on develop workflow take 2

- .github/workflows/develop.yml
This reverts commit 58abb989b7a6793459b63fec9d1a7afff1c1a2e4.
and 45f57d0740
> Revert "verify docker container on develop workflow (#8876)"

- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/OsakaGasCalculator.java
- evm/src/test/java/org/hyperledger/besu/evm/gascalculator/OsakaGasCalculatorTest.java
> [fusaka-devnet-3] Fix edge case for modexp gas calculator

- ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteSyncBlocksTask.java
> chore: fix log level

- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/OsakaTargetingGasLimitCalculator.java
Fix failing tests for: fusaka-devnet-5 https://github.com/ethereum/execution-spec-tests/releases/tag/fusaka-devnet-5@v1.0.0
- test_excess_blob_gas.py::test_correct_decreasing_blob_gas_costs[fork_Osaka-parent_blobs_5-parent_excess_blobs_1695-blockchain_test-new_blobs_1][Osaka]]
- tests/cancun/eip4844_blobs/test_excess_blob_gas.py::test_correct_decreasing_blob_gas_costs[fork_Osaka-parent_blobs_5-parent_excess_blobs_1845-blockchain_test-new_blobs_1][Osaka]]
- tests/cancun/eip4844_blobs/test_excess_blob_gas.py::test_correct_increasing_blob_gas_costs[fork_Osaka-parent_blobs_7-parent_excess_blobs_1244-blockchain_test-new_blobs_1][Osaka]]
- tests/cancun/eip4844_blobs/test_excess_blob_gas.py::test_correct_increasing_blob_gas_costs[fork_Osaka-parent_blobs_7-parent_excess_blobs_1694-blockchain_test- …
> fix(osaka): fix overflow multiplication

- CHANGELOG.md
#8869 is included in 25.8.0-RC3
> RC3 changelog - 8869 included 25.8.0

- .github/pull_request_template.md
> PR template - add hive test instructions

- .github/workflows/codeql.yml
codeql config - add missing language matrix 
think this was removed here 9cb6600456000c68aebec54670cb27ac017f6f61
This should fix the codeql scanning config error
> codeql - add language matrix

- CHANGELOG.md
match release notes for https://github.com/hyperledger/besu/releases/tag/25.8.0
> [CHANGELOG] add fixed CVEs to changelog

- app/src/main/java/org/hyperledger/besu/services/TraceServiceImpl.java
Fixing a tracing issue we added in this PR https://github.com/hyperledger/besu/pull/8981
fixes #9098
> fix tracing issue 

- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ExecuteTransactionStep.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/BlockTracer.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/TransactionTrace.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/CallTracerResultConverter.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/OpCodeLoggerTracerResult.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/StructLog.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/StructLogWithError.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/diff/StateDiffGenerator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/Action.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/FlatTraceGenerator.java
- ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/vm/VmTraceGenerator.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugAccountAtTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceTransactionTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/TransactionTracerTest.java
- ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/StructLogTest.java
- ethereum/core/src/integration-test/java/org/hyperledger/besu/ethereum/vm/TraceTransactionIntegrationTest.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/DebugOperationTracer.java
- ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/DebugOperationTracerTest.java
- evm/src/main/java/org/hyperledger/besu/evm/tracing/OperationTracer.java
- evm/src/main/java/org/hyperledger/besu/evm/tracing/TraceFrame.java
Minor refactor, later prs will build on top of this to more easily provide interruptable tracing.
> refactor so all tracers can provide TraceFrames

- ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
- evm/src/main/java/org/hyperledger/besu/evm/gascalculator/Eip4762GasCalculator.java
Changes for updates in https://github.com/ethereum/EIPs/pull/10202
> EIP-4762 - Remove system contract warming gas cost code path

- app/src/main/java/org/hyperledger/besu/cli/options/MiningOptions.java
- app/src/test/java/org/hyperledger/besu/cli/options/MiningOptionsTest.java
- app/src/test/java/org/hyperledger/besu/controller/AbstractBftBesuControllerBuilderTest.java
- app/src/test/java/org/hyperledger/besu/controller/CliqueBesuControllerBuilderTest.java
- app/src/test/resources/everything_config.toml
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
- ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/InterruptibleOperationTracer.java
- ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/MiningConfiguration.java
- plugin-api/build.gradle
- plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java
* Time limited plugin txs selection
> Backport: Time limited plugin txs selection 

- CHANGELOG.md
Release tracker: https://github.com/hyperledger/besu/issues/9216
> Rotate changelog for 25.9.0

- CHANGELOG.md
added known issue to 25.9.0 changelog
> [CHANGELOG] add known issue for eth_subscribe and ethstats 

- CHANGELOG.md
> changelog for RC2
