hyperledger/besu

CHANGELOG.md
gradle/versions.gradle

- Updated jackson-databind library to version 2.13.4.2 addressing [CVE-2022-42003](https://nvd.nist.gov/vuln/detail/CVE-2022-42003)
- Also updated other jackson deps to 2.13.4

Upgrade jackson-databind to 2.13.4.2 and other jackson deps to 2.13.4

---

evm/src/main/java/org/hyperledger/besu/evm/EVM.java

Restore two tracing behaviors in the EVM introduced by the unrolled loop
* change gas only on successful operations
* send post execution call after gas and PC changes.

Adjust tracing calls

---

ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java

Some London tests from [`ethereum/tests`](https://github.com/ethereum/tests) are failing because they send more transactions from the same sender than those accepted in the transaction pool by default (e.g. `BlockchainTests/ValidBlocks/bcEIP1559/feeCap.json` sends 16 transactions for the same block). This PR increases the percentage of same account transactions allowed in the transaction pool for the `retesteth` environment.
#4461

Increase same account percentage in transaction pool for `retesteth`

---

evm/src/main/java/org/hyperledger/besu/evm/tracing/StandardJsonTracer.java
evm/src/test/java/org/hyperledger/besu/evm/StandardJsonTracerTest.java

The EVM refactor introduced a couple of EVM trace changes that are outside the EIP-3115 standards.
* pc, gasRemaining, and memory were all post-execution values
* some places null should be "0x0" or "0x"

Bring standard tracer closer to EIP standards

---

evm/src/main/java/org/hyperledger/besu/evm/tracing/StandardJsonTracer.java
evm/src/test/java/org/hyperledger/besu/evm/StandardJsonTracerTest.java

The EVM refactor introduced a couple of EVM trace changes that are outside the EIP-3115 standards.
* pc, gasRemaining, and memory were all post-execution values
* some places null should be "0x0" or "0x"

Bring standard tracer closer to EIP standards (#4586)

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiInMemoryWorldState.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiPersistedWorldState.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateKeyValueStorage.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateUpdater.java
evm/src/main/java/org/hyperledger/besu/evm/worldstate/AbstractWorldUpdater.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java

Create a specific calculateRootHash for BonsaiInMemoryWorldState, avoid committing and rollbacking as it is not necessary. This PR parallelize also the accounts update storage in calculateRootHash method.
The yellow line below is the version with the modifications in this PR, the other node is used as a reference node (a baseline) regarding block size and the number of transactions per block. 
We have below engine_newPayloadV1 RPC call (Block processing) mean time comparaison between this PR, version 22.7.6 and version 22.7.7
We can notice also that calculateRootHash method is consuming less (real) time on CPU because of the parallelization and the fact we removed commit and rollback method.
**Before this PR**
**After this PR**
Mitigate #4549
[updates are …

Create a specific calculateRootHash method for BonsaiInMemoryWorldState to improve performance

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java

wrap sender account info as SimpleAccount to prevent holding references to BonsaiAccount's in memory, and their corresponding rocksdb transactions and worldstates
fixes #4604

Use SimpleAccount references in TxPool

---

plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBSnapshot.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBSnapshotTransaction.java

Short term fix to ensure snapshot transactions are closed and snapshots released before their respective objects are GC'd.
This is a stop-gap measure until a subsequent PR addresses #4641 and can use static analysis to ensure all worldstates are closed at the end of their lifecycle.
Fixes  #4643 

Ensure snapshots released before gc

---

ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiSnapshotIsolationTests.java

explicitly close snapshot worldstates and their copies to avoid a segfault on circle-ci when running BonsaiSnapshotIsolationTest

Fix circleCI snapshot segfaults

---

CHANGELOG.md
gradle/versions.gradle

The new version of RocksDB JNI library was published in maven on Oct 25, 2022, this PR will upgrade rocksdb JNI library from 7.6.0 to 7.7.3.

Upgrade RocksDB from version 7.6.0 to 7.7.3

---

evm/src/main/java/org/hyperledger/besu/evm/EVM.java

This PR removes the opcodes `SHL`, `SHR` and `SAR` from the base EVM b/c those were added in [EIP-145](https://eips.ethereum.org/EIPS/eip-145) and shouldn't be available since Genesis.
Spotted by @winsvega during the execution of LegacyTests. E.g.
```shell
$ ./retesteth -t LegacyTests/Constantinople/BCGeneralStateTests/stShift -- --singletest shr11_d0g0v0 --clients besu --singlenet Byzantium --nodes 127.0.0.1:8545
```

Remove SHL, SHR and SAR from default EVM

---

plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBSnapshotTransaction.java

If we are adding finalize, at least add some way to investigate a potential not closed object. 

Adding option to debug the potential problems with closing Transaction

---

besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
besu/src/main/java/org/hyperledger/besu/controller/ConsensusScheduleBesuControllerBuilder.java
besu/src/main/java/org/hyperledger/besu/controller/IbftLegacyBesuControllerBuilder.java
besu/src/main/java/org/hyperledger/besu/controller/MergeBesuControllerBuilder.java
besu/src/main/java/org/hyperledger/besu/controller/TransitionBesuControllerBuilder.java
consensus/ibftlegacy/src/main/java/org/hyperledger/besu/consensus/ibftlegacy/protocol/Istanbul99ProtocolManager.java
consensus/ibftlegacy/src/test/java/org/hyperledger/besu/consensus/ibftlegacy/protocol/Istanbul99ProtocolManagerTest.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTestUtil.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TestNode.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactoryTest.java

Signed-off-by: Gabriel Trintinalia <gabriel.trintinalia@gmail.com>
- Rename fastSyncEnabled to fullSyncDisabled as it can mislead someone into the assumption that the sync mode is FAST SYNC while it may be snap/checkout.
- Pass SynchronizerConfiguration object down to EthProtocolManager instead of Boolean fastSyncEnabled

Remove misleading fastSyncEnabled variable

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DataStorageConfiguration.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchiveTest.java

In light of the stability fix for layered worldstates in #4700, and the higher performance of in-memory worldstates versus snapshot worldstates, this PR reverts the default behavior of bonsai back to layered worldstates:
This reverts commit 305897c075947ea73e71b0f5d68717163a3ea861.

Revert "make snapshots the default behavior"

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/AbstractTrieLogManager.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiInMemoryWorldState.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiLayeredWorldState.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiSnapshotWorldStateKeyValueStorage.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateKeyValueStorage.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/SnapshotTrieLogManager.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/AbstractIsolationTests.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiInMemoryIsolationTests.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiSnapshotIsolationTests.java

In `BonsaiLayeredWorldState.copy()`, use a snapshot worldstate as the basis for a BonsaiInMemoryWorldstate copy
Prevents stateroot mismatches that arise from the persisted worldstate being different than the worldstate assoicated with a given layered worldstate.
Also moves isolation test setup into an abstract class, and adds a new BonsaiInMemoryIsolationTest

Use snapshots for in-memory copies of layered worldstate

---

metrics/core/src/main/java/org/hyperledger/besu/metrics/MetricsSystemFactory.java

Prevent trying to re-disable OpenTelemetry global if it has already been disabled previously.  Otherwise `evmtool` was failing to start with this error:
```
java.lang.IllegalStateException: GlobalOpenTelemetry.set has already been called. GlobalOpenTelemetry.set must be called only once before any calls to GlobalOpenTelemetry.get. If you are using the OpenTelemetrySdk, use OpenTelemetrySdkBuilder.buildAndRegisterGlobal instead. Previous invocation set to cause of this exception.
at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:99)
at org.hyperledger.besu.metrics.MetricsSystemFactory.disableGlobalOpenTelemetry(MetricsSystemFactory.java:38)
...
```
[updates are …

Fix OpenTelemetry disabling in MetricsSystemFactory

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/encoding/TransactionDecoderTest.java

Signed-off-by: Gabriel Trintinalia <gabriel.trintinalia@gmail.com>
The eth/68 protocol intends to pass the transaction size along with the transaction announcement.
fixes #4723

Calculate Transaction Size

---

ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/messages/MessageWrapperTest.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/BlockchainReferenceTestCaseSpec.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestWorldState.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/StateTestVersionedTransaction.java

Change nonce hex parsing to be treated as encoded longs, not trimmed byte arrays.
fixes #4719

Treat nonces as quantities

---

besu/src/test/java/org/hyperledger/besu/cli/options/AbstractCLIOptionsTest.java
besu/src/test/java/org/hyperledger/besu/cli/options/NetworkingOptionsTest.java

Remove deprecated method isEqualToIgnoringGivenFields from the package org.assertj.core.api 

Removing deprecated method

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiSnapshotWorldStateKeyValueStorage.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateKeyValueStorage.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/CachedMerkleTrieLoader.java

in 22.10.1, two new operations pre-load account and storage from their respective worldstate asynchronously.  If the worldstate is based on a snapshot, there is a race where the snapshot might be closed ahead of the async operations completing, and subsequently result in a segfault when trying to access a closed rocksdb snapshot.  
This PR adds a subscriber implementation for BonsaiWorldStateKeyValueStorage which ensures that the storage will not be closed while subscribers are still operating on it.
#4765 

Ensure that Snashot worldstates remain open for async operations

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/PipelineChainDownloader.java

Signed-off-by: mark-terry <mark.terry@consensys.net>
Change the log level for a common chain download error from `error` to `debug`.
Fixes #4081 

Changed chain download error log level from error to debug.

---

.github/workflows/release.yml
build.gradle
gradle.properties

Expands the github release workflow to support adding the latest tags for all the docker variants and architectures.
* Replace the use of git sha tags with existing release tags to avoid creating a lot of unneeded tags. When creating the latest tags for all the variants, arch and manifests 15 tags are needed in total
* Added latest tags for variants as was done for previous releases
* Added latest tags for all the architectures
* Added latest tags for multi-arch images

Docker release task for latest tags

---

.circleci/config.yml
CHANGELOG.md
build.gradle

Besu currently has 3 privacy modes. The privacy mode that provides compatibility with GoQuorum privacy is intertwined with mainnet code at the transaction and block processing level. We also have not seen demand for this privacy mode within the Besu community.
We plan to deprecate the GoQuorum-compatible privacy feature, along with IBFT 1.0, in the coming quarterly release 23.1, and then remove it in the following quarterly release 23.4.
Removing the code associated with this feature will reduce the complexity of the transaction and block processing code, reducing friction for mainnet-focused development.
This will not affect the remaining 2 privacy modes (EEA privacy and flexible privacy groups).
This will not affect IBFT 2.0 or …

Deprecation notice for GoQuorum-compatible privacy and IBFT 1.0

---

.github/workflows/dco.yml

The action we're using here only supports pull_request events
https://github.com/tim-actions/get-pr-commits/blob/c64db31d359214d244884dd68f971a110b29ab83/index.js#L4

rollback dco on push

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/AbstractTrieLogManager.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiInMemoryWorldState.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiLayeredWorldState.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiPersistedWorldState.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiSnapshotWorldState.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiSnapshotWorldStateKeyValueStorage.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchive.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateKeyValueStorage.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/CachedMerkleTrieLoader.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/LayeredTrieLogManager.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/SnapshotTrieLogManager.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/TrieLogManager.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/SnapshotMutableWorldState.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/AbstractIsolationTests.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiSnapshotIsolationTests.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiSnapshotWorldStateArchiveTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchiveTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/LayeredWorldStateTests.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldStateDownloader.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBSnapshot.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBSnapshotTransaction.java

This PR addresses a race where snap and checkpoint syncs can cause a segfault when starting a worldstate download.  The segfault occurs when rocksdb snapshot transactions are read/written after a storage truncation.  To prevent this and to ensure future uses of clear() and clearFlatDatabase() cannot cause segfaults, this PR:
* adds BonsaiStorageSubscriber type to handle storage events
* removes addCachedLayer from TrieLogManager, moves to AbstractTrieLogManager
* TrieLogManager takes a snapshot immediately in addCachedLayer rather than deferring it 
* notifies subscribers on events that can affect the worldstate, specifically:
* clear (truncate)
* clearFlatDatabase (truncating a subset of storage)
* close (closing the worldstate storage)
Additionally, only drop cached layers by distance …

Bugfix snapshot transaction segfaults after storage truncation

---

CHANGELOG.md
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommandOptionsModule.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolComponent.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/MetricsSystemModule.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/ProtocolModule.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/StateTestSubCommand.java

Add a CLI flag --json-alloc that will output the post-execution state of the allocations the EVM Tool executed in. As well as post-execution state for state-tests.

Add post-run allocation output to EVMTool

---

consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateKeyValueStorage.java

Ensure we do not leave the bonsai database in an inconsistent state where chain head and worldstate are at different block hashes
relates to #4784

Bugfix potential chain head and worldstate inconsistency

---

errorprone-checks/src/main/java/org/hyperledger/errorpronechecks/MethodInputParametersMustBeFinal.java
errorprone-checks/src/test/resources/org/hyperledger/errorpronechecks/MethodInputParametersMustBeFinalNegativeCases.java

Custom ErrorProne checks should not be validating generated code we cannot change, hence the "method params must be final" ErrorProne check will not fire in classes with a "generated" annotation.  This covers Dagger generated code.

Do not apply final arguments ErrorProne to generated code

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java

Add a warning if besu is started with isQuorum mode in genesis file. 
Advise to use `--privacy-enabled` instead
Fixes #4848 

Deprecation warning for Goquorum privacy mode

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionInvalidReason.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractRetryingSwitchingPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetHeadersFromPeerByHashTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetHeadersFromPeerByNumberTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncTargetManager.java

Disconnect "worst" peer in two cases
* AbstractRetryingSwitchingPeerTask - when retrying task with multiple peers and all peers have been tried and found wanting
* FastSyncTargetManager - if best peer is behind the pivot block, disconnect worst peer 
Also add some extra context info to "Best peer" log message

Peering - disconnect worst peer

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugResyncWorldstate.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/DebugJsonRpcMethods.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/JsonRpcMethodsFactory.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/BadBlockManager.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Synchronizer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/DefaultSynchronizer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardsSyncAlgorithm.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/checkpointsync/CheckpointDownloaderFactory.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/worldstate/FastDownloaderFactory.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapDownloaderFactory.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/state/SyncState.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/NewPooledTransactionHashesMessageHandler.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PeerTransactionTracker.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactory.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionsMessageHandler.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/AbstractPendingTransactionsSorter.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/BaseFeePendingTransactionsSorter.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/GasPricePendingTransactionsSorter.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/LowestInvalidNonceCache.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastDownloaderFactoryTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactoryTest.java
ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/DummySynchronizer.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/BesuEvents.java

Implements a  debug rpc endpoint and a behavior to resync just the worldstate.  

Worldstate-only resync behavior

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateUpdater.java

During an initial worldstate sync, a self-destruct that occurs between the initial pivot block and final heal pivot block will leave stale code in bonsai code storage.  If subsequently the code is redeployed via create2 to the same contract address, the bonsai db will fail to roll code changes to the block where the redeployment occurs.  This presents in a handful of ways such as 'worldstate not present' or 'unable to copy layered worldstate'.
Discussing with @matkt, since the repivot and heal process does not presently have an opportunity to 'heal' the code storage, and we should be able to trust the trielogs, this PR changes the rollCodeForward behavior to overwrite stale code if/when it is found.  This should resolve #4784 and give the besu team an opportunity to revisit this in flat …

Address bonsai self-destruct stale code present 

---

acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/login/LoginRequestFactory.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpServiceHostWhitelistTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/AbstractJsonRpcHttpBySpecTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/AdminJsonRpcHttpServiceTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceHostAllowlistTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceLoginTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceParameterizedTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceRpcApisTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/filter/EthJsonRpcHttpServiceTest.java

Content type moved to second arg where needed to avoid deprecation warning

[MINOR] Correct order of args to RequestBody.create

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/WithdrawalsProcessor.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/WithdrawalsProcessorTest.java

Some cleanup, the noop withdrawals processor is no longer needed since ProtocolSpec returns an Optional<WithdrawalsProcessor> instead.

Remove noop WithdrawalsProcessor

---

consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionProtocolSchedule.java
consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/TransitionProtocolScheduleTest.java

Signed-off-by: Karim TAAM [karim.t2am@gmail.com](mailto:karim.t2am@gmail.com)
Co-authored-by: Ameziane H [ameziane.hamlat@consensys.net](mailto:ameziane.hamlat@consensys.net)
There is a performance regression in the RC version 23.1.0-RC1 compared to 22.10.3 in both engine_getPayloadV1 and engine_forkchoiceUpdatedV1 calls. This regression is related to recent changes in the way we get the protocol specifications. We get the whole block by decoding each single transaction to use only the block header.
```
return Optional.ofNullable(protocolContext)
.map(ProtocolContext::getBlockchain)
.flatMap(blockchain -> blockchain.getBlockByNumber(number))
.map(Block::getHeader)
.map(timestampSchedule::getByBlockHeader)
.orElseGet(
() ->
transitionUtils.dispatchFunctionAccordingToMergeState( …
```

Improve get protocol schedule (only get header and not the entire block)

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java

Swap lines order to ensure we commit FCU even if payload timestamp is before head timestamp
Signed-off-by: Gabriel Fukushima <gabrielfukushima@gmail.com>
This PR fixes the regression introduced recently.
Makes Besu compliant with ForkChoiceUpdate_V1 - item 7 of the Engine API specs for Paris. (https://github.com/ethereum/execution-apis/blob/main/src/engine/paris.md)

Fix: Hive engine api FCU regression

---

besu/src/main/java/org/hyperledger/besu/cli/util/TomlConfigFileDefaultProvider.java
besu/src/test/java/org/hyperledger/besu/cli/TomlConfigFileDefaultProviderTest.java

Fix TOML parsing of double 
- no special processing required for double or float
- refactor getInteger to getNumeric since it works for all number types
- added a test to ensure we can parse an int value into double type
eg 
tx-pool-limit-by-account-percentage=1.0
should work the same as
tx-pool-limit-by-account-percentage=1
Ref #4899 which didn't quite work for me. 
@bl0up does this work for you? 
Fixes #4896 

Fix TOML parsing of double and float values

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/test/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommandTest.java

This fixes the NPE from some of the engine-api hive test that call the importBlock subcommand

Fix npe from subcommands

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV1.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV1.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdatedTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV1Test.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV1Test.java

Signed-off-by: Zhenyang Shi <wcgcyx@gmail.com>
Update engine API to include some new changes introduced in 
- [ethereum/execution-apis#338](https://github.com/ethereum/execution-apis/pull/338) and 
- [ethereum/execution-apis#337](https://github.com/ethereum/execution-apis/pull/337)
fixes #4916 

Shanghai Engine API Updates

---

build.gradle

Exclude Dagger generated sources from ErrorProne

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/BlockResult.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/BlockResultFactory.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockWithMetadata.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java

This is the critical piece that will allow Withdrawals interop to work.
Integration tests and any other RPCs that return a block will be added in a subsequent PR.
Signed-off-by: Simon Dudley <simon.dudley@consensys.net>
Critical piece of #4808

Add withdrawals details to eth_getBlock methods

---

besu/src/test/java/org/hyperledger/besu/services/BesuEventsImplTest.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/BlockReplay.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/TransactionTracerTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiSnapshotWorldStateKeyValueStorage.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBSnapshotTransaction.java
services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/InMemoryKeyValueStorage.java

There has been a regression on Besu regarding the transaction pool. Indeed it seems that the transaction pool validation part does not make a copy of the worldstate during the GetMutable and this means that we can have a version which can change and which is not safe. A copy mechanism has been set up which allows to use the snapshot and to protect against worldstate modifications during validation. it was used elsewhere except in transaction pool validation and block replay.
This caused us to invalidate too many transactions

Fix transaction pool issue

---

consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionProtocolSchedule.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/PoWBlockCreatorTest.java

Don't cache the protocol spec in the block creator.  With the new shanghaiTimestamp the correct spec may be a function of the timestamp not just the block number.  So every time we are asked to build a block re-query the spec.

Don't cache protocol spec in block creator

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/BlockResultFactory.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockValueCalculator.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/BlockValueCalculatorTest.java

address corner case where long does not fit the calculated block value included in engine_getPayloadV2.
Change BlockValueCalculator to use Wei rather than unnecessarily converting to long (just to later be converted again into a Quantity)

address case of block values exceeding long

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/MainnetBlockValidator.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockBodyValidator.java

* Associate block number and hash with the various invalid block warnings, in the format:
`Invalid block {blockNumber} ({blockHash}): ... mismatch (expected=..., actual=...)`
Instead of 
```
WARN  | MainnetBlockBodyValidator | Invalid block: receipts root mismatch (expected=0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, actual=0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421) 
```
we now have 
```
WARN  | MainnetBlockBodyValidator | Invalid block 1 (0xd2ce6fb30db1ab80b0a5c137f3c8a83d12052e5a40366eba4c15b229c6a863e6): receipts root mismatch (expected=0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, actual=0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421) 
```
---
* Print a less obscure message when there's no error …

Improve MainnetBlockBodyValidator logging

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java

Fix create block using the wrong protocol schedule when the parent is genesis.

Fix create block using wrong protocol schedule when parent is genesis

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/TransactionCompleteResult.java

Fix do not evaluate second expression if the value is present.
Signed-off-by: ħþ <12281088+helderjnpinto@users.noreply.github.com>
This is causing some issues when we got a earlier version of besu after this PR https://github.com/hyperledger/besu/pull/3065, the problem is caused by gasPrice existing in transaction but is too big to fit in Long types.
Evaluating the second expression is not needed if the gasPrice is present also causing extra processing.

Change to optional orElseGet

---

.circleci/config.yml
acceptance-tests/tests/build.gradle
container-tests/tests/build.gradle

Ref #4921 
* split ATs into two groups - mainnet and non-mainnet
* run "non-mainnet" ATs on nightly build
* did 2 runs with run both groups of ATs on PRs (to make sure it works - the right numbers of tests are run - see comments for details)

split ATs into privacy/permissioning/etc and the rest

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeCapabilities.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/ExecutionEngineJsonRpcMethods.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeCapabilitiesTest.java

https://github.com/ethereum/execution-apis/pull/364

Implement engine_exchangeCapabilities

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/WithdrawalsProcessor.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/WithdrawalsProcessorTest.java
evm/src/main/java/org/hyperledger/besu/evm/worldstate/WorldUpdater.java

This fixes an issue that was found in the withdrawal reference tests where we update an account with a balance of zero. Ensure that the withdrawals processor clears empty accounts so that we conform to eip-158.

Withdrawals processor delete empty account

---

.circleci/config.yml

This reverts commit b22a52a88e42a5c11f0564f1c9603bff55687e9e.
It seems not all tests are running. Needs more investigation.
See #4921 

Revert "parallelization for unit tests (#5000)"

---

README.md

Signed-off-by: Gabriel Fukushima <gabrielfukushima@gmail.com>
Removes the lgtm (has been shut down In Dec 2022) labels from the readme.

remove lgtm labels

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java

When withdrawals are null (i.e. disabled, pre-shanghai) then display nothing extra in the log.
When withdrawals are present, display their size, even when 0.
Chose 'ws' as a short name to keep the overall log small and since this is mostly useful for developers debugging rather than useful info for a node operator.
Tested on withdrawals-devnet-6, here's the Shanghai fork transition...
```
2023-01-30 20:53:44.059+10:00 | vert.x-worker-thread-0 | INFO  | AbstractEngineNewPayload | Imported #304 / 0 tx / base fee 7 wei / 0 (0.0%) gas / (0x5d96179b829a1c2ba62774b9559a401b198375bc6d6b6a39521594ac6e5996e4) in 0.000s. Peers: 1
2023-01-30 20:53:44.818+10:00 | vert.x-worker-thread-0 | INFO  | AbstractEngineNewPayload | Imported #305 / 0 tx / 0 ws / base fee 7 wei / 0 (0.0%) gas / …
```

Add optional withdrawals to the NewPayload log

---

plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBSnapshotTransaction.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/unsegmented/RocksDBKeyValueStorage.java

This PR will disable checksum verification on RocksDB during Block retrieva.
We could't do it before because there is this issue in RocksDB, you can find more context here : https://github.com/facebook/rocksdb/issues/11002
@matkt did a PR https://github.com/facebook/rocksdb/pull/11099 and fixed the issue, we can now enable it in Besu.

Disable RocksDB checksum verification on reads

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateTransactionProcessor.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/CodeValidateSubCommand.java
evm/src/main/java/org/hyperledger/besu/evm/EVM.java
evm/src/main/java/org/hyperledger/besu/evm/code/CodeFactory.java
evm/src/main/java/org/hyperledger/besu/evm/code/CodeInvalid.java
evm/src/main/java/org/hyperledger/besu/evm/code/CodeV0.java
evm/src/main/java/org/hyperledger/besu/evm/code/CodeV1.java
evm/src/main/java/org/hyperledger/besu/evm/contractvalidation/CachedInvalidCodeRule.java
evm/src/main/java/org/hyperledger/besu/evm/contractvalidation/EOFValidationCodeRule.java
evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCreateOperation.java
evm/src/test/java/org/hyperledger/besu/evm/code/CodeFactoryTest.java
evm/src/test/java/org/hyperledger/besu/evm/code/CodeV0Test.java
evm/src/test/java/org/hyperledger/besu/evm/internal/CodeCacheTest.java
evm/src/test/java/org/hyperledger/besu/evm/operations/Create2OperationTest.java
evm/src/test/java/org/hyperledger/besu/evm/operations/CreateOperationTest.java
evm/src/test/java/org/hyperledger/besu/evm/operations/JumpOperationTest.java
evm/src/test/java/org/hyperledger/besu/evm/processor/ContractCreationProcessorTest.java

Speedup initcode validation by
* optimizing the jumpdest loop
* not caching initcode in the code cache (but keep codecache for normal contracts).

Speed up initcode validation

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiInMemoryWorldState.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiLayeredWorldState.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/AbstractPendingTransactionsSorter.java

Fixes an issue where the latest block in BonsaiWorldStateArchive had a closed worldstate.  Persisting BonsaiInMemoryWorldState instances were creating entries in the archive with a snapshot worldstate that would subsequently be closed.  The net result was that queries using the worldstate for the `latest` block would frequently return Optional.empty() when accessing the closed worldstate.
this PR:
* uses a dedicated copy of the Bonsai in memory worldstate when creating a trielog
* adds a close() override to Bonsai layered worldstate to ensure the worldstate resources are cleaned up
* makes minor log change 
fixes #5038 

Keep Worldstate Storage open for Bonsai archive latest layer

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiInMemoryWorldState.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiLayeredWorldState.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/AbstractPendingTransactionsSorter.java

This reverts commit e7150102ea208165ac29bd10986fe26bc9e176d0.
This is causing "Unable to copy Layered Worldstate" errors affecting canary nodes, devnets and the 23.1.0 burn-in

Revert "Keep Worldstate Storage open for Bonsai archive latest layer (#5039)"

---

besu/src/test/java/org/hyperledger/besu/ForkIdsNetworkConfigTest.java
config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
config/src/main/resources/sepolia.json
consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionProtocolSchedule.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/DefaultTimestampSchedule.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/HeaderBasedProtocolSchedule.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSchedule.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/forkid/ForkIdTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/forkid/ForkIdTestUtil.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/TimestampScheduleBuilderTest.java

Announced here: https://github.com/ethereum/execution-specs/pull/716
Move timestamp forks from getForkBlockNumbers to getForkBlockTimestamps in JsonGenesisConfigOptions - this ultimately gets used to popoulate the ForkIdManager which handles lists of blocks and timestamps the same way so this hasn't changed any actual behaviour, but rather supports the test fixes.
Implement TransitionProtocolSchedule.streamMilestoneBlocks as a concatenation of blockNumbers++blockTimestamps. This may have been a latent bug since it's used to update the node record when a fork transition occurs.

Add shanghaiTime to sepolia

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/AbstractTrieLogManager.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiInMemoryWorldState.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiLayeredWorldState.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/AbstractPendingTransactionsSorter.java
gradle.properties

burn-in release of 23.1.0 onto  [RC2](https://github.com/hyperledger/besu/tree/23.1.0-RC2) tag
* cherry pick of #5076
* consolidated changelog

Burn in build of 23.1.0

---

docker/graalvm/Dockerfile
docker/openjdk-17-debug/Dockerfile
docker/openjdk-17/Dockerfile
docker/openjdk-latest/Dockerfile

Same issue existed on Teku: https://github.com/ConsenSys/teku/pull/6740 
Can't use the docker image when running it with another user than root or `1000`.
```sh
$ docker pull consensys/besu 
$ docker run --rm -it --entrypoint ls  consensys/besu 
LICENSE  besu.autocomplete.sh  bin  lib  license-dependency.html 
$ docker run --rm -it --entrypoint ls --user=1000  consensys/besu 
LICENSE  besu.autocomplete.sh  bin  lib  license-dependency.html
$ docker run --rm -it --entrypoint ls --user=1003  consensys/besu 
ls: cannot open directory '.': Permission denied
```

Allow other users to read the /opt/besu dir when using docker

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockValueCalculator.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/BlockValueCalculatorTest.java

This PR fix the block value calculation mechanism by using gasUsed instead of the cumulativeGas to calculate the block value.
This change has been tested against the hive test(GetPayloadV2 Block Value) for this feature.
Fixes #5040

Fix block value calculation

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/DefaultCommandValues.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcConfiguration.java

default global rpc max batch size to 1000 for 23.1.0, revisit in 23.1.1

re-default global max rpc batch size to 1k

---

besu/src/main/java/org/hyperledger/besu/cli/DefaultCommandValues.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcConfiguration.java

Prysm CL appears to request headers in batches of 1001 rather than 1k.  Bump default max batch size to 1024

bump max rpc batch size to 1024

---

.github/workflows/release.yml

Java 17 is required for building with Gradle, but is not available in the default images.

Update to Java 17

---

besu/src/main/java/org/hyperledger/besu/cli/DefaultCommandValues.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcConfiguration.java

#5108 was released in 23.1.0 (via release-23.1.x branch)

Cherry-pick of "bump max rpc batch size to 1024 #5108"

---

.github/workflows/dco.yml

argh dco does not support merge_group event - it's the same problem we had with merge to main https://github.com/hyperledger/besu/actions/runs/4400701640 

[GHA] no DCO on merge_group

---

.github/workflows/dco-merge-group.yml
.github/workflows/dco.yml

Add a separate yml file with the merge_group event trigger that doesn't invoke the PR based dco

[GHA] add separate dco yml for merge_group event

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java

Increase max log range to 5000 - was reduced to 1000 in #4597 

increased default to 5000

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractProtocolScheduleBuilder.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/TimestampScheduleBuilder.java

This PR removes getByBlockNumber from the ProtocolScheduleBuilder using the existing builders to fetch the original Spec for the blocks where the Dao/Classic fork will be inserted.
This PR has successfully generated the same ProtocolSchedules for Sepolia/Goerli and Mainnet. 
Samples:
- Sepolia
`2023-03-10 16:42:13.691+11:00 | main | INFO  | AbstractProtocolScheduleBuilder | Protocol schedule created with milestones: [London: 0, ParisFork: 1735371]
2023-03-10 16:42:13.695+11:00 | main | INFO  | AbstractProtocolScheduleBuilder | Protocol schedule created with milestones: [Shanghai: 1677557088]`
- Goerli
`2023-03-10 16:47:02.803+11:00 | main | INFO  | AbstractProtocolScheduleBuilder | Protocol schedule created with milestones: [Petersburg: 0, Istanbul: 1561651, Berlin: 4460644, London: …

Remove getByBlockNumber from dao classic specs

---

.github/pull_request_template.md
.github/workflows/pr-checklist-on-open.yml

This GHA will add the checklist that's currently in the PR template, as a comment, on newly opened PRs. 
Because it needs write access (to add the comment), it needs to run on the `pull_request_target` action, which means you won't see the outcome on _this_ PR, but only once it's merged in, you'll see it on subsequent PRs - example - https://github.com/daisy-row/vigilant-octo-umbrella/pull/51

[GHA] Checklist action

---

CHANGELOG.md
besu/src/test/java/org/hyperledger/besu/ForkIdsNetworkConfigTest.java
config/src/main/resources/mainnet.json

Schedule shanghaiTime for Mainnet and configure forkId for tests

---

.github/workflows/checks.yml
.github/workflows/codeql.yml

A few  github actions explicitly uses amd64 binary version of java.  needs to specify they can only run on X64:
- codeql
- spotless
- javadoc_17

use x86 for codeQL github action

---

besu/src/main/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilder.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/authentication/EngineAuthService.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/JsonRpcRequest.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetLogs.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncDownloader.java

* During startup print "Besu version ..." instead of just "Besu ..." to make searching for the version in the logs easier.
* eth_getLogs now prints request along with exception:
```
2023-03-20 12:42:17.918+10:00 | Test worker | DEBUG  | EthGetLogs | eth_getLogs request JsonRpcRequest{id=null, method='eth_getLogs', params=[FilterParameter{fromBlock=BlockParameter{type=NUMERIC, number=Optional[0]}, toBlock=BlockParameter{type=NUMERIC, number=Optional[50]}, fromAddress=[], toAddress=[], addresses=[], topics=[], maybeBlockHash=Optional.empty, logsQuery=LogsQuery{addresses=[], topics=[], after=Optional.empty, count=Optional.empty, isValid=true}], version='2.0', isNotification=true} failed
java.lang.IllegalArgumentException: Requested range exceeds maximum range limit
at …
```

Minor improvements to logging

---

.github/workflows/repolinter.yml

Docker actions that write to files during actions leave files in the repository owned by the docker user rather than the runner user.  This leaves the runner filesystem in a state that makes non-docker actions fail.

Cleanup after GHA docker user

---

.circleci/config.yml
CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/ZeroBaseFeeMarket.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/feemarket/ZeroBaseFeeMarketTest.java

This fixes an issue where on IBFT and QBFT invalid blocks are created by the proposer when using London with a zeroBaseFee.
The cause of this is that the ZeroBaseFeeMarket was returning true for the implementsDataFee check which meant that the excessDataGas field was added to the block header. This is only valid after Shanghai.
fixes #5270

Fix BFT creating invalid blocks on London when zero base fee is used

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockByNumber.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTest.java

While syncing, it is possible that we access the cached header's number before the block itself has had chance to be imported. In other words there is a mismatch between cached blockNumber and non-cached blockHeader that is being retrieved for the RPC.
Discovered after adding debug in https://github.com/hyperledger/besu/pull/5288
https://github.com/hyperledger/besu/issues/5281
Tested X_SNAP with each CL on sepolia as well as nimbus on goerli.
Without the fix: prysm, lighthouse and nimbus received the error (see https://github.com/hyperledger/besu/issues/5281#issuecomment-1491753557).
With the fix: no errors

Use cached header for latest eth_getBlockByNumber

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/execution/BaseJsonRpcProcessor.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockByNumber.java

I think this would impact all RPCs, except maybe engine API. I am interesting in eth_getBlockByNumber for debugging purposes.
Error looks like this:
```
Error processing method: eth_getBlockByNumber ["latest",false]
java.lang.NullPointerException: Cannot invoke \"org.hyperledger.besu.ethereum.core.BlockHeader.getHash()\" because \"headHeader\" is null
at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetBlockByNumber.latestResult(EthGetBlockByNumber.java:86)
at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.findResultByParamType(AbstractBlockParameterMethod.java:90)
at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.response(AbstractBlockParameterMethod.java:102)
at …
```

Log an error when RPC responds with INTERNAL_ERROR

---

.github/workflows/sonarcloud.yml

I would like to propose some blasphemy:
we should run the weekly sonarqube job with gradle --continue so it proceeds on, regardless of test failure.
this week a flaky test failed, and so we got no analysis.
the sonarqube job produces no artifacts of any use, it is meant as a weekly diagnostic, so while blasphemous, I believe this to be safe.

continue despite test failures

---

ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTest.java

Attempt to fix flaky getBlockByNumberForLatest test

---

.circleci/config.yml
acceptance-tests/tests/build.gradle

Gradle tasks for the acceptance tests were not running any Junit5 tests.
current mainnet tests: 61
with this change mainnet tests: 137
current non-mainnet tests: 271
with this change non-mainnet tests: 279
fixes #5299

Configure gradle AT tasks to run junit5 tests

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueSegmentIdentifier.java

Addresses database backwards compatibility broken by https://github.com/hyperledger/besu/commit/067a26337411833ad92d649f208255b1a7954268
Fixes `org.rocksdb.RocksDBException: Column families not opened:` error
See #5303

uncomment columns related to GoQuorum privacy

---

besu/src/test/java/org/hyperledger/besu/util/LocalPermissioningConfigurationValidatorTest.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/peers/EnodeURLImpl.java
ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/peers/EnodeURLImplTest.java

Improved error message when verifying enode syntax with xdns-enabled
https://github.com/hyperledger/besu/issues/2569

Improved error message when verifying enode syntax with xdns-enabled

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeCapabilities.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EnginePreparePayloadDebug.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/EnginePreparePayloadParameter.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/EnginePreparePayloadResult.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/ExecutionEngineJsonRpcMethods.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EnginePreparePayloadDebugTest.java

PR to enable debugging block proposals by re-adding an updated version of the deprecated 
`engine_preparePayload` endpoint
*be sure to use the current or a recent parent blockhash or you will DoS bonsai db*
All fields in the parameter are optional, including the parameter itself
example usage:
```
curl --location --request POST 'http://localhost:8551' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTkwNDEzMzZ9.4PDdSaG9hFOFR4Th7rEgaKKECsXfz6IPckFRcfSP13o' \
--data-raw '{
"jsonrpc":"2.0",
"method":"engine_preparePayload_debug",
"params":
[
{
"parentHash": "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
"feeRecipient": "0x0000000000000000000000000000000000000000",
"timestamp": "0x0", …
```

add engine_preparePayload_debug endpoint

---

CHANGELOG.md
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivCallAcceptanceTest.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivCall.java
ethereum/referencetests/build.gradle

priv_call was showing incorrect error -"invalid params" even when execution is reverted. PR fixes to show correct error - "REVERT_ERROR" and show correct revert reason data
https://github.com/hyperledger/besu/issues/5223

Show correct revert reason data in priv_call

---

ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/NodeSmartContractV2PermissioningController.java

Tries not pass `null` value to `List.of` on method `org.hyperledger.besu.ethereum.permissioning.NodeSmartContractV2PermissioningController.createPayload`
Sometimes method `enodeUrl.toURI().getHost()` returns `null`. In this case, we use `enodeUrl.getIpAsString()` to get IP address. And, if this method returns `null`, use empty String in `List.of`.
fixes #5370

Permissioning - Fix NullPointerException on createPayload (Issue #5370)

---

CHANGELOG.md
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/CallSmartContractFunction.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/contract/ContractTransactions.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/eth/EthCallTransaction.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/eth/EthEstimateGasTransaction.java
acceptance-tests/tests/contracts/TestDepth.sol
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthEstimateGasAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/RevertReasonAcceptanceTest.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGas.java

eth_estimateGas currently conservatively estimates gas this change will take that estimate and use it as a high bound and will use gasUsed as a lower bound to hone in on the most true gas limit required.
Outstanding Issues/questions
- The estimate comes back lower than geth, I suspect this is due to the protocol schedule being used in the acceptance tests.
- further optimise the binary search?
- ganache does a better job of getting an exact gas requirement with only a few runs https://github.com/trufflesuite/ganache-cli-archive/releases/tag/v6.4.2
fixes https://github.com/hyperledger/besu/issues/4244

Use binary search to eth_estimateGas more accurately

---

CHANGELOG.md
gradle.properties

update changelog
prep for next point release

prepare main for next point release

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java

I could happen that when restoring many transactions from disk, to have Vertx thread blocked exception, to avoid that is it safer to restore transactions serially than in parallel.

Restore transactions from disk searially to avoid blocking other threads

---

CHANGELOG.md
docker/openjdk-17-debug/Dockerfile
docker/openjdk-17/Dockerfile
ethereum/evmtool/src/main/docker/Dockerfile

Fix Besu failing to start when using Docker 23.4.0 due to `NoClassDefFoundError` for `org.xerial.snappy.Snappy`.
The cause was that we are using an older version of glibc for some Docker images due to the older version of the Ubuntu distro being used.
Changes
- Updated docker images to use Ubuntu 22.04 so that a newer version of glibc is used. This fixes an issue with snappy library where the library cannot be loaded.
- Included ca-certificates-java as a separate install to fix Java install issue on Ubuntu https://github.com/adoptium/installer/issues/105
Related to the update of the snappy library https://github.com/xerial/snappy-java/issues/417#issuecomment-1513916298
fixes #5463

Fix Docker image failing to start Besu with NoClassDefFoundError for org.xerial.snappy.Snappy

---

besu/src/main/java/org/hyperledger/besu/components/BesuCommandModule.java
besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java

fix cases where BesuCommand is constructed without a dagger context

handle cases where dagger besuComponent is null

---

plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactory.java
plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactoryTest.java

This PR skips creation of the database directory if it exists. While the call to `Files.createDirectories()` (which we use to initialise it if the DB needs creating) should be a no-op in this case, symlinks cause it to fail so the safer thing to do is confirm that the directory doesn't actually exist before making that call.
Fixed https://github.com/hyperledger/besu/issues/4043

Only create DB data dir if it doesn't already exist

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/trielog/AbstractTrieLogManager.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/worldview/BonsaiWorldStateUpdateAccumulator.java

Fixes a refactor omission.  TrieLogFactory was still statically constructed and used in accumulator.  This would lead to besu writing trie logs to its database with the default TrieLog serializer rather than one (potentially) configured via plugin.

Remove bonsai accumulator trielogfactory

---

ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/PeerDiscoveryController.java

encountered during testing.  Quick fix.
```
...
rocketpool_eth1  | 2023-05-24 23:45:06.677+00:00 | Timer-0 | INFO  | DNSResolver | Resolved 2409 nodes
rocketpool_eth1  | 2023-05-24 23:45:34.417+00:00 | vert.x-eventloop-thread-3 | ERROR | ContextBase | Unhandled exception
rocketpool_eth1  | java.lang.NullPointerException: Cannot invoke "java.util.Map.remove(java.lang.Object)" because "peerInteractionStateMap" is null
rocketpool_eth1  |      at org.hyperledger.besu.ethereum.p2p.discovery.internal.PeerDiscoveryController$PeerInteractionState.execute(PeerDiscoveryController.java:802)
rocketpool_eth1  |      at org.hyperledger.besu.ethereum.p2p.discovery.internal.PeerDiscoveryController$PeerInteractionState.lambda$execute$0(PeerDiscoveryController.java:797)
rocketpool_eth1  |      at …
```

NPE in peer discovery disconnect

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java

Change the peer disconnect message to debug level. Since that's not useful to end users.

Change disconnect peer message to debug level.

---

build.gradle

Debugging for https://github.com/hyperledger/besu/issues/5521
Print out commands being executed
Separate out docker push and docker manifest push commands for release to make it easier to spot which one fails in #5521

Make docker commands easier to debug during upload and manifest creation

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/ExecutionEngineJsonRpcMethod.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/KeyValueStorage.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/OptimisticRocksDBColumnarKeyValueStorage.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueSnapshot.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBSnapshotTransaction.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/TransactionDBRocksDBColumnarKeyValueStorage.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/unsegmented/RocksDBKeyValueStorage.java
services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/InMemoryKeyValueStorage.java
services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/LayeredKeyValueStorage.java
services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/LimitedInMemoryKeyValueStorage.java
services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/SegmentedKeyValueStorage.java
services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/SegmentedKeyValueStorageAdapter.java
services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/SegmentedKeyValueStorageTransactionTransitionValidatorDecorator.java

gate transaction access on whether the underlying storage has closed.  This prevents segfaults at shutdown when we close rocksdb, but there are async processes attempting to access the db.
Currently evaluating to ensure there is no noticeable performance regression.
#5362

Prevent rocksdb segfaults when accessing closed storage

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java

This results in a port conflict check however the push metrics port refers to a push gateway for besu to connect to rather than a port it is serving itself.
If you run besu with push metrics [following this guide](https://besu.hyperledger.org/en/stable/public-networks/how-to/monitor/metrics/#run-prometheus-with-besu-in-push-mode) then the bug fixed by this PR is that you have to run besu first, followed by the push gateway.
Now you can start either besu or push gateway in any order.

Remove push metrics port from effective ports

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockHeaderValidator.java

Remove the Attached PoW rule used for the merge, as we are well past merge and this attached version of the PoW rule is causing unnecessary Ethash during chain sync:
relates to #5539

remove PoW header validation if merge is enabled

---

consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionProtocolSchedule.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadV3.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineGetPayloadTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/DefaultProtocolSchedule.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSchedule.java
ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/NoRewardProtocolScheduleWrapper.java

Make the return of hardforkfor optional.
For the EngineGetPayloadV3, when Shanghai and Cancun had the same milestone, an exception was 
```
java.lang.IllegalStateException: No hardfork found for predicate org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineGetPayloadV3$$Lambda$840/0x00000008010a4838@237b2852
at org.hyperledger.besu.ethereum.mainnet.DefaultProtocolSchedule.lambda$hardforkFor$4(DefaultProtocolSchedule.java:132)
at java.base/java.util.Optional.orElseThrow(Optional.java:403)
at org.hyperledger.besu.ethereum.mainnet.DefaultProtocolSchedule.hardforkFor(DefaultProtocolSchedule.java:131)
at org.hyperledger.besu.consensus.merge.TransitionProtocolSchedule.lambda$hardforkFor$3(TransitionProtocolSchedule.java:210)
at …
```

Make the return of hardforkfor optional

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/TransactionAdapter.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetMinerDataByBlockHash.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionReceipt.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/TransactionReceiptResult.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthJsonRpcMethods.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionReceiptWithMetadata.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionReceiptTest.java
ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestGetLogHash.java

[4844] Add dataGasUsed and dataGasPrice to receipts for 4844 txs
#5489

[4844] Add dataGasUsed and dataGasPrice to receipts for 4844 txs

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/blobs/VersionedHash.java

Add toString to VersionedHash and set it to be the JsonValue of the VersionedHash object
Actual: 
```
{
...
blobVersionedHashes: [{
versionId: 1
}, {
versionId: 1
}, {
versionId: 1
}, {
versionId: 1
}, {
versionId: 1
}, {
versionId: 1
}],
...
}
```
Expected:
```
{
...
blobVersionedHashes: ["0x01a8a4a49dcd1b91c376c87d7d6a6e73ee3792205864bf61781e8e3ad19d0092", 
"0x01069693395fb9a698b257e6c25380f32393bc0cf17a290f9e7fcea3c4ae7b8b", 
"0x01111dafbfcc0caa0803fc22f697fd3b9171252504e14ec0443f04a2b3288715", 
"0x01d1dfff9c15b3201980d8f9b958a8ade73e3e1e0ca76c54785a33e09519be7a", 
"0x01a7b4b55dd68d59685abcd629708c5de44c8e9edf3671602538eba23375893c", 
"0x013586020d67ab6808e681c2e6a2d1e854c84e5bc49df2ed34e218eace844f8b"],
...
}
```

[4844] Add toString to VersionedHash

---

enclave/build.gradle
gradle/check-licenses.gradle
metrics/core/build.gradle
plugins/rocksdb/build.gradle
plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/OptimisticTransactionDBRocksDBColumnarKeyValueStorageTest.java
plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorageTest.java
plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBKeyValueStorageTest.java
plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/TransactionDBRocksDBColumnarKeyValueStorageTest.java
services/kvstore/build.gradle
services/kvstore/src/test/java/org/hyperledger/besu/services/kvstore/LimitedInMemoryKeyValueStorageTest.java
services/pipeline/build.gradle
services/pipeline/src/test/java/org/hyperledger/besu/services/pipeline/AsyncOperationProcessorTest.java
services/pipeline/src/test/java/org/hyperledger/besu/services/pipeline/BatchingReadPipeTest.java
services/pipeline/src/test/java/org/hyperledger/besu/services/pipeline/CompleterStageTest.java
services/pipeline/src/test/java/org/hyperledger/besu/services/pipeline/FlatMapProcessorTest.java
services/pipeline/src/test/java/org/hyperledger/besu/services/pipeline/IteratorSourceStageTest.java
services/pipeline/src/test/java/org/hyperledger/besu/services/pipeline/MapProcessorTest.java
services/pipeline/src/test/java/org/hyperledger/besu/services/pipeline/PipeTest.java
services/pipeline/src/test/java/org/hyperledger/besu/services/pipeline/PipelineBuilderTest.java
services/pipeline/src/test/java/org/hyperledger/besu/services/pipeline/ProcessingStageTest.java
services/pipeline/src/test/java/org/hyperledger/besu/services/pipeline/SharedWritePipeTest.java
services/tasks/build.gradle
services/tasks/src/test/java/org/hyperledger/besu/services/tasks/AbstractTaskQueueTest.java
services/tasks/src/test/java/org/hyperledger/besu/services/tasks/CachingTaskCollectionTest.java
services/tasks/src/test/java/org/hyperledger/besu/services/tasks/InMemoryTasksPriorityQueuesTest.java
testutil/build.gradle
testutil/src/main/java/org/hyperledger/besu/kvstore/AbstractKeyValueStorageTest.java

fixes #5558 
fixes #5557
Also pulled in some plugins tests, that extended testutil AbstractKeyValueStorageTest

services - migrate to junit 5

---

config/build.gradle
config/src/test/java/org/hyperledger/besu/config/BFTForkTest.java
config/src/test/java/org/hyperledger/besu/config/CliqueConfigOptionsTest.java
config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
config/src/test/java/org/hyperledger/besu/config/GenesisConfigOptionsTest.java
config/src/test/java/org/hyperledger/besu/config/JsonBftConfigOptionsTest.java
config/src/test/java/org/hyperledger/besu/config/JsonGenesisConfigOptionsTest.java
config/src/test/java/org/hyperledger/besu/config/JsonQbftConfigOptionsTest.java
config/src/test/java/org/hyperledger/besu/config/JsonUtilTest.java

[MINOR] config module - junit5

---

evm/src/main/java/org/hyperledger/besu/evm/frame/Memory.java
evm/src/main/java/org/hyperledger/besu/evm/frame/MessageFrame.java
evm/src/main/java/org/hyperledger/besu/evm/operation/MCopyOperation.java

wire in deep call to System.arrayCopy instead of buffer copy.

Faster MCOPY implementation

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugGetRawTransaction.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/DebugJsonRpcMethods.java

Add the new debug_getRawTransaction to the DEBUG engine
Part of #5377

Add debug_getRawTransaction

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueStoragePrefixedKeyBlockchainStorage.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueStoragePrefixedKeyBlockchainStorageTest.java

#5471 is backward incompatible, and there is a procedure to do before downgrading, but if the procedure is not followed the db becomes inconsistent, to avoid that this PR tries to detect this scenario and fail fast in case it founds a previous migration, giving the user a possibility to retry the rollback procedure.
If an inconsistency is found this log is printed
```
2023-06-23 16:06:21.885+00:00 | main | ERROR | KeyValueStoragePrefixedKeyBlockchainStorage | Inconsistency found when migrating chainHeadHash to variables storage, probably this is due to a downgrade done without running the `storage revert-variables` subcommand first, see https://github.com/hyperledger/besu/pull/5471
chainHeadHash mismatch: blockchain storage value=0x25a5cc106eea7138acab33231d7160d69cb777ee0c2c553fcddf513899 …
```

Fail fast in case of downgrade done without reverting variables storage

---

ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/B11rSubCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nSubCommand.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestProtocolSchedules.java
evm/src/main/java/org/hyperledger/besu/evm/EvmSpecVersion.java
evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java

Updates needed to keep executing execution-spec-tests
* add withdrawals support
* add access lists to transactions
* accept t8n and b11r CLI args that are zero length or all whitespace
* Enumerate forks in t8n and b11r help
* remove JSON wrapping from t8n transaction RLP

Updates for execution-spec-tests

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetPrecompiledContractRegistries.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java
evm/src/main/java/org/hyperledger/besu/evm/fluent/EVMExecutor.java
evm/src/main/java/org/hyperledger/besu/evm/precompile/MainnetPrecompiledContracts.java

BLS12 signatures were speculatively added in cancun in late 2022.  This is no longer accurate.  Move the implementation to the "Future_EIPs" fork so that it will remain testable and not accidentally get included accidentally.  Also add missing fluent APIs.

Remove BLS12 from cancun

---

evm/src/main/java/org/hyperledger/besu/evm/gascalculator/CancunGasCalculator.java
evm/src/test/java/org/hyperledger/besu/evm/gascalculator/CancunGasCalculatorTest.java

Fixing the formula according to `calc_excess_data_gas` in https://eips.ethereum.org/EIPS/eip-4844

[4844] CancunGasCalculator ->  Fix Excess Data Gas Calculation

---

CHANGELOG.md
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/encoding/TransactionAnnouncementDecoder.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/encoding/TransactionAnnouncementEncoder.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/NewPooledTransactionHashesMessageProcessorTest.java
ethereum/rlp/src/main/java/org/hyperledger/besu/ethereum/rlp/AbstractRLPInput.java
ethereum/rlp/src/main/java/org/hyperledger/besu/ethereum/rlp/RLPInput.java
ethereum/rlp/src/test/java/org/hyperledger/besu/ethereum/rlp/BytesValueRLPInputTest.java
ethereum/rlp/src/test/java/org/hyperledger/besu/ethereum/rlp/BytesValueRLPOutputTest.java

Align Besu to what other clients are doing, treating the sizes as an array of scalar ints and not 4 bytes, this also prevent being disconnected from Geth due to `invalid-message` error:
```
DEBUG[06-19|15:15:40.347] Ethereum peer connected                  id=a1697db12e1f2986 conn=inbound name=besu/v23.4.0/linux-x...
DEBUG[06-19|15:15:40.360] Message handling failed in `eth`         id=a1697db12e1f2986 conn=inbound err="invalid message: message msg #8 (157028 bytes): invalid message: (code 8) (size 157028) rlp: non-canonical integer (leading zero bytes) for uint32, decoding into (eth.NewPooledTransactionHashesPacket68).Sizes[0]"
DEBUG[06-19|15:15:40.360] Removing p2p peer                        peercount=10 id=a1697db12e1f2986 duration=12.956ms     req=false err="invalid message: message …
```

Eth/68: treat transaction size as scalar unsigned int

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/Runner.java
besu/src/test/java/org/hyperledger/besu/RunnerBuilderTest.java
ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/frontier/EthGetFilterChangesIntegrationTest.java
ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/london/EthGetFilterChangesIntegrationTest.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcErrorConverter.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionInvalidReason.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/DisabledPendingTransactions.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/NewPooledTransactionHashesMessageHandler.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionAddedResult.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionBroadcaster.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolEvictionService.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactory.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionsMessageHandler.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/AbstractTransactionPoolTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/AbstractTransactionsLayeredPendingTransactionsTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionBroadcasterTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactoryTest.java

This PR review the way the txpool is enabled/disabled in a more intuitive way and also[ fix a bug ](https://github.com/hyperledger/besu/issues/5636)that happens when enabling the layered txpool when not synced.
The main point of disabling the txpool, is to avoid its overhead during the initial sync (or resync) phases, since pending transactions are always evaluated and processed against the current head, so if we are syncing there is no value in processing them, and we can wait until the sync is done to enabled the txpool.
The current implementation is a bit convoluted, since the txpool is always enabled at startup, but if the initial sync is not done, then the txpool is disabled, to be re-enabled after the sync is done, while it is straightforward to just start with the txpool disabled, …

Start with txpool disabled

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockHeaderValidator.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/DataGasValidationRule.java
ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/BlockHeaderTestFixture.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/DataGasValidationRuleTest.java
evm/src/main/java/org/hyperledger/besu/evm/gascalculator/CancunGasCalculator.java
evm/src/test/java/org/hyperledger/besu/evm/gascalculator/CancunGasCalculatorTest.java

Add dataGasExcess header validation according to https://eips.ethereum.org/EIPS/eip-4844
>     # check that the excess data gas was updated correctly
>     assert block.header.excess_data_gas == calc_excess_data_gas(block.parent.header)

[4844] Add Data Gas Excess Validation to the Header Validations

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractGetHeadersFromPeerTask.java

We only need to update the peers chain state with the highest block header, which is the first or the last block in the list. Currently we are trying to update with every block header, which can be 200 or so.

Only update peer with the first and last block

---

build.gradle

We need to replace previous release's latest tag. Might be broken due to a recent change in the docker command implementation

Add --amend to docker manifest create to fix docker latest tag

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java

Check the params earlier and move blob validation to a new method
In case CL sends a payload with invalid blob params for a known header, we should return invalid.
Expected Behaviour: return invalid
Actual Behaviour: Returns are valid because we have already seen that payload.
This PR moves the validation earlier in the flow and encapsulates the validation login into a method for readability.

[4844] Check params earlier and move blob validation to a new method

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilder.java
besu/src/test/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilderTest.java
config/src/main/java/org/hyperledger/besu/config/BftConfigOptions.java
config/src/main/java/org/hyperledger/besu/config/CliqueConfigOptions.java

Unrelated: clarify epoch length in javadoc

Add Xlayered-tx-pool to the config log printout

---

CHANGELOG.md
evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCreateOperation.java
evm/src/test/java/org/hyperledger/besu/evm/operation/AbstractCreateOperationTest.java

Add hooks for a successful contract create, a failed contract create, and an invalid contact create. Users of the library will be able to customize create responses without having to replace core logic.

Add hooks to AbstractCreateOperation for library users

---

ethereum/evmtool/build.gradle
ethereum/evmtool/src/main/graal/reflection-config.json
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nExecutor.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nServerSubCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nSubCommand.java
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/t8n/berlin-calculate-difficulty.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/t8n/berlin-example-yul.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/t8n/cancun-blobs-per-tx.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/t8n/istanbul-cumulative-gas.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/t8n/london-env-no-basefee.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/t8n/shanghai-blockhash.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/t8n/shanghai-init-code.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/t8n/shanghai-withdrawals-no-nonce.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/t8n/shanghai-withdrawals-overflow.json
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestEnv.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestProtocolSchedules.java

Update t8n tool to support new fields (data gas related) for Cancun in the execution-spec-tests,
also, refactor so the t8n server benefits from the changes.

Test updates for cancun execution-spec-tests

---

config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/GenesisState.java

Fix from @spencer-tb 
https://github.com/hyperledger/besu/pull/5664#issuecomment-1620559037
> We recently added the hive pyspec simulator to https://hivecancun.ethdevops.io/, which runs the tests from https://github.com/ethereum/execution-spec-tests using the EngineAPI
> 
> In order to start running the tests the genesis state needs to include the `excessDataGas` and `dataGasUsed`, otherwise we get a genesis mismatch -> leading to a `SYNCING` status when adding the first block with `NewPayloadV3` via the EngineAPI, as opposed to a `VALID` or expected `INVALID` status.
> We recently added the hive pyspec simulator to https://hivecancun.ethdevops.io/, which runs the tests from https://github.com/ethereum/execution-spec-tests using the EngineAPI
> 
> In order to start running the tests the …

[4844] [Hive] Fix for genesis mismatch

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV1.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV2.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV3.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV2Test.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV3Test.java

Add excessDataGas and dataGasUsed validation to EngineNewPayloadV3

[4844] Add excessDataGas and dataGasUsed validation to EngineNewPayloadV3

---

evm/src/main/java/org/hyperledger/besu/evm/precompile/KZGPointEvalPrecompiledContract.java

- Use PrecompileContractResult methods to halt and succeed;
- Do not return Bytes.Empty

[4844] KZGPointEvalPrecompiled - Use PrecompileContractResult methods to halt and succeed

---

ethereum/ethstats/build.gradle
ethereum/ethstats/src/test/java/org/hyperledger/besu/ethstats/EthStatsServiceTest.java
ethereum/ethstats/src/test/java/org/hyperledger/besu/ethstats/util/EthStatsConnectOptionsTest.java
ethereum/ethstats/src/test/java/org/hyperledger/besu/ethstats/util/PrimusHeartBeatsHelperTest.java
ethereum/evmtool/build.gradle
ethereum/evmtool/src/test/java/org/hyperledger/besu/evmtool/CodeValidationSubCommandTest.java
ethereum/evmtool/src/test/java/org/hyperledger/besu/evmtool/StateTestSubCommandTest.java
ethereum/mock-p2p/build.gradle
ethereum/mock-p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/testing/MockNetworkTest.java

This PR removes junit4 dependency from ethereum/ethstats, ethereum/evmtool, ethereum/mock-p2p files
Split part 5 PR from https://github.com/hyperledger/besu/pull/5678 
https://github.com/hyperledger/besu/issues/5564

ethereum/part5 - migrated tests from Junit4 to Junit5

---

ethereum/permissioning/build.gradle
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/AccountLocalConfigPermissioningControllerTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/AllowlistPersistorTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/LocalPermissioningConfigurationBuilderTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/LocalPermissioningConfigurationTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/NodeLocalConfigPermissioningControllerTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/NodeSmartContractPermissioningControllerTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/NodeSmartContractV2PermissioningControllerTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/TransactionSmartContractPermissioningControllerTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningControllerFactoryTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningControllerTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/node/InsufficientPeersPermissioningProviderTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/node/NodePermissioningControllerFactoryTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/node/NodePermissioningControllerTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/node/PeerPermissionsAdapterTest.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/node/provider/SyncStatusNodePermissioningProviderTest.java

This PR removes junit4 dependency from ethereum/permissioning files
Split part 7 PR from https://github.com/hyperledger/besu/pull/5678
https://github.com/hyperledger/besu/issues/5564

ethereum/permissioning - migrated tests from Junit4 to Junit5

---

CHANGELOG.md
acceptance-tests/tests/src/test/resources/permissioning/simple_permissioning_genesis.json
acceptance-tests/tests/src/test/resources/permissioning/simple_permissioning_ibft_genesis.json
acceptance-tests/tests/src/test/resources/permissioning/simple_permissioning_v2_genesis.json
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java

Override the transactionSimulator's default TransactionValidationParams with one that allows for exceeding the account balance (which effectively zeros the baseFee). This mimics the way that eth_estimateGas and eth_call are implemented. Similar change to #5277
Update ATs to use londonBlock (existing genesis allocs necessitate zeroBaseFee as well)

Make smart contract permissioning features work with london fork

---

ethereum/referencetests/build.gradle
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/BlockchainReferenceTestCaseSpec.java

Update Reference Tests to 12.3
* fix decoding error
* add ignored field
* update module

Reference tests 12.3

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockTransactionSelector.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockTransactionSelectorTest.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/LondonFeeMarketBlockTransactionSelectorTest.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java

Apart from some little code cleanup, the main goal of this PR is to add, to the result of a block transaction selection, all the evaluated but the not selected transactions, with the reason they were not selected, this will potentially give more data during block creation, that could try different strategies to include some of the invalid transient transactions.

Return all not selected transactions, not only invalid ones

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/TransactionEncoder.java
ethereum/p2p/build.gradle

Address a performance regression observed in import testing -
* ensure we are on a single tuweni version
* factor out an unneeded concatenate

Address import performance issues

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommand.java

The "code" mode of the EVMTool did not support the side effects of a contract create. Expose the TransactionProcessor method that handles that switching.

EVMTool contract create processing

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/EngineGetPayloadResultV3.java

simply default to false for now. 
This should fix some failing hive tests.
fixes #5739

fix: added shouldOverrideBuilder field to engine_getPayloadV3 response

---

ethereum/referencetests/build.gradle

#5774 broken builds on Windows due to the different separation char, this PR just replace the '/' with the system separator char as provided by the jvm

Make referencetests build script Windows friendly

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java

EngineNewPayload should not return the  latestValidHash when blockHash validation fails:
Current:
{status: INVALID_BLOCK_HASH, latestValidHash: `latestValidHash`, validationError: errorMessage | null} if the blockHash validation has failed
Expected:
{status: INVALID_BLOCK_HASH, latestValidHash: `null`, validationError: errorMessage | null} if the blockHash validation has failed

EngineNewPayload -  Fix Invalid Block Hash return

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockHeaderValidator.java

Geth has removed this check (block too far in the future) since the merge. Fixes #5800 - and 9 related hive tests that start with `cancun/eip4788_beacon_root/beacon_root_contract/`

don't check block timestamp drift for PoS

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/forkid/ForkIdManager.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/forkid/ForkIdTest.java

Make sure that we are passing the fork id check if there are no forks and the genesis timestamp is not 0

fix ForkId if there are no Forks and the starting timestamp is not 0

---

datatypes/src/main/java/org/hyperledger/besu/datatypes/BlobsWithCommitments.java
datatypes/src/test/java/org/hyperledger/besu/datatypes/BlobsWithCommitmentsTest.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/TransactionBuilderTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/RespondingEthPeer.java

make sure that a blob transaction has at least one blob.

enforce that BlobTransactions have at least one blob

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/StorageSubCommand.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/OptimisticRocksDBColumnarKeyValueStorage.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/TransactionDBRocksDBColumnarKeyValueStorage.java
plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorageTest.java

The `revert storage-variables` subcommand correctly reverts the storage-variable column family move, but inadvertently creates ignorable column family segments.  This behavior breaks backward compatibility prior to 23.1.0.  
This PR exposes `setIgnorableStorageSegments()` from BesuCommand and calls it from the revert storage-variables subcommand.
Additionally, this PR adds much needed visibility into the column family errors that RocksDB reports by parsing the RocksDBException and translating them into printable strings for more useful/actionable error messages.
example output for unidentified column family:
```
RocksDBException: Unhandled column families: ['Donny'(0x446f6e6e79), 'Walter'(0x57616c746572), 'Maude'(0x4d61756465), 'Dude'(0x44756465)]
```
fixes #5808

Do not create ignorable segments on `revert storage-variables`

---

consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/PayloadIdentifier.java
consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/PayloadIdentifierTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdatedTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineGetPayloadTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadV3Test.java

This fixes a problem where two engine_forkchoiceUpdated RPC calls with the same parameters, except for the parentBeaconBlockRoot, caused besu to produce a block with the wrong block hash.
The beacon root was not used in the calculation of the payload id, which meant that we were not updating the block production after the second call.

add parent beacon block root to payload id calculation

---

datatypes/src/main/java/org/hyperledger/besu/datatypes/Address.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ParentBeaconBlockRootHelper.java

In EIP-4788 the address of the contract used to store and retrieve the parent beacon block roots has been changed. This PR sets the correct value.

set the beacon root address to the correct value

---

ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/EthStatsService.java

Filter peer collection by those ready for connection.

display only peers ready for requets on ethstats

---

besu/src/main/java/org/hyperledger/besu/cli/util/TomlConfigFileDefaultProvider.java

Fix for a regression introduced by #5772 that causes the following exception when the option `tx-pool-limit-by-account-percentage` is defined as a number in the configuration file
```
TomlInvalidTypeException: Value of 'tx-pool-limit-by-account-percentage' is a float while processing argument at or before arg[0] '--config-file=./config.toml' in [--config-file=./config.toml]: org.apache.tuweni.toml.TomlInvalidTypeException: Value of 'tx-pool-limit-by-account-percentage' is a float
```
the fix is to simply convert percentage options to string when parsing the file

Fix: correctly convert percentage options in TOML configuration file

---

ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockByNumberTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/BlockParameterTest.java

Just an additional test to prove that hex and binary are both supported at this level

[MINOR] Block number param additional test

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ParentBeaconBlockRootHelper.java

Beacon root address has changed again - this PR is still draft so need to keep an eye on it leading up to devnet 9
https://github.com/ethereum/EIPs/pull/7672/files

[4788] update beacon root address to latest - post audit tweaks

---

ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/AbstractHandshakeHandler.java

The geth cmd 
./build/bin/devp2p rlpx ping enodeAddress
expects the client with address enodeAddress to respond with a HelloMessage right after successfully receiving the handshake message from the initiator.
Existing behaviour in Besu is to wait for the HelloMessage from the initiator before sending the HelloMessage back.

fix geth rlpx ping command

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ParentBeaconBlockRootHelper.java

Fix null latest valid hash when validation blobs/expected hashes
Fix HISTORICAL_ROOTS_MODULUS used by hive/devnet 9

[4844] Fix some Devnet9 Hive tests

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineGetPayload.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV3.java

Fix some hive tests
- Return JsonRpcErrorResponse instead of JsonRpcSuccessResponse when fork not supported or parameters invalid.
- Validate parameter before fork validation
- Validate getParentBeaconBlockRoot on EngineForkchoiceUpdatedV3

[4844] [Hive] Fix fcuV3 parameter return 

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV2.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdatedTest.java

re-arranges validations so the failures occurr when hive expects them to.

Forkchoice v2 hive tests

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV2.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdatedTest.java

Fixes more Hive tests when a payload that is invalid is passed along with an FCU

Apply fcu even on invalid payload

---

datatypes/src/main/java/org/hyperledger/besu/datatypes/Transaction.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java

Exposes getSize to transaction interface so it can be used by plugins

[MINOR] Expose getSize to transaction interface

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/AllAcceptingTransactionSelector.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockTransactionSelectorTest.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/txselection/TransactionSelectorFactory.java

Revert plugin interface to return an object instead of a list

[Plugin API] - Simplify plugin transaction selector interface to return object instead of list

---

ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommand.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
evm/src/main/java/org/hyperledger/besu/evm/frame/Memory.java
evm/src/main/java/org/hyperledger/besu/evm/internal/Words.java
evm/src/main/java/org/hyperledger/besu/evm/precompile/AltBN128MulPrecompiledContract.java
evm/src/main/java/org/hyperledger/besu/evm/precompile/AltBN128PairingPrecompiledContract.java
evm/src/main/java/org/hyperledger/besu/evm/precompile/BLAKE2BFPrecompileContract.java
evm/src/main/java/org/hyperledger/besu/evm/precompile/BigIntegerModularExponentiationPrecompiledContract.java
evm/src/main/java/org/hyperledger/besu/evm/precompile/KZGPointEvalPrecompiledContract.java
evm/src/test/java/org/hyperledger/besu/evm/toy/EvmToyCommand.java

Change array copying by re-using arrays when safe.

Change Array Copying

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockTransactionSelectorTest.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/txselection/TransactionSelector.java

Notify plugins when a transaction is selected/rejected

[Plugin API] - TransactionSelector - Notify plugins when transaction is selected/rejected

---

CHANGELOG.md

Read the rendered version [here](https://github.com/fab-10/besu/blob/release-23.10.x/CHANGELOG.md#layered-transaction-pool-the-new-default-transaction-pool-implementation)

Describe the migration to and how to configure the layered txpool

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthFeeHistory.java

This PR has a minor optimization on Eth_feeHistory, on top of [this other optimization on Eth_feeHistory ](https://github.com/hyperledger/besu/pull/6011).
Instead of sorting rewardPercentiles for each block header, this PR sorts only once and the sorted list is used as a parameter for each call to compute rewards.

Minor optimization on Eth_feeHistory

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV1.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV2.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV3.java

re-orders the validity checking and priority on forkchoice updated calls.
- payloadAttributes needs to be validated apart from new head validity, so there are now two steps for checking so that we can fail differently if the head being built on is missing or irrelevant to the building payload.

Fcu v2 defer fork validation

---

build.gradle
consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV1.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV2.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV3.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV3.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/UnsignedLongParameter.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockHeaderBuilder.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ParentBeaconBlockRootHelper.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ScheduledProtocolSpec.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/IncrementalTimestampRule.java

Merge after pr #6037 , was built on top of that.
the pyspec simulator in Hive likes to check fields for max capacities, which showed us a lot of places where using signed longs is a problem. This pr fixes many of them.
broader adoption of CheckerFramework is suggested at a later time, so that we can see where else we are affected by this.

Unsigned timestamps and blob gas used

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilder.java
besu/src/main/java/org/hyperledger/besu/cli/util/CommandLineUtils.java
besu/src/main/java/org/hyperledger/besu/services/BesuPluginContextImpl.java
besu/src/main/java/org/hyperledger/besu/services/RpcEndpointServiceImpl.java

* log plugins summary at info (part of config overview)
* include affected CLI option when there's a compatibility issue found by `failIfOptionDoesntMeetRequirement`

[MINOR] ux improvements

---

CHANGELOG.md
gradle.properties

Fix changelog - Add issue numbers

Update changelog release

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateProvider.java
ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/InMemoryKeyValueStorageProvider.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/BlockImportExceptionHandlingTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/LogRollingTests.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/RollingImport.java

Was only used for supporting test code and can instead reuse static factory from InMemoryKeyValueStorageProvider

[MINOR] Remove a BonsaiWorldStateProvider constructor

---

CHANGELOG.md
besu/src/test/java/org/hyperledger/besu/ForkIdsNetworkConfigTest.java
config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
config/src/main/resources/mordor.json
config/src/test/resources/all_forks.json
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminNodeInfoTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecFactory.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java

This PR adds support to [ECIP-1109](https://ecips.ethereumclassic.org/ECIPs/ecip-1109).
Block number is set to https://github.com/ethereumclassic/ECIPs/pull/514, already set in core-geth in https://github.com/etclabscore/core-geth/pull/571
I also set the DNS discovery tree to what's in [core-geth#bootnodes_mordor.go](https://github.com/etclabscore/core-geth/blob/v1.12.14/params/bootnodes_mordor.go#L29)

ETC 'Spiral' network upgrade

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/services/TraceServiceImpl.java
besu/src/test/java/org/hyperledger/besu/services/TraceServiceImplTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/data/BlockTraceResult.java
plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionTraceResult.java
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/TraceService.java

* The TraceService returns the result of the processed transactions
* In case of an internal error during tx processing, the stack trace is added to the error message as well.
fixes #6077

TraceService: return results for transactions in block

---

CHANGELOG.md
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestEnv.java

Fix tpyo that resulted in an NPE in t8n blob gas calculations.

Correct reference test blobgas calculation

---

gradle/verification-metadata.xml

Makes Idea happy again as documented here https://docs.gradle.org/6.8.3/userguide/dependency_verification.html#sec:skipping-javadocs

Restore javadoc and sources jar as trusted artifacts

---

CHANGELOG.md

[MINOR] - Add 23.10.1 correct changelog

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockHeader.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockHeaderBuilder.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/ProcessableBlockHeader.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/SealableBlockHeader.java
ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/NonBesuBlockHeader.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestEnv.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/data/BlockHeader.java
plugin-api/src/main/java/org/hyperledger/besu/plugin/data/ProcessableBlockHeader.java

This removes a few fields that don't make sense and that are not used in the existing core/ProcessableBlockHeader class. 
This introduces a interface ProcessableBlockHeader in the plugin module.

clean up the ProcessableBlockHeader

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java

Change `CHAIN_HEAD_NOT_AVAILABLE` to a warning, not a trace log entry
Fixes #6126

Log missing chain head as warning, not trace

---

ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionByHashTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/BlobPooledTransactionDecoder.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/encoding/TransactionRLPDecoderTest.java
ethereum/evmtool/src/test/java/org/hyperledger/besu/evmtool/StateTestSubCommandTest.java
ethereum/rlp/src/main/java/org/hyperledger/besu/ethereum/rlp/AbstractRLPInput.java

Fix the flakiness in EthGetTransactionByHashTest as well as some other sonar identified cleanup.

fix yParity flakey test

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/TimestampBoundedByFutureParameter.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputation.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractGetHeadersFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractPeerRequestTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractRetryingSwitchingPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetHeadersFromPeerByHashTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetHeadersFromPeerByNumberTask.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/DiscoveryProtocolLogger.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/AbstractPeerConnection.java

* only include peer id in the peer.toString() method (remove from peerConnection)
* only log enode not id also
fixes #6169

[MINOR] Eth peer toString() improvements

---

acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/OpenTelemetryAcceptanceTest.java

this particular test is flaky. There are other tests for the same class that work more reliably. 
Example of flaky fail -
https://app.circleci.com/pipelines/github/hyperledger/besu/25195/workflows/a5a40b6e-0f1d-4ac3-87e6-108bcce92b9e/jobs/164640

comment out flaky part of acceptance test

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputation.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputationTest.java

Noticed in peering logs we are disconnecting quite useful peers with timeouts and "useless responses". This exacerbates peering issues because we are quite early to disconnect, whereas if we just wait a bit longer the peer can still be useful. More of an issue in low peer count networks. 
* consider peer reputation score when deciding whether to disconnect peer for repeated timeouts/useless responses
* increase threshold for timeout counts
* decrease score points deducted for timeout/useless response
```
➜  besu grep  "Disconnect - Outbound" besu03.log
2023-11-17 17:47:27.730+10:00 | nioEventLoopGroup-3-5 | DEBUG | EthProtocolManager | Disconnect - Outbound - 0x0b TIMEOUT - 0x45d5... - 5 peers left
2023-11-17 17:49:10.232+10:00 | nioEventLoopGroup-3-1 | DEBUG | EthProtocolManager | …
```

consider peer reputation score when deciding to disconnect

---

CHANGELOG.md
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/TransactionSelectionResults.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/PriceTransactionSelector.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockTransactionSelectorTest.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java

With this PR a transaction selection plugin can extend TransactionSelectionResult to implement its custom return values.
Plus a couple of log fixes.

Allow a transaction selection plugin to specify custom selection results

---

CHANGELOG.md
ethereum/evmtool/build.gradle

If Gradle property `dockerArtifactName` is specified, then both Besu and `evmtool` Docker images will use it has name, resulting in one overriding the other. 
The fix in this PR is to always add the `-evmtool` suffix to the `evmtool` Docker image

Fix Docker image name clash between Besu and evmtool

---

CHANGELOG.md
docker/openjdk-latest/Dockerfile

Switched base image to `ubuntu:rolling`, that follow any stable Ubuntu release, currently 23.10) since OpenJDK Java 21 is not available on latest LTS Ubuntu.

Update OpenJDK latest Docker image to use Java 21

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/LogAdapter.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/TransactionAdapter.java

Returns an empty `Account` with only the `address` field in the `from` and `to` fields for a 'Transaction` instead of an error in a GraphQL request even if the world state is not retrievable.
In addition an empty `Account` is also returned in the `logger` field.
Sample input:
```
query {
block (number:10207858) {
transactions {
hash
from { address balance }
to { address balance }
logs {
account { address transactionCount }
}
}
}
}
```
Sample output:
```
{
"data" : {
"block" : {
"transactions" : [ {
"hash" : "0x8536795a87ab8ba3de721a9b5745f57c3c515221490817737a742d53f3b226d4",
"from" : {
"address" : "0xec6a5154ba367f393c565b3597034540ba00c836",
"balance" : "0x0"
},
"to" : {
"address" : "0xec6a5154ba367f393c565b3597034540ba00c836",
"balance" : "0x0"
},
"logs" : [ ]
}, {
"hash" : …
```

Return `address` from the `from` and `to` fields in a GraphQL

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractGetHeadersFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetHeadersFromPeerByHashTask.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/internal/RecursivePeerRefreshState.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/AbstractPeerConnection.java

* Moved the full "mismatched network id" message to TRACE and have a brief version at DEBUG
* moved "Disconnect - Outbound" brief message to INFO
* moved the EthPeers {} collection logging to TRACE

Eth peer logging improvements

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/TransactionReceiptResult.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionReceiptWithMetadata.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/TransactionDataFetcherTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionReceiptTest.java

Assign log index to transaction receipt according to position in block instead of in transaction.
fixes #6204

Fix log index in transaction receipt

---

docker/openjdk-17-debug/Dockerfile
docker/openjdk-17/Dockerfile
ethereum/evmtool/src/main/docker/Dockerfile

CI builds are currently broken because an ubuntu package update breaks with ca-certificates-java version 20190909. If we allow it to use updates to the version (such as 20190909ubuntu1.2) the build un-breaks.

Unpin ca-certificates-java version

---

services/pipeline/src/main/java/org/hyperledger/besu/services/pipeline/Pipeline.java

log a message only at info
log stack trace at debug/trace depending on type of exception
fixes #5533

[MINOR] move Pipeline stack trace to trace/debug level

---

besu/src/main/java/org/hyperledger/besu/services/TraceServiceImpl.java

This fixes double calls to trace{Start,End}Transaction.
Fixes #6246

fix: double calls to trace{Start,End}Transaction

---

besu/src/test/java/org/hyperledger/besu/PrivacyTest.java
docker/openjdk-17-debug/Dockerfile

fixes for issues discovered while debugging #6003 
static temp dir in PrivacyTest causes flaky test behavior.  fix by not using static temp dir:
remove opinionated configs in debug docker image as they can cause difficult to discover failures/conflicts with existing network configs:
* explicit add of `*` to BESU_HOST_ALLOWLIST can cause ```Values '*' or 'all' can't be used with other hostnames``` if config has explict host configs (or even a duplicate `*` for hosts allow)
* explicit set of BESU_RPC_HTTP_API can cause ```Method not found``` for rpc namespaces added by config like for linea plugins, etc

Small fixes in main

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/ChainHeadTracker.java

We are logging this:
LOG.debug("Failed to retrieve chain head info. Disconnecting {}", peer, error);
Error is not printed 
Also noticed a similar issue in EthProtocolManager
before
```
2023-12-07 09:51:03.857	
2023-12-06 23:51:03.857+00:00 | EthScheduler-Timer-0 | DEBUG | ChainHeadTracker | Failed to retrieve chain head info. Disconnecting PeerId: 0xcbbaacaf47a005cb38... PeerReputation score: 99, timeouts: {3=1}, useless: 0, validated? true, disconnected? false, client: Geth/v1.13.2-stable-dc34fe82/linux-amd64/go1.21.1, [Connection with hashCode 2029564766 inboundInitiated? false initAt 1701906657037],...
```
after
`2023-12-07 13:19:53.174+10:00 | EthScheduler-Timer-0 | DEBUG | ChainHeadTracker | Failed to retrieve chain head info. Disconnecting 0x82b8a8b80c6c37caad... …

[MINOR] fix log params for Failed to retrieve chain head

---

acceptance-tests/tests/build.gradle

Seems redundant but it fixes this warning
```
Execution optimizations have been disabled for task ':acceptance-tests:tests:processTestResources' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: '/Users/sallymacfarlane/workspace/b2/acceptance-tests/test-plugins/build/libs'. Reason: Task ':acceptance-tests:tests:processTestResources' uses this output of task ':acceptance-tests:test-plugins:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

add extra gradle task dependency to silence warning

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java

at startup, log the counts (at info) and list (at debug level)

log bootnodes and static nodes list at debug level

---

CHANGELOG.md
besu/src/test/java/org/hyperledger/besu/ForkIdsNetworkConfigTest.java
config/src/main/resources/classic.json

This PR sets ETC Mainnet activation block as defined in [ECIP-1109](https://ecips.ethereumclassic.org/ECIPs/ecip-1109) to `19_250_000`. This change was already merged in core-geth in https://github.com/etclabscore/core-geth/pull/595
I also set the DNS discovery tree to what's in [core-geth#bootnodes_classic.go](https://github.com/etclabscore/core-geth/blob/v1.12.17/params/bootnodes_classic.go#L28)

ETC mainnet 'Spiral' activation block

---

ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/core/TransactionTest.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/core/TransactionTestCaseSpec.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/rlp/RLPRefTest.java

Add new forks to transaction tests, add bad rlp to rlp ref tests.

Increase scope of reference tests

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketMessageHandler.java

Trace WS JSON/RPC responses (successes and failures)
Fixes https://github.com/hyperledger/besu/issues/6276
Successful `eth_getBlockByNumber`:
```
2023-12-12 10:43:41.553+00:00 | vert.x-eventloop-thread-1 | TRACE | WebSocketMessageHandler | {"jsonrpc":"2.0","id":51,"result":{"number":"0x0","hash":"0x74f92c171677a9f8b1eac53fc4f2c2e0d6bbc7a7b9b259fd0067f7b573951e16","mixHash":"0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","logsBloom":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```

Add trace to web socket JSON/RPC responses

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/test/java/org/hyperledger/besu/util/LocalPermissioningConfigurationValidatorTest.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/peers/EnodeURLImpl.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestBlockchain.java

eg in bootnodes config
Before
2023-12-13 12:08:50.949+10:00 | main | ERROR | Besu | Failed to start Besu Invalid IP address (or DNS query resolved an invalid IP). --Xdns-enabled is true but --Xdns-update-enabled flag is false.
After
2023-12-13 12:11:14.581+10:00 | main | ERROR | Besu | Failed to start Besu Invalid IP address 'enode://bob@bob:8000' (or DNS query resolved an invalid IP). --Xdns-enabled is true but --Xdns-update-enabled flag is false.

[MINOR] Include Enode URL in error message if parsing exception

---

ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/AbstractPeerConnection.java

There are two invocations to the method "terminateConnection" (ApiHandler and NettyPeerConnection). In the case of NettyPeerConnection it is called inside a listener.
The correct thing is to control that the terminateConnection method is executed once even if it is called several times.
#6201

[#6201] Duplicate "Terminating connection" message on peer connections

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java

When a node is full syncing or backward syncing, it is possible the processing of block added in the txpool, causes a tight loop, with the result of high cpu consumption, that causes the node to basically halt doing other tasks.
This is a quick workaround, while a proper solution, that also avoids to process added blocks during full sync is in progress, and will be ready.

Quick fix to avoid a tight loop when processing added blocks in txpool

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessorTest.java

Call `OperationTracer.traceEndTx` even when a transaction failed.
fixes #6312

fix: call OperationTracer.traceEndTx for failing transactions

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractRetryingSwitchingPeerTask.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/peervalidation/AbstractPeerBlockValidatorTest.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/peers/DefaultPeerPrivileges.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/peers/PeerPrivileges.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java

In one place there was a check missing to allow static peers to exceed the connection limit.
Another improvement is that streamBestPeers() does only return fully validated peers.

add missing check for static peers to allow them to exceed the connection limit

---

besu/src/test/java/org/hyperledger/besu/controller/BesuControllerBuilderTest.java
besu/src/test/java/org/hyperledger/besu/controller/BesuControllerTest.java
besu/src/test/java/org/hyperledger/besu/controller/ConsensusScheduleBesuControllerBuilderTest.java
besu/src/test/java/org/hyperledger/besu/controller/MergeBesuControllerBuilderTest.java
besu/src/test/java/org/hyperledger/besu/controller/QbftBesuControllerBuilderTest.java
besu/src/test/java/org/hyperledger/besu/controller/TransitionControllerBuilderTest.java

[MINOR] migrate controller builder test junit5

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/test/java/org/hyperledger/besu/ForkIdsNetworkConfigTest.java
besu/src/test/java/org/hyperledger/besu/RawForkIdTest.java
config/src/main/resources/goerli.json
config/src/main/resources/holesky.json
config/src/main/resources/sepolia.json
evm/src/main/java/org/hyperledger/besu/evm/precompile/KZGPointEvalPrecompiledContract.java
evm/src/test/java/org/hyperledger/besu/evm/precompile/KZGPointEvalPrecompileContractTest.java

add new forkids for testnets, update forkid test to Junit5, no longer need named network specific trusted setups

Cancun forkids for non-mainnets

---

CHANGELOG.md
gradle.properties

bump gradle properties version and adjust changelog to match release

Set build version to 24.1.0-SNAPSHOT

---

CHANGELOG.md
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java

Currently Besu uses the default RocksDB WAL options, with the result that usually the WAL files could occupy ~15GB of disk space, due to the fact that different column families are flushed at very different intervals, this has also the bad effect of slow restarts, when Besu has to parse an reapply all these WAL files.
Capping the WAL files total size to 1GB and reusing old files when possible, has the advantage of a faster restart, and a more linear disk usage, instead of the classic saw tooth shape that we see today.

Optimize RocksDB WAL file

---

CHANGELOG.md
ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/frontier/EthEstimateGasIntegrationTest.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcErrorConverter.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractEstimateGas.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/RpcErrorType.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java
ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_estimateGas_invalid.json
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionInvalidReason.java

This PR adds a setter for the `reason` field in `JsonRpcError`.
If a caller sets the `reason`, it is appended to the message for the error that is taken from the `RpcErrorType` enums.
It also adds a new `RpcErrorType` of `EXECUTION_HALTED` to be used during transaction simulations (e.g. during `eth_estimateGas()` calls) so a failed gas estimation doesn't just return `INTERNAL_ERROR` when there's a problem with the execution.
The specific example I hit this in was using a Shanghai smart contract with the `JUMP0` opcode against a QBFT Besu node (QBFT doesn't currently support Shanghai).
Fixes #4914 
(See also https://github.com/hyperledger/besu/pull/5706 which improves the error messages sent back to the user for reverted transactions)

Make RPC reason settable, pass execution failure reason in RPC error message

---

acceptance-tests/dsl/build.gradle
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/AcceptanceTestBase.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/AcceptanceTestBaseJunit5.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/AcceptanceTestBaseTestWatcher.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/bft/qbft/QbftContractAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/BadCLIOptionsPluginTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/BesuEventsPluginTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/PermissioningPluginTest.java

migrate the TestWatcher functionality from junit 4 Rule to junit 5
introduced a new superclass to be able to separate junit4 tests vs junit5 tests, to avoid having to change all at once.
fixes #6348

TestWatcher junit5

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/worldview/BonsaiWorldState.java

This PR fixes a bug in the generation of the trie log when we have a selfdestruct and create2 of the same account in the same block, and if this contract contains a non-empty storage. This bug occurred on the mainnet, and we were able to reproduce the bug and validate that the fix resolves the problem. We had a previous PR to fix this bug but it was not completly fixed on this one
This bug was fixed when we create the trie log with a persistent BonsaiWorldstate, but not with a non-persistent BonsaiWorldstate, which is what happens with the call of the newPayload method. BackwardSync uses the persistent worldstate, and that's why the BackwardSync unlocks the situation.
#6357

fixing trielog generation when selfdestruct/create2 on same block

---

besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java

Move bootnodes logging to RunnerBuilder so that we always log the actual bootnodes being used.

[MINOR] Move bootnodes logging to RunnerBuilder

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractEstimateGas.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGas.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCreateAccessListTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java

Optimistically get the chain head block without taking a lock. If that fails, retry under the lock.
This is an identical fix to https://github.com/hyperledger/besu/pull/6143.
I did consider making a more generic helper/util function to wrap the logic for any place in the code that needs it, but looking through the code I can't see any other cases where the a failed attempt to get the chain head block results in an internal error or exception. Most others treat it as optional and just retry on the next go round.
Fixes https://github.com/hyperledger/besu/issues/6344

Use synchronized call to access the chain head block in `eth_estimateGas`

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/DefaultCommandValues.java
besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java

Add an alias for fast-sync-min-peers
refs #6327

Added alias --sync-min-peers for --fast-sync-min-peers

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/BlockHeaderValidator.java

When a validation rule fails in `BlockHeaderValidator`, debug message falls back to using just name when canonical name is not available.
Fixes #6177

Fix: Fallback to getName when canonicalName is null in BlockHeaderValidator DEBUG log

---

CHANGELOG.md
docker/openjdk-latest/Dockerfile

The openjdk-latest Docker image is using UID 1001 for besu, because its base image `ubuntu:23.10` now contains a default "ubuntu" user with UID 1000. (This UID change causes the besu user with UID 1001 to not have access to files created for past versions with UID 1000.)
This PR removes the default ubuntu user and explicitly uses UID 1000 when creating the besu user.
**Note that this change will re-break file permissions for people who've already changed besu file ownership from 1000 -> 1001 when upgrading to 23.10.3, as the besu user goes back to UID 1000, as it was in versions prior to 23.10.3.**
Fixes #6358

fix: use UID 1000 for besu user (#6358)

---

build.gradle

Ignore generated files in `bin/` directories when running the SPDX license check.  Visual Studio Code generates build files in various bin directories, which causes this check to fail.

Ignore bin files when running the spdx license check

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java

Log a warning instead of failing startup
fixes #6327 
Before:
```
➜  b2 git:(sync-min-peers) ✗ besu --sync-mode="full" --sync-min-peers=1
2024-01-09 12:17:57.498+10:00 | main | INFO  | Besu | Starting Besu
2024-01-09 12:17:57.866+10:00 | main | ERROR | Besu | Failed to start Besu
picocli.CommandLine$ParameterException: --sync-min-peers can't be used with FULL sync-mode [--sync-min-peers]
at org.hyperledger.besu.cli.util.CommandLineUtils.failIfOptionDoesntMeetRequirement(CommandLineUtils.java:129)
```
and startup fails.
After:
```
➜  b2 git:(sync-min-peers) ✗ besu --sync-mode="full" --sync-min-peers=1
2024-01-09 12:24:50.728+10:00 | main | INFO  | Besu | Starting Besu
2024-01-09 12:24:51.539+10:00 | main | WARN  | Besu | --sync-min-peers is ignored in FULL sync-mode
2024-01-09 …
```

full sync - don't fail startup if sync-min-peers specified

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java

When doing a detached copy of a transaction, copy also the computed fields to avoid to recompute them

Copy also computed fields, when doing a Transaction detached copy

---

CHANGELOG.md
gradle.properties

bump release version to 24.1.1-SNAPSHOT
add/edit/move changelog entries
TBA links for 24.1.0
add missing changelog entry for 23.10.2

Bump to nex release snapshot 24.1.1

---

CHANGELOG.md
evm/src/main/java/org/hyperledger/besu/evm/fluent/EVMExecutor.java

The fluent API incorrectly added the code size limit in Tangerine Whistle instead of first adding it in Spurious Dragon.

In fluent APIs correct Tangerine Whistle definition.

---

ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java

When using the `From` address specified by a peer, ensure it is a valid IP address. Otherwise revert to using the UDP source host.
See comment https://github.com/hyperledger/besu/pull/6225#issuecomment-1900243754

Only accept an address from a peer if it is a valid IP address

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilder.java
besu/src/main/java/org/hyperledger/besu/cli/options/stable/DataStorageOptions.java
besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogHelper.java
besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogSubCommand.java
besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
besu/src/test/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilderTest.java
besu/src/test/java/org/hyperledger/besu/cli/options/stable/DataStorageOptionsTest.java
besu/src/test/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogHelperTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DataStorageConfiguration.java

Part of https://github.com/hyperledger/besu/issues/5390
* `$BESU --Xbonsai-limit-trie-logs-enabled=true` will use the default value of `--bonsai-historical-block-limit=512`
* `$BESU --Xbonsai-limit-trie-logs-enabled=true --bonsai-historical-block-limit=511` throws error as must be >= 512
* `$BESU --Xbonsai-limit-trie-logs-enabled=false --bonsai-historical-block-limit=511` does not throw error as this is allowed until limit-trie-logs-enabled.
This implementation avoids a breaking change for anyone that has a node with --bonsai-historical-block-limit already set to < 512 (could be noone?)
However, we should be aware that if `--Xbonsai-limit-trie-logs-enabled` ever becomes default then this breaking change will come back again

Reuse --bonsai-historical-block-limit for trie log pruning

---

CHANGELOG.md
besu/src/test/java/org/hyperledger/besu/services/TraceServiceImplTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nExecutor.java
evm/src/main/java/org/hyperledger/besu/evm/tracing/OperationTracer.java

`OperationTracer.traceStartTransaction` is triggered before the EVM execution, but after the sender account has been updated (i.e. its balance decreased from the upfront cost and its nonce increased), hiding its actual initial state from the `OperationTracer`.
This PR adds a new hook, `OperationTracer.tracePrepareTransaction`, that is triggered after the transaction has been validated for execution, but before any change to the sender account, hence presenting its pristine state to the `OperationTracer`.

feat: add `OperationTracer.tracePrepareTransaction`

---

ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java
ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgentTest.java

address another pathological default PingPacketData from address we are seeing on mainnet - a broadcast address 255.255.255.255 seems to be a default value for some implementations.
For example we are seeing a lot of these log lines on mainnet:
```
{
"@timestamp":"2024-01-24T06:18:16,129",
"level":"WARN",
"thread":"vert.x-eventloop-thread-3",
"class":"VertxPeerDiscoveryAgent",
"message":"Sending to peer DiscoveryPeer{status=bonding, enode=enode://5d01e72875f3485fdcce5255720696087ea7d704c6632282fbe39329db6417a6f5ef940cf05519677be7f9c31b6b553fe9192e9e9feed37db3fb97bcc7fd099e@255.255.255.255:30313, firstDiscovered=1706077069751, lastContacted=0, lastSeen=1706077069751} failed, native error code -13, packet: 0x3123aed37feabe25bd4cc2625a1d1e2b12a5a1bbe6f3ef594c1ea76abbfbae670ab30477655186a5a3bf …
```

Add broadcast address to PingPacketData from filter

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncContext.java

Ensure we do not attempt to start BWS sessions if initial sync has not yet completed.  This change prevents BWS from triggering via engine-api during:
* initial sync
* auto-heal
* resync worldstate

ignore bws sync requests until initial sync is complete

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/test/resources/everything_config.toml
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/ApiConfiguration.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceFilter.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/TraceJsonRpcMethods.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceFilterTest.java

Enable a limit on the range of blocks that can be supplied to the JSON-RPC trace_filter method.
The limit has a default value and can be overridden with a command line option at start up.
fixes #5971

Enable limit on range Of JSON-RPC API trace_filter method (#5971)

---

besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogHelper.java
besu/src/test/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogHelperTest.java

Rework error messaging in this case.
This can occur if pruning is attempted before the node has reached the configured retention limit (512 by default)

Skip pruning if trie log count is less than retention limit

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/options/MiningOptions.java
besu/src/main/java/org/hyperledger/besu/cli/util/TomlConfigurationDefaultProvider.java
besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
besu/src/test/java/org/hyperledger/besu/cli/options/AbstractCLIOptionsTest.java
besu/src/test/java/org/hyperledger/besu/cli/options/MiningOptionsTest.java
besu/src/test/java/org/hyperledger/besu/cli/options/SynchronizerOptionsTest.java

Fix `poa-block-txs-selection-max-time` option that was inadvertently reset to its default after being configured.
Mining options needs the value of the block period from the genesis file, so the way to pass it to the class has been improved to avoid using the mining options if that value was not set, in order to be less error prone.

Fix `poa-block-txs-selection-max-time` option that was inadvertently reset to its default after being configured

---

ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java
ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgentTest.java

add empty source addresses to ping packet filter lsit
currently on main we are seeing packet errors like:
```
2024-01-27 07:21:53.144+00:00 | vert.x-eventloop-thread-1 | WARN  | VertxPeerDiscoveryAgent | Sending to peer DiscoveryPeer{status=bonding, enode=enode://b3af6e4685a1c54447b0510b29397c5534a66ce32224efd250e775ebd0f56c609e3f29d76fcae1893a1b437d6d383673915d9b1c60643be0e45e52acb2f2f335@[::]:28568, firstDiscovered=1706340111143, lastContacted=0, lastSeen=1706340111143} 
failed, native error code -97, packet: 0xc76f91fa10c899a6a7d270611aba4b9f931447770a3cac9722996ebae807e0d9a403e5c090ef23cec3d81b8a27db826322dd66964656ba0acc6964ee387753796cf000fdc92e10970ec4b6e3ae12f7895c6922a0c07754ce267b98b046c124da0101eb05cb847f000001829d6f829d6fd79000000000000000000000000000000000826f98826f988465b4af4 …
```

filter empty ipv4 and ipv6 ping packet source addresses

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java

Removes `--engine-jwt-enabled`. Replaced by `--engine-jwt-disabled`
It has been deprecated since 2022.

Remove `--engine-jwt-enabled` deprecated option

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/SyncTargetManager.java
services/pipeline/src/main/java/org/hyperledger/besu/services/pipeline/Pipeline.java
util/src/main/java/org/hyperledger/besu/util/log/LogUtil.java
util/src/test/java/org/hyperledger/besu/util/log/LogUtilTest.java

Add a summarize stack log util, use it in Pipeline to summarize abort errors at an info level

info level log for pipeline abort

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/options/unstable/EvmOptions.java
besu/src/main/java/org/hyperledger/besu/cli/options/unstable/MetricsCLIOptions.java
besu/src/main/java/org/hyperledger/besu/cli/options/unstable/NetworkingOptions.java

where the default is number/boolean/string, just leave it to the initialized value for the actual field.
same as was done for Sync Options in #6499

[MINOR] remove duplicate setting of default values for CLI options

---

ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java
util/src/main/java/org/hyperledger/besu/util/NetworkUtility.java
util/src/test/java/org/hyperledger/besu/util/NetworkUtilityTest.java

updates PeerDiscoveryAgent to 
* use existing NetworkUtility to filter for any/none peers
* fall back to source address if ipv6 is not supported (like in a docker container)
fixes #6475

Filter Discovered peers for ipv6 support

---

.github/workflows/acceptance-tests.yml
acceptance-tests/tests/build.gradle

exclude privacy tests since they are currently flaky (they are run on a separate nightly cadence)

Acceptance Tests - only run non-privacy ATs

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
evm/src/main/java/org/hyperledger/besu/evm/ClassicEVMs.java

During the last ETC network upgrade, Besu nodes got stalled because, inadvertently, [EIP-4399](https://eips.ethereum.org/EIPS/eip-4399) was _included_ instead of _omitted_.
For the future, we'll also test omissions to the protocol and not only additions.

Add ETC Spiral EVM configuration

---

acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/pubsub/WebSocket.java

Increase timeout for websocket ATs since a few of them are flaky eg https://app.circleci.com/pipelines/github/hyperledger/besu/27037/workflows/036ea38e-b0b0-4e2e-8d9c-a280f53134e3/jobs/179105/tests#failed-test-0

increase timeout for websocket pub/sub tests

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java

we enforce that you can't specify FAST sync if privacy is enabled - do the same check for SNAP and CHECKPOINT

error if snap or checkpoint sync specified with privacy

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DataStorageFormat.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactory.java
plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactoryTest.java

Improve message error when existing database with a different version is detected
`Mismatch: DB at '/path' is FOREST (Version 1) but config expects BONSAI (Version 2). Please check your config.`
see: #5926

[minor] Improve message when existing database is different from the configuration

---

build.gradle

I'm getting a gradle build failure due the "checkLicenses" task.  This looks like a misspelling:
```
% ./gradlew dev -x test
FAILURE: Build failed with an exception.
* What went wrong:
Task 'checkLicenses' not found in root project 'besu' and its subprojects. Some candidates are: 'checkLicense'.
```
Fix this by using the existin "checkLicense" task.

Fix checkLicense gradle task

---

.circleci/config.yml

These tests are flaky right now for 2 reasons, and work is in progress to fix. 
See 
Run tessera as a process (currently using docker) for ATs https://github.com/hyperledger/besu/pull/5968
Also occasionally errors since the txpool is disabled during initial sync - it's been somewhat [mitigated](https://github.com/hyperledger/besu/pull/6479) but hasn't totally fixed it

disable privacy tests since they are currently flaky

---

besu/src/test/java/org/hyperledger/besu/ForkIdsNetworkConfigTest.java
config/src/main/resources/mainnet.json
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/mainnet/DifficultyCalculatorTests.java
evm/src/main/java/org/hyperledger/besu/evm/precompile/KZGPointEvalPrecompiledContract.java

Timestamp set for cancun on mainnet.

timestamp set for dencun on mainnet.

---

besu/src/test/java/org/hyperledger/besu/cli/CascadingDefaultProviderTest.java
besu/src/test/java/org/hyperledger/besu/cli/ProfilesTest.java
config/src/main/resources/profiles/minimalist-staker.toml

Add tests to ensure that the profiles are sensible and besu will start with each of them
Refs #6323

Add tests for user profiles

---

besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/RocksDbSubCommand.java
besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogSubCommand.java

Following on from #6540, use `total-sst-files-size + total-blob-file-size` instead of `estimate-live-data-size` for x-trie-log prune estimate.

[MINOR] Use better savings estimate for x-trie-log prune

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthBlobBaseFee.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthJsonRpcMethods.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthBlobBaseFeeTest.java

Add `eth_blobBaseFee`
fixes #6579

feat: add `eth_blobBaseFee`

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/VersionMetadata.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/VersionMetadataTest.java

Resolves breaking change in PR https://github.com/hyperledger/besu/pull/6307 that blocks Besu startup if the data dir doesn't exist already

During version check, create data dir if it doesn't exist

---

besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/StorageSubCommand.java
besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
besu/src/test/java/org/hyperledger/besu/cli/subcommands/storage/StorageSubCommandTest.java

Fixes NPE when running the revert variables subcommand. 
Due to changes in how the data storage configuration is handled the approach of using the storage provider directly from the `BesuSubcommand` no longer works. Instead changed the approach that to use what was used in the trielog subcommands and creates the BesuController using the `BesuCommand.buildController()` to get access to the `StorageProvider`. 
fixes #6614

Fix NPE when running revert variable subcommand

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/options/unstable/SynchronizerOptions.java
besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapSyncConfiguration.java

Reverted since there's an issue with snap sync that is revealed by not being able to turn off this flag.
refs https://github.com/hyperledger/besu/issues/6157

revert 6499 flat-db-healing-enabled false by default

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java

Fixes #6385 
Docs - can't see anywhere in the docs where we mention snap or checkpoint on the private networks side, but may be worth adding an explicit note that you must use FAST or FULL if using PoA consensus.

prevent startup if PoA and snap/checkpoint

---

besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
besu/src/test/java/org/hyperledger/besu/cli/BesuCommandWithRequiredOptionsTest.java
besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
besu/src/test/java/org/hyperledger/besu/cli/HostAllowlistOptionsTest.java
besu/src/test/java/org/hyperledger/besu/cli/NatOptionsTest.java
besu/src/test/java/org/hyperledger/besu/cli/PkiOptionsTest.java
besu/src/test/java/org/hyperledger/besu/cli/PrivacyOptionsTest.java
besu/src/test/java/org/hyperledger/besu/cli/PruningOptionsTest.java
besu/src/test/java/org/hyperledger/besu/cli/TxPoolOptionsTest.java

Refs #6428 
* split out some tests into separate test classes
* Also use tempDir for the `dataDirOptionMustBeUsed` test to avoid leaving behind `besu/VERSION_METADATA.json` file

Besu command test split

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java

Docs - can't see anywhere in the docs where we mention snap or checkpoint on the private networks side, but may be worth adding an explicit note that you must use FAST or FULL if using BFT consensus.
Adjustment to #6625
Fixes https://github.com/hyperledger/besu/issues/6385

allow snap/checkpoint with clique

---

CHANGELOG.md
ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/frontier/EthCallIntegrationTest.java
ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/frontier/EthCreateAccessListIntegrationTest.java
ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/frontier/EthEstimateGasIntegrationTest.java
ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/london/EthCallIntegrationTest.java
ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/london/EthEstimateGasIntegrationTest.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcErrorConverter.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthFeeHistory.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonCallParameter.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/RpcErrorType.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/FeeHistory.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcErrorTypeConverterTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCallTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCreateAccessListTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthFeeHistoryTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivCallTest.java
ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_call_blob.json
ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_call_blob_missing_maxFeePerBlobGas.json
ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_call_blob_too_many_blobs.json
ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_call_blob_zero_fee.json
ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_feeHistory_fieldNamesWithReward.json
ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_feeHistory_fieldNamesWithoutReward.json
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/CallParameter.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulatorTest.java

Cherry-picks #6679 and #6661 for blob support

RC4 - eth_call and eth_feeHistory add blob fields

---

besu/src/main/resources/log4j2.xml

quickie pr to silence the vertx counterpart to the tuweni dns errors

Silence vertx dns errors

---

build.gradle

The `assemble` task has been modified to additionally depends on `compileIntegrationTestJava` so that any compilation issues are reported earlier locally and in CI.
Fixes #6670

[build] - Update gradle build to invoke int test compile task on assemble task

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactory.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactoryTest.java

Fix and unit test for transaction pool inSync listener to ensure we account for initial sync state when enabling/disabling the pool.
The inSync listener responds to chain events only and does not take into account worldstate sync.  This pr adds an additional initial sync condition in the sync listener to ensure we do not enable the pool when the chain sync finishes, but the worldstate is incomplete (like in the case of a debug_resyncWorldState)

fix for txpool inSync listener to honor initial sync state

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/controller/IbftBesuControllerBuilder.java
besu/src/main/java/org/hyperledger/besu/controller/QbftBesuControllerBuilder.java

When creating a BFT mining coordinator, if the sync phase is already complete then enable the coordinator but don't start it.
Start will be done either during starting of the ethereum main loop, or on receiving an event notification that syncing has completed.
Fixes https://github.com/hyperledger/besu/issues/6674

Don't start the BFT mining coordinator when it is created, just enable it

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/BadBlockCause.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/BadBlockReason.java

BadBlockReason was an non-static inner enum in BadBlockCause and it was used in static context. This caused one of our custom errorprone checks to not pick up the "method param not final argument" correctly. Refactoring it out as an static top level class. Now all the checks are applied correctly.
#6685

Refactor BadBlockReason enum out of BadBlockCause

---

build.gradle
gradle.properties

As part of our recent build and release changes, we no longer need to explicitly maintain the build version in gradle.properties file.
This PR is a proposal to change our "develop" builds to use git commit and HEAD details to specify a dynamic build version.
for example this PR, prior to committing the changes, produced a build named:
`besu-24.3.7-develop-610927511e.tar.gz`
After committing the gradle changes and rebuilding, it produced a build named:
`besu-24.3.7-develop-600d812d89.tar.gz`
Open to suggestions, feedback, and identifying corner cases

proposed "develop" build versions

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PluginPrivacyController.java

Refactor PluginPrivacyController. Fix parameter name to match overridden method. Identified during errorprone plugin update.

Refactor PluginPrivacyController to fix parameter name

---

ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/VertxPeerDiscoveryAgent.java

For one user, this log was appearing every couple of seconds.
We determined that it shouldn't affect the peers required for the node to function therefore there's potentially nothing to act on WARN level is too high.

[MINOR] Move potentially spammy peer discovery warn log to debug

---

acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthSendRawTransactionAcceptanceTest.java

relates to #6718 - ignore this flaky test for now

ignore flaky test EthSendRawTransaction AT

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/VersionMetadata.java

chore: fix some typos

---

build.gradle
ethereum/evmtool/build.gradle

`getCheckedOutGitCommitHash` was removed in https://github.com/hyperledger/besu/pull/6699
This updates to use the new function

fix checked out git commit hash for docker builds

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractGasLimitSpecification.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/TargetingGasLimitCalculatorTest.java

Suppress ComparisonOutOfRange error-prone warning in AbstractGasLimitSpecification. This was reported during errorprone plugin update. Add a unit test to cover the max limit as well.

Suppress ComparisonOutOfRange errorprone warning in AbstractGasLimitSpecification

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java

Current blog logging shows blob transaction count.  The blob count is more relevant and reflects the label better.

Log blob count

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/RpcErrorType.java

Fix for `Method input parameters must be final` compilation error

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/Scalars.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/RpcErrorType.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/scalar/Bytes32ScalarTest.java

Fix error where GraphQL fails to serialize the versioned hash of a blob transaction.

GraphQL serializes BlobVersionedHashes

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/PluginJsonRpcMethod.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcTestHelper.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/PluginJsonRpcMethodTest.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/exception/PluginRpcEndpointException.java

Move the logging to debug to reduce the noise, then explicit than the eventual string parameters passed to `PluginRpcEndpointException` is the additional data for the exception, the only use case now is for the revert reason, and not a free text message.

Improve PluginRpcEndpointException

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/cache/TransactionLogBloomCacher.java

Example log:
> Caching logs bloom for block 0x127804
During sync with DEBUG enabled, this is extremely noisy...printed nearly 600K times during a holesky sync in < 1 hour...

Set noisy TransactionLogBloomCacher debug log to trace

---

build.gradle
wslsh.bat

With this PR it is possible to run Gradle tasks that require a shell to also run on Windows + WSL

Support running executable Gradle tasks on Windows with WSL

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java

Update the interruption message for transaction selection to clarify that the process involves multiple transactions exceeding the configured time limit. This change aims to eliminate ambiguity, explicitly indicating that the interruption occurs when the cumulative selection process surpasses the configured duration, rather than being related to a single transaction.

Modify the message when the selection of transactions is interrupted

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/common/DiffBasedWorldStateProvider.java

Makes the logs more clear about historical queries in Bonsai when you exceed the `bonsai-historical-block-limit`
None

Logging improvements for Bonsai historical queries 

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java

Refactor of private method
Was passing peer.getId() as a param in both instance where it was called
* which is unnecessary since the peer is passed as a param
* and the null check is done within registerDisconnect
* added an extra trace log line since it may be pathological that this method is called with a null peer
Fixes #6840

[MINOR] refactor to check for null peer

---

CHANGELOG.md
besu/src/main/resources/log4j2.xml
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/AbstractPendingTransactionsSorter.java

Transactions that during block creation are found to be invalid are removed from the pool, and could be difficult to retrieve the content of the tx, so if needed for debug, with this PR is possible to enable the log the RLP of the invalid tx, along with some other info, these log lines have the marker `INVALID_TX_REMOVED` and the following fields, that can be used to format the log line as required:
- `txhash` hash of the tx
- `txlog` human readable log of the tx
- `reason` why the tx was invalid
- `txrlp` the RLP encoding of the tx
Log4j2 example configuration to enable the invalid tx log:
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration monitorInterval="30" status="INFO">
<Properties>
<Property name="root.log.level">INFO</Property>
</Properties>
<Appenders>
<Console …
```

Dedicated log marker for invalid txs removed from the txpool

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/RequestDataStep.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/StackTrie.java

snap client fixes discovered during besu snap-client -> besu snap-server testing.
* correctly handle empty range responses
* skip stack trie commits without keys
* adjust remote peer connection limit arithmetic to cover cases where max-peers is 1
RIP coder buddy

Snap client fixes

---

.github/workflows/artifacts.yml
build.gradle

The 24.4.0 release deployed artifacts to artifactory as expected, but failed when updating the build-info, which was a surprise. This is a workaround which disables that publishing temporarily, and also defers jar publishing till the end of the workflow, to avoid derailing more important steps.

workaround for broken publishing of buildinfo

---

CHANGELOG.md
ethereum/referencetests/build.gradle

New revision of Cancun era reference tests

Upgrade reference tests to 13.2

---

build.gradle

build: Remove incomplete artifactory task. The top level artifactory task was used to upload dists to artifactory which has been moved to GH

build: Remove incomplete artifactory task

---

config/src/main/resources/holesky.json

This PR adds the missing enrtree prefix to the dns address of the holesky network. Kudos to @matkt for picking up this one.

Add prefix to dns on holesky

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractGetHeadersFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/BufferedGetPooledTransactionsFromPeerFetcher.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetHeadersFromPeerByHashTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetNodeDataFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetPooledTransactionsFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetReceiptsFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotBlockConfirmer.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java

Similar to #6849 - ellipsis is now included in loggableId. There were a few more places where this was duplicated.

[MINOR] nuke those extra ellipses

---

.github/workflows/artifacts.yml
.github/workflows/docker.yml
.github/workflows/release.yml

An interesting subtlety of the github api is that when referring to a ref, there may be multiple and they are sorted alphabetically. So if we assume that the version to use in the build is what we tagged it as, we will only get the right value if the second tag is alphabetically earlier.
This fixes it by using whatever name is given to the release. Don't be clever, just use calver for now!

use event name instead of ref, which may be non-deterministic

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputation.java

Relax the peer timeout threshold, align with EthPeer max outstanding requests

Relax PeerReputation timeout threshold

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncDownloadPipelineFactory.java

Logging for debugging #6884 
Example when peer disconnected:
```
DEBUG | FastSyncDownloadPipelineFactory | Stopping chain download due to disconnected peer PeerId: 0x143e11fb766781d2... PeerReputation score: 150, timeouts: {}, useless: 4, validated? true, disconnected? true, client: Geth/v1.13.14-stable-2bd6bd01/linux-amd64/go1.21.7, [Connection with hashCode 68650968 inboundInitiated? false initAt 1712288750661], enode://143e11fb766781d22d92a2e33f8f104cddae4411a122295ed1fdb6638de96a6ce65f5b7c964ba3763bba27961738fef7d3ecc739268f3e5e771fb4c87b6234ba@146.190.1.103:30303
```
Example when lastRoundHeader >= pivotBlockHeader:
```
DEBUG | FastSyncDownloadPipelineFactory | Stopping chain download as lastRoundHeader=1283816 is not less than pivotBlockHeader=1283816 for peer PeerId: …
```

Add debug logging to see why we stop downloading from peer

---

CHANGELOG.md
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolMetrics.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/AbstractTransactionsLayer.java

Expose transaction count by type metrics for each layer of the layered txpool
The new metric name is `besu_transaction_pool_number_of_transactions_by_type` and has `layer` and `type` as labels.
Example panel 
Besu Full Grafana dashboard will be updated to render this metrics once the PR will be merged.

Expose transaction count by type metrics for the layered txpool

---

acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/pubsub/NewPendingTransactionAcceptanceTest.java

marks NewPendingTransactionAcceptanceTest as flaky
evidence of flakiness:  https://github.com/hyperledger/besu/actions/runs/8596349136/job/23553493115?pr=6758
intermittent failures

marks NewPendingTransactionAcceptanceTest as flaky

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/subcommands/rlp/IbftExtraDataCLIAdapter.java
besu/src/main/java/org/hyperledger/besu/cli/subcommands/rlp/JSONToRLP.java
besu/src/main/java/org/hyperledger/besu/cli/subcommands/rlp/QbftExtraDataCLIAdapter.java
besu/src/main/java/org/hyperledger/besu/cli/subcommands/rlp/RLPSubCommand.java
besu/src/test/java/org/hyperledger/besu/cli/subcommands/rlp/RLPSubCommandTest.java

Adds `decode` subcommand to rlp based on this [Issue](https://github.com/hyperledger/besu/issues/3074)
Example
```
besu rlp decode --from=<input-file> --to=<output-file> --type=<IBFT_EXTRA_DATA|QBFT_EXTRA_DATA>
```

add rlp decode subcommand

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java

Logging was confusing - we were getting a "fork id check failed" for a peer that had already responded and given us a good block. I suspect they were in the process of disconnecting us. 
This PR adds some extra (trace) logging for why the EthProtocolManager does not want to connect, and ensures we only log "fork ID check failed" if in fact that is the problem.

[MINOR] logging for fork ID check failed

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java

Currently seeing NPE on trace level due to the possibility of the ethPeer variable be null at that point of the code.

fix npe on trace msg

---

ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestProtocolSchedules.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/GeneralStateReferenceTestTools.java

Execution-spec-tests and reference tests have migrated Merge to Paris.
Support both.

Add Paris Support to tests

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateTransactionValidator.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidatorTest.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/AbstractSequentialTransactionsLayer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/SparseTransactions.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/PendingTransactionsForSender.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nExecutor.java
evm/src/main/java/org/hyperledger/besu/evm/processor/ContractCreationProcessor.java

Make handling of absurdly large nonces
more consistent across txpool and EVM.

Consistent nonce handling

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/VersionMetadata.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/VersionMetadataTest.java

Address downgrade default for named networks.  Previously the check for named network was only considering command line params, and not toml config files.
Also implemented Comparable on VersionMetadata, and added explicit version test cases for a variety of build versions.

Fix named network default disabled for downgrade protection

---

ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/PeerDenylistManager.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/wire/messages/DisconnectMessage.java
ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/PeerDenylistManagerTest.java

Fix bug introduced in #6925
UNKNOWN disconnect reason has null code
Fixes #6937

check for empty in disconnect reason bytes

---

.github/workflows/develop.yml
build.gradle
ethereum/evmtool/build.gradle

Add a minimal github action to publish `develop` docker containers on merge to main.  
The task will publish one develop image per arch, and a multi-arch manifest.
e.g. the images that this task will publish on every merge to main (currently) are:
* develop multi-arch
* develop-arm64  (aarch64)
* develop-amd64 (amd64)

Docker develop publishing task

---

acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/AcceptanceTestBase.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/BesuNode.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java

Attempt to revert long running AT times from 7e46889
Signed-off-by: Simon Dudley <simon.dudley@consensys.net>

Attempt to speed up ATs

---

ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/B11rSubCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/StateTestSubCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nExecutor.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nServerSubCommand.java
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/t8n/cancun-blobs-per-tx.json
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/BonsaiReferenceTestWorldStateStorage.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestEnv.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/GeneralStateReferenceTestTools.java
evm/src/main/java/org/hyperledger/besu/evm/frame/MessageFrame.java
evm/src/main/java/org/hyperledger/besu/evm/frame/TxValues.java
evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCallOperation.java
evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCreateOperation.java

Update t8n, b11r, and friends to support current execution spec
* bonsai migration introduced issues with deleted storage/accounts
* status on pre-constantinople json was invalid
* track refund across tx, not call frame
* allow tests to be executed by name

Update execution-spec-tests support

---

acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AccountLocalAndOnchainPermissioningAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AccountLocalConfigPermissioningAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AccountLocalConfigPermissioningImportAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AccountSmartContractPermissioningAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AllowlistPersistorAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AllowlistWithDnsPersistorAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeLocalAndOnchainPermissioningAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeLocalConfigPermissioningAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningIbft2StallAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningOutOfSyncAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningV2AcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningV2DNSAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodesSmartContractPermissioningStaticNodesAcceptanceTest.java

Run `./gradlew --max-workers 1 acceptanceTestPermissioning` locally
fixes #6262

Port permissioning acceptance tests to JUnit 5 

---

consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/statemachine/IbftController.java
consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftController.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryTestHelper.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/PrometheusMetricsSystem.java

chore: fix some typos in comments

---

docker/test.sh

Fixes docker.yml github workflow on self-hosted runner version 2.315.0 (docker ~25.0.4+~ 26.0.0?)
Since docker 26.0.0, IPv6 is used by default but our goss_wait test is expecting ports to be exposed on IPv4.
Disabling IPv6 should work for all docker versions, at least while the runners are on various versions of docker.
Once all runners are on 26+ then we could probably change goss_wait.yml to:
```
port:
tcp6:30303:
listening: true
ip:
- '::'
udp6:30303:
listening: true
ip:
- '::'
tcp6:8545:
listening: true
ip:
- '::'
tcp6:8546:
listening: true
ip:
- '::'
tcp6:8547:
listening: true
ip:
- '::'
```
and reenable IPv6
Fixes #6929

Fix docker goss test

---

.github/workflows/acceptance-tests.yml
.github/workflows/splitTestsByTime.sh
acceptance-tests/tests/build.gradle

Current `splitTestsByTime.sh` script fails to detect ATs that are removed and does not add new test, this PR add support for both

Support for removed and added test when splitting by time in CI

---

.github/workflows/artifacts.yml

Tested here https://github.com/siladu/besu/releases/tag/0.0.6
Also echoing them in the workflow itself as a backup reference https://github.com/siladu/besu/actions/runs/8812363410/job/24187912126 (under "hashes")

Map SHA outputs correctly

---

ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/CodeValidateSubCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EOFTestSubCommand.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/eof/EOFReferenceTestTools.java
evm/src/main/java/org/hyperledger/besu/evm/Code.java
evm/src/main/java/org/hyperledger/besu/evm/code/CodeFactory.java
evm/src/main/java/org/hyperledger/besu/evm/code/CodeV1.java
evm/src/main/java/org/hyperledger/besu/evm/code/CodeV1Validation.java
evm/src/main/java/org/hyperledger/besu/evm/code/EOFLayout.java
evm/src/main/java/org/hyperledger/besu/evm/operation/EOFCreateOperation.java
evm/src/test/java/org/hyperledger/besu/evm/code/CodeV1Test.java

[Adopt subcontainer Validation](https://github.com/hyperledger/besu/commit/3817a47367c9b04a5aa50561c5a748a728587bee)

Adopt subcontainer Validation

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/options/stable/DataStorageOptions.java
besu/src/main/java/org/hyperledger/besu/cli/options/unstable/SynchronizerOptions.java
besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
besu/src/test/java/org/hyperledger/besu/cli/options/SynchronizerOptionsTest.java
besu/src/test/resources/everything_config.toml
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/common/storage/flat/FlatDbStrategyProvider.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DataStorageConfiguration.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/diffbased/bonsai/AbstractIsolationTests.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/diffbased/bonsai/BonsaiSnapshotIsolationTests.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/diffbased/bonsai/storage/BonsaiWorldStateKeyValueStorageTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/diffbased/common/storage/flat/FlatDbStrategyProviderTest.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapSyncConfiguration.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldStateDownloader.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldDownloadStateTest.java

This PR changes the default storage mode of bonsai to use code storage by code hash, and uses flat db by default.  This supports the future direction of bonsai, and simplifies the configuration necessary for besu to serve snap protocol (see description on #6640, now just `--Xsnapsync-server-enabled` is necessary).
changes:
* defaults bonsai to using a fully flattened db
* defaults bonsai to using code stored by code hash
* deprecates snap sync full flat config param
* creates --Xbonsai-full-flat-db-enabled parameter
* FlatDbStrategyProvider defers config if db is empty and persists a flat db strategy config
tested with:
* full sync, correctly creates full flattened db
* snap sync, correctly creates full flattend db, correctly heals flat db
* existing holesky sync, with FULL flat db  and …

Default bonsai to fully flat db and code storage by codehash 

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/options/unstable/SynchronizerOptions.java
besu/src/test/java/org/hyperledger/besu/cli/options/SynchronizerOptionsTest.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/SynchronizerConfiguration.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncDownloadPipelineFactory.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotSelectorFromSafeBlock.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncDownloadPipelineFactory.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/range/SyncTargetRangeSource.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/DynamicPivotBlockSelector.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldDownloadState.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldStateDownloadProcess.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldStateDownloader.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldDownloadStateTest.java

Cherry-pick worldstate halt and chain fixes from https://github.com/hyperledger/besu/pull/7027 into release branch

Cherry-pick World state halt and chain halt fixes into release

---

datatypes/build.gradle
evm/build.gradle
plugin-api/build.gradle

build - Fix gradle build for Java 21. Add compileOnly dependencies to allow gradle build to run against Java 21

build - Fix gradle build for Java 21

---

besu/src/main/java/org/hyperledger/besu/cli/util/TomlConfigurationDefaultProvider.java

There is a bug introduced by [#6700](https://github.com/hyperledger/besu/pull/6700) that prevents plugin CLI options from being used in config files. 
Move `checkUnknownOptions` to happen after the plugins register their custom CLI options.

Move unknown options check further in the startup

---

metrics/core/src/main/java/org/hyperledger/besu/metrics/MetricCategoryRegistryImpl.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/MetricsConfigurationModule.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/MetricsSystemModule.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/noop/NoOpMetricsSystem.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/noop/NoOpValueCollector.java
metrics/rocksdb/src/main/java/org/hyperledger/besu/metrics/rocksdb/RocksDBStats.java
nat/src/main/java/org/hyperledger/besu/nat/docker/DockerDetector.java
nat/src/main/java/org/hyperledger/besu/nat/docker/HostBasedIpDetector.java
nat/src/main/java/org/hyperledger/besu/nat/kubernetes/KubernetesDetector.java
pki/src/main/java/org/hyperledger/besu/pki/crl/CRLUtil.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/configuration/RocksDBConfigurationBuilder.java
services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/InMemoryStoragePlugin.java
services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/SegmentedInMemoryKeyValueStorage.java
testutil/src/main/java/org/hyperledger/besu/kvstore/AbstractKeyValueStorageTest.java
testutil/src/main/java/org/hyperledger/besu/testutil/MockExecutorService.java
testutil/src/main/java/org/hyperledger/besu/testutil/MockScheduledExecutor.java
testutil/src/main/java/org/hyperledger/enclave/testutil/EnclaveKeyUtils.java
testutil/src/main/java/org/hyperledger/enclave/testutil/TesseraTestHarnessFactory.java

build: Add default constructor and javadoc for metrics, nat, pki, plugins, services, testutil, util

build: Add default constructor and javadoc for metrics, nat, pki, plugins, services, testutil, util

---

plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/data/BlockTraceResult.java

javadoc - Adding default constructor and javadoc for :plugin-api

javadoc - Adding default constructor and javadoc for :plugin-api

---

docker/Dockerfile
ethereum/evmtool/src/main/docker/Dockerfile

A recent modification in the Dockerfiles triggers a linting error which fails the pipeline running on the `main` branch. Ignoring the rule seems a bad idea, because it is enforcing that all packages which are installed via apt-get have a defined version number, which is a best practice.
Instead I have opted for replacing the ENV variable which triggers the error with the respective string.

do not use NO_PROXY_CACHE env variable with apt-get install to avoid a linting error

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/chainimport/JsonBlockImporter.java
consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueMinerExecutorTest.java
consensus/common/src/main/java/org/hyperledger/besu/consensus/common/MigratingMiningCoordinator.java
consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/blockcreation/BftBlockCreatorFactory.java
consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/blockcreation/BftMiningCoordinator.java
consensus/common/src/test/java/org/hyperledger/besu/consensus/common/MigratingMiningCoordinatorTest.java
consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/blockcreation/BftMiningCoordinatorTest.java
consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/TransitionCoordinator.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/miner/MinerGetExtraData.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/miner/MinerSetExtraData.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/MinerJsonRpcMethods.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/miner/MinerGetExtraDataTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/miner/MinerSetExtraDataTest.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractMinerExecutor.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractMiningCoordinator.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/MiningCoordinator.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/NoopMiningCoordinator.java

Add two new RPC methods to get and set the vanity extra data that goes into the related field of a built block.
`miner_getExtraData` request has no parameters, and the response is the hex string of the extra data bytes
`miner_setExtraData` request has only 1 parameter: the hex string of the extra data bytes.

New RPC methods `miner_setExtraData` and `miner_getExtraData`

---

acceptance-tests/tests/src/test/resources/jsonrpc/engine/prague/test-cases/06_prague_getPayloadV4.json
acceptance-tests/tests/src/test/resources/jsonrpc/engine/prague/test-cases/09_prague_newPayloadV4.json
acceptance-tests/tests/src/test/resources/jsonrpc/engine/prague/test-cases/15_prague_getPayloadV4.json
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalRequestParameter.java

The name of the parameter should be `validatorPublicKey`. This change https://github.com/hyperledger/besu/pull/7121/commits/7e78da631a24a55f990a58dfdcb7f63ca95b0267 tried to fix it but only made the change in the @JsonProperty in the constructor, that is used for deserialization.
To fix this, we need to fix it on the getter method with the @JsonGetter annotation. This is what is used for serialization and infers the name of the field from the name of the getter method. So `getValidatorPublicKey` becomes `validatorPublicKey` when serializing to json.
I have also removed the method `asJsonObject` because it is not being used.

Fix name of parameter for WithdrawalRequest

---

.github/workflows/acceptance-tests.yml
.github/workflows/pre-review.yml
.github/workflows/splitTestsByTime.sh
acceptance-tests/tests/build.gradle
ethereum/api/build.gradle

This PR reduces the time of the `pre-review` workflow from ~30min to <20min, splitting unit tests by time, and removing the dependency between `compile` and `unit tests` since the Gradle cache is disabled and so test tasks need to recompile anyway.
Also reduced the number of ATs runners to 10 since the workflow takes only ~10min to complete.
Next step is to see if reference tests can be split by time as well.

Split unit tests by time

---

.github/workflows/acceptance-tests.yml
.github/workflows/pre-review.yml
.github/workflows/update-test-reports.yml

JUnit test reports are used to split acceptance and unit tests by time, but since these reports are only downloaded from main branch, and we do not run tests on main, it is necessary to just copy the reports from the last merge PR to the main branch, as done in this PR.
Note: since this PR is referencing some artifacts that are still not present on main (they will be after this PR is merged), tests are just split in a round robin way as fallback, and some download actions will report error.

Update JUnit test reports on PR merged on main

---

.github/workflows/dco.yml

DCO App not working and needed to be disabled the check. Introducing DCO GitHub action workflow to validate the commit signatures.
fixes #7175

DCO Check GitHub workflow

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/config/ProfileName.java
config/src/main/resources/profiles/enterprise-private.toml

Also remove lower casing of profile names to keep CLI string values consistent with other options

In enterprise profile, use sync-mode=FULL and data-storage-format=FOREST

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/options/stable/DataStorageOptions.java
besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
besu/src/test/java/org/hyperledger/besu/cli/options/stable/DataStorageOptionsTest.java
besu/src/test/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogHelperTest.java
besu/src/test/resources/everything_config.toml
config/src/main/resources/profiles/enterprise-private.toml
config/src/main/resources/profiles/minimalist-staker.toml

Create --bonsai-limit-trie-logs-enabled as alias of --Xbonsai-limit-trie-logs-enabled and unhide option
Same for bonsai-trie-logs-pruning-window-size
Remove --bonsai-historical-block-limit=512 from minimalist_staker profile so it inherits the default which is the same value
Follow on from #7181 
Will restructure code from Unstable -> Stable in next PR.

Promote option - bonsai-limit-trie-logs-enabled and bonsai-trie-logs-pruning-window-size

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/options/stable/DataStorageOptions.java
besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogHelper.java
besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
besu/src/test/java/org/hyperledger/besu/cli/options/stable/DataStorageOptionsTest.java
besu/src/test/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogHelperTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DataStorageConfiguration.java

Also --bonsai-trie-logs-pruning-window-size
Following https://github.com/hyperledger/besu/pull/7181 and https://github.com/hyperledger/besu/pull/7192

Promote --bonsai-limit-trie-logs-enabled to stable

---

ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSDaemon.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSResolver.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSDaemonTest.java

Refactor Node DNS Resolver to use vertx virtual threads (Java 21).

feat: Refactor Node DNS Resolver to use vertx virtual threads

---

ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSDaemonTest.java

Disable this test since it's blocking PRs
refs #7201

disable flaky test - DNSDaemon periodic

---

acceptance-tests/tests/src/test/resources/jsonrpc/engine/prague/test-cases/06_prague_getPayloadV4.json
acceptance-tests/tests/src/test/resources/jsonrpc/engine/prague/test-cases/09_prague_newPayloadV4.json
acceptance-tests/tests/src/test/resources/jsonrpc/engine/prague/test-cases/15_prague_getPayloadV4.json
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalRequestParameter.java

Updated WithdrawalRequestV1 field according to https://github.com/ethereum/execution-apis/pull/549.
(validatorPublicKey -> validatorPubkey)
This will soon be updated in Teku as well (https://github.com/Consensys/teku/issues/8359)
N/A

Updated EIP-7002 WithdrawalRequestV1 field (validatorPublicKey -> validatorPubkey)

---

docker/Dockerfile

This reverts commit dfe256e6478a91122e40adda928a71e1353668f1.
Reverts https://github.com/hyperledger/besu/pull/7203
There's an issue running docker develop workflow
https://github.com/hyperledger/besu/actions/runs/9491467523
```
Run docker run --rm -i hadolint/hadolint < docker/Dockerfile
Unable to find image 'hadolint/hadolint:latest' locally
latest: Pulling from hadolint/hadolint
db4123164570: Pulling fs layer
db4123164570: Download complete
db4123164570: Pull complete
Digest: sha256:fff226bdf9ebcc08db47fb90ee144dd770120b35c2b1cbbb46e932a650cfe232
Status: Downloaded newer image for hadolint/hadolint:latest
-:7 DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
Error: Process completed with exit code 1.
```

Revert "Update Dockerfile - reuse NO_PROXY_CACHE env (#7203)"

---

.github/workflows/container-security-scan.yml

Repository follow standard to use git hash to pin the GitHub actions. Updated the container security scan workflow actions with their git hashes.
fix requested in [discord](https://discord.com/channels/905194001349627914/905205502940696607/1250837893040177175) message

fix: pin github actions in container security scan workflow

---

CHANGELOG.md

Add download links to 24.6.0 release and move changelog entries after 24.6.0 to next release section.

Changelog download links for 24.6.0 release and next release changelog

---

.github/workflows/release.yml

Release workflow publish step was missing the depepndency of artifacts jobs. Due to this reason it could not collect the artifact hashes from the artifacts job. This was introduced in the release workflow consolidation
fixes #7229

fix: update artifacts hash on release page

---

.github/workflows/container-security-scan.yml

Trivy scan result upload to GitHub fails due to permission issue. Added permission security-events=write to the workflow file as a fix. Since workflow permission explicitly defined, it requires contents=read explicity set as well

fix: workflow permission to upload trivy sarif report

---

.github/workflows/BesuContainerVerify.sh
.github/workflows/container-verify.yml
.github/workflows/release.yml

Container verification step in release process automated with the container verify GitHub workflow. New workflow is triggered at the end of the release workflow which will check the released container images starts successfully. Verification test only checks container starts and reach the Ethereum main loop.
fixes #7176

container verify GitHub workflow

---

ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/eof/EOFReferenceTestTools.java
evm/src/main/java/org/hyperledger/besu/evm/code/CodeV1Validation.java
evm/src/main/java/org/hyperledger/besu/evm/code/EOFLayout.java
evm/src/test/java/org/hyperledger/besu/evm/code/CodeFactoryTest.java
evm/src/test/java/org/hyperledger/besu/evm/code/EOFLayoutTest.java

Check and test for the unused container rule, and only returncontract
targets can have truncated data rule.
Also test the other subcontainer rules in unit tests.

Check for EOFCreate subcontainer rules

---

CHANGELOG.md

- This PR fixes some typos found in the changelog

chore: fix typos in changelog

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/SnapServer.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/snap/SnapServerTest.java

Allows snapsync server to GetTrieNodes request for storage to handle a hash with less than 32 bytes. It's not mentioned in the snap sync spec but Geth handles such requests and the hive tests rely on this behaviour. Implementing this fixes a hive test case.

Snapserver GetTrieNodes request to handle short hash for storage

---

besu/src/main/java/org/hyperledger/besu/cli/logging/XmlExtensionConfiguration.java
build.gradle
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/EthStatsService.java
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/authentication/AuthenticationData.java
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/authentication/NodeInfo.java
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/report/BlockReport.java
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/report/HistoryReport.java
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/report/LatencyReport.java
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/report/NodeStatsReport.java
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/report/PendingTransactionsReport.java
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/report/PingReport.java
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/request/EthStatsRequest.java
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/util/EthStatsConnectOptions.java
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/util/PrimusHeartBeatsHelper.java
ethereum/evmtool/src/main/resources/log4j2.xml
util/build.gradle
util/src/main/java/org/hyperledger/besu/util/log4j/plugin/BesuLogMessageConverter.java
util/src/test/java/org/hyperledger/besu/util/log4j/plugin/BesuLogMessageConverterTest.java

javadoc: Adding javadoc for ethstats module. Enabled javadoc lint check for ethstats package
`./gradlew :ethereum:ethstats:javadoc` should not return any errors.

javadoc: Adding javadoc for ethstats module

---

CHANGELOG.md
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningV2AcceptanceTest.java
besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java

This PR adds the bootnodes to the maintained-peer list in a permissioned chain. Currently the maintained node list only contains static nodes and nodes added with `admin_addPeer`. Adding bootnodes to the maintained list ensures that if a bootnode is offline when the node starts, it will retry its connection once a minute rather than requiring a restart.
Bootnode connectivity in a public-chain node remains unchanged.
Fixes https://github.com/hyperledger/besu/issues/7261
Based on the outcome of this PR, I plan to raise a docs PR to describe how connections are maintained to bootnodes and static nodes since there isn't much detail covering the behaviour today. I'll wait for the outcome of this PR before raising the docs changes though.

Add bootnodes to the maintained peer list

---

ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nExecutor.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/BlockchainReferenceTestCaseSpec.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestEnv.java

Update t8n executor to support new isStateTest env flag that will
disable extra-transactional processing such as block rewards and beacon
root. Also, make sure such extra-transactional commits don't create 
empty accounts.

T8n support for isStateTest and empty accounts

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogSubCommand.java

Following https://github.com/hyperledger/besu/pull/7193

Promote storage x-trie-log subcommand to trie-log

---

evm/src/main/java/org/hyperledger/besu/evm/worldstate/UpdateTrackingAccount.java
evm/src/main/java/org/hyperledger/besu/evm/worldstate/WorldUpdater.java

Consider previously self-destructed accounts when creating accounts.

Deeper tracing of self-destructed accounts

---

README.md

Documentation has been moved to GitHub pages and no longer use readthedocs. Updated the README status badge for docs with correct link
fixes #7303

Fix status badge for documentation

---

plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java

we can safely stop transaction selection for block creation after a `TX_EVALUATION_TOO_LONG`, since it means that the tx took more that the block selection timeout to evaluate, and so does not make sense to continue the evaluation.

Stop transaction selection on `TX_EVALUATION_TOO_LONG`

---

CHANGELOG.md
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlobSizeTransactionSelector.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlockSizeTransactionSelector.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlobSizeTransactionSelectorTest.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java

The main goal of this PR is to make clearer the reason a blob tx is not selected during block creation, with the introduction of 2 specifics not selected results:
- BLOBS_FULL = The block already contains the max number of allowed blobs.
- TX_TOO_LARGE_FOR_REMAINING_DATA_GAS = The transaction has not been selected since there is not enough remaining data gas in the block to fit the blobs of the tx.
and to achieve that it was clearer to extract the blob tx selection login in its own class `BlobSizeTransactionSelector`, while doing that a small bug was fixed, since data gas used was added to gas used when computing if a block was full, while these 2 gas types are independent, [see here for details](https://github.com/hyperledger/besu/pull/7312/files#r1677540274).

Improve blob size transaction selector

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/common/trielog/TrieLogPruner.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/diffbased/bonsai/trielog/TrieLogPrunerTest.java

Add 3 counters, can be referenced in grafana with:
besu_pruner_trie_log_added_to_prune_queue_total
besu_pruner_trie_log_pruned_from_queue_total
besu_pruner_trie_log_pruned_trie_log_pruned_orphan_total

Add metrics for trie log pruner

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogSubCommand.java
besu/src/test/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogSubCommandTest.java

This avoids executing TrieLogPruner.preload unnecessarily during execution of the various trie log subcommands.

Disable limit trie logs for trie log subcommand

---

ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/StateTestSubCommand.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/GeneralStateTestCaseEipSpec.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/GeneralStateTestCaseSpec.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/GeneralStateReferenceTestTools.java

In linea arithmetization we are updating unit tests to use the GeneralStateTestCaseEipSpec for testing. For that I need to 
1. Update the constructor to public so that it can be instantiated in other packages.
2. Include multiple transactions as we have unit tests that test multiple transactions.

Update GeneralStateTestCaseEipSpec for use in linea-arithmetization

---

consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/jsonrpc/methods/DiscardTest.java
consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/jsonrpc/methods/ProposeTest.java
ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/DebugTraceTransactionIntegrationTest.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/handlers/JsonRpcArrayExecutor.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/handlers/JsonRpcObjectExecutor.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/execution/TracedJsonRpcProcessor.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcErrorResponse.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcNoResponse.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcResponse.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcSuccessResponse.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcUnauthorizedResponse.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/ipc/JsonRpcIpcService.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketMessageHandler.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockByNumberTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdatedTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeCapabilitiesTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfigurationTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadBodiesByHashV1Test.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadBodiesByRangeV1Test.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/MultiTenancyRpcMethodDecoratorTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivDebugGetStateRootTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/MutableJsonRpcSuccessResponse.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/PrivacyApiGroupJsonRpcMethodsTest.java
ethereum/retesteth/src/test/java/org/hyperledger/besu/ethereum/retesteth/methods/TestImportRawBlockTest.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/rpc/RpcResponseType.java

This PR has is preparatory for PR https://github.com/hyperledger/besu/pull/7379/, to make the latter easier to review, there are no functional changes here, but just the move `JsonRpcResponseType` to `RpcResponseType` in the plugin API module.

Move `JsonRpcResponseType` to `RpcResponseType` in the plugin API module

---

acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/ethereum/SetCodeTransactionAcceptanceTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AuthorityProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java

Process the authority list before increasing the sender nonce, make sure that the updated balance of the sender is calculated correctly if they sign an authorization as well
fixes #7391

7702 bugfixes for devnet-1

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/common/trielog/TrieLogPruner.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/diffbased/common/trielog/TrieLogPrunerTest.java

An improved version of https://github.com/hyperledger/besu/pull/7365
Example of INFO level logging during timeout...
```
{"@timestamp":"2024-07-29T11:58:49,398","level":"INFO","thread":"main","class":"TrieLogPruner","message":"Trie log pruner queue preload starting...","throwable":""}
{"@timestamp":"2024-07-29T11:58:49,399","level":"INFO","thread":"main","class":"TrieLogPruner","message":"Attempting to load first 5000 trie logs from database...","throwable":""}
{"@timestamp":"2024-07-29T11:58:49,400","level":"INFO","thread":"main","class":"TrieLogPruner","message":"Trie log pruning will timeout after 30 seconds. If this is timing out, consider using `besu storage trie-log prune` subcommand, see https://besu.hyperledger.org/public-networks/how-to/bonsai-limit-trie-logs","throwable":""} …
```

Refactor TrieLogPruner preload timeout to be more testable

---

evm/src/main/java/org/hyperledger/besu/evm/code/EOFLayout.java

EOF subcontainer parsing was recursive, potentially opening up stack
attacks. 
Replace subcontainer parsing with a flat iterative solution.

Change EOF Parsing to be non-recursive

---

CHANGELOG.md
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/BesuNode.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeConfiguration.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeConfigurationBuilder.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeFactory.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/NodeConfigurationFactory.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyNode.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/miner/MinerGetMinGasPriceTransaction.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/miner/MinerRequestFactory.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/miner/MinerTransactions.java
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestInProcessRpcServicePlugin.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/InProcessRpcServicePluginTest.java
besu/src/main/java/org/hyperledger/besu/Runner.java
besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/options/unstable/InProcessRpcOptions.java
besu/src/main/java/org/hyperledger/besu/services/RpcEndpointServiceImpl.java
besu/src/test/java/org/hyperledger/besu/RunnerBuilderTest.java
besu/src/test/java/org/hyperledger/besu/RunnerTest.java
besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/InProcessRpcConfiguration.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/RpcEndpointService.java
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/rpc/PluginRpcRequest.java
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/rpc/PluginRpcResponse.java
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/rpc/RpcResponse.java

Expose a way to call RPC method in process, so they can be invoked by plugins without the overhead of the network (or native socket) and the json (de)serialization.
The interface is still fragile, because RPC method inputs and outputs are not typed, but just Object, so a next step will be to make them typed so plugins will discover at compile time that something is broken, but that will be address in another PR.
Do not be scared by the amount of file changed since many are due to the move of some classes in the plugin-api module.
This feature is disabled by default and can be enabled setting the new experimental flag `Xin-process-rpc-enabled=true`, and to enabled specific RPC namespaces use the new experimental option `Xin-process-rpc-apis` with a comma separated list of namespaces.

In process RPC service

---

evm/src/main/java/org/hyperledger/besu/evm/fluent/EVMExecutor.java
evm/src/main/java/org/hyperledger/besu/evm/precompile/KZGPointEvalPrecompiledContract.java

- Addresses an issue in the Fluent API where certain EVM bytecode could lead to executions that mismatch canonical execution.
- Uses `LOG.debug` instead of `System.out.println` to prevent console spam during fuzzing.
Both lines were written by @shemnon, he can provide more information if required.

Small fuzzing fixes

---

ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/PrettyPrintSubCommand.java
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/pretty-print/dangling-data.json
evm/src/main/java/org/hyperledger/besu/evm/code/CodeV1Validation.java
evm/src/main/java/org/hyperledger/besu/evm/code/EOFLayout.java
evm/src/test/java/org/hyperledger/besu/evm/code/CodeV1Test.java
evm/src/test/java/org/hyperledger/besu/evm/code/EOFLayoutTest.java

Ensure forward calls stack height range is preserved.

EOF Validation stack heights

---

ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/CodeValidateSubCommand.java
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/code-validate/initcode.json

Update how newlines are handled for fuzzing CLI tools.

Update newling handling in fuzzing CLI tools

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/controller/TransitionBesuControllerBuilder.java

Let me start by saying that I don't fully understand the intricacies of the `TransitionCoodinator`, so it is possible that this PR is going in the wrong direction. However, after analyzing the changes on https://github.com/hyperledger/besu/pull/6027 I noticed that we have changed the existing behaviour when we are on a pre-merge network. This was caught by one of our tests in Teku that tests the merge transition, when I was trying to upgrade the version of Besu we use in our ATs (we are using 23.10.1).
In the code before commit 20a82d45482194129e68133973533c290be8eb1c, we were building a copy of `MiningParameters` using the instance of mining parameter that was passed as a parameter, that contains the options specified by the user. In this particular case, I am focusing on the …

Restore previous behaviour for preMergeBesuControllerBuilder

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AuthorityProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateMutableWorldStateUpdater.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/common/worldview/accumulator/DiffBasedWorldStateUpdateAccumulator.java
evm/src/main/java/org/hyperledger/besu/evm/fluent/SimpleWorld.java
evm/src/main/java/org/hyperledger/besu/evm/frame/MessageFrame.java
evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCallOperation.java
evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCreateOperation.java
evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractExtCallOperation.java
evm/src/main/java/org/hyperledger/besu/evm/worldstate/AbstractWorldUpdater.java
evm/src/main/java/org/hyperledger/besu/evm/worldstate/EVMWorldUpdater.java
evm/src/main/java/org/hyperledger/besu/evm/worldstate/JournaledUpdater.java
evm/src/main/java/org/hyperledger/besu/evm/worldstate/WorldUpdater.java
evm/src/test/java/org/hyperledger/besu/evm/toy/ToyWorld.java

In a first version of 7702 the code injection into the EOA accounts required every class that implements the `WorldUpdater` interface to have the correct plumbing to inject that code from 7702 transactions. This PR introduces a new world updater `EVMWorldUpdater` which wraps the actual world updater and the code injection only needs to happen in this new wrapper. The previous code injection is removed from the other world updaters.

Wrapped WorldUpdater into `EVMWorldupdater`

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
crypto/algorithms/src/main/java/org/hyperledger/besu/crypto/AbstractSECP256.java
crypto/algorithms/src/main/java/org/hyperledger/besu/crypto/Blake2bfMessageDigest.java
crypto/algorithms/src/main/java/org/hyperledger/besu/crypto/SECP256K1.java
crypto/algorithms/src/main/java/org/hyperledger/besu/crypto/SECP256R1.java
crypto/algorithms/src/main/java/org/hyperledger/besu/crypto/SignatureAlgorithm.java
crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/SECP256R1Test.java
evm/src/test/java/org/hyperledger/besu/evm/precompile/AltBN128PairingPrecompiledContractTest.java
evm/src/test/java/org/hyperledger/besu/evm/precompile/BLAKE2BFPrecompileContractTest.java
evm/src/test/java/org/hyperledger/besu/evm/precompile/ECRECPrecompiledContractTest.java
evm/src/test/java/org/hyperledger/besu/evm/precompile/MODEXPPrecompiledContractTest.java

For tests that have a native/java switch ensure that the java path gets
the same tests native paths do.

Add test coverage for java precompiles

---

ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/CodeValidateSubCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommandOptionsModule.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/GenesisFileModule.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/MainnetGenesisFileModule.java
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/badcode.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/charge-intrinsic.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/coinbase-cold.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/coinbase-warm.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/create-eof.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/eof-section.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/eof.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/revert.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/warm-contract.json
evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractExtCallOperation.java
evm/src/main/java/org/hyperledger/besu/evm/tracing/StandardJsonTracer.java

A lot of small nitpicks for standard tracing conformance
* Change evmtool run defaults to mirror go-ethereum's choices
* Add fields to run summary
* Make EOF PC zero to section
* Correct EXT*CALL min gas

EIP-3155 Last Call Nitpicks

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/diff/StateDiffGenerator.java
evm/src/main/java/org/hyperledger/besu/evm/processor/MessageCallProcessor.java
evm/src/test/java/org/hyperledger/besu/evm/processor/MessageCallProcessorTest.java

This fixes a tracing problem while replaying a transaction that executes a precompiled contract but it runs out of gas. We were getting an empty `TraceFrame` array back from the tracer because the halt condition was never traced.
fixes #7318

Precompile calls were not traced when insuficient gas

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/options/stable/MetricsOptionGroup.java

Pulls MetricsOptionGroup out into its own class.
Renames `controllerBuilderFactory` to the more accurate `controllerBuilder`

isolates MetricsOptionGroup for future reusability, minor renaming

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGasPriceTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/Blockchain.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchain.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/t8n/T8nBlockchain.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestBlockchain.java

As well explained by @matthew1001 [here](https://github.com/hyperledger/besu/issues/7287#issuecomment-2244649612), since in PR https://github.com/hyperledger/besu/pull/7102, the current chain head is correctly included in the computation of the gasPrice, it could happen that the chain head block body is still not persisted, so in order to always retrieve it successfully we first try optimistically, then if not found, the new `getBlockBodySafe` that is synchronized and so will wait until the pending persist operation is done.
fixes #7287

Fix BlockchainQueries::gasPrice when chain head block body still not fully persisted

---

.github/workflows/release.yml

pre-process release title in release actions to ensure it conforms to a besu release version and trim any leading or trailing spaces
Tested on forked repo with a variety of whitespace and failure modes.

CI Fix: Preprocess release title in gha

---

CHANGELOG.md
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockSelectionContext.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/TransactionEvaluationContext.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlockSizeTransactionSelector.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/MinPriorityFeePerGasTransactionSelector.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/MinPriorityFeePerGasTransactionSelectorTest.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlobSizeTransactionSelectorTest.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/txselection/TransactionEvaluationContext.java

Add pending block header to `TransactionEvaluationContext` plugin API, so `PluginTransactionSelector` can access info of the pending block

Add pending block header to `TransactionEvaluationContext`

---

CONTRIBUTING.md

The page https://wiki.hyperledger.org/display/BESU/Roadmap is not working anymore. Replaced it with new page.

Contributing: fix wiki

---

ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/BlockchainTestSubCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/CodeValidateSubCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EOFTestSubCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/PrettyPrintSubCommand.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/StateTestSubCommand.java
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/create-eof-error.json
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestProtocolSchedules.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/core/TransactionTest.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/eof/EOFReferenceTestTools.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/GeneralStateReferenceTestTools.java
ethereum/referencetests/src/reference-test/templates/EOFReferenceTest.java.template
evm/src/main/java/org/hyperledger/besu/evm/code/CodeV1Validation.java
evm/src/main/java/org/hyperledger/besu/evm/code/EOFLayout.java
evm/src/test/java/org/hyperledger/besu/evm/code/CodeFactoryTest.java
evm/src/test/java/org/hyperledger/besu/evm/code/CodeV1Test.java

Update the EOF validation error strings so that they can validate
against expected exceptions.

Update EOF validation error strings

---

acceptance-tests/tests/src/test/resources/jsonrpc/engine/shanghai/test-cases/05_shanghai_prepare_payload_invalid_null_withdrawals.json
acceptance-tests/tests/src/test/resources/jsonrpc/engine/shanghai/test-cases/09_shanghai_newPayloadV2_invalid_null_withdrawals.json

Updated error message in json test files "invalid withdrawals"
fixes #7492

update error message in test files

---

acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/AcceptanceTestBase.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/AcceptanceTestBaseJunit5.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/AbstractJsonRpcTest.java

Related to this https://github.com/hyperledger/besu/pull/7317, we need to add a dummy @Test to be sure parameterized ATs are selected, at least until https://github.com/gradle/gradle/issues/29895 is fixed
fixes #7490

Update parameterized acceptance tests so they enumerate with --dry-run

---

acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java

Update the test node runners to use whatever the test has configured for data storage config, not hard-coded FOREST defaults
Looking at the test code the tests all configure the node's configuration with the FOREST default anyway, so this change should have no affect on its own but it allows tests to pass in BONSAI and have that setting honoured (e.g. see draft PR https://github.com/hyperledger/besu/pull/7496 which requires this PR)

For test node runners use provided data storage config

---

docs/tracing/README.md

The opentelemetry-specification had a reactor. we should update the outdated link

tracing: update outdated link

---

besu/src/main/java/org/hyperledger/besu/services/SynchronizationServiceImpl.java

make fireNewUnverifiedForkchoiceEvent() method in SynchronizationServiceImpl safe for use not-in-the-context-of post merge networks.

Fleet-mode safe behavior for fcU in SynchronizationService

---

ethereum/evmtool/src/test/java/org/hyperledger/besu/evmtool/CodeValidationSubCommandTest.java
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/pretty-print/dangling-data.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/state-test/create-invalid-eof.json
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/eof/EOFReferenceTestTools.java
evm/src/main/java/org/hyperledger/besu/evm/code/EOFLayout.java
evm/src/test/java/org/hyperledger/besu/evm/code/CodeV1Test.java
evm/src/test/java/org/hyperledger/besu/evm/code/EOFLayoutTest.java

Update the eof layout error codes to match codes in reference tests.
This includes support for multiple possible errors for a specific test.

EOF testing error codes for layout

---

evm/src/main/java/org/hyperledger/besu/evm/ClassicEVMs.java
evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java
evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCreateOperation.java
evm/src/main/java/org/hyperledger/besu/evm/operation/Create2Operation.java
evm/src/main/java/org/hyperledger/besu/evm/operation/CreateOperation.java
evm/src/main/java/org/hyperledger/besu/evm/operation/EOFCreateOperation.java
evm/src/test/java/org/hyperledger/besu/evm/operation/AbstractCreateOperationTest.java
evm/src/test/java/org/hyperledger/besu/evm/operation/Create2OperationTest.java
evm/src/test/java/org/hyperledger/besu/evm/operation/CreateOperationTest.java

Refactor the max code size to no longer be a part of the operation but
instead is queried from the EVM version specification.

Refactor max code size

---

CHANGELOG.md
evm/src/main/java/org/hyperledger/besu/evm/precompile/AltBN128MulPrecompiledContract.java

Highlighted by [arewefastyet report](https://arewefastyet.report/?timerange=Last+year,365&category=Gas+Benchmarks,gas&testcase=ALL,all&clients=besu), this PR addresses a recent regression in performance for eip-196 scalar multiplication when the point is at infinity
local testing shows significant improvement for these benchmarks:
  | 24.6.0 | 24.7.1 | 24.8.0 | 24.8-develop
-- | -- | -- | -- | -- 
EcMulInfinities2Scalar | 1455.8 | 381.58 | 390.36 | 2526.56
EcMulInfinities32ByteScalar | 1246.28 | 242.1 | 245.67 | 2478.99

Check for infinity in eip-196 ecmul

---

build.gradle

Attempts to fix an issue in which a supplied version already has a commit hash appended and existing code was appending a second commit hash.

Check for commit hash before appending another in build.gradle calculateVersion

---

build.gradle

Noticed in a PR for a hasty fix (https://github.com/hyperledger/besu/pull/7548) that the VCS_REF passed to docker build was unintentionally lengthened to 8 chars, when it should have stayed 7 chars.

Set docker VCS_REF back to a 7 char hash

---

evm/src/main/java/org/hyperledger/besu/evm/fluent/SimpleAccount.java
evm/src/main/java/org/hyperledger/besu/evm/fluent/SimpleWorld.java
evm/src/test/java/org/hyperledger/besu/evm/fluent/SimpleWorldTest.java

Fix several NPEs in `SimpleWorld` and I also decided to use `Optional` for accounts since the return from `get`/`getAccount` was ambiguous between an account that has been deleted or has never existed. Now there's a clear distinction between deleted (`Optional.empty()`) or has never existed (`null`). Also `getTouchedAccounts` returned null values when there were deleted accounts within which can be dangerous to the caller.
Note: `SimpleWorld` seems to only be used by the test framework, so this is not critical.
fixes #7524

refactor SimpleWorld to use Optional for storing accounts and extra null checks

---

.github/workflows/acceptance-tests.yml
.github/workflows/pre-review.yml

Added new GHA job to upload HTML test reports on every run, even if tests fail, so it will be easier to investigate why a test is failing on CI. 
This already helped fixing https://github.com/hyperledger/besu/issues/7525
fixes  #7540

CI: new job to upload HTML test reports even if tests fail

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/eof/EOFReferenceTestTools.java
evm/src/main/java/org/hyperledger/besu/evm/EVM.java
evm/src/main/java/org/hyperledger/besu/evm/contractvalidation/MaxCodeSizeRule.java
evm/src/main/java/org/hyperledger/besu/evm/fluent/EVMExecutor.java
evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCreateOperation.java
evm/src/main/java/org/hyperledger/besu/evm/operation/ReturnContractOperation.java
evm/src/test/java/org/hyperledger/besu/evm/processor/ContractCreationProcessorTest.java

Restore lost functionality: the maxcodesize and maxinitcodesize should
be plumed into the operations and validation rules when set.

Plumb maxCode overriddes into EVM

---

acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/perm/AllowListContainsKeyAndValue.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyNode.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/bootstrap/ClusterThreadNodeRunnerAcceptanceTest.java
besu/build.gradle
besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
besu/src/main/java/org/hyperledger/besu/services/PermissioningServiceImpl.java
besu/src/main/java/org/hyperledger/besu/services/SecurityModuleServiceImpl.java
besu/src/main/java/org/hyperledger/besu/services/StorageServiceImpl.java
besu/src/main/java/org/hyperledger/besu/services/TransactionPoolValidatorServiceImpl.java
besu/src/main/java/org/hyperledger/besu/services/TransactionSelectionServiceImpl.java
besu/src/test/java/org/hyperledger/besu/FlexGroupPrivacyTest.java
besu/src/test/java/org/hyperledger/besu/PrivacyReorgTest.java
besu/src/test/java/org/hyperledger/besu/RunnerTest.java
besu/src/test/java/org/hyperledger/besu/chainexport/RlpBlockExporterTest.java
besu/src/test/java/org/hyperledger/besu/chainimport/JsonBlockImporterTest.java
besu/src/test/java/org/hyperledger/besu/chainimport/RlpBlockImporterTest.java
besu/src/test/java/org/hyperledger/besu/components/EnclaveModule.java
besu/src/test/java/org/hyperledger/besu/components/GenesisConfigModule.java
besu/src/test/java/org/hyperledger/besu/components/MockBesuCommandModule.java
besu/src/test/java/org/hyperledger/besu/components/NoOpMetricsSystemModule.java
besu/src/test/java/org/hyperledger/besu/components/PrivacyParametersModule.java
besu/src/test/java/org/hyperledger/besu/components/PrivacyTestModule.java
besu/src/test/java/org/hyperledger/besu/controller/AbstractBftBesuControllerBuilderTest.java
besu/src/test/java/org/hyperledger/besu/controller/CliqueBesuControllerBuilderTest.java
besu/src/test/java/org/hyperledger/besu/controller/MergeBesuControllerBuilderTest.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/peers/EnodeURLImpl.java

re-attempt of pr #7341 with better support for linea.
- Separate out flex group privacy test since it requires differently configured dependencies.
- test specific, inline module/component definitions
- reusable module for providing mockable enclaves, besu commands, and genesis
- dagger support for transaction simulation
- dagger support for plugin setup

Dagger controller tests

---

ethereum/referencetests/build.gradle
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/eof/EOFReferenceTestTools.java

Updates the reference tests to 14.1, which mostly consists of removing
duplicate tests covered by execution-spec-tests or invalid tests from
EOF portions of the prague tests.

Update reference tests to 14.1

---

ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayersTest.java

`EthScheduler` was created with a `txWorkerQueueSize=1` with the result that some submitted tests could be rejected, failing the test, preventing this using the `DeterministicEthScheduler`
fixes #7525

Fix LayersTest flaky test by using the `DeterministicEthScheduler`

---

CHANGELOG.md

Besu docs used to be part of besu repo.
This is why documentation updates are listed in the besu changelog for older versions of besu
This PR removes those entries from the changelog - no longer relevant and also containing links that are likely to be or become out of date.

[CHANGELOG] remove docs updates from changelog

---

acceptance-tests/tests/src/test/resources/jsonrpc/engine/prague/test-cases/16_prague_getPayloadV4.json
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/ConsolidationRequestParameter.java

Fixing the serialization of `ConsolidationRequestV1`. The casing on `sourcePubkey` and `targetPubkey` was wrong (it was using capital `K`).
Reference: https://github.com/ethereum/execution-apis/blob/main/src/engine/prague.md#consolidationrequestv1
N/A

Fix consolidation request json key casing

---

CHANGELOG.md
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolMetrics.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/AbstractSequentialTransactionsLayer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/AbstractTransactionsLayer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/BaseFeePrioritizedTransactions.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/EndLayer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/TransactionsLayer.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/AbstractPrioritizedTransactionsTestBase.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/BaseTransactionPoolTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/EvictCollectorLayer.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactionsTest.java

Notifications for tx added to the layered txpool were incorrectly sent also when the tx was already added and was just internally moved between layers, potentially resulting in duplicated notifications.
Tests for this change are part of the following PR #7538 that is also fixing the drop notifications.

Layered txpool: do not send notifications when moving tx between layers

---

acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/ethereum/CodeDelegationTransactionAcceptanceTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
evm/src/main/java/org/hyperledger/besu/evm/worldstate/DelegatedCodeService.java

Transactions from account with delegated code are currently not validated correctly. This PR makes sure that those accounts can send tx, as specified in EIP-7702.

Fix tx validation if sender has delegated it's code via 7702 transaction

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchain.java

feat: exported metrics for current finalized and safe block number

---

.github/workflows/release.yml

Fixes pre-processed release name propagation in the release workflow jobs via a dedicated preprocessing job.
Post-24.8.0 release, preprocessing of release names was added to ensure they are well formed.  The envar method of propagation is limited to a single job however.  Subsequent release workflow jobs do not have this value and are failing.
This PR:
* moves release name preprocessing to its own job
* makes release_name a job output
* for each job that require an explicit release version:
* adds a dependency on `pre_process_release_name`
* declares an envar RELEASE_NAME from the output of the preprocess_release_name job
Verified on a [fork](https://github.com/garyschulte/besu/actions/runs/10801154312/job/29961599252) that release name is propagated to the dependent jobs:

CI Fix, propagate release name preprocessing

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchain.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchainTest.java

This complements PR https://github.com/hyperledger/besu/pull/7601 to make sure possible NPEs are checked during unit tests around `DefaultBlockchain` when the right order of initialization is not followed.

Change test to tease NPEs during DefaultBlockchain.<init>() caused by initilization order

---

besu/src/test/java/org/hyperledger/besu/cli/TxPoolOptionsTest.java

This reverts commit 07adb415eec5341fe22442ac9938e7f7b8a9de11.
this test is failing again in CI https://github.com/hyperledger/besu/actions/runs/10830553170/job/30055039117#step:13:324, 
the test seems to fail only in specific conditions, so it is hard to reproduce the failure, so until there is a fix when need to disable it to be able to merge PRs.
The test seems to fail only in specific conditions, so it is hard to reproduce the failure.
related to #7451

Revert "Re-enable TxPoolOptionsTest::txpoolForcePriceBumpToZeroWhenZeroBaseFeeMarket (#7565)"

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java

Fix logging the evaluation time when a tx is selected for block creation

---

docker/Dockerfile

Suppressing/Ignoring hadolint warning about the last USER in Dockerfile being the root user - with reasoning that the root user has very specific job to do and then besu runs as besu user . 
Follow up to https://github.com/hyperledger/besu/pull/7575
Follow up fix to #4292

Handle hadolint check failure with proper risk assessment

---

MAINTAINERS.md

I am no longer aligned with the Governance policies and practices of 
LFDT and resign my position as maintainer.

Remove Danno Ferrin as maintainer

---

.github/workflows/acceptance-tests.yml
crypto/algorithms/src/main/java/org/hyperledger/besu/crypto/AbstractSECP256.java
crypto/algorithms/src/main/java/org/hyperledger/besu/crypto/CodeDelegationSignature.java
crypto/algorithms/src/main/java/org/hyperledger/besu/crypto/SignatureAlgorithm.java
crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/CodeDelegationSignatureTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/CodeDelegationTransactionDecoder.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/encoding/CodeDelegationDecoderTest.java

7702 signatures have different bound checks than regular transaction signatures. This PR create a new signature class for them with their own checks.

Fix 7702 signature bound checks

---

docker/tests/02/goss_wait.yaml

Follow up of #7575, this fixes the current issue building Docker images on CI

Wait for Besu to be up before running Goss Docker test 02

---

.github/workflows/acceptance-tests.yml
.github/workflows/pre-review.yml
.github/workflows/reference-tests.yml

Rebalance GHA runners to reduce ATs failure and speedup unit tests

---

.github/workflows/acceptance-tests.yml
.github/workflows/pre-review.yml
.github/workflows/reference-tests.yml

Missed to update the `runner_index` arrays

Rebalance GHA runners to reduce ATs failure and speedup unit tests [part 2]

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java

This PR allows changing the log level when the RPC gas limit is modified during a transaction simulation.

change set rpc gas limit log level during transaction simulation 

---

README.md

This page https://wiki.hyperledger.org/display/BESU/Hyperledger+Besu is now https://wiki.hyperledger.org/display/BESU/Besu - I've asked for a redirect to be setup as well but for now it's a broken link

[README] fix broken wiki link

---

ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSDaemonTest.java

fix: Fix DNSDaemonTest - remove flaky assertion
fixes #7690

fix: Fix DNSDaemonTest - remove flaky assertion

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/verkle/worldview/VerkleWorldState.java
ethereum/verkletrie/src/main/java/org/hyperledger/besu/ethereum/verkletrie/VerkleEntryFactory.java
gradle/versions.gradle

This PR addresses 2 noted issues:
- See PR from [besu-verkle-trie](https://github.com/hyperledger/besu-verkle-trie/pull/70) for fixing BASIC_DATA_LEAF encoding.
- Code hash even if code is empty needs to be inserted in the tree on account creation.

Fix verkle state root calculation

---

build.gradle

Removes enabling .jfr capture on every process started by acceptanceTest targets. This can still be added via any other target, or even explicitly via command line per-run.

dont' activate flight recorder dumps by default, RIP my ssd

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulatorTest.java

A recent PR (https://github.com/hyperledger/besu/pull/6978) made the optional `rpc-gas-cap` config to always override the gas cap used for tx simulation, when specified, but while this could be good for `eth_call`, it does not work well with calls like `eth_estimateGas` when the gas cap could be based on what use provided or the sender balance, and it also diverging from what Geth does.
This PR align the gas cap calculation used during tx simulation, to what Geth does, with only a little difference, the algorithm is the following:
- if the user specific the gas limit, then use it unless it is bigger than the `rpc-gas-cap`, in which case we return the latter
- if there is not user specified gas limit, then use `rpc-gas-cap` if configured, otherwise use the block gas limit^.
^ in this case …

Align gas cap calculation for transaction simulation to Geth approach

---

.github/workflows/docker-promote.yml
.github/workflows/draft-release.yml

Previously GitHub release will be created which triggers building and publishing the artifacts. Release engineers found workflow could fail after the GitHub release created. Community may subscribed to GitHub releases but if the workflow failed, artifacts for the release would not available.
Proposed solution requires release engineer to run a GitHub workflow manually by providing the Git tag which creates a draft GitHub release. During this workflow, release artifacts binary distribution, docker images (not latest), Artifactory jars created and published. Release engineer can update the release notes in draft release and publish the release. At the time when the release is published, release engineer is confident all the artifacts are ready. Upon publishing the release, another workflow …

Update release process

---

besu/src/main/java/org/hyperledger/besu/cli/options/stable/JsonRpcHttpOptions.java
besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcConfiguration.java

set the default value for the rpc Http Host CLI option so that it gets initialized correctly
fixes #7721

add correct default to rpcHost

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/verkle/worldview/VerkleWorldState.java
ethereum/verkletrie/src/main/java/org/hyperledger/besu/ethereum/verkletrie/VerkleEntryFactory.java

Spotted an issue while running one of the reference tests when an account already exists with code and only the account data is updated in the trie. In that case, since there won't be any updates for code, the current code will not be added to the BASIC_DATA_LEAF.

Fix BASIC_DATA_LEAF update on account with existing code size value

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthFeeHistory.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthJsonRpcMethods.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthFeeHistoryTest.java

The issue is that, when bounding rewards returned by `eth_feeHistory` by configuration, the `minPriorityFeePerGas` runtime value is used, but it could not be great enough to return acceptable values in order to estimate which `priorityFeePerGas` to use in a tx to ensure it is paying enough to be mineable.
To fix that a _a mineable lower bound_ for the priority fee is calculated and used in place of `minPriorityFeePerGas` conf value, when it is greater that the latter, so we are reasonably sure that we are returning value that can be used to estimate the priority fee when submitting new txs.

Fix eth_feeHistory rewards when bounded by configuration

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetHeadersFromPeerByNumberTask.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/task/GetHeadersFromPeerByNumberTaskTest.java

Remove code from GetHeadersFromPeerByNumberTask only used in test, update test to use used code

7311: Remove code from GetHeadersFromPeerByNumberTask only used in test, update test to use used code

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/services/BesuEventsImpl.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/pending/PendingTransactionDroppedSubscriptionService.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/subscription/pending/PendingTransactionDroppedSubscriptionServiceTest.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PeerTransactionTracker.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/RemovalReason.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/AbstractPrioritizedTransactions.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/AbstractSequentialTransactionsLayer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/AbstractTransactionsLayer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/BaseFeePrioritizedTransactions.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/EndLayer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredRemovalReason.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/ReadyTransactions.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/SparseTransactions.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/TransactionsLayer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/AbstractPendingTransactionsSorter.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/SequencedRemovalReason.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/PeerTransactionTrackerTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactionsTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayersTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/ReplayTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/AbstractPendingTransactionsTestBase.java

If a tx is removed from the pool due to eviction policies, but it is valid, we should be able to accept that tx again in future, but now this could not happen, since we keep track, in a cache, of all the tx hashes that we have seen, to avoid reprocessing txs, and so if the hash of the evicted txs is still in the cache, it will not be accepted again.
This PR tune the already seen txs tracker to stop tracking a valid tx that is removed from the pool, opening to the possibility to re-accept it in future.
fixes #7081

Fine tune already seen txs tracker when a tx is removed from the pool

---

.github/ISSUE_TEMPLATE/release-checklist.md

Following on from the 24.10.0 release https://github.com/hyperledger/besu/issues/7710

Update release checklist

---

acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java

Add metrics related services to the Besu context for acceptance tests so that it is possible to test plugins that works with metrics

Add metrics related services to the Besu context for acceptance tests

---

acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/blockchain/ExpectBlockNotCreated.java

Follow-on from #7793 and blocker for #7790 - junit4 transitive dependency via test containers

[TESTING] AT Condition to use junit5

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/test/java/org/hyperledger/besu/cli/options/MetricsOptionsTest.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/MetricCategoryRegistryImpl.java
metrics/core/src/test/java/org/hyperledger/besu/metrics/MetricCategoryRegistryImplTest.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/metrics/MetricCategoryRegistry.java

Adding the new method `MetricCategoryRegistry::isMetricCategoryEnabled` to plugin API, so plugins can check if their added metrics categories are enabled, that include checking both that the metrics are enabled and the category is enabled.

Add a method to check if a metric category is enabled to the plugin API

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV2.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV2Test.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV3Test.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV4Test.java

The method under test was EngineNewPayloadV3 so the passing tests weren't valid 😅 
Remove optional maybeRequests from `AbstractEngineNewPayloadTest.setupValidPayload`, instead relying on the V4  `@Override ... createBlockHeader` and `@Override ... resp` methods to construct a valid V4 request.
Also change "Missing" -> "Unexpected" message when V3 blob params sent to V2
More tidy up of this test hierarchy needed, but this unblocks adding tests for EIP-7742

Test against EngineNewPayloadV4 in EngineNewPayloadV4Test

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugSetHead.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugSetHeadTest.java

This PR adds an optional parameter to `debug_setHead` that allows one to move the head worldstate along with the blockchain.  This is a no-op for Forest, but for DiffBased worldstates like bonsai and verkle, this will roll the head worldstate to the specified block number / block hash.
This is a debug method only and __should  not__ be used when a consensus client is directing besu, or while the node is actively importing or proposing blocks.
This feature is a stop-gap measure until #7475 is complete.  This debug feature will allow users to move bonsai worldstate head far back into block history so that expensive operations like `debug_traceBlock` can be run on historical blocks.  Otherwise, trying to execute RPC calls on old historical states will inevitably encounter an OOM (out of …

feature: Add optional worldstate move flag to debug_setHead

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionBroadcaster.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java

PR https://github.com/hyperledger/besu/pull/7755 was missing one fundamental step, the registration of `PeerTransactionTracker` to dropped tx notifications, and without that the evicted valid txs are not correctly removed from the already seen tracker.
This PR just add that missing registration.
fixes #7081

Fix missing registration of PeerTransactionTracker to dropped tx notifications

---

besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/MainnetBlockValidator.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/bonsai/BonsaiWorldStateProvider.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/forest/ForestWorldStateArchive.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/WorldStateArchive.java
ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/InMemoryKeyValueStorageProvider.java
ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/WorldStateHealerHelper.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/diffbased/bonsai/AbstractIsolationTests.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/diffbased/bonsai/BonsaiWorldStateProviderTest.java

A followup to this suggestion https://github.com/hyperledger/besu/pull/7792#issuecomment-2434648358
to remove the circular dependency between `ProtocolContext` and `Synchronizer` and also make the heal action a native function of the `WorldStateArchive` as this seems to be more appropriate.
Next PR will complete the removal of the `Synchronizer` from `ProtocolContext`

Make healing an action of the WorldStateArchive

---

besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/ProtocolContext.java
ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/BlockchainSetupUtil.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/MainnetBlockValidatorTest.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/SnapProtocolManager.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/SnapServer.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/snap/SnapServerGetAccountRangeTest.java

Followup to #7862, completes the removal of the `Synchronizer` from `ProtocolContext` thus making the latter an immutable object and simplifying its instantiation.

Remove synchronizer from protocol context

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceBlock.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceFilter.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceReplayBlockTransactions.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/JsonRpcMethodsFactory.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/TraceJsonRpcMethods.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceFilterTest.java
ethereum/core/build.gradle
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchain.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/bonsai/cache/BonsaiCachedMerkleTrieLoader.java
ethereum/p2p/build.gradle
metrics/core/build.gradle
metrics/core/src/main/java/org/hyperledger/besu/metrics/ObservableMetricsSystem.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/noop/NoOpMetricsSystem.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/opentelemetry/OpenTelemetrySystem.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/PrometheusMetricsSystem.java
metrics/core/src/test-support/java/org/hyperledger/besu/metrics/StubMetricsSystem.java
metrics/rocksdb/build.gradle
metrics/rocksdb/src/main/java/org/hyperledger/besu/metrics/rocksdb/RocksDBStats.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/MetricsSystem.java
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/metrics/ExternalSummary.java
plugins/rocksdb/build.gradle
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBMetricsFactory.java

~~Built on top of #7879~~ [MERGED]
This is the first PR of a series to refresh the metrics system, to pay some tech debt, and to migrate to the new Prometheus Java lib to version 1.x, from the current legacy Simpleclient version 0.x.
Along with the upgrade to the new Prometheus lib, these other tasks are planned to refresh the metrics system:
- Refactor the way the observation mechanism works to simplify it and make it more OO
- Replace our HTTP server implementation with the provided one, so we can benefit from the new export formats (like protobuf) without having to re-implement them
- Use Prometheus to provide OpenTelemetry metrics, and so remove the dedicated OpenTelemetry deps and code
- Add support for Histogram and Summary metric types.
The scope of this first PR is to consolidate …

Consolidate all metric collectors into the metrics system

---

besu/src/main/java/org/hyperledger/besu/controller/CliqueBesuControllerBuilder.java
consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/CliqueDifficultyCalculator.java
consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/CliqueHelpers.java
consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/CliqueMiningTracker.java
consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/CliqueProtocolSchedule.java
consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/headervalidationrules/CliqueDifficultyValidationRule.java
consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/CliqueDifficultyCalculatorTest.java
consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/CliqueProtocolScheduleTest.java
consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueBlockCreatorTest.java
consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueMinerExecutorTest.java
consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueMiningCoordinatorTest.java
consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/headervalidationrules/CliqueDifficultyValidationRuleTest.java
consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BaseBftProtocolScheduleBuilder.java
consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/MergeProtocolSchedule.java
consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/MergeProtocolScheduleTest.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/difficulty/fixed/FixedDifficultyCalculators.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicDifficultyCalculators.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/DifficultyCalculator.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetDifficultyCalculators.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/CalculatedDifficultyValidationRule.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/difficulty/fixed/FixedProtocolScheduleTest.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestEnv.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/mainnet/DifficultyCalculatorTests.java

Cleanup and little refactoring PR, with no functional changes, to remove the need to pass the protocol context when calculating the difficulty for the next block, since that was only needed by Clique and so we can take a different approach and move everything related to Clique difficulty calculation inside the Clique specific classes, without having to touch other consensus mechanism.

Simplify difficulty calculator interface

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/MonitoredExecutors.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/peertask/PeerTaskExecutor.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolMetrics.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/noop/NoOpMetricsSystem.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/noop/NoOpValueCollector.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/opentelemetry/OpenTelemetryLabelledSuppliedMetric.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/opentelemetry/OpenTelemetrySuppliedCounter.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/opentelemetry/OpenTelemetrySystem.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/PrometheusMetricsSystem.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/PrometheusSuppliedValueCollector.java
metrics/core/src/test-support/java/org/hyperledger/besu/metrics/StubMetricsSystem.java
metrics/core/src/test/java/org/hyperledger/besu/metrics/opentelemetry/OpenTelemetryMetricsSystemTest.java
metrics/core/src/test/java/org/hyperledger/besu/metrics/prometheus/PrometheusMetricsSystemTest.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/MetricsSystem.java
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/metrics/LabelledSuppliedMetric.java

Another PR of the series to upgrade and refresh the metric system.
This time we fix the type of two metrics used in the `MonitoredExecutors` class, that are counters but were created as gauges, probably since there was no way to create counters with an external supplied value, so this kind of counter has been added, and the concept of metrics with external supplied values has been extended to cover both counters and gauges.
Other than for using the correct metric type, this fix is required, because with the following upgrade to Prometheus Java lib 1.x, only counters can have a `_total` suffix.

Add support for counter metric with external supplied value

---

acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/privacy/TestPrivacyPluginPayloadProvider.java
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/options/PrivacyPluginOptions.java
besu/src/main/java/org/hyperledger/besu/services/PrivacyPluginServiceImpl.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPluginPrecompiledContract.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/PrivacyPluginService.java
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/privacy/PrivacyPluginPayloadProvider.java

* Add deprecation messages to help descriptions
* Add warning log if privacy-enabled option is specified
Note I did not add any `@Deprecation` annotations to types or methods - feedback welcome on whether you think this is needed.

Privacy deprecation warnings on CLI

---

docs/tracing/README.md

**Issue:**
The original sentence:
> "This allows to report all JSON-RPC traffic as traces."
has an unusual sentence structure and could be improved for readability.
**Fix:**
The sentence has been changed to:
> "This allows reporting all JSON-RPC traffic as traces."
**Importance:**
While this is not a technical error, improving the sentence structure enhances the clarity and readability of the documentation. This change ensures that the documentation follows more natural English phrasing, making it easier for users to understand.

Fix minor stylistic issue in tracing documentation

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugSetHead.java

simple change to state rolling increment for `debug_setHead`.  This PR shortens this interval to 32.
Discovered while verifying #7804, chain and state rolling with an interval of 512 can lead to out-of-memory.  
confirmed by rolling state 209k blocks back on main to the block referenced in #7804.  trace for the block in question attached
[trace_block_21030627.json](https://github.com/user-attachments/files/17872858/trace_block_21030627.json)

shorten rolling increment to 32

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapSyncMetricsManager.java

Correct other counters that were created as gauges

---

acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/services/MiningServiceImpl.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/mining/MiningService.java

Add mining service to plugin API

Expose Mining service to the plugin api

---

ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/NodeLocalConfigPermissioningController.java
ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/NodeLocalConfigPermissioningControllerTest.java

ArrayList() used for allowlist is not threadsafe. Adding/removing entries while iterating the list to check for an entry in isPermitted() will throw this exception. Added a testcase for this situation.
```bash
java.util.ConcurrentModificationException
at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1687)
at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
at …
```

Fix concurrent access of node permissioning allow list

---

acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/BadCLIOptionsPlugin.java
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestBesuEventsPlugin.java
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestBlockchainServiceFinalizedPlugin.java
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestInProcessRpcServicePlugin.java
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestMetricsPlugin.java
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestPermissioningPlugin.java
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestPicoCLIPlugin.java
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestPrivacyServicePlugin.java
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestRpcEndpointServicePlugin.java
besu/src/main/java/org/hyperledger/besu/services/BesuPluginContextImpl.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/BesuPlugin.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBPlugin.java
services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/InMemoryStoragePlugin.java

Reverts change to Plugin interface's register() method to not require newly introduced class.

revert to unchanged plugin interface signature

---

besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/PeerResult.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/AdminJsonRpcHttpServiceTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminPeersTest.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/peertask/task/GetReceiptsFromPeerTask.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthPeerTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTestUtil.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/RequestManagerTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ethtaskutils/AbstractMessageTaskTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ethtaskutils/PeerMessageTaskTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/peertask/task/GetReceiptsFromPeerTaskTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/AbstractBlockPropagationManagerTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TestNode.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactoryTest.java

Removes the protocol name from EthPeers and EthPeer. The protocol name was always set to "eth".
Fixes #7810

remove protocol name

---

metrics/core/src/main/java/org/hyperledger/besu/metrics/MetricsService.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/opentelemetry/MetricsOtelPushService.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/MetricsHttpService.java
metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/MetricsPushGatewayService.java

Shutdown `MetricsSystem` when stopping `MetricsService`, so any registered collector is cleaned, that is most useful during acceptance tests.

Shutdown MetricsSystem when stopping MetricsService

---

evm/src/main/java/org/hyperledger/besu/evm/gascalculator/Eip4762GasCalculator.java
evm/src/main/java/org/hyperledger/besu/evm/gascalculator/FrontierGasCalculator.java
evm/src/main/java/org/hyperledger/besu/evm/gascalculator/GasCalculator.java
evm/src/main/java/org/hyperledger/besu/evm/operation/CallCodeOperation.java

Fixes small issue with CALLCODE gas costs while running reference tests for previous forks.

Fix CALLCODE gas costs regression with previous forks

---

acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/clique/CliqueMiningAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/clique/CliqueProposeRpcAcceptanceTest.java

verify nodes are fully connected otherwise blocks could not be propagated
#7992

Fix flaky Clique tests waiting for nodes to be fully connected and in sync

---

CHANGELOG.md
datatypes/src/main/java/org/hyperledger/besu/datatypes/AccountOverride.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCallTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/util/AccountOverrideParameterTest.java

account overrides: parse hex string into nonce long

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/NormalBlockAdapter.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/PendingStateAdapter.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/TransactionAdapter.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockReceipts.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetMinerDataByBlockHash.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueriesTest.java

1. Retrieve all transaction receipts in a block in 1 call to blockchain query instead of a call for each transaction in a block
2. Calculate transaction fee reward for miner based on `effectivePriorityFeePerGas` instead of `effectiveGasPrice` because `baseFee` would be burnt.

Retrieve all transaction receipts for a block in one request

---

datatypes/src/main/java/org/hyperledger/besu/datatypes/Address.java

We've noticed when profiling the SELFBALANCE during load testing that the throughput issue is related to the equals operation on the address class. 
This PR introduces a new implementation of the equals method in the Address class to replace the one inherited from AbstractBytes. The issue with equals in AbstractBytes is that it compares each byte from both addresses individually, and the get method used is megamorphic.

Improve equals performance on Address

---

build.gradle
platform/build.gradle

Artifactory publication need to be extended to include also Java Platform BOM pom.

Fix BOM pom publication to Artifactory

---

datatypes/src/main/java/org/hyperledger/besu/datatypes/AccountOverride.java
ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_call_stateOverride_movePrecompileToAddress.json

Builder needed to ignore unknown properties also
Fixes #8023

eth_call state override bugfix - movePrecompileToAddress

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java

Correctly set the `timestamp` field of the pending block, that was wrongly set to milliseconds in #7951

Fix simulate pending block timestamp

---

CHANGELOG.md
evm/src/main/java/org/hyperledger/besu/evm/gascalculator/GasCalculator.java

Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>## PR description
There were some breaking changes that are already released in 24.12 - removed those from the "upcoming breaking changes" section.
Also clarified a comment.

[CHANGELOG] clarify breaking changes

---

besu/src/main/java/org/hyperledger/besu/services/TraceServiceImpl.java

This reverts commit 6a546c5e6f5cb961891fbe3ab2f14da29796c242.
Revert commit that was added to fix tracing for journal updater mode but we found that this fix added a regression in another part.

Revert "update trace logique to fix journal updater issue (#7758)"

---

CHANGELOG.md
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java

it could happen, especially at startup, that the node switch from in sync to out of sync quickly, and if that happens during the txpool restore from the dump file, the restore could be incomplete.
This is an log example of this issue:
```
1. Loading transaction pool content from file /data/besu/txpool.dump
2. Node out of sync, disabling transaction handling
3. Added 88 transactions of 442 loaded from file /data/besu/txpool.dump
4. Saving 88 transactions to file /data/besu/txpool.dump
5. Saved 88 transactions to file /data/besu/txpool.dump
6. Node is in sync, enabling transaction handling
7. Loading transaction pool content from file /data/besu/txpool.dump
8. Added 87 transactions of 88 loaded from file /data/besu/txpool.dump
```
So at the beginning the node was restoring the txpool (1.), …

Fix possible incomplete txpool restore from dump file

---

ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionReceiptTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/FeeMarket.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/PragueFeeMarket.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/feemarket/PragueFeeMarketTest.java

Prague blob fee market for EIP-7691
#8060

prague fee market for blob gas

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/services/TraceServiceImpl.java
besu/src/test/java/org/hyperledger/besu/services/TraceServiceImplTest.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/InterruptibleOperationTracer.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/tracer/BlockAwareOperationTracer.java

This passes the miningBeneficiary, which in most cases should be the coinbase but for other consensus approaches could be different, to BlockAwareOperationTracer::traceStartBlock calls.
fixes #8094

Pass miningBeneficiary address to BlockAwareOperationTracer::traceStartBlock calls

---

plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/tracer/BlockAwareOperationTracer.java

This PR adds back removed methods from the tracer API that are now marked as deprecated and will removed at a later point. This is to avoid breaking any other existing customers of the API.

Add back deprecated traceStartBlock methods to the tracer API

---

CHANGELOG.md

There's several bonsai CLI options that have been deprecated for a while - added the complete list in the "Upcoming breaking changes" section

[CHANGELOG] list deprecated bonsai CLI options

---

ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestProtocolSchedules.java
ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java

No need to ignore Prague tests now (think the specific BLS ignores were all that were required)
Removing osakaTime from Prague Schedule fixes some tests when using https://github.com/ethereum/execution-spec-tests/releases/tag/pectra-devnet-5%40v1.2.0
and doesn't break main.

Unignore Prague ref tests and remove osakaTime from Prague

---

acceptance-tests/tests/src/test/resources/dev/dev_prague.json
besu/src/test/java/org/hyperledger/besu/controller/MergeBesuControllerBuilderTest.java
config/src/main/java/org/hyperledger/besu/config/BlobScheduleOptions.java
config/src/main/resources/holesky.json
config/src/main/resources/mainnet.json
config/src/main/resources/sepolia.json
config/src/test/java/org/hyperledger/besu/config/BlobScheduleOptionsTest.java
config/src/test/java/org/hyperledger/besu/config/GenesisConfigOptionsTest.java
config/src/test/resources/mainnet_with_blob_schedule.json
consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java
consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeReorgTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGasPriceTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionReceiptTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthMaxPriorityFeePerGasTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/CancunFeeMarket.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/FeeMarket.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/FixedBaseFeeMarket.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/LegacyFeeMarket.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/LondonFeeMarket.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/PragueFeeMarket.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/ZeroBaseFeeMarket.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/feemarket/CancunFeeMarketTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/feemarket/LondonFeeMarketTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/BaseFeeMarketBlockHeaderGasPriceValidationRuleTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/GasLimitElasticityValidationRuleFixedBaseFeeMarketTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/GasLimitElasticityValidationRuleTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/GasLimitElasticityValidationRuleZeroBaseFeeMarketTest.java

Add baseFeeUpdateFraction to blobSchedule genesis config

---

plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/tracer/BlockAwareOperationTracer.java

This reverts commit 1f67cb511ccf5c23e17dbca2598122804ffaca8d.

Revert "Add back deprecated traceStartBlock methods to the tracer API (#8112)"

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/FlatTraceGenerator.java
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/state-test/create-eof.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/state-test/create-invalid-eof.json
ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/trace/badcode.json
evm/src/main/java/org/hyperledger/besu/evm/EVM.java
evm/src/main/java/org/hyperledger/besu/evm/frame/ExceptionalHaltReason.java
evm/src/main/java/org/hyperledger/besu/evm/operation/InvalidOperation.java

This PR updates the behavior of the invalid operation opcode to return an error that includes the problematic opcode in the message, replacing the previous generic message.

Improve error message for INVALID OPERATION opcode

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockByNumber.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockByNumberTest.java

This PR addresses a bug in the eth_getBlockByNumber method, where invoking it with empty parameters results in the error message "Invalid block, unable to parse RLP".
There're some consideration while I investigate & fix the bug
- I would have preferred to use the message proposed in the issue; however, a pre-defined error message better fits this situation, so I opted to use it.
- Adding data would require modifications to org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(), which is outside the scope of this fix.
- The message for RpcErrorType.INVALID_BLOCK_PARAMS might seem slightly inconsistent, but adjusting it is also beyond the scope of this PR.
- Request
```
POST http://localhost:8545
Content-Type: application/json …
```

Fix eth_getBlockByNumber with empty params returns

---

acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/ethereum/CodeDelegationTransactionAcceptanceTest.java
datatypes/src/main/java/org/hyperledger/besu/datatypes/Transaction.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/CodeDelegationProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/encoding/CodeDelegationDecoderTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/CodeDelegationProcessorTest.java
ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nExecutor.java
ethereum/rlp/src/main/java/org/hyperledger/besu/ethereum/rlp/RLP.java
ethereum/rlp/src/test/java/org/hyperledger/besu/ethereum/rlp/RLPTest.java
evm/src/main/java/org/hyperledger/besu/evm/account/AbstractCodeDelegationAccount.java
evm/src/main/java/org/hyperledger/besu/evm/account/Account.java
evm/src/main/java/org/hyperledger/besu/evm/account/AccountState.java
evm/src/main/java/org/hyperledger/besu/evm/account/CodeDelegationAccount.java
evm/src/main/java/org/hyperledger/besu/evm/account/MutableCodeDelegationDelegationAccount.java
evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCallOperation.java
evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractExtCallOperation.java
evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractExtCodeOperation.java
evm/src/main/java/org/hyperledger/besu/evm/operation/ExtCodeCopyOperation.java
evm/src/main/java/org/hyperledger/besu/evm/operation/ExtCodeHashOperation.java
evm/src/main/java/org/hyperledger/besu/evm/operation/ExtCodeSizeOperation.java
evm/src/main/java/org/hyperledger/besu/evm/worldstate/CodeDelegationGasCostHelper.java
evm/src/main/java/org/hyperledger/besu/evm/worldstate/CodeDelegationHelper.java
evm/src/main/java/org/hyperledger/besu/evm/worldstate/CodeDelegationService.java
evm/src/main/java/org/hyperledger/besu/evm/worldstate/EVMWorldUpdater.java

* fix code hash for delegated accounts in ExtCodeHashOperation
* move common code to AbstractExtCodeOperation class
fixes #8147

Devnet-5: bug fixes for 7702

---

evm/src/main/java/org/hyperledger/besu/evm/gascalculator/Eip4762GasCalculator.java

An issue was spotted during verkle devnet-7 sync after merging main@b3b33da540 into verkle, where the precompile list was not being taken from Cancun but would be from Prague instead.

Fix consensus issue due to modified precompile list

---

CHANGELOG.md
besu/src/test/java/org/hyperledger/besu/ForkIdsNetworkConfigTest.java
config/src/main/resources/holesky.json
config/src/main/resources/sepolia.json

Pectra testnet fork slot proposals (TBC based on how devnet-6 goes next week): 
Holesky: 3620864 (Wed, Feb 12 at 09:32:48 UTC)
Sepolia: 219392 (Wed, Feb 19 at 15:48:48 UTC)
for those speaking epoch time:
Holesky: 1739352768
Sepolia: 1739980128
forkids for confirming:
holesky: 0xf818a0d6
sepolia: 0xbafd09c3

Pectra testnet fork slots

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/services/TransactionSimulationServiceImpl.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/TransactionValidationParams.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/TransactionSimulationService.java

Extend the simulate transaction plugin API to allow for plugin to access the pending block header, and giving the possibility of allowing future nonce during the simulation, for example we accepting txs to the txpool, also the coinbase of the pending block header is now correctly populated, and removed deprecated methods.
fixes #8173

Extend simulate transaction on pending block plugin API

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractDebugTraceBlock.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockByHashTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockTest.java

By using the other Tracing.processTracing overloaded method, this avoids this lookup https://github.com/hyperledger/besu/blob/b3192a5960bd9f277e5bdd063598a117c6fb4807/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/Tracer.java#L38
and means you don't need to have the block already in the chain when you call `debug_traceBlock` with a block's RLP in the request.
Since this is an Abstract class, I'm not 100% sure how this might impact the other subclasses (think it's just DebugTraceBlockByHash).
Would like some clarification from someone who knows the API better.
Tested output is the same between `debug_traceBlock` vs `debug_traceBlockByNumber` vs `debug_traceBlockByHash`.

debug_traceBlock use existing block header instead of hash

---

.github/workflows/sonarcloud.yml

Example of warning here:
https://sonarcloud.io/component_measures?id=hyperledger_besu&metric=new_coverage

fixes warning on sonar analysis

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/verkle/LeafBuilder.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/verkle/cache/preloader/StemPreloader.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/verkle/storage/flat/VerkleStemFlatDbStrategy.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/verkle/worldview/VerkleWorldState.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/diffbased/verkle/storage/flat/VerkleStemFlatDbStrategyTest.java
evm/src/main/java/org/hyperledger/besu/evm/gascalculator/stateless/Eip4762AccessWitness.java
platform/build.gradle

This PR aims to rename certain classes of Verkle to make the code more readable. It will also update the besu-verkle-trie library, which has also some modifications to optimize the generation of stems.

clean verkle code and update besu-verkle-trie library

---

besu/src/main/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommand.java

This PR fixes the `UnsatisfiedLinkError` during Hive tests for the KZG point precompile. The missing init step for the KZG precompile is executed before importing a block via the `block` subcommand.
fixes #8218

Init KZG precompile contract before importing blocks

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/ForkSupportHelper.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/ForkSupportHelperTest.java

If the timestamp is set to `> 2^63 - 1 and <= 2^64 - 1 (UnsignedLong.MAX_VALUE = 18446744073709551615)`, then since we use a (signed) primitive long by default this can overflow and e.g. we interpret `18446744073709551615` as timestamp = -1
This fixes some hive tests as part of #8177

Treat timestamp as unsigned long in engine api fork validation

---

CHANGELOG.md
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/AbstractTransactionSelector.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/SkipSenderTransactionSelector.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockTransactionSelectorTest.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/LondonFeeMarketBlockTransactionSelectorTest.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactionsTest.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java

During block creation, if a sender has more that one pending txs and one of them if not selected for any reason, then it is worthless to keep evaluation other pending txs from the same sender, since they will also be not selected due to the nonce gap. 
Before this PR, this check was only done in the layered txpool, but it is better to move it as a standard tx selector, so it applies also to the sequenced txpool.

Add a tx selector to skip txs from the same sender after the first not selected

---

acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/clique/CliqueProposeRpcAcceptanceTest.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/LegacyFeeMarketBlockTransactionSelectorTest.java

Disabling these tests for now since they are blocking the PR pipeline
Refs #7973 and #8238

disable flaky test classes

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/options/ApiConfigurationOptions.java
besu/src/test/java/org/hyperledger/besu/cli/options/ApiConfigurationOptionsTest.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/ApiConfiguration.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulatorTest.java

Change rpc-gas-cap default from 0 (unlimited) to 50M
Fixes #8175

update rpc gas cap default to 50M

---

datatypes/src/main/java/org/hyperledger/besu/datatypes/PendingTransaction.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/TransactionEvaluationContext.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/MinPriorityFeePerGasTransactionSelector.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/PriceTransactionSelector.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockTransactionSelectorTest.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransaction.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/txselection/PluginTransactionSelector.java
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/txselection/TransactionEvaluationContext.java

This PR is a prerequisite for letting plugins propose pending transaction during block creation, it removes the assumption that during block creation all pending transactions are of our internal type `org.hyperledger.besu.ethereum.eth.transactions.PendingTransaction` using the `PendingTransaction` interface instead.
No functional changes introduced by this PR.

Use PendingTransaction interface in block creation classes

---

besu/src/test/java/org/hyperledger/besu/ForkIdsNetworkConfigTest.java
config/src/main/resources/holesky.json
config/src/main/resources/sepolia.json

https://github.com/ethereum/pm/issues/1265#issuecomment-2637778317
> Client testnet releases out by Feb 10
> Holesky slot: 3670016 (Wed, Feb 19 at 05:23:12 UTC)
> Sepolia slot: 7061504 (Tue, Feb 25 at 08:20:48 UTC)
Merging in the earliest times optimistically to allow a burn-in to start today and maximise soaking time, if Feb 10 becomes our target release date.

Prague times for holesky and sepolia

---

.github/workflows/pre-review.yml
.github/workflows/reference-tests.yml

Relocating 4 runners from reference-tests to unit-tests, since the latter job is longer than the former to complete

Rebalance GHA runners

---

platform/build.gradle

This reverts commit 0ad85ecadafb8062ffdbea279f2f3dc266aa7ce0.
since the issue is solved

Revert "Hotfix for gradle compile issue by locking in json-smart version (#8282)"

---

ethereum/evmtool/src/main/docker/Dockerfile

Fixes this [build failure](https://github.com/hyperledger/besu/actions/runs/13381142166/job/37369815247) 
`#7 4.118 E: Version '20190909*' for 'ca-certificates-java' was not found`
could see the ca-certificates-java gets pulled in even without this explicit install.
```
#6 32.17 Setting up openjdk-21-jre-headless:arm64 (21.0.6+7-1~24.04.1) ...
#6 32.19 update-alternatives: using /usr/lib/jvm/java-21-openjdk-arm64/bin/java to provide /usr/bin/java (java) in auto mode
#6 32.19 update-alternatives: using /usr/lib/jvm/java-21-openjdk-arm64/bin/jpackage to provide /usr/bin/jpackage (jpackage) in auto mode
#6 32.19 update-alternatives: using /usr/lib/jvm/java-21-openjdk-arm64/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
#6 32.19 update-alternatives: using …
```

[build] evmtool Dockerfile - update apt-get packages

---

build.gradle
ethereum/referencetests/build.gradle

distDocker was only creating evmtool docker not besu docker image
it affects CI as well - no longer publishing docker for besu: https://hub.docker.com/r/hyperledger/besu/tags (last develop was 5 days ago)
Seems to have been broken by this commit -
https://github.com/hyperledger/besu/commit/1508b5cba517f1a99f18c9232f14d987338cfe95#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7
This PR reverts one change from #8295

fix distDocker - revert gradle change to providers.exec

---

ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactionEstimatedMemorySizeTest.java

Disable this test class on mac OS
Fixes #8269

disable on mac: PendingTransactionEstimatedMemorySizeTest

---

config/src/main/resources/holesky.json
config/src/main/resources/sepolia.json

Correct deposit contract testnet addresses

---

CHANGELOG.md
consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlobSizeTransactionSelectorTest.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlockSizeTransactionSelectorTest.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransaction.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/AbstractTransactionPoolTestBase.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolSaveRestoreTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/BaseTransactionPoolTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/ReplayTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/AbstractPendingTransactionsTestBase.java

Support pending transaction score when saving and restoring txpool

---

consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/blockcreation/ProposerSelector.java

Expose static method that can be used for qbft proposal selection without needing the blockchain, block interface or validator provider. This allows the logic to be reused in other projects without requiring a Besu block.

Expose static method that can be used for qbft proposal selection

---

datatypes/src/main/java/org/hyperledger/besu/datatypes/Transaction.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/TransactionIntegrationTest.java

Add a method to get the encoded preimage of a transaction

---

consensus/qbft-core/src/main/java/org/hyperledger/besu/consensus/qbft/core/types/QbftValidatorProvider.java
consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/adaptor/QbftValidatorProviderAdaptor.java
consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/adaptor/QbftValidatorProviderAdaptorTest.java

Remove unused method getValidatorsAtHead from QbftValidatorProvider

Remove unused method getValidatorsAtHead from QbftValidatorProvider

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockImporter.java

Block importer was previously advancing the head for the world state by default. 
This method is only used by backward sync context and rlp block importer.  It works directly on the head world state.  
This PR introduces a check so that the worldstate only updates head if the block processing (import) was successful. This then matches how the scenario would play out when driven by the Engine API.
This fixes a hive test that uses RLPBlockImporter to set up a specific scenario `checkGasLimit_Cancun`

Block Import: move worldstate head only if import successful

---

platform/build.gradle

This is a constraint on a version and not a transitive dependency to another BOM/platform. If a Gradle projects depends on both `javax.inject:javax.inject` and `besu`, you currently can run into an error like this:
```
Cannot select module with conflict on capability '...' also provided by [javax.inject:javax.inject:1(platform-compile), javax.inject:javax.inject:1(compile)]
```
https://scans.gradle.com/s/f237bkq632kb4/failure#1
Discovered in https://github.com/hiero-ledger/hiero-gradle-conventions/pull/136
- ~[ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).~
- ~[ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and …

Fix: javax.inject:javax.inject:1 entry in BOM

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/handlers/JsonRpcExecutorHandler.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/handlers/TimeoutOptions.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/handlers/JsonRpcExecutorHandlerTest.java

I think there is some refactor to do around the HTTP timeout, because it seems to be enforced twice, but as quick fix we can just replace the hard coded 30 secs with the existing timeout configuration `Xhttp-timeout-seconds` and set the latter to 30 seconds instead of 5 minutes.
fixes #7975

Use existing HTTP timeout configuration instead of the hard coded value

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/AbstractTransactionPoolTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/AbstractTransactionPoolTestBase.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolSaveRestoreTest.java

Fix to use the POOLED_TRANSACTION format also when reading from disk to fix the issue related to saving blob tx with that format but reading them with the BLOCK_BODY format.
Writing a test for this, I found that we where not correctly supporting the enable/disable feature in the unit tests, so that required a bit of refactoring on the test code.
fixes #8449

Fix restoring txpool from disk when blob transactions are present

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractEstimateGas.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java

If not set in call params, don't override gasPrice. TransactionSimulator does the work of deciding whether it is set and whether it needs overriding.
This was discovered by looking at rpc-compat hive tests but doesn't actually fix any hive tests directly.
What is fixed by this is transactions will be detected as EIP1559 if no gas price set.

estimate gas - don't override gasPrice if not set

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCreateAccessList.java
ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_createAccessList_value_transfer.json

follow on from #8472 - this is the same fix for eth_createAccessList
If not set in call params, don't override gasPrice. TransactionSimulator does the work of deciding whether it is set and whether it needs overriding.
Also added a spec test for eth_createAccessList although it does duplicate a hive test so not strictly necessary just a faster feedback loop
##Fixed Issue(s)
This was discovered by looking at rpc-compat hive tests but doesn't actually fix any hive tests directly.
What is fixed by this is transactions will be detected as EIP1559 if no gas price set.

create access list - don't override gasPrice if not set

---

ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCreateAccessListTest.java

I spent a little too long figuring this out so proposing a rename.

[MINOR] renaming method in test to help readability

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/storage/BonsaiWorldStateKeyValueStorage.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/common/storage/PathBasedWorldStateKeyValueStorage.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/common/trielog/TrieLogManager.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/common/worldview/PathBasedWorldState.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/BonsaiSnapshotIsolationTests.java

This PR addresses a regression where bonsai database can be left in a broken state on an abnormal shutdown.  
When besu commits a bonsai worldstate, it commits the trielog and the worldstate.  if the worldstate is committed first, and besu gets killed before it can commit the trielog, upon resuming operations besu will fail to create or import blocks, giving an error similar to: 
>Optional[Unable to process block because parent world state 0xcdee53accfeaa10680a304bc3ab3b721f15caeb61a4ede8ddde994f788892ced is not available]
The fix is to move the trielog commit ahead of the worldstate commit, and add the methods necessary to isolate the commit of both transactions.
Although this PR is very short, there is a lot of complexity hidden in it.  Several edge cases were discovered and addressed …

bonsai: commit trielog ahead of state

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/MainnetBlockValidator.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSpecBuilder.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/common/StateRootMismatchException.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/common/worldview/PathBasedWorldState.java
ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/BlockchainSetupUtil.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/BlockImportExceptionHandlingTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/MainnetBlockValidatorTest.java

fixes first part of #8204 by using BadBlockManager from protocol context

fixes #8204 by using BadBlockManager from protocol context

---

CHANGELOG.md
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/wire/PeerClientName.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/wire/PeerClientType.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/wire/PeerInfo.java

A new metric is exported with the count of peers by client type
```
besu_peers_peer_count_by_type{client="Besu"} 0.0
besu_peers_peer_count_by_type{client="Erigon"} 0.0
besu_peers_peer_count_by_type{client="Geth"} 5.0
besu_peers_peer_count_by_type{client="Nethermind"} 2.0
besu_peers_peer_count_by_type{client="Nimbus"} 0.0
besu_peers_peer_count_by_type{client="Reth"} 18.0
besu_peers_peer_count_by_type{client="Unknown"} 0.0
```
with it you can create graphs like this one 
fixes #8439

Add metrics to report peer count by client

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/verkle/LeafBuilder.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/diffbased/verkle/worldview/VerkleWorldState.java

The codehash should be removed when account is removed from the trie.

Fix codehash removal upon account removal

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/options/EthProtocolOptions.java

Address https://github.com/hyperledger/besu/pull/8492#discussion_r2021853398

feat!: remove deprecated `compatibility-eth64-forkid-enabled` option

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/options/TransactionPoolOptions.java
besu/src/test/java/org/hyperledger/besu/cli/options/TransactionPoolOptionsTest.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PeerTransactionTracker.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolConfiguration.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactory.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/task/BufferedGetPooledTransactionsFromPeerFetcherTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/task/BufferedGetPooledTransactionsFromPeerFetcherUsingPeerTaskTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/AbstractTransactionPoolTestBase.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/NewPooledTransactionHashesMessageSenderTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/PeerTransactionTrackerTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionsMessageSenderTest.java

In PR #7755 the default behavior of the peer transaction tracker changed from always remember the txs exchanged with a peer (at least until they fits in the cache) to forget a txs has been already exchanged in case it is evicted from the pool for reason not related to the validity.
While the new default solves issues with re-broadcasting the same tx in small networks, it does not works well for public networks, where there are many thousands of pending txs and a lot of independent nodes, since it can cause the broadcast and the re-evaluation of already seen txs, with the waste of network and computation resources.
So this PR changes the current default based on the txpool implementation that is chosen:
* for Layered the default is to not forget on eviction (new behavior), since it is the …

Tune and make configurable the `PeerTransactionTracker` 

---

CHANGELOG.md
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/BlockProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PrivacyBlockProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/parallelization/MainnetParallelBlockProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/parallelization/ParallelTransactionPreprocessing.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/parallelization/ParallelizedConcurrentTransactionProcessor.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/MainnetBlockValidatorTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessorIntegrationTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessorTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockProcessorTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/PrivacyBlockProcessorTest.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/parallelization/ParallelizedConcurrentTransactionProcessorTest.java

motivation: Block Import tracing needs to both start AND end block tracing.  
#8534 added block import tracing, but does not call block tracing end.  In order to have BlockBody available to call traceBlockEnd(), the BlockProcessor interface and implementations have to be refactored a bit.
The resulting interface is cleaner IMO, so that is a bonus

feature:Block Start/End tracing in AbstractBlockProcessor, refactor of BlockProcessor interface

---

ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/mainnet/DifficultyCalculatorTests.java

Fixes initialization error re prague time - required since #8521 
```
Genesis Config Error: 'Prague' is scheduled for milestone 1746612311 but it must be on or after milestone 999999999999.
java.lang.RuntimeException: Genesis Config Error: 'Prague' is scheduled for milestone 1746612311 but it must be on or after milestone 999999999999.
at org.hyperledger.besu.ethereum.mainnet.ProtocolScheduleBuilder.validateForkOrder(ProtocolScheduleBuilder.java:267)
at org.hyperledger.besu.ethereum.mainnet.ProtocolScheduleBuilder.validateEthereumForkOrdering(ProtocolScheduleBuilder.java:233)
```

[TEST] add pragueTime override in DifficultyCalculatorTest

---

besu/src/main/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilder.java
besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/VersionMetadata.java

The refactor in https://github.com/hyperledger/besu/pull/8536 introduced a change in the version logged as part of the overview, instead of the short version `Besu version 25.4.1` the long version is used `Besu version besu/v25.4.1/linux-x86_64/openjdk-java-21`, this PR restore the previous behavior.

Fix the version printed in the overview

---

besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/PrunePreMergeBlockDataSubCommand.java

- Hide the pre-merge block pruner subcommand
- Make it clear the pre-merge block pruner subcommand is experimental
- Make pre-merge block pruner subcommand start from block 1 (previously genesis block)

Hide and make explicit the experimental status of the subcommand

---

CHANGELOG.md
config/src/main/resources/sepolia.json

With the history expiration approaching Sepolia on May 1st, nodes might encounter difficulties in checkpointing block bodies prior to the merge block. This PR updates the Sepolia checkpoint at genesis to align with the merge block.

chore: update Sepolia checkpoint to merge block number

---

CHANGELOG.md
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java

Further to PR #7961 the logs are now rather long (183 characters), requiring font size 9 to fit on one line within a Ubuntu console at its maximum size.
Moreover, the labels are now standardised to be appended instead of prepended to values, and block hash labels are standardised without the word `blockHash` 
```
printf 'Imported #21,293,789  (0xdcec.....503fa)|  212 tx| 16 ws| 2 blobs| base fee  13.78 gwei| gas used  19,512,289 ( 65.0%%)| exec time 0.249s| mgas/s  78.36| Parallel txs 36.8%%| peers: 25' | wc -c
183
```
This PR attempts to trim down log size.
```
printf 'Imported #22,300,103  (a8e1d.....b63b5)|   60 tx ( 65.0%% parallel)| 16 ws| 0 blobs| 355.69 mwei base|  4,087,850 ( 11.4%%) gas used| 0.083s exec|  49.25 Mgas/s|  7 peers' | wc -c
168
```
Sample log lines:
```
2025-04-19 …
```

Standardise log content in AbstractEngineNewPayload and AbstractEngineForkchoiceUpdated

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputation.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/peertask/PeerTaskExecutor.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/GetAccountRangeFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/GetBytecodeFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/GetStorageRangeFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/GetTrieNodeFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractGetHeadersFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractPeerRequestTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetBodiesFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetNodeDataFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetPooledTransactionsFromPeerTask.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetReceiptsFromPeerTask.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputationTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/peertask/PeerTaskExecutorTest.java

Fix: Timeouts are now indexed by both request code and protocol.

---

CHANGELOG.md
consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/MergeProtocolSchedule.java
consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java

Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>## PR description
refs #8249 
Sepolia and Holesky now increasing to 60M

increase Holesky and Sepolia default gas limit to 60M

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/VersionMetadata.java

This PR adds a check to verify whether the data path exists and is writable. If the directory does not exist or cannot be created, an exception is thrown to prevent misleading startup behaviour.
fixes #8587

Fix: improve error message when data path is not writable

---

besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/PrunePreMergeBlockDataSubCommand.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueSegmentIdentifier.java

* Also skip pruning the totalDifficulty, for consistency with how the history expiry sync works as per https://github.com/hyperledger/besu/commit/1db03138508db8d630fc1aae74b7aff6f4926281
* Improve UX
* more flexible number of threads default 
* logging to show settings and remaining blocks estimate
Note, this PR does not enable BlobDB GC, that will be another PR.
Mainnet testing brings the prune time down from many days to ~5 minutes.
We can add back in the transaction location pruning once this PR is in https://github.com/hyperledger/besu/pull/8590
Example run using a dummy hoodi example, pruning the first 150,000 blocks:
```
➜  besu git:(improve-prune-ux) ✗ $BESU --data-path=/tmp/besu --network=hoodi storage x-prune-pre-merge-blocks
2025-05-08 12:40:23.786+10:00 | main | INFO  | …
```

history-expiry: Prune fast by skipping pruning the transaction locations

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessor.java

Fix an issue for PoA consensus mechanisms where the blockheader coinbase and mining beneficiary are different (like clique)

use correct mining beneficiary in processBlock for blockImport tracing

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/options/TransactionPoolOptions.java
besu/src/test/java/org/hyperledger/besu/cli/options/TransactionPoolOptionsTest.java

Remove the deprecated `--tx-pool-disable-locals` option

---

datatypes/src/test/java/org/hyperledger/besu/datatypes/VersionedHashTest.java

Following this issue https://github.com/hyperledger/besu/issues/8624 I added two unit tests to make the case clear and covered by unit tests.

improve VersionedHash unit tests

---

ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/BlockchainSetupUtil.java
ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/InMemoryKeyValueStorageProvider.java

Enable BlockchainSetupUtil based tests to plumb a plugin ServiceManager
If we want to enable plugins to use test-support for building test cases, we need to be able to supply and configure a plugin service manager.

Add plugin servicemanager to test-support

---

ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSEntry.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSResolver.java
ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSResolverTest.java

Add in a way to log what are these ENR records that are causing issues in node discovery - by looking at the issue it is impossible to tell but likely a wrong format in the Base64 encoding of a record's value. If we see that there's no control over the format we can possibly silently drop this record and avoid exception propagation.
fixes #8368

Add try/catch to log issues with ENR records

---

CHANGELOG.md
ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcTestMethodsFactory.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractEstimateGas.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCreateAccessListTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java

First PR of a series that improve gas estimations.
When calling `eth_estimateGas` is the block number or tag parameter is not present, then default to `pending` instead of `latest` to improve the accuracy, since the estimation if for inclusion in the next block.
Comparing this PR with current main branch, using https://github.com/Consensys/compate-estimate-gas-plugin, there are less under estimations:
BesuNightly 11434
BesuPR8627 11276
more improvements will be part of following PRs

Estimate gas on pending block by default

---

CHANGELOG.md
besu/src/main/java/org/hyperledger/besu/cli/UnstableOptionsSubCommand.java
besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java

Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>## PR description
fixes #8661
Also added a test for Unstable options subcommand

unstable options help - ensure no duplicates

---

acceptance-tests/tests/src/test/resources/qbft/qbft-london.json

Adding the missing test genesis file which somehow didn't make it to original PR. #8486 
Couple of QBFT based ATs were failing due to missing this missing resource .

Add missing genesis file used by QBFT based ATs

---

docker/Dockerfile

fix for this error
https://github.com/hyperledger/besu/actions/runs/15197711930/job/42745663154
```
Run docker run --rm -i hadolint/hadolint < docker/Dockerfile
Unable to find image 'hadolint/hadolint:latest' locally
latest: Pulling from hadolint/hadolint
db4123164570: Pulling fs layer
db4123164570: Verifying Checksum
db4123164570: Download complete
db4123164570: Pull complete
Digest: sha256:fff226bdf9ebcc08db47fb90ee144dd770120b35c2b1cbbb46e932a650cfe232
Status: Downloaded newer image for hadolint/hadolint:latest
-:29 DL3020 error: Use COPY instead of ADD for files and folders
Error: Process completed with exit code 1.
```

fix in docker file

---

besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
besu/src/main/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilder.java
besu/src/main/java/org/hyperledger/besu/cli/options/storage/DataStorageOptions.java
besu/src/main/java/org/hyperledger/besu/services/BesuConfigurationImpl.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DataStorageConfiguration.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/DataStorageConfiguration.java
plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactory.java

`besu --Xhistory-expiry-prune`
will automatically set the following rocksdb GC options based on the testing conducted in https://github.com/hyperledger/besu/pull/8599:
```
--Xplugin-rocksdb-blockchain-blob-garbage-collection-enabled
--Xplugin-rocksdb-blob-garbage-collection-age-cutoff=0.5
--Xplugin-rocksdb-blob-garbage-collection-force-threshold=0.1
```
The config overview displays:
```
```
and the full settings are shown in an INFO log:
`2025-05-23 09:39:40.179+10:00 | main | INFO  | RocksDBKeyValueStorageFactory | History expiry prune is enabled so setting --Xplugin-rocksdb-blockchain-blob-garbage-collection-enabled; --Xplugin-rocksdb-blob-garbage-collection-age-cutoff=0.5; --Xplugin-rocksdb-blob-garbage-collection-force-threshold=0.1`
It is still possible to set these options …

Add `--Xhistory-expiry-prune` for enabling optimal RocksDB GC settings

---

CHANGELOG.md
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/CallSmartContractFunction.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/DeploySmartContractTransaction.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/contract/ContractTransactions.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthEstimateGasAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthEstimateGasZeroToleranceAcceptanceTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptanceqbft/jsonrpc/EthEstimateGasAcceptanceTest.java
ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/frontier/EthEstimateGasIntegrationTest.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractEstimateGas.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCreateAccessList.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGas.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCreateAccessListTest.java
ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/TransactionValidationParams.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java

Second PR of the series that improves gas estimation.
Besu implementation of `eth_gasEstimation` accepts the non standard parameters `strict`, that by default is `false`.
This parameters tells Besu that when processing the tx to estimate the gas used, the sender is allowed to exceeds his balance, and this is achieved setting to `0` all the gas price related field in the tx and in the block header.
This approach is not the standard, and could cause wrong gas estimations for some txs, so this PR set the default value of the `strict` parameter to `true`.
It is still possible to force the previous behavior, explicitly passing the `strict` parameter in the request, set to `false`.
Since `strict` mode does not alter gas pricing parameters, there is the need to calculate the gas limit upper …

Make gas estimation strict by default

---

CHANGELOG.md
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSEntry.java
ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSResolver.java
ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSDaemonTest.java
ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSResolverTest.java
ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/MockDnsServerVerticle.java

Badly encoded ENR nodes should be ignored instead of crashing the daemon. Example of a badly encoded ENR node seen in the wild:
```
{"@timestamp":"2025-05-23T02:26:27,631","level":"ERROR","thread":"vert.x-virtual-thread-3681","class":"DNSResolver","message":"Failed to parse record: enr:-Lu4QMFaKrYJyYO06WxKfW8njcWATSuGJZV72zCIv6dTsihJJ4QM48Sxpi1xN--CI3MX4MTy-qhknkn9ESZF3_AOvhuGAZS-S2T2g2V0aMrJhPxk7ASDEYwwgmlkgnY0gmlwhLkcZFKDaXA2kCABFegBEChSAAAAAAAAAAGJc2VjcDI1NmsxoQM9Tj7Od8vEHMK8qCD8T0RHeN_LeLbbETpKFlfhx4UVzIRzbmFwwIN0Y3CCdl-DdWRwg","throwable":""}
```
#fixes 8368

ignore invalid ENR nodes in DNS daemon

---

ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/KVReader.java
ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSResolverTest.java

I also noticed an edge case in ENR records where if its value, which is encoded in Base64, contains a `=` that is a perfectly legit character and means a padded value, then the parsing will fail. 
fixes #8697

Swap precedence order while parsing enr records

---

datatypes/src/main/java/org/hyperledger/besu/datatypes/BlobType.java

Seems that #8631 broke the docker build so this should fix it
Opened #8730 to address the root cause

BlobType - add final keyword 

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/DefaultSynchronizer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/SnapServerChecker.java

This reverts commit ed1086d1a91eb7b3044b744d6a76e6dbdd6d2922.
There is an issue with how this commit tracks if a peer is serving snap data. Reverting for now as it will need to be better explored.

Revert "feat: remove chain head check if peer supports eth/69 (#8725)"

---

.github/workflows/acceptance-tests.yml
acceptance-tests/tests/build.gradle

Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>## PR description
`acceptanceTestNotPrivacy` is now `acceptanceTest` and GHA is accordingly updated. Removed separate gradle tasks which were essentially duplicated.

[TESTING] deduplicate gradle tasks for ATs

---

acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeConfigurationBuilder.java
ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcTestMethodsFactory.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcApis.java

Privacy removal means these RPCs have been removed.

Remove RPC categories for removed RPCs: PRIV and EEA

---

evm/src/main/java/org/hyperledger/besu/evm/internal/FlexStack.java

This PR changes the stack rate growth strategy of `FlexStack` to grow at a 50% rate instead of constantly growing by 32 slots as is currently. The former is the approach adopted by the JDK for `ArrayList`.
With a 50% allocation rate and considering a max stack size of 1024, setting the initial size to 91 one can reach the worse case (1024) in just 6 resizes compared to 32 required with the current approach.
Also the current usage on mainnet has shown that CALLs never go above 150 deep during execution.

Change stack size growth strategy to 0.5 rate

---

CHANGELOG.md
consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java

45M gas for mainnet

---

ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreatorTest.java

The abstract test class `AbstractBlockCreatorTest` was never subclassed, so its test methods were not executed along with other tests in the module. After making the class concrete to run the tests, one test was failing due to `libckzg4844jni.so` not being loaded. To load the native library, the test class was made to extend `TrustedSetupClassLoaderExtension` as per convention.

Run and fix tests in AbstractBlockCreatorTest

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlockRlpSizeTransactionSelector.java

Fix a log issue in BlockRlpSizeTransactionSelector and add a transaction hash in the log.

Fix a log issue in BlockRlpSizeTransactionSelector

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/handlers/JsonRpcArrayExecutor.java

In case of a RPC multi call, only the request is logged when TRACE level is enable, this PR also add the logging of the responses.

Log response also for a RPC multi call

---

.github/workflows/acceptance-qbft-tests.yml
.github/workflows/acceptance-tests.yml
.github/workflows/integration-tests.yml
.github/workflows/pre-review.yml
.github/workflows/reference-tests.yml
evm/src/main/java/org/hyperledger/besu/evm/gascalculator/CancunGasCalculator.java

This code should not be merged into main. This is the fast way we have to test ModExp new pricing. It is scheduler for Fusaka but we enable it for Cancun on the performance branch to be able to test it.

Only for performance benchmarking : change ModExp pricing for Cancun

---

testutil/src/main/resources/mainnet-data/mainnet.json

Think it makes sense for this (test) genesis file to be fairly up to date. Used by BlockchainSetupUtil
related to #8944

refresh the mainnet.json used for blockchain util tests

---

CONTRIBUTING.md

Move the trivial clause to the bottom of the page. Also fixed the roadmap link.

[CONTRIBUTING] move trivial clause to bottom

---

app/src/test/java/org/hyperledger/besu/RunnerTest.java

Remove these fast sync tests that are flaky eg https://github.com/hyperledger/besu/actions/runs/16333574965/job/46141294930?pr=8967 
Fast sync is deprecated per #7906 and broken per #7511

remove fast sync from genesis tests from RunnerTest

---

consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineGetPayload.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadV1.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadV2.java

Currently the logs during block creation are broken, since Besu lost the log that was done when the consensus client fetches the payload, that is fixed, and to make the logs more informative, the best proposal built so far is logged as well, that could be useful to see the progression and to reconstruct what happened in case of investigations.
Logs will look like this (non relevant parts removed):
```
:"Start building proposals for block 8868631 identified by 0x282b5c1167ce49e4","throwable":""}
ated","message":"FCU(VALID) | head: 604ca.....1c4bf | safe: 1ec4d.....26dd8 | finalized: 25051.....8b3c2","throwable":""}
ssage":"New proposal for payloadId 0x282b5c1167ce49e4 block 8868631 (0x5a30fdc5016ea856020b24a48b7b93a97e80db02245862e3f3844c167cc0280d) gas used 12968343 transactions 32 reward …
```

Improve info logs during block creation

---

ethereum/referencetests/build.gradle
evm/src/main/java/org/hyperledger/besu/evm/EVM.java
evm/src/main/java/org/hyperledger/besu/evm/operation/JumpService.java

This PR is to align with Geth after https://github.com/gballet/go-ethereum/pull/530.
I noticed we are already accounting for the JUMP and JUMPI charges if jumps are valid because the next PC at the start of the interpreter loop will point to the exact code chunk to charge for but not the case where the destination is not JUMPDEST.
I also moved the touch code chunks before getting the operation because charges should come immediately after we know what's the new PC (start of the loop).
fixes #8150

Invalid jump dest not charged

---

ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/snap/SnapServerTest.java

The tests in `SnapServerTest` are currently failing for `FlatDbMode.ARCHIVE`.
In `FlatDbMode.ARCHIVE`, every flat database read and write needs a context that is taken from `WORLD_BLOCK_NUMBER_KEY`. The write path adds one to this value before storing the entry, while the read path uses the stored value directly.
Because `insertTestAccounts` never increments the block number after committing, subsequent reads look for data tagged with the old block context and fail to find the written value.

Fix SnapServerTest for `FlatDbMode.ARCHIVE`

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/common/GenesisWorldStateProvider.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/BonsaiWorldStateProvider.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/cache/BonsaiCachedWorldStorageManager.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/cache/NoOpBonsaiCachedWorldStorageManager.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/common/cache/PathBasedCachedWorldStorageManager.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/parallelization/ParallelizedConcurrentTransactionProcessorTest.java
ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/BonsaiReferenceTestWorldState.java

`PathBasedCachedWorldStorageManager` currently only offers a public constructor that defaults to `EvmConfiguration.DEFAULT`, which always sets the world updater mode to `STACKED`.
Later, when world states are created e.g. during block processing through `BonsaiCachedWorldStorageManager`, those states are built with this default configuration, ignoring configuration set via `--Xevm-worldstate-update-mode` CLI flag.
In order to allow setting the world state update mode via CLI flag, this PR
* extends the constructor of `BonsaiCachedWorldStorageManager` to accept `EvmConfiguration`, and
* passes the global `EvmConfiguration` from `BonsaiWorldStateProvider` to `BonsaiCachedWorldStorageManager` on construction.

Propagate `EvmConfiguration` to `PathBasedCachedWorldStorageManager`

---

CHANGELOG.md
config/src/main/resources/lukso.json

This PR adds Prague configurations for LUKSO Mainnet. The Pectra fork is scheduled for 17th September 2025, 16:20 GMT.

feat: LUKSO Mainnet Pectra Hardfork

---

app/src/main/java/org/hyperledger/besu/controller/IbftBesuControllerBuilder.java
app/src/main/java/org/hyperledger/besu/controller/QbftBesuControllerBuilder.java
consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BftRoundExpiryTimeCalculator.java
consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/RoundExpiryTimeCalculator.java
consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/RoundTimer.java
consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/BftRoundExpiryTimeCalculatorTest.java
consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/RoundTimerTest.java
consensus/ibft/src/integration-test/java/org/hyperledger/besu/consensus/ibft/support/TestContextBuilder.java
consensus/qbft-core/src/integration-test/java/org/hyperledger/besu/consensus/qbft/core/support/TestContextBuilder.java

Allows for other implementations for round expiry time calculation in Bft consensus.

Make the Bft expiry time algorithm configurable

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/systemcall/SystemCallProcessor.java

log system call address and frame state when system call fails to help with debugging system call failures.

log system call address and frame state when system call fails

---

CHANGELOG.md
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java

This PR improves the performance of the block creation phase, reducing the time spent during the commit of the world state updaters, see the screenshot below that compares the time spent for the commit, between a control Besu running 25.7.0 and a dev Besu running this PR. 
Thanks to @ahamlat and @matkt for spotting this PR and suggesting how performance could be improved

Block transaction selector performance

---

.github/workflows/develop.yml
ethereum/eth/src/jmh/java/org/hyperledger/besu/ethereum/eth/sync/worldstate/WorldStateDownloaderBenchmark.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncActions.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncDownloadPipelineFactory.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncState.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncStateStorage.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotBlockConfirmer.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotSelectorFromPeers.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotSelectorFromSafeBlock.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncDownloadPipelineFactory.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/range/RangeHeadersValidationStep.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapSyncProcessState.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/RangeHeadersFetcherTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/RangeHeadersValidationStepTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/checkpointsync/CheckPointSyncChainDownloaderTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncActionsTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncChainDownloaderTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncDownloadPipelineFactoryTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncDownloaderTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncStateStorageTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotBlockConfirmerTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/PivotBlockRetrieverTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/worldstate/FastWorldStateDownloaderTest.java
ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/DynamicPivotBlockManagerTest.java

Backport Skip header validation if the chain is POS (https://github.com/hyperledger/besu/pull/9038) from main.
Also adding back the attachedValidationPolicy and ommerValidationPolicy for the ImportBlocksStep. These were removed on main when we changed to using the ImportSyncBlocksStep.

backport Skip header validation if the chain is POS (#9038)

---

app/src/main/java/org/hyperledger/besu/controller/IbftBesuControllerBuilder.java
app/src/main/java/org/hyperledger/besu/controller/QbftBesuControllerBuilder.java
consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BftRoundExpiryTimeCalculator.java
consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/RoundExpiryTimeCalculator.java
consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/RoundTimer.java
consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/BftRoundExpiryTimeCalculatorTest.java
consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/RoundTimerTest.java
consensus/ibft/src/integration-test/java/org/hyperledger/besu/consensus/ibft/support/TestContextBuilder.java
consensus/qbft-core/src/integration-test/java/org/hyperledger/besu/consensus/qbft/core/support/TestContextBuilder.java

Backport Make the Bft expiry time algorithm configurable (#9085)

Backport Make the Bft expiry time algorithm configurable (#9085)

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldDownloadState.java

Inconsistent synchronization of getter and setter
To fix the problem, we must ensure that all access to the shared mutable field (accountsHealingList) is properly synchronized. This means the getter method getAccountsHealingList should be declared as synchronized in addition to the setter and modifier methods. This ensures that reads and writes to the field cannot interleave in a way that exposes inconsistent or partially updated state. The best way to fix this is simply to add the synchronized modifier to the getAccountsHealingList method, declared at line 331 of the file.

fix inconsistent synchronisation of getter and setter

---

evm/src/main/java/org/hyperledger/besu/evm/precompile/P256VerifyPrecompiledContract.java

fix(evm): correct P256VERIFY input length in error message

---

CHANGELOG.md
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/AbstractTestTransactionSelectorPlugin.java
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestBlockchainServicePlugin.java
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestTransactionSelectorPlugin1.java
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestTransactionSelectorPlugin2.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/BlockchainServicePluginTest.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/TransactionSelectorPluginTest.java
app/src/main/java/org/hyperledger/besu/services/TransactionSelectionServiceImpl.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockTransactionSelectorTest.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/txselection/PluginTransactionSelectorFactory.java

Currently is only possible to register one `PluginTransactionSelectorFactory` with the `TransactionSelectionService`, so it is not possible to have multiple transaction selector plugins deployed at the same time.
This PR extends the registration mechanism to allow the registration of an arbitrary number of `PluginTransactionSelectorFactory`, thus allowing multiple transaction selector plugins to work together.
Note that at this point there is no way to force a specific order for the transaction selectors, and the order is based on the plugin registration order, a future PR will add the possibility to specify the order in which the plugin are called. For example this could be important when calling `PluginTransactionSelectorFactory::selectPendingTransactions`

Support multiple transaction selector plugins

---

app/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java

Refactor BesuCommandTests that use the output of the startup config summary log. Depending on local environment, some other log lines are also printed (eg "using native impl of XYZ") so changed the logic to not rely on the exact number of log lines emitted.
fix besu command tests that were failing locally
Tests that were failing:
```
BesuCommandTest > shouldShowCorrectFormatForCustomNetworkCustomTargetGasLimit() FAILED
java.lang.AssertionError at BesuCommandTest.java:2933
BesuCommandTest > shouldShowCorrectFormatForTestnetCustomTargetGasLimit() FAILED
java.lang.AssertionError at BesuCommandTest.java:2885
BesuCommandTest > shouldShowCorrectFormatForMainnetCustomTargetGasLimit() FAILED
java.lang.AssertionError at BesuCommandTest.java:2836
BesuCommandTest > …
```

[TESTS] refactor log parsing to make tests more robust

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/era1prepipeline/Era1FileSource.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/era1prepipeline/Era1HttpFileSource.java

make regex more precise
Fix Overly permissive regular expression range

fix hex regex in era1 filename match

---

app/src/main/java/org/hyperledger/besu/services/BesuConfigurationImpl.java
ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcConfiguration.java
ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/AbstractIsolationTests.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/services/BesuConfiguration.java

add rpc http timeout to the plugin api

add rpc http timeout to the plugin api

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreatorTest.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockSimulator.java

Should disable bal for transaction selection when not activated

disable bal for transaction selection when not activated

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/TransactionSelectionResults.java

The log of the block creation results are useful for debugging, it is only logged when TRACE is enable, but in case of a very large amount of txs evaluated, the log line can be too long for some log aggregation systems that reject it.
This PR make the log more compact only logging the hash of the tx, and grouping not selected txs by reason, so the line is much shorted than before, and having the hash is always possible to get txs details from previous log lines when the single tx is processed and logged.

Make the log of the block creation results more compact

---

CHANGELOG.md
app/src/main/java/org/hyperledger/besu/cli/options/MiningOptions.java
app/src/test/java/org/hyperledger/besu/cli/options/MiningOptionsTest.java
app/src/test/java/org/hyperledger/besu/controller/AbstractBftBesuControllerBuilderTest.java
app/src/test/java/org/hyperledger/besu/controller/CliqueBesuControllerBuilderTest.java
app/src/test/resources/everything_config.toml
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/InterruptibleOperationTracer.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/MiningConfiguration.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java

This PR gives control on how much time plugins can use to propose their own transactions during block creation.
The max time is configurable in term of percentage of the overall block creation max time, using the new configuration option `plugin-block-txs-selection-max-time` that by default is set to `50` meaning `50%` or half of the overall block creation time.

Time limited plugin txs selection

---

CHANGELOG.md
app/src/test/java/org/hyperledger/besu/ForkIdsNetworkConfigTest.java
config/src/main/resources/holesky.json
config/src/main/resources/hoodi.json
config/src/main/resources/sepolia.json

Update Fusaka forks for testnets

Update Fusaka forks for testnets

---

CHANGELOG.md
ethereum/ethstats/build.gradle
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/EthStatsService.java
ethereum/ethstats/src/main/java/org/hyperledger/besu/ethstats/request/EthStatsRequest.java
ethereum/ethstats/src/test/java/org/hyperledger/besu/ethstats/EthStatsServiceTest.java

Fix EthStats not updating blocks. This due the `BlockResult` containing an Optional<BlockAccessListResult>.
This is the exception we are currently getting
```
ERROR | EthStatsService | Failed to send BLOCK ethstats request with error Java 8 optional type `java.util.Optional<org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.BlockAccessListResult>` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jdk8" to enable handling (through reference chain: org.hyperledger.besu.ethstats.request.EthStatsRequest["emit"]->java.util.ArrayList[1]->org.hyperledger.besu.ethstats.report.ImmutableBlockReport["block"]->org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.BlockResult["blockAccessList"])
```

Fix EthStats integration with updating blocks

---

CHANGELOG.md
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/account/Accounts.java
acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/account/AccountTransactions.java
acceptance-tests/test-plugins/build.gradle
acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/AbstractTestTransactionSelectorPlugin.java
acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/TransactionSelectorPluginTest.java
ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java

Adding protection against unexpected runtime exceptions that could be triggered by plugins, or internally, during block creation.
These exceptions are treat like internal errors, because they should have been handled, so they represent bugs and for that reason are logged as error for high visibility, and to avoid possible a inconsistent state a rollback is forced, so that the selection can continue with a clean state.
fixes #9167

Manage unexpected exceptions during block creation

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java

Also add some more logging for penalization of interrupted pending txs
Use services executor for txpool tasks trigger by block creation, since the transactions executor, since the former is bounded and tasks could be discarded if its queue is full, while it is mandatory that they are executed.
Also add some more logging for penalization of interrupted pending txs.

Use services executor for txpool tasks trigger by block creation

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockTransactionSelectorTest.java
plugin-api/build.gradle
plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java

https://github.com/hyperledger/besu/pull/9208 introduced a regression, where a `CancellationException` is treated like an internal error, while it is not, since it is used to cancel the block creation.
In this PR I took the opportunity to fix the regression and handle the block selection cancellation without the use of exceptions, but using normal transaction selection result propagation, using the new `SELECTION_CANCELLED` result.

Fix: handle block selection cancellation without exception

---

ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransaction.java

Hash and sender must be reported fully and not as short hex string, because every byte counts

Fix `PendingTransaction::toString` loss of information

---

ethereum/core/src/jmh/java/org/hyperledger/besu/ethereum/vm/operations/BinaryOperationBaselineBenchmark.java
ethereum/core/src/jmh/java/org/hyperledger/besu/ethereum/vm/operations/BinaryOperationBenchmark.java
ethereum/core/src/jmh/java/org/hyperledger/besu/ethereum/vm/operations/TernaryOperationBaselineBenchmark.java
ethereum/core/src/jmh/java/org/hyperledger/besu/ethereum/vm/operations/TernaryOperationBenchmark.java

When using JMH `@Param` this results in duplicate baseline runs, one for each Param which can add up.
The downside of this PR is you must explicitly ask for the baseline when you apply benchmark filtering:
Example run that explictly includes the Baseline benchmarks
```
./gradlew :ethereum:core:jmh -Pincludes=Add,Baseline -Pexcludes=AddMod --rerun-tasks
...
Benchmark                                           Mode  Cnt    Score   Error  Units
AddOperationBenchmark.executeOperation              avgt    5  110.220 ± 6.635  ns/op
BinaryOperationBaselineBenchmark.executeOperation   avgt    5    8.547 ± 1.634  ns/op
TernaryOperationBaselineBenchmark.executeOperation  avgt    5   14.546 ± 5.494  ns/op
```
---
Before this PR the baseline was included within each Operation...
```
./gradlew …
```

Extract duplicate baseline benchmarks for Binary and Ternary operations

---

ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java

This PR improves mgas/s number accuracy in the logs.
I have noticed in some devnets logs like 
```
2025-09-29 09:19:06.027+0000 | vert.x-worker-thread-0 | INFO  | AbstractEngineNewPayload | Imported #18,812,701  (98032.....b127b)|    2 tx|  0 blobs|      7 wei bfee|      42,000 (  0.0%) gas used| 0.000s exec|   0.00 Mgas/s| 25 peers
```
We can see that Mgas/s is 0 in the log. This is happening because executing the 2 transfers is taking less than 1 ms, which make the execution time 0 s because the time in seconds is displayed only with 3 decimals.
In this PR, we use also System.nanoTime()  instead of System.currentTimeMillis(), because  System.nanoTime() is less dependant on the OS changes. We also use the time in nanoseconds to calculate mgas/s, so if there is any transaction, mgas/s …

Improve the accuracy of mgas/s number in the logs

---

ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlockRlpSizeTransactionSelector.java
ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/txselection/selectors/BlockRlpSizeTransactionSelectorTest.java

The safety margin that makes sure that the block we are building is not too big was not taking everything into account, e.g. the size of the withdrawals. This PR increases that safety margin to 256kB.

Increase safety margin when selecting Transactions

---

ethereum/core/src/main/java/org/hyperledger/besu/ethereum/components/ProtocolScheduleModule.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/components/ProtocolSpecModule.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecFactory.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/milestones/MilestoneDefinitions.java

Just a refactor PR to uniform the way genesis config options are passed to protocol specs, no functional changes expected. This refactor will make the next PR https://github.com/hyperledger/besu/pull/9257 much easier to read.

Refactor: uniform the way genesis config options are passed to protocol specs
